### ISSUE TITLE
[QUESTION] About 6.0.2

### ISSUE THREAD

**Issue by dorian-kwon** [TypedProject/tsed#1016]
Hello,

I just migrated tsed v6.0.0 to v6.0.2

I have some question.

1. Controller returns empty field like [{}, {}, {}].
It seems because of RawDataPacket that typeorm and mysql driver is using.
I often use raw query without specific type.
So, now I attached Middleware that return res.json(data).
Is that bug or you expect? I need to prepare about it.

2. About Auth Decorator
I read this doc https://tsed.io/docs/authentication.html#create-your-auth-decorator
Operator is deprecated and Returns cannot be class decorator.
Is there any way to use it?
It made code repetition in my code.

Thanks

**Comment by Romakita** [comment]
Hello @dorian-kwon 

Can you give me more detail. I'm not sure to understand your first point.

For the second point this part of the documentation isn't up to date. I miss that :). Here the right change:
https://github.com/TypedProject/tsed/pull/1018/files

You have to use the new `@In` decorator to describe your header Authorization. Then, Ts.ED provide an utils `decorateMethodsOf` to use an existing method decorator on class.

Example:

```typescript
import {decorateMethodsOf} from "@tsed/core";

export MyClassDecorator(options) {
   return (target) => {
      return decorateMethodsOf(target, MyMethodDecorator(options))
  }
}
```

See you
Romain

**Comment by dorian-kwon** [comment]
Thank you!!

I solved second thing now!

and first one example code is here

Part of a service
```
 // we get the query from other db because it is BI tool.
 // means it cannot have a specific type and it returns RawDataPacket[]
 public getUser(query: string, params: any[]) { 
    return getConnectionManager().get('userDefinedDB').query(query, params);
 }
```

Part of a controller
```
  @Get('/')
  public getUser(...) {
     // do something
     return this.userService.getUser(query, params);
  }
```

What I'm doing on Controller
```
  @UseAfter(SerializeMiddleWare)
  @Get('/')
  public getUser(...) {
     // do something
     return this.userService.getUser(query, params);
  }
```

Part of SerializeMiddleWare
```
  public use(@ResponseData() responseData: any, @Response() response: express.Response) {
      response.json(responseData);
  }
```

See you 👍

**Comment by Romakita** [comment]
Hello @dorian-kwon 
Default doesn't exists on OpenSpec on the parameter level, but on schema level yes:
https://github.com/TypedProject/tsed/blob/production/packages/openspec/src/openspec3/OS3Parameter.ts
This is why this method isn't implemented:
https://github.com/TypedProject/tsed/blob/production/packages/schema/src/decorators/operations/in.ts
If you have a solution, you can make a short PR to add Default method to `@In` decorator :).

For your second point. Use response.json() isn't recommended, because you bypass the Ts.ED serializer.

if you modifying the response before send it, just return data from your middleware:

```typescript
public use(@Context() ctx: Context) { 
      const {data} = ctx;
      // do something

      return data
}
```
> Note: Prefer the Context decorator usage :) ctx contain all information about your endpoint, the data, and the response/request object. (https://tsed.io/docs/platform-api.html)

**Comment by dorian-kwon** [comment]
Yes exactly!

What I supposed was avoid Ts.ED serializer.

Because Ts.ED serializer serializes RowPacketData[](from raw query) like [{}, {}, ... ]. there is only Object[]. no properties.

And about *@In*. When I get the end of this project I will look down it!

Thanks.

**Comment by Romakita** [comment]
If there is only Object[], the serialize should return the entire object without any transformation. If you don't provide model with @Returns decorator, the serialize will simply return the entire object. Isn't normal to use an extra middleware to avoid this bug. Is it possible to have a reproducible repository example? 

See you
Romain

**Comment by dorian-kwon** [comment]
Here is example.
The rdbms should be mysql or mariaDB. (those are using RawDataPacket Object)

ConnectionManager
```typescript
import { ConnectionManager, getConnectionManager, ConnectionOptions } from 'typeorm';

@Service()
export class ExampleConnectionManagerService {
    private typeormConnectionManager: ConnectionManager;

    constructor() {
        this.typeormConnectionManager = getConnectionManager();
    }

    create(dataSource: ConnectionOptions) {
        this.typeormConnectionManager.create({
            ...dataSource,
            logging: ['error'],
            synchronize: false,
        });
    }

    getConnection(name: string) {
        return this.typeormConnectionManager.get(name);
    }

   .....
}
```

```typescript
@Service()
export class ExampleQueryExecutorService {
    constructor(private connectionManager: ExampleConnectionManagerService ) {
    }

    query(dbName: string, q: string, param: any[]) {
        return this.connectionManager.getConnection(dbName).query(q, param);
    }

   ....
}
```

```typescript
@Controller("/examples")
export class ExampleCtrl {
  constructor(
      private executorService: ExampleQueryExecutorService,
      // it's typed repository
      private biQueryRepository: ExampleBiQueryRepository
      ) {
  }

  @Get("/")
  async get(@QueryParams() ....) {
    // so somthing
    const biQuery = this.biQueryRepository.findByID(id).
    return this.exampleService.query(query.dbName, biQuery.query, params);
  }
}
```

FYI, we are developing and maintenance BI system like [tableau](https://www.tableau.com/).
Our customers input their database information and queries to our system.

Thanks! :)

**Comment by Romakita** [comment]
Thanks @dorian-kwon  I reproduced the issue. Currently it's because you don't use Property decorator on your property class (as you mentionned). You should add at least this decorator to solve your issue. The documentation is pretty clear about that ;) 

I'll fix the issue on my side because it's probably a regression compared to v5 ^^.
See you
Romain

**Comment by dorian-kwon** [comment]
Thank you for solving it!
And sorry for my explanation.
I know I should put Decorator for all schemas.
I publushed 3 projects with TS.ed!

Our DB is all Decorated.

Unfotunatly, we cannot make any entity and any Decorator for DB of customers.
Becuase it's a visualazation service. 
We can't know what customers save thier own datasouce and query to our db.
It's decided on runtime and can be changed running time.
Last thing is we don't want to fix our code every time they change schemas.

Thanks again! :)
Dorian.
