### ISSUE TITLE
[BUG] Documentation: @HeaderParams() incorrectly shows documentation for @Headers()

### ISSUE THREAD

**Issue by reed-lawrence** [TypedProject/tsed#1019]
I apologize if this is the wrong format to be reporting this, but I did not see any feedback sections on the website, and searching for this build error online did not return any results. 

https://tsed.io/api/common/mvc/decorators/params/HeaderParams.html#overview

In the second code sample, we can see:

```typescript

@Controller('/')
class MyCtrl {
   @Get('/')
   get(@Header() body: any) {
      console.log('Entire body', body);
   }

   @Get('/')
   get(@Header('x-token') token: string) {
      console.log('token', id);
   }
}
```

But when used with the `@Header()` as stated above this causes the following build error: 
**UnsupportedDecoratorType [Error]: Returns cannot be used as parameter decorator on [Controller Name]**

To fix this, I used the `@HeaderParams()` decorator instead of `@Header()`:
```typescript
@Controller('/')
class MyCtrl {

   @Get('/')
   get(@HeaderParams('x-token') token: string) {
      console.log('token', id);
   }

}
```

**Comment by Romakita** [comment]
Hello @reed-lawrence 

Thanks for your feedback. Yes the code example is totally wrong. The Header decorators is here to set response header, while HeaderParams is here to get request header.

I'll fix that :) 
Thanks again!
See you
Romain

**Comment by Romakita** [comment]
PR https://github.com/TypedProject/tsed/pull/1020/files
