### ISSUE TITLE
App Starting Error

### ISSUE THREAD

**Issue by okancancoskun** [TypedProject/tsed#1023]
![tsederror](https://user-images.githubusercontent.com/65512468/97589704-e8a62900-1a0e-11eb-89bd-f5f4c4b81471.png)

When I try to start my app, I take this error. That's my first experience with Ts.ED. Can you help how can i pass this error ? 

These are my other files ; 

![tsedindex](https://user-images.githubusercontent.com/65512468/97589790-02e00700-1a0f-11eb-91a8-fdbf896b89d9.png)

![tsedserv](https://user-images.githubusercontent.com/65512468/97589900-2014d580-1a0f-11eb-89e4-7794b75e880c.png)

![Screenshot_68](https://user-images.githubusercontent.com/65512468/97589940-2c992e00-1a0f-11eb-9e16-2ce02e6b26cf.png)

**Comment by IARKI** [comment]
You are making GET "/", based on your controller it should be GET "/hello-world"

**Comment by okancancoskun** [comment]
> You are making GET "/", based on your controller it should be GET "/hello-world"
> `@Controller("/hello-world")` define root path for the controller's API routes

I got it, Thank you.  Have a good work
