### ISSUE TITLE
Add hook for cleanup/teardown of injected objects

### ISSUE THREAD

**Issue by reed-lawrence** [TypedProject/tsed#1024]
https://tsed.io/docs/hooks.html

Reading the hooks documentation above, it does not look like there are any hooks for tear down methods within the injected components. Perhaps something like this is handled automatically already, but for example in unit testing with the `PlatformTest` each spin up and spin down exposes the possibility of unmanaged and unclosed connections within the components. 

Adding a lifecycle hook would allow for clean teardown such as:

```typescript
@Service()
export class DbService implements OnDestroy {

  constructor() {}

  public dbpool: Pool = createPool(MySqlConfig);

  public async GetConnection() {
    // stuff
  }

  $onDestroy() {
    this.dbpool.end();
  }

}
```

**Comment by Romakita** [comment]
Hello @reed-lawrence 

The hook exists but isn’t correctly documented ;)
