### ISSUE TITLE
[BUG] @tsed/exception not found at npm

### ISSUE THREAD

**Issue by ghmendonca** [TypedProject/tsed#1025]
## Information

- **Version:** 6.x

When trying to install `@tsed/exception`, I got not found from npm.

![Capturar](https://user-images.githubusercontent.com/29390554/97600344-b7fec900-19e7-11eb-8c71-57dd9d9818e5.PNG)

**Comment by IARKI** [comment]
it should be `@tsed/exceptions`

**Comment by Romakita** [comment]
Yes it’s exceptions.
