### ISSUE TITLE
[QUESTION] How to stop the server instance programatically with lifecycle hooks

### ISSUE THREAD

**Issue by reed-lawrence** [TypedProject/tsed#1027]
I have full integration tests that I want to test via HTTP rest calls. 

With mocha a basic end-to-end test might look like: 

```typescript
describe('Account Controller - Integration', () => {

  let requestToken: string;
  let platform: PlatformExpress;

  before(async () => {
    platform = await PlatformExpress.bootstrap(Server);
    await platform.listen();
  });

  after(async () => {
    platform.stop(); // <-- pseudo-code/does not exist
  });

});
```

The code in the `after()` method doesn't work for obvious reasons. But I have been scratching my head how to accomplish this. I'd like to hit all the `$onDestroy` hooks as well. Is there a graceful way to stop the server instance?

**Comment by Romakita** [comment]
Hello @reed-lawrence 
Simply use the PlatformTest.reset() as is described in the documentation :) https://tsed.io/docs/testing.html#test-your-rest-api

PlatformTest.reset call the all $onDestroy hooks and clean the DI.


Example:

```typescript
describe("Rest", () => {
  // bootstrap your Server to load all endpoints before run your test
  let request: SuperTest.SuperTest<SuperTest.Test>;

  beforeAll(PlatformTest.bootstrap(Server));
  beforeAll(() => {
    request = SuperTest(PlatformTest.callback());
  });
  afterAll(PlatformTest.reset);

  describe("GET /rest/calendars", () => {
    it("should do something", async () => {
      const response = await request.get("/rest/calendars").expect(200);

      expect(typeof response.body).toEqual("array");
    });
  });
});

```

**Comment by reed-lawrence** [comment]
Hello @Romakita thank you for the reply. 

I was having a handful of issues using it the PlatformTest way. Can you help explain the difference between these two? Your way works, but mine does not... Which is what lead me to try to use the PlatformExpress in the first place.

Yours (working):
```typescript
  before(PlatformTest.bootstrap(Server))
  before(() => {
    request = SuperTest(PlatformTest.callback());
  });
```

Mine (not working): 
```typescript
  before(async () => {
    await PlatformTest.bootstrap(Server);
    request = SuperTest(PlatformTest.callback());
  });
```
Throws error: `Error: PlatformTest.injector is not initialized. Use PlatformTest.create(): Promise before PlatformTest.invoke() or PlatformTest.injector`

**Comment by Romakita** [comment]
Hello @reed-lawrence 
PlatformTest create a context to bootstrap the server and DI then release resource after the integration test.
You example code doesn't work because PlatformTest.bootstrap(Server) return a function.

The correct code is:

```typescript
  before(async () => {
    await PlatformTest.bootstrap(Server)();
    request = SuperTest(PlatformTest.callback());
  });
```
But it's preferable to use this:

```typescript
  before(PlatformTest.bootstrap(Server))
  before(() => {
    request = SuperTest(PlatformTest.callback());
  });
```
Try the first example with my fix, it should works as expected :)
Romain

**Comment by reed-lawrence** [comment]
@Romakita You are correct, your code sample does work. Thanks for linking a future fix as well. 

I am really enjoying this framework, excellent work!
