### ISSUE TITLE
[BUG] graphql route not found

### ISSUE THREAD

**Issue by ghmendonca** [TypedProject/tsed#1047]
## Information

- **Version:** 6.2.2

I just started a new project with graphql and when I start the server, I get that my graphql server is running under `http://0.0.0.0:8080/graphql`, so everything seems to be working. But when I try to open the `/graphql` in the browser or fetch the schemas from  other softwares, I get a not found error saying `NOT_FOUND: Resource "/graphql" not found`.

Here is my server configuration:
![Capturar](https://user-images.githubusercontent.com/29390554/98118716-62646980-1e8a-11eb-96f7-7e1b51c1af68.PNG)

**Comment by Romakita** [comment]
PR #1050

**Comment by Romakita** [comment]
Released :) v6.2.4

**Comment by ghmendonca** [comment]
Awesome! Thanks @Romakita :)

**Comment by Romakita** [comment]
;) your welcome!
I added sandbox also: https://codesandbox.io/s/tsed-graphql-pgvfz?from-embed
