### ISSUE TITLE
[QUESTION] How to set Authorization Header Swagger Definition

### ISSUE THREAD

**Issue by jappyjan** [TypedProject/tsed#1053]
I want to have a definition of my auth mechanism in the generated Swagger JSON but can't figure out how to do it.
I would like to do it without passport so i can avoid a bigger refactoring of my current strategy.
The least i would like to achieve is to add a required header field to any method decorated by my custom "@Auth" decorator.

For the custom decorator i followed the dos here:
https://tsed.io/docs/authentication.html#create-your-auth-decorator

But they seem to be outdated or wrong.
they mention the "Operations" decorator but it is marked as deprecated.
And in the code they use the "In" decorator(?) but this one does not work for me.

Bonus points:
Would be nice if i could somehow instruct ts.ed to insert the auth strategy / how to do auth into the swagger so i could use the "authorize" button inside swagger ui

**Comment by Romakita** [comment]
@jappyjan The documentation doesn't mention the `@Operation` decorator but the `@In`.

For me the example works:
```
@Controller("/dashboard")
class DashboardCtrl {
  @Get("/")
  @CustomAuth({role: "admin", scopes: ["email", "firstname"]})
  public getResource() {
  }
}
```

But the decorator doesn't work is you use it on class, @In doesn't support usage on class.

To configure security options you have to give the spec information on server level:

```typescript

@Configuration({
swagger: [
    {
      path: "/doc",
      spec: {
        info: {
        },
        securityDefinitions: {
          // add you security definitions
        },
      }
    }
  ],

})
export class Server {

}
```

I'll try to rewrite the example ;)

**Comment by Romakita** [comment]
What is your Ts.ED version?

**Comment by Romakita** [comment]
Hello @jappyjan 
v6.3.0 fix some issue on Swagger documentation. 
I also rewritten examples on authentication page and added a sandbox example: https://tsed.io/docs/authentication.html
See you
Romain

**Comment by jappyjan** [comment]
I'm using version 5.65
Thanks for the hint to v6... upgrading helped 👍

**Comment by Romakita** [comment]
Cool :)
