### ISSUE TITLE
[V6] [BUG] PlatformBuilder getConfiguration bug prevents routes in tests

### ISSUE THREAD

**Issue by tobiasstrebitzer** [TypedProject/tsed#1058]
## Information

- **Version:** 6.x
- Packages: @tsed/common

This line wrongly assigns `componentsScan` configuration to `mount`, preventing any routes / controllers to be registered:
https://github.com/TypedProject/tsed/blob/2ac21a149a60f7b65798e8f67f1b3006678b8047/packages/common/src/platform-builder/utils/getConfiguration.ts#L16

**Comment by Romakita** [comment]
Hello @tobiasstrebitzer 
Thanks for your issue :)
The PR is ready!
