### ISSUE TITLE
Add support for model inheritance

### ISSUE THREAD

**Issue by dvarnai** [TypedProject/tsed#1062]
## Informations
OpenAPI 3 supports model inheritance using the allOf keyword, however the package doesn't.

**Describe the solution you'd like**

Read parent models automatically / implement a class decorator to specify the parent model. Use the allOf keyword as specified in the specification.

**Comment by Romakita** [comment]
Hello @dvarnai 

OS2 support allOf ? If not, I won't support it right now. The current implement works as expected even if it is not exactly the same mechanics.

One another point, allOf is not a an inheritance in the strict sense but rather the application of a set of constraints. Represent some usecases with allOf is not possible.
Example:

```typescript

export class Base {
   @Required()
   @Min(0)
   @Max(10)
   myNumber: number;
} 

export class Child extends Base {
   @Required()
   @Min(10)
   @Min(15)
   myNumber: number;
}
```

In this case, the allOf may not work properly because, each models have his one Min and Max constraints which are not compatible to each other.

This is why I made the decision to not use allOf to generate JsonSchema. :( Maybe I'm wrong but isn't straight forward ;)
See you
Romain

**Comment by dvarnai** [comment]
> Hello @dvarnai
> 
> OS2 support allOf ? If not, I won't support it right now. The current implement works as expected even if it is not exactly the same mechanics.
> 
> One another point, allOf is not a an inheritance in the strict sense but rather the application of a set of constraints. Represent some usecases with allOf is not possible.
> Example:
> 
> ```ts
> export class Base {
>    @Required()
>    @Min(0)
>    @Max(10)
>    myNumber: number;
> } 
> 
> export class Child extends Base {
>    @Required()
>    @Min(10)
>    @Min(15)
>    myNumber: number;
> }
> ```
> 
> In this case, the allOf may not work properly because, each models have his one Min and Max constraints which are not compatible to each other.
> 
> This is why I made the decision to not use allOf to generate JsonSchema. :( Maybe I'm wrong but isn't straight forward ;)
> See you
> Romain

Hi Romain!

Thanks for clearing that up. I'm not sure if it's supported in OpenAPI 2.

Best regards,
Daniel

**Comment by Romakita** [comment]
Hi @dvarnai 

I hope my given previous example is coherent for you ^^. I'm not close to this topic, I'd just want to challenge your needs and vice versa :)

See you
Romain

**Comment by dvarnai** [comment]
> Hi @dvarnai
> 
> I hope my given previous example is coherent for you ^^. I'm not close to this topic, I'd just want to challenge your needs and vice versa :)
> 
> See you
> Romain

Personally I just need it for two classes only, I can just use have those two classes without inheritance, it doesn't really matter as I only needed it for automatic client-side validation, which I can still do.

I was referring to the inheritance as described here by the way:

https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

I don't know if this existed in OS2 though.

**Comment by Romakita** [comment]
Thanks for the link. The OS2 doesn't support the polymorphism while OS3 yes. I think in v7 i'll remove the OS2 support and rework this part to use allOf instead of the current mechanism. :)
