### ISSUE TITLE
[BUG] Async factories are injected as Promises in the Server

### ISSUE THREAD

**Issue by dvarnai** [TypedProject/tsed#1065]
## Information

- **Version:** 6.x
- Packages: tsed/core

When an async factory is injected using the @Inject decorator to the Server provider, the Promise is not resolved. Using the old method, the injector service, it does get resolved properly.

## Example

export class Server {

    @Inject()
    app!: PlatformApplication;

    @Inject(REDIS)
    redis!: RedisClient; //<--- injected as Promise<RedisClient>

    constructor(private injectorService: InjectorService) {
    }

    public $beforeRoutesInit(): void {
        this.injectorService.get<RedisClient>(REDIS); //<--- injected propery as RedisClient
    }
}

## Acceptance criteria

- [ ] Bug resolved

**Comment by Romakita** [comment]
PR Ready :) #1067

**Comment by Romakita** [comment]
Released
