### ISSUE TITLE
[BUG] MergeSpec doesn't dedupe tags

### ISSUE THREAD

**Issue by dvarnai** [TypedProject/tsed#1076]
## Information

- **Version:** 6.x
- Packages: tsed/schema

MergeSpec ignores duplicate tags in the spec, resulting in an invalid swagger.json

**Comment by dvarnai** [comment]
PR ready #1077

**Comment by Romakita** [comment]
Merged and released :)

**Comment by Romakita** [comment]
v6.6.2
