### ISSUE TITLE
[BUG] Page Returns - /api/schema/decorators/operations/Returns

### ISSUE THREAD

**Issue by angelquin1986** [TypedProject/tsed#1085]
@Returns(404, Model) no generate schema  documentation for 400(s) error  for swagger 
![image](https://user-images.githubusercontent.com/32068691/99025171-35712000-2536-11eb-9f9e-49e6931850f8.png)

the swagger json 
![image](https://user-images.githubusercontent.com/32068691/99025395-bc25fd00-2536-11eb-91a9-94ec6d4226b1.png)

**Comment by Romakita** [comment]
@angelquin1986 Yes the PR #1084 should solve the issue :)

**Comment by angelquin1986** [comment]
> @angelquin1986 Yes the PR #1084 should solve the issue :)
> 
> Have you added at least `@Property` decorator on your properties model?

of  course have @Property
![image](https://user-images.githubusercontent.com/32068691/99112112-2b453500-25bb-11eb-865c-8f54bbe2473e.png)

**Comment by Romakita** [comment]
The latest version released solve rhe issue ;) can try it please?
Romain

**Comment by angelquin1986** [comment]
ok thanks
