### ISSUE TITLE
[BUG] Swagger doesn't generate ui to upload file

### ISSUE THREAD

**Issue by arturrozputnii** [TypedProject/tsed#1092]
## Information

-   "@tsed/ajv": "^6.8.1",
    "@tsed/common": "6.8.1",
    "@tsed/core": "6.8.1",
    "@tsed/di": "6.8.1",
    "@tsed/exceptions": "^6.8.1",
    "@tsed/passport": "6.8.1",
    "@tsed/platform-express": "^6.8.1",
    "@tsed/swagger": "^6.8.1",
    "@tsed/typeorm": "^6.8.1",
    "@tsed/schema": "^6.8.1",
    "@tsed/json-mapper": "^6.8.1",
    "@types/multer": "^1.4.4",
    "@types/swagger-schema-official": "^2.0.21",
    "@tsed/multipartfiles": "^5.65.10",

After update TS.ED to v6 swagger has stopped to generate ui to upload file (also switched to OAS3). Maybe some new specific config for swagger or decorators for controllers? It was working fine with latest TS.ED v5. Attached example of my code

## Example

created simple controller to test it
```
import {Controller, MulterOptions, MultipartFile, Put} from "@tsed/common";
import {Returns} from "@tsed/schema";

@Controller("/upload")
export class UploadController {

    @Put("/")
    @Returns(201, {description: "Created"})
    @MulterOptions({dest: `${process.cwd()}/.tmp`})
    async add(@MultipartFile("file") file: MultipartFile): Promise<any> {
        return true;
    }
}

```

part of config from Server.ts
```
    swagger: [
        {
            path: "/swagger",
            specVersion: "3.0.1",
            specPath: `${rootDir}/swagger.json`,
            options: {
                oauth2RedirectUrl: "http://localhost:8083/swagger/oauth2-redirect.html",
                oauth: {
                    clientId: ******,
                    clientSecret: ******,
                    scopes: ["openid"]
                }
            }
        }
    ],

```

my swagger.json
```
{
  "openapi": "3.0.1",
  "paths": {},
  "info": {}
  },
  "security": [
    {
      "Google_oauth": []
    }
  ],
  "components": {
    "securitySchemes": {
      "Google_oauth": {
        "type": "oauth2",
        "description": "Use simple OAuth2 mechanism to receive token from Google",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
            "tokenUrl": "https://oauth2.googleapis.com/token"
          }
        },
        "x-tokenName": "id_token"
      }
    }
  }
}

```

## Acceptance criteria

- generate correct documentation;
- allow to upload file via Swagger UI;

**Comment by Romakita** [comment]
@arturrozputnii 
You have to remove @tsed/multipartfiles dependency. A recent PR by @dvarnai had fixed that. I’ll check it tomorrow.
See you

**Comment by arturrozputnii** [comment]
ok, thx, will check it too.

**Comment by arturrozputnii** [comment]
confirm, it works, sorry about noise, didn't know that was fixed. Thx @Romakita @dvarnai

**Comment by Romakita** [comment]
No worries ;)
