### ISSUE TITLE
[BUG] Cannot read property '$selfRequired' of undefined

### ISSUE THREAD

**Issue by silveoj** [TypedProject/tsed#1100]
## Information

- **Version:** 6.10.2
- Packages: 
```
    "@tsed/ajv": "6.10.2",
    "@tsed/common": "6.10.2",
    "@tsed/core": "6.10.2",
    "@tsed/di": "6.10.2",
    "@tsed/exceptions": "6.10.2",
    "@tsed/platform-express": "6.10.2",
    "@tsed/schema": "6.10.2",
    "@tsed/swagger": "6.10.2",
    "@tsed/typeorm": "6.10.2",
```
1. I replaced `GlobalErrorHandlerMiddleware` to `ExceptionFilterMethods`.
Also I removed `"@tsed/multipartfiles"` 5.65.
I replaced (and reverted later) some deprecated `swagger`/`common` decorators to `schema` (all of from doc: WARNING These decorators have moved from @tsed/common/@tsed/swagger to @tsed/schema)
I get

```
TypeError: Cannot read property '$selfRequired' of undefined
    at \node_modules\@tsed\schema\src\utils\getRequiredProperties.ts:13:16
    at Array.reduce (<anonymous>)
    at Object.getRequiredProperties (\node_modules\@tsed\schema\src\utils\getRequiredProperties.ts:12:57)
    at Object.serializeJsonSchema (\node_modules\@tsed\schema\src\utils\serializeJsonSchema.ts:278:9)
    at Map.toJSON (\node_modules\@tsed\schema\src\domain\JsonSchema.ts:748:20)
    at serializeAny (\node_modules\@tsed\schema\src\utils\serializeJsonSchema.ts:175:26)
    at Object.serializeItem (\node_modules\@tsed\schema\src\utils\serializeJsonSchema.ts:110:68)
    at Map.toJSON (\node_modules\@tsed\schema\src\domain\JsonParameter.ts:65:24)
    at Map.toJSON (\node_modules\@tsed\schema\src\domain\JsonOperation.ts:223:62)
    at \node_modules\@tsed\schema\src\utils\getSpec.ts:111:51
    at Map.forEach (<anonymous>)
    at \node_modules\@tsed\schema\src\utils\getSpec.ts:110:32
    at get (\node_modules\@tsed\schema\src\utils\getSpec.ts:62:20)
    at Object.getSpec (\node_modules\@tsed\schema\src\utils\getSpec.ts:99:10)
    at SwaggerService.buildRoutes (\node_modules\@tsed\swagger\src\services\SwaggerService.ts:115:12)
    at \node_modules\@tsed\swagger\src\services\SwaggerService.ts:48:27
    at Array.forEach (<anonymous>)
    at SwaggerService.getOpenAPISpec (\node_modules\@tsed\swagger\src\services\SwaggerService.ts:43:26)
    at \node_modules\@tsed\swagger\src\SwaggerModule.ts:70:40
    at Array.forEach (<anonymous>)
    at SwaggerModule.$onRoutesInit (\node_modules\@tsed\swagger\src\SwaggerModule.ts:68:19)
    at Map.emit (\node_modules\@tsed\di\src\class\LocalsContainer.ts:15:34)
```

2. https://tsed.io/api/schema/decorators/common/Schema.html#overview there is typo in `use 
UseSchema`  -> `use Schema`

I don't know root cause. Of course I try to debug `tsed` code. But maybe you know cause)

**Comment by Romakita** [comment]
@silveoj It's a bit strange. It mean on of the props are note defined...

I'll fix that, but I'm curious about the reason. Can you given a reproducible example please :)

**Comment by Romakita** [comment]
There is no Typo ==> UseSchema have been renamed by Schema.

**Comment by Romakita** [comment]
I create a small PR to avoid this error, but without a reproducible example, I don't If it fix correctly the issue or create another issue. :) 
Thanks for you help @silveoj

**Comment by silveoj** [comment]
Thanks. It works now. I will test my app but I'm not sure I can reproduce it in small example app for you.

What about `additionalProperties` in AJV options https://ajv.js.org/keywords.html#additionalproperties
You don't have it in TS.

_You can close it._

**Comment by Romakita** [comment]
https://tsed.io/api/schema/decorators/common/AdditionalProperties.html#app This?

**Comment by silveoj** [comment]
here
```
@Configuration({
  // ...
  ajv: {
    errorFormatter: (error) =>  `error description ...`,
    allErrors: true,
    additionalProperties: true, // --> HERE
  } as any, // --> any because "is not assignable to type 'IAjvSettings'"
})
```
I use this property and this property works (as minimum until v.6)

**Comment by Romakita** [comment]
Haaa is just because the definition type his missing... ok. Small fix :)

**Comment by silveoj** [comment]
About `@MulterOptions` from `@tsed/common`

Add `fileFilter` into `interface MulterOptions`

```
@MulterOptions({
  storage: ...,
  fileFilter: (req, file, callback) => { // describe it in MulterOptions interface
    // ...
  },
})
```

**Comment by Romakita** [comment]
Hello @silveoj ,
After reading the AJV documentation, I don't see the additionalProperties as a part of global Ajv option: https://github.com/ajv-validator/ajv/blob/master/docs/api.md#options

AdditionalProperties is only available for the schema definition here (mentioned by you): https://ajv.js.org/keywords.html#additionalproperties

The equivalent with Ts.ED is the `@AdditionalProperties` decorator: 

https://tsed.io/api/schema/decorators/common/AdditionalProperties.html

Before v6 this properties doesn't exists on Ajv but on converters yes. This option works only for the converters/json-mapper. But it would be preferable to use AdditionalProperties decorator on your Model.

```@typescript
@AdditionalProperties(true)
class MyClass {
   [key: string]: any;
} 
```

The IAjvSettings inherit from the .d.ts provided by Ajv. If the author doesn't mention this props in his interface. I'm surprised that about the effect of this code, if ajv instance doesn't use it:
```typescirpt
@Configuration({
  // ...
  ajv: {
    errorFormatter: (error) =>  `error description ...`,
    allErrors: true,
    additionalProperties: true, // --> HERE
  } as any, // --> any because "is not assignable to type 'IAjvSettings'"
})
```

See you
Romain

**Comment by Romakita** [comment]
@silveoj I found a way to have a depreciation warning with: @Returns(200, { type: MyClass})
The documentation will be updated for the v6.10.4 :)
