### ISSUE TITLE
[QUESTION] GlobalErrorHandlerMiddleware and Exception filter have difference

### ISSUE THREAD

**Issue by silveoj** [TypedProject/tsed#1102]
In v.5 we use `@Middleware() GlobalErrorHandlerMiddleware` which `implements IMiddlewareError`.
In v6 we use `@Catch(Exception)` which `implements ExceptionFilterMethods`.
But they work differently with standard `throw [new] Error(...)`

```
@Get('/my-get')
public async myGet(
  throw Error('my error'); // only in v5
  // throw new BadRequest('my error'); // both v5 and v6
}
```

`GlobalErrorHandlerMiddleware` handles both `throw Error` AND `throw new BadRequest`
But `Catch` handles only `throw new BadRequest`. And skips `throw Error`.
Temporarly solution for me in v6: whatever use `GlobalErrorHandlerMiddleware` without `implements IMiddlewareError`.

Thanks.

**Comment by Romakita** [comment]
To catch all error you can use this example:

```typescript
@Catch(Error)
export class ErrorFilter implements ExceptionFilterMethods {

}
```

**Comment by silveoj** [comment]
in v6 do I need to use 2 filters?
- @Catch(Exception) - for TSED errors
- @Catch(Error) - for standard JS errors

**Comment by Romakita** [comment]
If you define two filters, the best appropriate filter will be used. 

But you can handler all errors (Exceptions and Error) with only one filter :)

**Comment by silveoj** [comment]
Oh, exactly. I can use `Catch` twice
```
@Catch(Error)
@Catch(Exception)
```

But I will divide them. It will be more readable.
Thanks!
