### ISSUE TITLE
[QUESTION] How to Send Packets to Clients

### ISSUE THREAD

**Issue by LiteSun** [TypedProject/tsed#1114]
I use the code below to try to send `file.tar.gz` to the client, but nothing happened.

```ts
@Controller("/release")
export class ReleaseControllers {
  @Get("/")
  async get(
    @QueryParams("url") url: string,
    @Res() res: any
  ): Promise<any> {
    res.download('/path-to-file')
  }
}
```

Can anyone tell me how to make this happen? 👀👀👀

**Comment by Romakita** [comment]
Hello @LiteSun 

Your answer is in this page: https://tsed.io/docs/controllers.html#observable-stream-buffer

You can return a stream or a buffer. `res.download` is a pur Express approach. It's preferable to use a nodejs approach :)


```typescript
import {createReadStream, ReadStream} from "fs";

@Controller("/")
export class KindOfResponseCtrl {
  @Get("/stream")
  stream(): ReadStream {
    return createReadStream(__dirname + "/response.txt");
  }

  @Get("/stream")
  buffer(): Buffer {
    return Buffer.from("Hello");
  }
}
```

See you
Romain
