### ISSUE TITLE
TypeScript-Babel setup

### ISSUE THREAD

**Issue by trailblazer2006** [TypedProject/tsed#1115]
I tried to set up TypeScript-Babel in the tsed example project as described here https://github.com/microsoft/TypeScript-Babel-Starter. Unfortunately, I got the following error just at startup.
![image](https://user-images.githubusercontent.com/5860308/100355485-e7165380-3002-11eb-96ec-950443b71e8d.png)
Do you have any idea why this is happening?

My server.ts is

```typescript
import {Configuration, Inject, PlatformApplication} from "@tsed/common";
import "@tsed/platform-express";
import "@tsed/swagger";
import * as bodyParser from "body-parser";
import * as compress from "compression";
import * as cookieParser from "cookie-parser";
import * as cors from "cors";
import * as methodOverride from "method-override";
import {join} from "path";

const rootDir = __dirname;

@Configuration({
  rootDir,
  acceptMimes: ["application/json"],
  httpPort: process.env.PORT || 8083,
  httpsPort: false, // CHANGE
  logger: {
    debug: true,
    logRequest: true,
    requestFields: ["reqId", "method", "url", "headers", "query", "params", "duration"]
  },
  mount: {
    "/rest": [
      `${rootDir}/controllers/**/*.ts` // Automatic Import, /!\ doesn't works with webpack/jest, use  require.context() or manual import instead
    ]
  },
  componentsScan: [
    "${rootDir}/mvc/**/*.ts",
    "${rootDir}/services/**/*.ts",
    "${rootDir}/middlewares/**/*.ts"
  ],
  swagger: [
    {
      path: "/api-docs"
    }
  ],
  calendar: {
    token: true
  },
  statics: {
    "/": join(__dirname, "..", "statics")
  }
})
export class Server {
  @Inject()
  app: PlatformApplication;

  /**
   * This method let you configure the middleware required by your application to works.
   * @returns {Server}
   */
  $beforeRoutesInit(): void | Promise<any> {
    this.app
      .use(cors())
      .use(cookieParser())
      .use(compress({}))
      .use(methodOverride())
      .use(bodyParser.json())
      .use(bodyParser.urlencoded({
        extended: true
      }));

    return null;
  }
}
`

**Comment by Romakita** [comment]
Hello @trailblazer2006,
I don't know, supporting Babel-Typescript project isn't in the scope actually. Is it possible to have a repo example ?
See you
Romain

**Comment by trailblazer2006** [comment]
Hi @Romakita.

Here is a fork of your repo with Babel-Typescript config https://github.com/trailblazer2006/tsed-getting-started.git
You can reproduce the error by running `npm run start:babel` script.

Thank you in advance,
Alexander.

**Comment by Romakita** [comment]
@trailblazer2006 
there some other issues with babel. I'll make a PR on repo  with all fixes ;)
Romain

**Comment by trailblazer2006** [comment]
Thanks. You've been very helpful.
Sincerely, Alexander

**Comment by Romakita** [comment]
Hello @trailblazer2006 

Ts.ED cli support also webpack/babel bundler option ;)

See you

**Comment by trailblazer2006** [comment]
I'd suggest to change documentation for the cli to `npx @tsed/cli init` as in [create-react-app](https://github.com/facebook/create-react-app). This will allow you to always run the latest version of the cli.

**Comment by Romakita** [comment]
Hum... No sure, npx hasn't the same effect has `npm install -g @tsed/cli`. The CLI must be installed in global modules, like Angular CLI and Vue CLI. There is no reason to install CLI as a project dependencies :)

**Comment by trailblazer2006** [comment]
AFAIK `npx` just runs the package without installing (in reality it installs the package and then runs and deletes it). This way, you will always run the latest version of Ts.ED cli, without installing it globally and sticking at that version. For one-time run applications, this is the best way to use `npx ` instead of `npm i -g` IMO.
Alexander.

**Comment by Romakita** [comment]
ok :)

**Comment by trailblazer2006** [comment]
@Romakita Thanks for the explanation and your patience. Alexander.
