### ISSUE TITLE
[QUESTION] Multer how to upload after some conditions

### ISSUE THREAD

**Issue by EduFdezSoy** [TypedProject/tsed#1116]
I'm struggling with a file upload, I want to upload a file but only after checking other params but I don't know how to do it, it always ends with the file uploaded.
As far as I know now multer has a function to remove an uploaded file, I think that would work too but I don't know how to call it either way

I'm stuck, please **help**

here is my test code:
```typescript
@Controller("/upload") 
export class UploadController {
  @Post("/:id")
  @Returns(200)
  @Returns(404, NotFound)
  post(
    @PathParams("id") id: number,
    @MultipartFile("file") file: PlatformMulterFile
  ) {
    if (id != 1) {
      throw new NotFound("ID not found");
    }
  }
}
```

_I dont know if you, reader, can help me, but thank you :)_

**Comment by Romakita** [comment]
Hello @EduFdezSoy 

In multer documentation there is no documentation about a function to remove an uploaded file. https://www.npmjs.com/package/multer . By using Fs, you can remove the file easily.

```typescript
@Controller("/upload") 
export class UploadController {
  @Post("/:id")
  @Returns(200)
  @Returns(404, NotFound)
  post(
    @PathParams("id") id: number,
    @MultipartFile("file") file: PlatformMulterFile
  ) {
    if (id != 1) {
      fs.unlinkSync(file.path)
      throw new NotFound("ID not found");
    }
  }
}
```

See you
Romain

**Comment by EduFdezSoy** [comment]
The thing is I wrote my own storage engine and it has a method `_removeFile` but I guess its only internal to multer 

I'll try to write something like that, many thanks

**Comment by EduFdezSoy** [comment]
I was able to do what I has in mind, thank you again Romain
