### ISSUE TITLE
[BUG] Defining a service as a DataSourceService makes the PlatformTest.get always returns undefined

### ISSUE THREAD

**Issue by ghmendonca** [TypedProject/tsed#1118]
## Information

- **Version:** 6.11.3

I was implementing some unit tests and I discovered that if you adds the `@DataSourceService()` to a class, the `PlatformTest.get()` will always returns undefined. If I declare with the `@Service()` decorator, it works fine, but in my case I am also implementing integration tests for my graphql api and I want to use the `@Ctx('dataSources')` to get my service in my query.

## Example

```
@DataSourceService()
export class MyService {
    async test(): Promise<number> {
        return 10
    }
}

```

```
it("should return a number", async () => {
    const myService = PlatformTest.get<MyService>(MyService);

    console.log(myService)
})
```

In this example the variable `myService` is undefined.

**Comment by Romakita** [comment]
Hello @ghmendonca 

Use invoke method ;)

See you
Romain

**Comment by ghmendonca** [comment]
It works, thanks!

I am curious, why doesn't work using the get method? Isn't suppose to work as expected?

**Comment by Romakita** [comment]
Because get method doesn’t look on external DI. Your datasource class is created by typegraphql.

I don’t remember exactly why is not available throught the get method xD
