### ISSUE TITLE
[QUESTION] How to set Express App Setting with V6

### ISSUE THREAD

**Issue by c1moore** [TypedProject/tsed#1135]
With v5, you used to be able to set express app setting as shown in the code snippet on [this page](https://tsed.io/docs/platform-api.html#create-application) that used `ServerLoader`.  Now it looks like you need to inject the app into the Server.  That works, but I can't figure out how to set the express app settings (specifically the `query parser` setting).  I've tried the following:

```typescript
@Configuration({
  /* ... */
})
export default class Server {
  @Inject()
  app!: PlatformApplication<Application>;

  $beforeRoutesInit(): void {
    this.app.getApp().set('query parser', (queryString: string): any => parse(queryString, {
      comma: true,
      allowDots: true,
      depth: 5,
    }));

    this.app
      .use(cors())
      .use(bodyParser.json())
      .use(bodyParser.urlencoded({ extended: true }))
      .use(ErrorHandler);
  }
}
```

But it doesn't seem to use the specified query parser.

**How do I specify the query parser that TS.eD should use?**

**Comment by Romakita** [comment]
Hello @c1moore 
Sorry for the late answer. Your example should works. 

You can try this:
```typescript
@Configuration({
  /* ... */
})
export default class Server {
  @Inject()
  app!: PlatformApplication<Application>;

  $onInit(): void {
    this.app.getApp().set('query parser', (queryString: string): any => parse(queryString, {
      comma: true,
      allowDots: true,
      depth: 5,
    }));
 }
 $beforeRoutesInit(): void {
    this.app
      .use(cors())
      .use(bodyParser.json())
      .use(bodyParser.urlencoded({ extended: true }))
      .use(ErrorHandler);
  }
}
```
See you
Romain

**Comment by c1moore** [comment]
I tried that suggestion @Romakita and it's still not working.  I'm testing by sending a query string that contains a comma list and the comma list isn't being split into an array.

**Comment by Romakita** [comment]
H
