### ISSUE TITLE
[QUESTION] Programatically set cal hooks

### ISSUE THREAD

**Issue by pirouet** [TypedProject/tsed#1159]
Hi,

Out of curiosity, is there a way to configure the middleware that runs in $beforeRoutesInit and $afterRoutesInit without invoking these methods specifically. I am working on creating my own wrapper around tsed and this ability would be perfect

As it stands, I can use configuration and other ways to set specific details but the middleware is throwing me off. Would I simply use the underlying `use()` method, or something else that needs to be developer?

Michael

**Comment by Romakita** [comment]
Hello @pirouet 
You can create you custom configuration key on Server level then consume it in the middleware:

```typescript
@Configuration({
  myConfig: {}
})
class Server {}
```

```typescript
@Middleware()
class MyMiddleware {
  @Constant('myConfig')
  protected myConfig: any;
}
```

See you
Romain :)

**Comment by pirouet** [comment]
Ah of course, I forgot about the `@Constant` decorator!

Thank you very much

Michael
