### ISSUE TITLE
[QUESTION] @MongoosePlugin help

### ISSUE THREAD

**Issue by Swanty** [TypedProject/tsed#1164]
Hello, I am trying to use `@MongoosePlugin`, but when I try the sample code from documentation https://tsed.io/tutorials/mongoose.html#plugin I get error `Function implementation is missing or not immediately following the declaration.`

I am using example project from https://github.com/TypedProject/tsed-example-mongoose
and I want to test `@MongoosePlugin` so I added code from tsed plugin doc to Calendar model:

```
import {Property, Required} from "@tsed/common";
import {Model, ObjectID} from "@tsed/mongoose";
import * as findOrCreate from "mongoose-findorcreate";

@Model()
@MongoosePlugin(findOrCreate)
export class Calendar {
  static findOrCreate(condition: InstanceType<any>):
    Promise<{doc: InstanceType<any>, created: boolean}>;

  @ObjectID("id")
  _id: string;

  @Required()
  name: string;

  @Property()
  owner: string;
}
```

How to properly add mongoose plugins like the one mentioned in tsed doc `mongoose-findorcreate`?
Sorry if this is a dumb question, but I really can't figure out how to make this work.

**Comment by Romakita** [comment]
Hello @Swanty 
Based on the module documentation, you have to export extra type to have the right type checking.

```typescript
import {Property, Required} from "@tsed/common";
import {Model, ObjectID} from "@tsed/mongoose";
import * as findOrCreate from "mongoose-findorcreate";

@Model()
@MongoosePlugin(findOrCreate)
export class Calendar {
  @ObjectID("id")
  _id: string;

  @Required()
  name: string;

  @Property()
  owner: string;
}

export type CalendarModel = MongooseModel<Calendar & {
    findOrCreate(condition: InstanceType<any>): Promise<{doc: InstanceType<any>, created: boolean}>;
}>


@Injectable()
export class CalendarRepository {
  @Inject(Calendar)
  private calendarModel: CalendarModel;
  
  upsert(){
     this.calendarModel.findOrCreate()
  }
}
```

But.... this module is really necessary? Because mongoose has an upsert method which create an instance if the instance doesn't exists in db...

See you
Romain

**Comment by Romakita** [comment]
https://mongoosejs.com/docs/tutorials/findoneandupdate.html

**Comment by Swanty** [comment]
Thank you very much
