### ISSUE TITLE
[BUG] @OnDeserialize decorator isn't called on type array

### ISSUE THREAD

**Issue by CharleyPONS** [TypedProject/tsed#1171]
## Information

- **Version:** 6.14.2
- Packages: 

When i applied OnDeserialize decorator on a property of a class if the type is Array<any> the function isn't called

## Example

Simple exemple to reproduce quickly

Model =>
```
import {OnDeserialize} from "@tsed/json-mapper";

export class A {
    @OnDeserialize( b =>
        b.filter((v: string) => v === 'test'))
    b: string[]
}

```
Controller =>

```
import {BodyParams, Controller, Post} from "@tsed/common";
import {A} from "./a.model";

@Controller("/hello-world")
export class HelloWorldController {
  @Post("/")
  get(@BodyParams() t: A) {
    return t.b;
  }
}

```

**Comment by Romakita** [comment]
Hello @CharleyPONS 

As I see, you've forgot to use the CollectionOf decorator:

```typescript
import {OnDeserialize} from "@tsed/json-mapper";
import {CollectionOf} from "@tsed/schema";

export class A {
    @CollectionOf(String)
    @OnDeserialize( b =>
        b.filter((v: string) => v === 'test'))
    b: string[]
}
```
I think it should solve your issue :) 

See you
Romain

**Comment by CharleyPONS** [comment]
Hello @Romakita, 
Ok this is a change from the previous version, it is noted thank you for your answer.

See you,
Charley
