### ISSUE TITLE
[QUESTION] Global Headers (swagger parameters)

### ISSUE THREAD

**Issue by bkniffler** [TypedProject/tsed#1173]
Say I define a global parameter in my specs like this:
```
parameters: {
      tenantId: {
        in: 'header',
        name: 'X-TENANT-ID',
        required: false,
        schema: {
          type: 'string',
        },
      },
    }
```

Is there any way to add the `tenantId` header to my controllers without manually defining a HeaderParams in all my routes?

**Comment by Romakita** [comment]
Hello @bkniffler 

You can use the `@In` decorator on a class to apply your header for all methods.

```typescript
@Controller('/')
@In('header').Name('tenantId').Description('The tenant ID')
class MyController {

}  
```

See you
Romain

**Comment by bkniffler** [comment]
Hey, thanks @Romakita! Is there any way to add a $ref to the global parameter instead of having to redefine the tenantId on each of my controllers?

<img width="592" alt="Bildschirmfoto 2021-01-05 um 14 29 45" src="https://user-images.githubusercontent.com/4349324/103651831-76981600-4f62-11eb-970f-ab137b84b9a7.png">

Thanks for your help, really appreciate it!

**Comment by bkniffler** [comment]
Oops, never mind, the In().Schema function accepts $ref! Thanks :)

**Comment by Romakita** [comment]
^^
