### ISSUE TITLE
[QUESTION] Version 5.1.1. ServerLoader keeps trying to load services from *.ts files, componentsScan is empty. Any ideas?

### ISSUE THREAD

**Issue by carlosdubus** [TypedProject/tsed#1176]
I can't upgrade at the moment.

I'm running the server as plain Javascript (compiled) but ServerLoader keeps trying to import TS files, crashing the server.

Any ideas? componentsScan is an empty array.

**Comment by Romakita** [comment]
Hello @carlosdubus 
I need a reproducible example. But this problem is probably fixed in next version after 5.1.1.
See you
Romain

**Comment by carlosdubus** [comment]
Closed this. The issue was caused TypeORM, not tsed. Thanks for the quick reply.
