### ISSUE TITLE
[QUESTION] Injection error

### ISSUE THREAD

**Issue by LFSousa** [TypedProject/tsed#1179]
I'm trying to inject a service on my server, and receiving this error:

INJECTION_ERROR: Injection failed on AccountServer > IAccountService > IAccountRepository > AccountRegistry > MONGOOSE_CONNECTIONS
Origin: MONGOOSE_CONNECTIONS provider is not injectable to another provider

The `AccountServer` is the injection that causes trouble.
I'm injecting the `IAccountService` in some controllers
The `AccountRegistry` is my mongoose model, and works fine without the new injection at Server.

I didn't found anything like this in other topics. 

Can someone help me?

**Comment by Romakita** [comment]
Did you use @inject decorator or the constructor?

**Comment by LFSousa** [comment]
I'm using the @Inject

**Comment by Romakita** [comment]
Ok I need a reproducible repo example please :)
