### ISSUE TITLE
Add mongoose version check

### ISSUE THREAD

**Issue by freez10** [TypedProject/tsed#1181]
After upgrade of mongoose from 5.11.8 to 5.11.11 I've got a lot of "TS7006: Parameter 'result' implicitly has an 'any' type" errors
This happens because of "Since mongoose v5.11.0, the module expose his own file definition" as already mentioned in the documentation https://tsed.io/tutorials/mongoose.html#features

I think maybe it worth implementing a version check using `mongoose.version` and print the warning in the console in order to help devs to eliminate the issue faster.

**Comment by Romakita** [comment]
Hello @freez10 

The problem is the warning won’t be displayed, because, you have to fix typescript issue before running the server ^^.
I have no idea to implement this control.

Romain
