### ISSUE TITLE
[QUESTION] PlatformResponse/SendResponse middleware

### ISSUE THREAD

**Issue by mopcweb** [TypedProject/tsed#1182]
Hi!

After updating from v5.x to v6.x i couldn't find any alternative to 
[PlatformResponseMiddleware](https://github.com/TypedProject/tsed/blob/v5.65.10/packages/common/src/platform/middlewares/PlatformResponseMiddleware.ts#L0-L0)
or
[SendResponseMiddleware](https://github.com/TypedProject/tsed/blob/v5.65.10/packages/common/src/platform/middlewares/SendResponseMiddleware.ts).

Can you please suggest how to handle such functionality in current version?

Thanks)

**Comment by Romakita** [comment]
Hello @mopcweb 

have you read the migration guide?
https://tsed.io/getting-started/migration-from-v5.html#migration-guide

The answer about response middleware is in ^^
see you

**Comment by mopcweb** [comment]
Hi @Romakita,

sorry, didn't see that page, i'll look through.
Thanks
