### ISSUE TITLE
[BUG] @BodyParams error if the body is an array

### ISSUE THREAD

**Issue by CharleyPONS** [TypedProject/tsed#1186]
## Information

- **Version:** 6.19.2
- Packages: 

If a body is juste an array, the body throw an error (even if the body isn't explicitly type). 
`Bad request on parameter "request.body".Value should be object.
`

## Example

```
import {} from "@tsed/common";

```

## Acceptance criteria

- [ ] Criteria 1

**Comment by Romakita** [comment]
Hello @CharleyPONS ,

I already had a unit which is cover this usecase and it works:
https://github.com/TypedProject/tsed/blob/production/packages/platform-test-utils/src/tests/testBodyParams.ts#L22
And: https://github.com/TypedProject/tsed/blob/production/packages/platform-test-utils/src/tests/testBodyParams.ts#L95

Can you give me more details :) 
See you
Romain

**Comment by CharleyPONS** [comment]
Hi @Romakita, 

I created a tiny project from scratch to make it easier, I give you the controller code and the error of the request.

```
@Controller("/hello-world")
export class HelloWorldController {
  @Post("/")
  @Returns(200).Description('return toto')
  get(@Required() @BodyParams() toto: any) {
  $log.info('vcevce');
  return toto;
  }
}
```

<img width="1092" alt="Capture d’écran 2021-01-13 à 19 52 35" src="https://user-images.githubusercontent.com/48423735/104496155-e482b400-55d8-11eb-8be7-24ff37af5bcb.png">

See you 
Charley

**Comment by Romakita** [comment]
Hello @CharleyPONS,

After investigation, it's indeed a breaking change introduced with v6. I won't fix this behavior because it'll generate some other issue / breaking change with the current version.

To fix this issue, use `@Any` decorator :)
I added a warning on the website (on controller page and migration guide). Here is the fix:

```typescript
import {BodyParams, Controller, Post} from "@tsed/common";
import {Any} from "@tsed/schema";

@Controller("/any")
export class AnyCtrl {
   // Breaking change with v5
  @Post()
  updatePayload1(@BodyParams() payload: any): any { // accept only Object
    console.log("payload", payload);

    return payload;
  }

   // Solution:
  @Post()
  updatePayload2(@BodyParams() @Any() payload: any): any { // accept all types
    console.log("payload", payload);

    return payload;
  }

  // Alternatives:
  @Post()
  updatePayload3(@BodyParams() payload: any[]): any[] { // accept array of any types
    console.log("payload", payload);

    return payload;
  }

  @Post()
  updatePayload3(@BodyParams(MyModel) payload: MyModel[]): MyModel[] { // accept array of MyModel
    console.log("payload", payload);

    return payload;
  }
}

```
