### ISSUE TITLE
[QUESTION] jwt protocol authenticated endpoint undefined @BodyParams and @MultiPartFile

### ISSUE THREAD

**Issue by gkois** [TypedProject/tsed#1189]
**Information**
- Version: 6.21.0

Hello,

I am trying to upload a file and some body params using jwt protocol authentication.
I identified that when, within the protocol $onVerify function, I call a service or a typeorm repo to get data, the controller endpoint has undefined body.

Just to mention, on the latest 5.x version it was working.

I have uploaded a demo with the issue.

**Example**
https://github.com/gkois/tsed-issue.git

My Regards

**Comment by Romakita** [comment]
Hello @gkois 
Thanks for the repository. I'll check that ASAP :)
