### ISSUE TITLE
[QUESTION] eslint: `Returns` from @tsed/schema is deprecated

### ISSUE THREAD

**Issue by silveoj** [TypedProject/tsed#1195]
```
    "@tsed/...": "6.21.0", // ... all @tsed 6.21.0
    "eslint": "7.17.0",
    "eslint-config-prettier": "7.1.0",
    "eslint-import-resolver-typescript": "2.3.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-prettier": "3.3.1",
```

I get warning in all files for all ```Returns``` decorators
```eslint```: ```Deprecated: Since 2020. Use chained decorator version instead.```

```
import { Returns } from '@tsed/schema'; // wavy line in editor

@Get('/touch-me')
 @Returns(200, MyModel) // class // warning // wavy line in editor
@Returns(200, Object) // JS object {} // warning // wavy line in editor
@(Returns(200, String).Description(`I'm OK`)) // JS primitive string // warning // wavy line in editor
public async touchMe(
  return 'ok';
}
```

```
class MyModel {
  name: string;
  size: string;
}
```

But I use chained decorator. Or don't?
Thanks.

**Comment by Romakita** [comment]
@silveoj Yes is it. Did you import the decorator from `@tsed/common` or `@tsed/schema` ?

**Comment by silveoj** [comment]
Now from @tsed/schema
```import { Returns } from '@tsed/schema';``` _(github didn't display import in start message)_

**Comment by silveoj** [comment]
Now from @tsed/schema
```import { Returns } from '@tsed/schema';``` _(github didn't display import in start message)_

It seems you marked this schema decorator as deprecated, then removed it. But I think something was wrong so you returned it again (with deprecated)

**Comment by Romakita** [comment]
The Returns decorator isn't deprecated, only one of the signature usage.

```typescript
/**
 * @deprecated Since 2020. Use chained decorator version instead.
 */
export function Returns(status?: string | number, model?: object): ReturnsChainedDecorators;
export function Returns(status?: string | number, model?: Type<any> | any): ReturnsChainedDecorators 
```

In my case, the depreciation warning is only emitted when I use the Returns decorator as follow:
```typescript
@Return(200, {description: 'description', ...})
```
If you use the Return decorator with chained syntax, the depreciation isn't emitted :).

Depreciation:
<img width="602" alt="Capture d’écran 2021-01-17 à 11 19 49" src="https://user-images.githubusercontent.com/1763311/104837620-0f5d5880-58b6-11eb-871d-1ced679cfd1f.png">

Ok:
<img width="602" alt="Capture d’écran 2021-01-17 à 11 20 00" src="https://user-images.githubusercontent.com/1763311/104837616-040a2d00-58b6-11eb-9ad7-b1d76c5333a8.png">

Ok:
<img width="675" alt="Capture d’écran 2021-01-17 à 11 20 14" src="https://user-images.githubusercontent.com/1763311/104837611-ff457900-58b5-11eb-981f-4420bc94cd91.png">

For me it's ok :)
See you
Romain

**Comment by silveoj** [comment]
I get warning for OK choices yet:
`@Return(200).Description('..')`
`@Return(200).Type(String).Description('..')`

But it's not big issue for me). Thanks
