### ISSUE TITLE
[QUESTION] Migration from GlobalAcceptMimesMiddleware to PlatformAcceptMimesMiddleware

### ISSUE THREAD

**Issue by silveoj** [TypedProject/tsed#1196]
`@tsed` v6.21.0

Before I used:
```import { GlobalAcceptMimesMiddleware } from '@tsed/common';

@Configuration({
  acceptMimes: ["application/json", "pdf and so on"],
  // ..
});

  public $beforeRoutesInit() {
    this.app
      .use(GlobalAcceptMimesMiddleware)
      // ..
}
```
It worked

Now `GlobalAcceptMimesMiddleware` is deprecated.
So I just replace it to `PlatformAcceptMimesMiddleware`
And now I get `Cannot read property 'get' of undefined` for each route.
```import { PlatformAcceptMimesMiddleware} from '@tsed/common';

@Configuration({
  acceptMimes: ["application/json", "pdf and so on"],
  // ..
});

  public $beforeRoutesInit() {
    this.app
      .use(PlatformAcceptMimesMiddleware)
      // ..
}
```

` .use(PlatformAcceptMimesMiddleware)` - If I delete this line it will work. Or we don't need to use it like GlobalErrorHandlerMiddleware?

**Comment by Romakita** [comment]
@silveoj just remove the PlatformAcceptMime. Ts.ED load the middleware automatically now :)

**Comment by silveoj** [comment]
Ok. Thanks.
But how can I check this middleware?

I set `acceptMimes: ['text/plain']`
Request header: `Accept: application/json, text/plain, */*` (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept)

And all routes work. It's good. But how to check middleware?)

**Comment by Romakita** [comment]
Middlewares? If your middleware is attached to an endpoint the accept mimes will works. For other global middleware isn't supported in v6, and I won't support this it. You can implement your own middleware for that :)

**Comment by silveoj** [comment]
I use it in `Configuration` decorator
```
@Configuration({
  acceptMimes: ['application/json'],
```

> Ts.ED load the middleware automatically now
So server checks for acceptMimes globally and throws me error if frontend sends `text/plain` for example?

**Comment by Romakita** [comment]
This config is to set the default behavior for all endpoints. I removed the middleware on global level because it has a side effect on other global middlewares which not return the expected content types.

**Comment by silveoj** [comment]
So I just remove `GlobalAcceptMimesMiddleware` and I don't need remove this:
```
Configuration({
  acceptMimes: ['application/json', 'application/pdf', ...],
```

Am I right?

**Comment by Romakita** [comment]
Ok sorry for the confusing answers. 

If you set the acceptMimes on configuration level, Ts.ED will call PlatformAcceptMimesMiddleware on each endpoints and get the better content-type between the server configuration and the `@Returns().ContentType()` decorator.

But now, in v6, the middleware is applied on route and not on global level. It means the PlatformAcceptMimesMiddleware won't be called for a middleware added on global level if this middleware send a response.

If you want to the same behavior for all middlewares/endpoints, you want register the PlatformAcceptMimesMiddleware on the server (like in v5).

 But You have this error: `Cannot read property 'get' of undefined` because the implementation is wrong in the middleware:

```typescript
/**
 * @middleware
 * @platform
 */
@Middleware()
export class PlatformAcceptMimesMiddleware implements IMiddleware {
  @Constant("acceptMimes", [])
  acceptMimes: string[];

  public use(@Context() ctx: Context): void {
    const {endpoint, request} = ctx;
    const mimes = uniq((endpoint.get("acceptMimes") || []).concat(this.acceptMimes));

    if (mimes.length && !request.accepts(mimes)) {
      throw new NotAcceptable(mimes.join(", "));
    }
  }
}
```
I think the fix could be:

```typescript
/**
 * @middleware
 * @platform
 */
@Middleware()
export class PlatformAcceptMimesMiddleware implements IMiddleware {
  @Constant("acceptMimes", [])
  acceptMimes: string[];

  public use(@Context() ctx: Context): void {
    const {endpoint, request} = ctx;
    const mimes = uniq((endpoint?.get("acceptMimes") || []).concat(this.acceptMimes)).filter(Boolean);

    if (mimes.length && !request.accepts(mimes)) {
      throw new NotAcceptable(mimes.join(", "));
    }
  }
}
```

**Comment by silveoj** [comment]
@Romakita Thanks
This fix is working example.

For example
```
Configuration({
  acceptMimes: ['text/plain'], // no json
```

In Postman (not in browser) I set request header
`accept:application/json`
It throws me NotAcceptable error.

Works as expected.

**Comment by Romakita** [comment]
Ok, I'll fix that ASAP :)
