### ISSUE TITLE
[QUESTION] Server-scoped DI override for a shared Service

### ISSUE THREAD

**Issue by reed-lawrence** [TypedProject/tsed#1197]
I have multiple servers in under the same file directory, that utilize shared generic Services

For example: 
`/shared/services/db.service.ts`

```typescript
@Injectable()
export class MySqlConfig implements PoolConfig { }

@Service()
export class DbService implements IDbService, OnDestroy {

  constructor(config: MySqlConfig) {
    this.core = new DbServiceCore(config);
  }

  private core: IDbService;

 // ...

}

```

The above is to be shared and used with the intent that each `Server` would override the DI for `MySqlConfig` and pass its own parameters in. Such as:

`/auth/server.ts`
```typescript
export const MySqlConfigAuth: PoolConfig = {
  host: 'localhost',
  // ...
  database:  'db_auth'
}

registerProvider({
  provide: MySqlConfig,
  useValue: MySqlConfigAuth
});
```

And this works in limited use. But when I then attempt to unit test, it seems that the `registerProvider` method, overrides that in a scope outside of the server instance. So that the DI is not appropriately resolving when I then bootstrap the server on the `PlatformTest`

I can confirm this, because the errors I am getting are because the wrong SQL configs are being injected into my services. 

**Is there a way I can register providers on a Server specific level?**

**Comment by Romakita** [comment]
Hello @reed-lawrence 

I think, you shouldn't use the useValue for this usecase. 

If you have a configuration related to a the server, you should use the `@Configuration` decorator.

```typescript
import {Configuration} from "@tsed/di";

@Configuration({
    mysql: {
      host: 'localhost',
      database:  'db_auth'
   }
})
export class Server {}
```
Then:

```typescript
@Service()
export class DbService implements IDbService, OnDestroy {
  constructor(@Configuration() configuration: Configuration) {
    const mysqlConfig = configuration.get('mysql')
    this.core = new DbServiceCore(mysqlConfig);
  }
}
```
Unit test:

```typescript

describe('DbService', () => {
    beforeEach(() => PlatformTest.create({
       mysql: {} // set props to you unit test
    })
    afterEach(PlatformTest.reset)
    it('should do something', async () => {
       const dbService = await PlatformTest.invoke(DbService, [])
    })
})
```

See you
Romain

**Comment by reed-lawrence** [comment]
Excellent!
