### ISSUE TITLE
[QUESTION] Best practice for serving files through API Endpoint (Not static)

### ISSUE THREAD

**Issue by reed-lawrence** [TypedProject/tsed#1199]
I have the following endpoint sitting behind some middlewares on the controller. There are complex visibilty permissions, and it fetches a file from a cloud host, these are not static files. 

```typescript
  @Get('/get/:filename')
  async GetFile(@PathParams('filename') filename: string, @Res() res: Response) {

    const buffer: Buffer = await this.storage.FetchFile(filename);

    res.setHeader('Content-Disposition', `inline;filename=${filename}`);
    res.setHeader('X-Content-Type-Options', "nosniff");
    res.setHeader('Content-Type', 'image/png');

    res.send(buffer);

  }
```

The above code works - sort of. It is downloading the image, not displaying it inline as expected. The documentation outlines how to serve static files, but that approach does not fit as I am not serving files that are located on the server - nor are publicly accessible. 

What is the best practice for serving files via endpoints?

**Comment by Romakita** [comment]
If you return directly the buffer it should works, no?

**Comment by reed-lawrence** [comment]
No it does not send as a renderable image unless I call `res.send(buffer)`

`return buffer` will return a 200, and the response size is as expected, but the image does not render by the browser.

**Comment by Romakita** [comment]
Yes because you have to set the Content-type at least.

**Comment by reed-lawrence** [comment]
I have tried to set the content type with both `res.contentType('png')` and `res.setHeader('Content-Type', 'image/png')`, and can confirm that these headers are displaying in the response. However its displaying as an empty `<img>` unless I use `res.send(buffer)`

**Comment by Romakita** [comment]
Is it possible to have a minimal reproducible example on a repository?

**Comment by reed-lawrence** [comment]
Not so much as a repo, but here is a minimum viable working example endpoint: 

```typescript

  @Get('/get-google')
  async GetGoogle(@Res() res: Response) {
    const http: SuperAgentStatic = agent();

    const image_res = await http.get('https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png');

    res.setHeader('Content-Disposition', 'inline;filename=googlelogo_color_272x92dp.png;');
    res.setHeader('X-Content-Type-Options', "nosniff");
    res.setHeader('Content-Type', 'image/png');
    
    // res.send(image_res.body); // Works
    return image_res.body; // Does not work

  }

```

**Comment by Romakita** [comment]
Perfect I work on it!

**Comment by Romakita** [comment]
@reed-lawrence The PR is ready. You can review it: https://github.com/TypedProject/tsed/pull/1210

See you
Romain
