### ISSUE TITLE
Use @Require only for specific group

### ISSUE THREAD

**Issue by bkniffler** [TypedProject/tsed#1200]
## Informations
@Group is neat to define properties that should appear in returned entities only (like id), but not in post/put. But if I'd like properties to be existent+optional in put requests (for updates), but existent+required in post request, I'd have to create 2 separate models right now.

**Describe the solution you'd like**
Not sure about the exact syntax, but maybe @Required could accept a group string.

**Alternative**
Maybe as an alternative, you could consider adding some kind of @Partial decorator for put.

**Comment by bkniffler** [comment]
A code example

## Group in Require
```
@Schema({ title: 'BankAccount', description: 'Represents a bankAccount.' })
export class BankAccountModel extends IdBaseModel {
  @Required('!update')
  @Title('Name')
  @Property()
  @Example('HSBC Business Account')
  public name: string;
  @Required('!update')
  @Title('Unique Reference')
  @Property()
  @Example('HSBC-1')
  public uniqueRef: string;
  @Required('!update')
  @Title('Meta Data')
  @Any()
  @Example({
    iban: 'DE02300209000106531065',
    bic: 'BYLADEM1001',
  })
  public metadata: any;
}
```


## Partial alternative
```
  @Put('/:id')
  @(Returns(200, BankAccountModel).ContentType('application/json'))
  @UseAuth(CustomAuthMiddleware, { role: ROLE.USER })
  public async update(
    @Context() context: Context,
    @PathParams('id') id: string,
    @BodyParams(BankAccountModel)
    @Partial()
    @Required()
    payload: Partial<BankAccountModel>
  ): Promise<BankAccountModel> {
     ....
  }
```

**Comment by Romakita** [comment]
Hello @bkniffler 
It will be complicated to reuse the Required decorator to implement your need, because Required already accept a list of params to define the allowed empty values (empty string, etc...).

```
Required("", null, 0)
```

The solution should be to create chained decorator or create a new decorator.

Solution 1:
```
@Required().Groups("!update")
```
Solution 2:
```
@RequiredGroups("!update")
```
See you

**Comment by bkniffler** [comment]
Thanks for the quick reply. Yes, sorry, I meant patch. `@Required().Groups("!update")` looks like a good solution to me

**Comment by Romakita** [comment]
I'll add this story to the board, but I'm not sure to have the time this week to implement that :)

**Comment by bkniffler** [comment]
No worries, hope its something you (and others) will find useful as soon as its there. Keep up the great work!

**Comment by alexdonh** [comment]
+1 for this

**Comment by Romakita** [comment]
The solution 1 will be implemented soon.

```
@Required().Groups("!update")
```
