### ISSUE TITLE
[QUESTION] PlatformTesting providers with @Scope('request') yields undefined

### ISSUE THREAD

**Issue by bkniffler** [TypedProject/tsed#1203]
Using PlatformTest to get a request scoped provider will return undefined. Changing scope fixes the issue. Is there any way to test with @Scope('request')? Is this a bug or is this expected because there is no request available while using PlatformTest.get?

```
@Injectable()
@Scope('request')
export class TraceService {
 ...
}

import { PlatformTest } from '@tsed/common';

describe('TraceService', () => {
  beforeEach(() => PlatformTest.create());
  afterEach(() => PlatformTest.reset());

  it('should log a trace', async () => {
    const trace = PlatformTest.get<TraceService>(TraceService);
    trace.start('Hi').log('Hi');
    expect(trace.toJSON(true).logs.length).toEqual(1);
  });
});
```

**Comment by Romakita** [comment]
Hello @bkniffler 
In this case, you need to invoke the provider. Ts.ED doesn't build the service with a scope different of SINGLETON.

```typescript
@Injectable()
@Scope('request')
export class TraceService {
 ...
}

import { PlatformTest } from '@tsed/common';

describe('TraceService', () => {
  beforeEach(() => PlatformTest.create());
  afterEach(() => PlatformTest.reset());

  it('should log a trace', async () => {
    const trace = await PlatformTest.invoke<TraceService>(TraceService);
    trace.start('Hi').log('Hi');
    expect(trace.toJSON(true).logs.length).toEqual(1);
  });
});
```

**Comment by bkniffler** [comment]
Excellent, it works! Thanks for your amazing work, I've started contributing via openCollective. We'll increase the amount as soon as our service goes life, tsed is helping us to build an API big time and does a much better job than nestJS for us, thanks to the openAPI first approach.
