### ISSUE TITLE
[QUESTION] Passport.js req.user and req.isAuthenticated() on routes protected by @Authorize / @UseAuth(PassportMiddleware)

### ISSUE THREAD

**Issue by gionkunz** [TypedProject/tsed#1204]
Hi there

Thanks for all your work on Ts.ED, I think it's a pretty awesome example of how powerful declarative decorator based APIs can ease development :-)

I have a problem which I tried to isolate and came to the point where I can replicate in an example from your documentation on CodeSandbox. I'm also not sure if I'm mistakenly assuming that this should be working.

I would like to be able to access the user object added by Passport login and serialization / deserialization process. Somehow, if I access the request object (@Req request: Request) and check of request.user or request.isAuthenticated within an authorized controller, I always get undefined and false respectively.

I'm not sure if it is in issue with the session or if it's an issue with serialization / deserialization. What I noticed is that the Passport Authenticator.serializeUser is called with the callback through the PassportModule.$onInit setup. However, PassportSerializerService.serialize / deserialize is never called. Might be related to that?

I forked the Passport.js CodeSandbox example and added some logs in the authenticated index controller to show that user and isAuthenticated do not properly work. 
https://codesandbox.io/s/tsed-swagger-with-authorization-forked-s8fvs?file=/src/controllers/pages/IndexCtrl.ts

Any help would be appreciated.
Cheers
Gion

**Comment by Romakita** [comment]
Hello @gionkunz 

In this case I don't know why the user isn't attached on req.user. I logged the request we have instead the `req.account` with the expected user info. The problem is problably about the passport configuration for passport-http. 

Isn't a Ts.ED issue.

See you :)

**Comment by gionkunz** [comment]
Hi thanks for the quick reply. `account` does not seem to be a property of TsED.Request. Where is the type which declares this property?

**Comment by Romakita** [comment]
It's passport :)

**Comment by gionkunz** [comment]
It's really weird... In passport, there seems to be a discrepancy between the authorize function:
https://github.com/jaredhanson/passport/blob/1fd591d5cdcf6516d9eb446216843223c0e020c4/lib/authenticator.js#L188-L193

Which stores the user object into `req.account` and then the `isAuthenticated` function from the Request patch:
https://github.com/jaredhanson/passport/blob/1fd591d5cdcf6516d9eb446216843223c0e020c4/lib/http/request.js#L83-L90

Checks on the property `req.user` if the user is logged in...

One thing I wonder about passport is this section here:
https://github.com/jaredhanson/passport/blob/1fd591d5cdcf6516d9eb446216843223c0e020c4/lib/middleware/authenticate.js#L248-L251

This section, at least in the constellation of @tsed/passport, prevents a "proper" (no idea if that's really what's needed) `req.logIn`, which would in fact set the correct `user` property on the Request. Since we're always entering `success` with the `assignProperty` option set to `account`, the login is skipped and user is directly assigned.

The `req.logIn` function as far as I understand, will do the assignment of the user object to `req.user` and also call the session login (serialize the user in the session).

After further debugging, I found that the `Authenticator` in passport distinguishes the following:
- `authenticate`: Authentication will be delegated to the authenticate function on the passport framework, which is always the connect framework and the authenticate middleware. It does not use a `assignProperty` option and therefore proceed with the whole `logIn` functionality (store in `req.user` and persist in session (if available) using serialization).
- `authorize`: Meant to support 3rd party authorization in addition to an existing logged-in user. For this reason, they did not want to override `req.user` and pass a `assignProperty` option to the framework set to `account`. However, what's really weird is that the connect framework (only implementation and statically added) does not support an authorize function, so the call will fallback to `authenticate` on the framework https://github.com/jaredhanson/passport/blob/1fd591d5cdcf6516d9eb446216843223c0e020c4/lib/authenticator.js#L192.

So, my take form this is that:
- Passport seems to have some unfinished business here
- Does have an unfinished concept with user and account for additional authorizations
- There's not really a difference in calling authorize or authenticate, except that the user will not be stored as primary user in passport and serialization does not work

The solution for me is quite simple :-) Since you have a decorator in Ts.ED `Authenticate` which calls `authenticate` on the passport Authenticator (primary user login, stored in req.user and serialization in session) and there is a `Authorize` decorator, which calls the shady `authorize` function in Authenticator, I will just only use the Authenticate decorator and avoid the Authorize decorator completely. Passort anyway doesn't re-authenticate if the user is already logged in.

I need to say, I lost so much time with this, that I would probably have been better by implementing a custom middleware for my authentication, than relying on passport, which seems to have too many under-construction code.

**Comment by Romakita** [comment]
Very Interesting. I never understood the difference between authorize and authenticate but now it's clear. Thanks. 
I'm so sorry for this waste of time :(

So the final solution is to change the decorator used in passport sandbox example:
```
/**
 * Set BasicAuth access on decorated route
 * @param options
 */
export function BasicAuth(options: AuthorizeOptions = {}) {
  return useDecorators(
    Authenticate("basic", options), // this line
    Security("basic"),
    Returns(401, Unauthorized).Description("Unauthorized"),
    In("header").Name("Authorization").Description("Basic authorization").Type(String).Required(false)
  );
}
```

But there something I have to do on `@tsed/passport`?
See you
Romain

**Comment by gionkunz** [comment]
Well, no need to say sorry :-) It's passport, which is indeed a bit a rabbit hole ;-) Yeah, I think it's just all the example which need to be updated. I think it's still valid if you offer the Authorize decorator, since there might be a use-case for oneone who needs a primary authentication and a secondary one. Although, I believe the way how passport handles this is pretty useless.
