### ISSUE TITLE
[QUESTION] Best practice or/and HOW-To do a HTTP Proxy 

### ISSUE THREAD

**Issue by olegs-hl** [TypedProject/tsed#1207]
How to implement an HTTP PROXY with tsed?
I want all requests, unless we have a controller for it, to be redirected to a different server, but could not find any info on how to do that. I am planning to use `http-proxy-middleware` library with tsed. Thank you.

**Comment by Romakita** [comment]
Hello @olegs-hl,

Here a simple example:
```typescript

@Configuration({})
class Server {
   @Inject()
   app: PlatformApplication;

    $afterRoutesInit() {
       this.app.use('/api', createProxyMiddleware({ target: 'http://www.example.org', changeOrigin: true }));
    }   
}
```
Then follow the documentation :) https://github.com/chimurai/http-proxy-middleware

See you
Romain
