### ISSUE TITLE
[QUESTION] addControllers

### ISSUE THREAD

**Issue by pirouet** [TypedProject/tsed#1213]
I noticed there is a method called [addControllers] taking an endpoint and then list of controllers to add in. I have tried to use this in past and the routes do not show up for consumption simply throwing a HTTP 500.

Is there something I am missing such as runLifecycle, or any other method configuration I need to use to allow it to be picked up and registered?

**Comment by Romakita** [comment]
Hello @pirouet 

This is a legacy ihnerited from v5. To be honest, I never really tried to use it since a long time, because the mount option doing the job. Can you share me your code pls? 
there is a need /usecase to use this method?

see you
Romain

**Comment by pirouet** [comment]
Thanks for the quick response! 

No specific need for it, I saw the method and was seeing if I could leverage it for something I am working on for dynamic controllers

**Comment by Romakita** [comment]
Ok :) I’ll try test this method tomorrow. But the right way to add controller dynamicly is to inject Platform and use addRoute :)

https://github.com/TypedProject/tsed/blob/production/packages/common/src/platform/services/Platform.ts#L61

addController is to add controller in the bootstrap function but you can add controller with mount option at this step.
