### ISSUE TITLE
[BUG] Failed to load API definition for swagger default configuration on Windows

### ISSUE THREAD

**Issue by EmilienLeroy** [TypedProject/tsed#1220]
## Information

- **Version:** 6.23.2
- Packages: Swagger

I just create a fresh project with the cli. I have only added Swagger as plugin and use Express. When I start the project and go into the swagger docs I get this error `Failed to execute 'fetch' on 'Window': Failed to parse URL from http://localhost:8083C:\v2\docs\swagger.json http://localhost:8083C:\v2\docs\swagger.json`

![image](https://user-images.githubusercontent.com/31723722/106108548-b197fe80-6148-11eb-84e0-b186a6504046.png)
 

## Configuration

```ts
@Configuration({
  rootDir,
  acceptMimes: ["application/json"],
  httpPort: process.env.PORT || 8083,
  httpsPort: false, // CHANGE
  logger: {
    disableRoutesSummary: isProduction
  },
  mount: {
    "/rest": [
      `${rootDir}/controllers/**/*.ts`
    ],
    "/": [IndexCtrl]
  },
  swagger: [
    {
      path: "/v2/docs",
      specVersion: "2.0"
    },
    {
      path: "/v3/docs",
      specVersion: "3.0.1"
    }
  ],
  views: {
    root: `${rootDir}/../views`,
    viewEngine: "ejs"
  },
  exclude: [
    "**/*.spec.ts"
  ]
})

```
I think this trouble is probably due to the `outFile` property on Windows. In the error message, the swagger path have a `c:\` between the base url and the path to the swagger json. For exemple here I think `resolve(join(path, fileName))` add the drive letter on windows :
https://github.com/TypedProject/tsed/blob/fa827e42c6d3458a0547489c7ca9b608f2805b90/packages/swagger/src/SwaggerModule.ts#L87
https://github.com/TypedProject/tsed/blob/fa827e42c6d3458a0547489c7ca9b608f2805b90/packages/swagger/src/SwaggerModule.ts#L106

This is the result on windows.
```js
const path = require("path");

// return C:\docs\v2\swagger.json on Windows
path.resolve(path.join('/docs/v2', 'swagger.json'));
```

I find this framework really impressing ! The work made is awesome. Keep it up like this 👍

**Comment by Romakita** [comment]
Hello @EmilienLeroy 

My bad, I totally forgot this point ^^'. The fix will be released in few minutes on NPM. 
Thanks for the issue!

Romain ;)

**Comment by EmilienLeroy** [comment]
Thanks @Romakita !
It works perfectly 😄
