### ISSUE TITLE
[QUESTION] One ResponseFilter with content-type changes content-type for all responses

### ISSUE THREAD

**Issue by silveoj** [TypedProject/tsed#1222]
```
    "@tsed/ajv": "6.23.3",
    "@tsed/common": "6.23.3",
    "@tsed/core": "6.23.3",
    "@tsed/di": "6.23.3",
    "@tsed/exceptions": "6.23.3",
    "@tsed/platform-express": "6.23.3",
    "@tsed/schema": "6.23.3",
    "@tsed/swagger": "6.23.3",
```

If I use `@ResponseFilter('application/json')` then `content-type` is `application/json` (`ctx.response.raw.headers` inside `transform` method)
If I use `@ResponseFilter('text/plain')` then `content-type` is `text/plain` (`ctx.response.raw.headers`  inside `transform` method) 

I need to return `image/png` so I use `@ResponseFilter('application/json')` to skip `get-png` endpoint. But Filter is called for png.
It works in v.5. with middleware.
Is it expected behavior? Thanks.

```typescript
@Configuration({
  // acceptMimes // skipped
  responseFilters: [MyResponseFilter],
});

@Get('/get-png')
@Returns(200).ContentType('image/png') // I don't use swagger in a lot of endpoints. But even it doesn't help me.
public getPng(
  @Res() response: Express.Response /* or PlatformResponse */
) {
  const raw = '...';
  const img = Buffer.from(
    this.getBase64(raw),
    'base64',
  );
  response.setHeader('Content-Type', 'image/png');
  return img;
}

@ResponseFilter('text/plain') // text/plain for example.
export class MyResponseFilter implements ResponseFilterMethods {
  transform(data: any, ctx: Context) {
    // `ctx.response.raw.headers` is always has `content-type` as `text/plain; charset=utf-8`
    return data;
  }
}

```

**Comment by Romakita** [comment]
Hello @silveoj 

Your problem isn't clear, but I tried to reproduce it here: https://github.com/TypedProject/tsed/pull/1224
Right now, all works fine. 

Can you create codesandbox or reproducible repository example please. I won't take more time to investigate on it without that ;)

See you
Romain

**Comment by silveoj** [comment]
Hello @Romakita 
I can't reproduxe it in sandbox. But I can reproduce it locally (export from sandbox).
[sandbox example](https://codesandbox.io/s/tsed-filter-by-content-type-example-297yp?file=/src/Server.ts)

 But I rephrase my issue:
I use `text/plain` filter
```
@ResponseFilter("text/plain") // text/plain for example.
export class MyResponseFilter implements ResponseFilterMethods {
  transform(data: any, ctx: Context) {
    console.log("MyResponseFilter");
    return {
      filter: 'text/plain',
    };
  }
}
```
I send JSON:
```
@Get("/send-json")
// @(Returns(200).ContentType("application/json"))
public sendJson(@Res() response: PlatformResponse) {
  // response.setHeader("Content-Type", "application/json");
  return {
    jsonexample: 1
  };
}
```
But `text/plain` filter is called for JSON. Postman gets `{"filter":"text/plain"}` response.
It will not be called if I add `@(Returns(200).ContentType("application/json"))` OR `response.setHeader("Content-Type", "application/json");`

**Comment by silveoj** [comment]
Hello @Romakita 
I can't reproduce it in sandbox. But I can reproduce it locally (export from sandbox).
[sandbox example](https://codesandbox.io/s/tsed-filter-by-content-type-example-297yp?file=/src/Server.ts)

So I rephrase my issue:
I use `text/plain` filter
```
@ResponseFilter("text/plain") // text/plain for example.
export class MyResponseFilter implements ResponseFilterMethods {
  transform(data: any, ctx: Context) {
    console.log("MyResponseFilter");
    return {
      filter: 'text/plain',
    };
  }
}
```
I send JSON:
```
@Get("/send-json")
// @(Returns(200).ContentType("application/json"))
public sendJson(@Res() response: PlatformResponse) {
  // response.setHeader("Content-Type", "application/json");
  return {
    jsonexample: 1
  };
}
```
But `text/plain` filter is called for JSON. Postman gets `{"filter":"text/plain"}` response.
It will not be called if I add `@(Returns(200).ContentType("application/json"))` OR `response.setHeader("Content-Type", "application/json");`

**Comment by silveoj** [comment]
Hello @Romakita 
I can't reproduce it in sandbox. But I can reproduce it locally (export from sandbox).
[sandbox example](https://codesandbox.io/s/tsed-filter-by-content-type-example-297yp?file=/src/Server.ts)

So I rephrase my issue:
I use `text/plain` filter
```
@ResponseFilter("text/plain") // text/plain for example.
export class MyResponseFilter implements ResponseFilterMethods {
  transform(data: any, ctx: Context) {
    console.log("MyResponseFilter");
    return {
      filter: 'text/plain',
    };
  }
}
```
I send JSON:
```
@Get("/send-json")
// @(Returns(200).ContentType("application/json"))
public sendJson(@Res() response: PlatformResponse) {
  // response.setHeader("Content-Type", "application/json");
  return {
    jsonexample: 1
  };
}
```
But `text/plain` filter is called for JSON. Postman gets `{"filter":"text/plain"}` response.
It will not be called if I add `@(Returns(200).ContentType("application/json"))` OR `response.setHeader("Content-Type", "application/json");`

`@ResponseFilter("11text/plain11")` -> `{"filter":"text/plain"}`
`@ResponseFilter("455")` -> `{"jsonexample": 1}`

**Comment by silveoj** [comment]
Hello @Romakita 
I can't reproduce it in sandbox. But I can reproduce it locally (export from sandbox).
[sandbox example](https://codesandbox.io/s/tsed-filter-by-content-type-example-297yp?file=/src/Server.ts)

So I rephrase my issue:
I use `text/plain` filter
```
@ResponseFilter("text/plain") // text/plain for example.
export class MyResponseFilter implements ResponseFilterMethods {
  transform(data: any, ctx: Context) {
    console.log("MyResponseFilter");
    return {
      filter: 'text/plain',
    };
  }
}
```
I send JSON:
```
@Get("/send-json")
// @(Returns(200).ContentType("application/json"))
public sendJson(@Res() response: PlatformResponse) {
  // response.setHeader("Content-Type", "application/json");
  return {
    jsonexample: 1
  };
}
```
But `text/plain` filter is called for JSON. Postman gets `{"filter":"text/plain"}` response.
It will not be called if I add `@(Returns(200).ContentType("application/json"))` OR `response.setHeader("Content-Type", "application/json");`

You can change filter:
`@ResponseFilter("11text/plain11")` -> `{"filter":"text/plain"}`
`@ResponseFilter("455")` -> `{"jsonexample": 1}`

About `response.setHeader('content-type', 'image/png');` and `@ResponseFilter('*/*')`.
Browser gets `application/json`. I see result as `data:*/*;base64...` but must be `data:image/png;base64...`
If I disable my filter it will work.

**Comment by silveoj** [comment]
My task is set no cache headers for ALL responses.
My temporary solution in v6 is 
```
$beforeRoutesInit(): void {
  this.app
      .use(...)
      .use(MyGlobalSendResponseMiddleware)
      .use(...)
}

// MyGlobalSendResponseMiddleware doesn't work in afterRoutesInit but work for controllers and endpoints (I have more than 200)
/*$afterRoutesInit(): void {
  this.app
    .use(MyGlobalSendResponseMiddleware)
}*/
```

Here is my middleware [codesandbox](https://codesandbox.io/s/tsed-filter-by-content-type-example-297yp?file=/src/middlewares/MyGlobalSendResponse.ts)
(`ctx.data = { ... }` in `UseAfter` also doesn't work like in https://github.com/TypedProject/tsed/issues/914 But I don't need it. I only add headers)
```
import {IMiddleware, Middleware, Context, Next} from "@tsed/common";

@Middleware()
export class MyGlobalSendResponseMiddleware implements IMiddleware {
  use(@Context() ctx: Context, @Next() next: Next) {
    // ctx.data = { // it doesn't work
    //   isMiddleware: true,
    // }
    ctx.response.setHeaders({ 'my-example-header': 123 }); // works in global mode only for useBefore
    next();
  }
}
```

**Comment by silveoj** [comment]
My task is set no cache headers for ALL responses.
My temporary solution in v6 is 
```
$beforeRoutesInit(): void {
  this.app
      .use(...)
      .use(MyGlobalSendResponseMiddleware)
      .use(...)
}

// MyGlobalSendResponseMiddleware doesn't work in afterRoutesInit but works `@UseAfter` for controllers and endpoints (I have more than 200 so I use global)
/*$afterRoutesInit(): void {
  this.app
    .use(MyGlobalSendResponseMiddleware)
}*/
```

Here is my middleware [codesandbox](https://codesandbox.io/s/tsed-filter-by-content-type-example-297yp?file=/src/middlewares/MyGlobalSendResponse.ts)
(`ctx.data = { ... }` in `UseAfter` also doesn't work like in https://github.com/TypedProject/tsed/issues/914 But I don't need it. I only add headers)
```
import {IMiddleware, Middleware, Context, Next} from "@tsed/common";

@Middleware()
export class MyGlobalSendResponseMiddleware implements IMiddleware {
  use(@Context() ctx: Context, @Next() next: Next) {
    // ctx.data = { // it doesn't work
    //   isMiddleware: true,
    // }
    ctx.response.setHeaders({ 'my-example-header': 123 }); // works in global mode only for beforeRoutesInit
    next();
  }
}
```

**Comment by silveoj** [comment]
My task is set no cache headers for ALL responses.
My temporary solution in v6 is 
```
$beforeRoutesInit(): void {
  this.app
      .use(...)
      .use(MyGlobalSendResponseMiddleware)
      .use(...)
}

// MyGlobalSendResponseMiddleware doesn't work in afterRoutesInit but works `@UseAfter` for controllers and endpoints (I have more than 200 so I use global)
/*$afterRoutesInit(): void {
  this.app
    .use(MyGlobalSendResponseMiddleware)
}*/
```

Here is my middleware [codesandbox](https://codesandbox.io/s/tsed-filter-by-content-type-example-297yp?file=/src/middlewares/MyGlobalSendResponse.ts)
(O noticed `ctx.data = { ... }` in `UseAfter` doesn't work like in https://github.com/TypedProject/tsed/issues/914 But I don't need it. I only add headers)
```
import {IMiddleware, Middleware, Context, Next} from "@tsed/common";

@Middleware()
export class MyGlobalSendResponseMiddleware implements IMiddleware {
  use(@Context() ctx: Context, @Next() next: Next) {
    // ctx.data = { // it doesn't work
    //   isMiddleware: true,
    // }
    ctx.response.setHeaders({ 'my-example-header': 123 }); // works in global mode only for beforeRoutesInit
    next();
  }
}
```

**Comment by silveoj** [comment]
My task is set no cache headers for ALL responses.
My temporary solution in v6 is 
```
$beforeRoutesInit(): void {
  this.app
      .use(...)
      .use(MyGlobalSendResponseMiddleware)
      .use(...)
}

// MyGlobalSendResponseMiddleware doesn't work in afterRoutesInit but works `@UseAfter` for controllers and endpoints (I have more than 200 so I use global)
/*$afterRoutesInit(): void {
  this.app
    .use(MyGlobalSendResponseMiddleware)
}*/
```

Here is my middleware [codesandbox](https://codesandbox.io/s/tsed-filter-by-content-type-example-297yp?file=/src/middlewares/MyGlobalSendResponse.ts)
(I noticed `ctx.data = { ... }` in `UseAfter` doesn't work like in https://github.com/TypedProject/tsed/issues/914 But I don't need it. I only add headers)
```
import {IMiddleware, Middleware, Context, Next} from "@tsed/common";

@Middleware()
export class MyGlobalSendResponseMiddleware implements IMiddleware {
  use(@Context() ctx: Context, @Next() next: Next) {
    // ctx.data = { // it doesn't work
    //   isMiddleware: true,
    // }
    ctx.response.setHeaders({ 'my-example-header': 123 }); // works in global mode only for beforeRoutesInit
    next();
  }
}
```

**Comment by Romakita** [comment]
Hello @silveoj 

The better choice to set no-cache is to use a middleware registered on $beforeRoutesInit hooks. This the main principle with Express.js. Middlewares added after the handler which send the response, won't probably be called (in pure Express.js app).

Can you send me also a curl example. The content-type/accept headers sent by the browser especially :)

See you
Romain

**Comment by Romakita** [comment]
Hello @silveoj 
I created a repository based on your sandbox. https://github.com/Romakita/tsed-issue-1222

All unit test works! Can you checkout the repository and

**Comment by Romakita** [comment]
Fixed.

Please consider [supporting](https://tsed.io/support.html) the framework if it provides value to you or your company and this support was of help to you. Supporting the framework means, amongst other things, that such support will be available in the future.
