### ISSUE TITLE
[QUESTION] AJV - input params - null as string

### ISSUE THREAD

**Issue by silveoj** [TypedProject/tsed#1231]
## Information

- **Version:** 6.24.2
- Packages: 
``` typescript
    "@tsed/ajv": "6.24.2",
    "@tsed/common": "6.24.2",
    "@tsed/core": "6.24.2",
    "@tsed/di": "6.24.2",
    "@tsed/exceptions": "6.24.2",
    "@tsed/platform-express": "6.24.2",
    "@tsed/schema": "6.24.2",
    "@tsed/swagger": "6.24.2",
    "@tsed/typeorm": "6.24.2",
```
[sandbox](https://codesandbox.io/s/querystring-ajv-error-z2ucv?file=/src/controllers/rest/MyCtrlQuery.ts)
1.
```typescript
  @Post("/post-me-1") // doesn't work
  public postMe1(@BodyParams("myId") myId: string) {
    // send {"myId":null}
    if (myId === "null") {
      throw new BadRequest("null as string");
    }
    return myId;
  }
```
If you send `{"myId":null}` we get null converted to string: `'null'`.
If request doesn't have this field I get `undefined`.
Workaround is  `@Any()` + `string | null` sometimes doesn't work:
`postMe1_null(@Any() @BodyParams("myId") myId: string | null` // but works in example

But how to make it in one place (don't change 200 endpoints), not for each BodyParams variable? I can't find examples for old converters from v.5 or jsonMappers for null/object.

ajv `strict: false` doesn't help.

2.
in v.5 I used:
```
  @Any('null', 'string')
  @Schema({ type: 'string' })
  public myDate: Date;
```
I send date as string "05.02.2021",
It convert it to Date and allows only `should be null, string`. Not number. It was fine.

In v.6 it doesn't convert to Date. I removed `@Any('null', 'string')`. Now it converts to Date but allow numbers.
`@Format` doesn't work for me because I have specific date format. So I use `@Allow(null)` and `@Pattern`. But it doesn't convert to Date. If I remove `@Allow` it will work.

3. Is there possibility to change typing to use `@Enum` like
`@Enum(...getMyArray())` // because array can be returned from method

To avoid it I use:
```
  @Schema({
    type: 'string',
    enum: getMyArray(),
  })
```
or
```
  @Required()
  @Enum("", ...getMyArray())
```

Thanks.

**Comment by silveoj** [comment]
4. (Yes/No)
```
  @Get("/get-me-1")
  public getMe1(@QueryParams("myId") myId: any) { // or without any
    return myId;
  }
```

If we have `@QueryParams` or `@BodyParams` without type it will throw AJV error:
`"Bad request on parameter \"request.query.myId\".\nValue should be object.`
We need to add type:
```
public getMe1(@QueryParams("myId") myId: string) {
```

The same with enum
`@QueryParams("direction") direction: Direction = Direction.Up` // works
`@QueryParams("direction") direction = Direction.Up` // doesn't work

I suggest it's by design https://tsed.io/getting-started/migration-from-v5.html#any-with-bodyparams

**Comment by Romakita** [comment]
1. Will be fixed
2. If you use strange decorators combination, the result will be strange also. I'll add the `@Nullable` decorator, to solve your issue:

```typescript
export class Model {
  @Required(true, null) // allow null
  @Nullable(Date)
  prop2: Date | null;
}
```
3. WIll be fixed
4. Yes I recently discovered the side effect with the v6, since  inline validation is supported on BodyParams. TypeScript doesn't give the expected type for default value assignment. In this case, typescript set `Object` as type, not a `String`. 

The better way is to use `@Enum` decorator:

```typescript
@QueryParams("direction") @Enum(Direction) direction: Direction = Direction.Up
```

PR ready: https://github.com/TypedProject/tsed/pull/1233

>  200 endpoints
It's a big project ^^. Which project/product is it?

See you,
Romain

**Comment by silveoj** [comment]
Thanks @Romakita 

`return "" + data;` I read this code but didn't pay attention it can be issue for `null`)

It's outsource project (client uses it for internal purposes, inside the company).
I don't think it's a big project. We have a lot of similar endpoints: upload/download documents, huge requests/responses, 3 databases, different date format from DB, old IE browser. Also we didn't use AJV validation at the beginning. So now we get (for my opinion) interesting issues.

**Comment by Romakita** [comment]
Agreed, your feedback is interesting about ajv validation :)

**Comment by silveoj** [comment]
Thanks @Romakita 
I found one small issue with Date converting.
`null` -> 0 -> 1 Jan 1970

It will work if in `DateMapper` `deserialize` method add code to check for null (as in StringMapper):
`return data === null ? null : new Date(data);`

Or I suggest to see my way (helper for dates):
```
// checkDate(date: any) {
if (date === void 0 || date === null || typeof date === 'boolean') {
  // undefined gives us Invalid Date
  return false;
}

const possibleDate = new Date(date);
return possibleDate instanceof Date && !isNaN(possibleDate ); // isNaN checks for Invalid Date
```
I suggest maybe return:
if date is not correct -> input value
if date is correct -> successful converted Date

Also I will prepare 2 endpoints for model (date properties) with different combinations of decorators.
For example, will leave string as string -> doesn't convert to Date
```
  @Allow(null) // woill work without Allow
  @Schema({ type: 'string' })
  @Pattern(...)
  public myDate1?: Date;

  @Allow(null) // woill work without Allow
  @Nullable(Date)
  public myDate2?: Date;
```
