### ISSUE TITLE
[QUESTION] componentsScan types

### ISSUE THREAD

**Issue by EmilienLeroy** [TypedProject/tsed#1239]
In the [documentation](https://tsed.io/docs/providers.html#services), you can directly import a service into the `componentsScan`. But into the Configuration interface the `componentsScan` must be a `string | RegExp` array. This cause a type error and I must had an `as any` to the `componentsScan` field to avoid this error. You can find an example [here](https://github.com/EmilienLeroy/labs/blob/43d0a5f1f7cb5bf71e1d131880f4522d80ea5a49/todo-tsed/src/Server.ts#L56-L58 
).

I don't know if I missing something or is just a type problem ?

https://github.com/TypedProject/tsed/blob/cb1933b0e40af35229d83dd46072ad3b9248ac58/packages/common/src/config/interfaces/index.ts#L49

## From the documentation 

```ts
import {Configuration} from "@tsed/common";
import {CalendarsCtrl} from "./controllers/CalendarsCtrl";
import {CalendarsService} from "./services/CalendarsService";

@Configuration({
  mount: {
    "/rest": [CalendarsCtrl]
  },
  componentsScan: [
    CalendarsService
  ]
})
export class Server {
}
```

## Example

```ts
import {Env} from "@tsed/core";
import {Configuration, Inject} from "@tsed/di";
import {$log, BeforeRoutesInit, PlatformApplication} from "@tsed/common";
import { TodoController, TodoService } from './todos';
import "@tsed/platform-express"; // /!\ keep this import
import "@tsed/mongoose"; 
import "@tsed/swagger";
import bodyParser from "body-parser";
import compress from "compression";
import cookieParser from "cookie-parser";
import methodOverride from "method-override";
import cors from "cors";
import "@tsed/ajv";

export const rootDir = __dirname;
export const isProduction = process.env.NODE_ENV === Env.PROD;

if (isProduction) {
  $log.appenders.set("stdout", {
    type: "stdout",
    levels: ["info", "debug"],
    layout: {
      type: "json"
    }
  });

  $log.appenders.set("stderr", {
    levels: ["trace", "fatal", "error", "warn"],
    type: "stderr",
    layout: {
      type: "json"
    }
  });
}

@Configuration({
  rootDir,
  acceptMimes: ["application/json"],
  httpPort: process.env.PORT || 8083,
  httpsPort: false, // CHANGE
  logger: {
    disableRoutesSummary: isProduction
  },
  mongoose: {
    url: "mongodb://127.0.0.1:27017/todo",
    connectionOptions: {
      useNewUrlParser: true,
      useUnifiedTopology: true
    }
  },
  mount: {
    "/": [
      TodoController,
    ]
  },
  componentsScan: [
    TodoService as any,
  ],
  swagger: [
    {
      path: "/v2/docs",
      specVersion: "2.0",
    },
    {
      path: "/v3/docs",
      specVersion: "3.0.1"
    }
  ],
  exclude: [
    "**/*.spec.ts"
  ]
})
export class Server implements BeforeRoutesInit {
  @Inject()
  app: PlatformApplication;

  @Configuration()
  settings: Configuration;

  $beforeRoutesInit(): void {
    this.app
      .use(cors())
      .use(cookieParser())
      .use(compress({}))
      .use(methodOverride())
      .use(bodyParser.json())
      .use(bodyParser.urlencoded({
        extended: true
      }));
  }
}
```

**Comment by Romakita** [comment]
@EmilienLeroy It's totally normal, adding service/provider to componentsScan fields has no sense.
Ts.ED discover automatically services/providers as soon as it is imported into your application via an import ES6.
In most case, if your service is used by a controller or another service which is used by a controller, it's not necessary to import it explicitly (as it will be the case with angular for example). It is a will on my part to have this mechanism ;)

In you example just remove the TodoService import and keep the TodoController only (because TodoController probably use the TodoService).

See you
Romain

**Comment by EmilienLeroy** [comment]
@Romakita 
Thanks you for this very clear answer !
