### ISSUE TITLE
[QUESTION] Swagger file path

### ISSUE THREAD

**Issue by Madrity** [TypedProject/tsed#1242]
Hello,
 
my API is hosted on https://mydomain.io/my-api/

here is my swagger config : 

`swagger: ([{ path: "/swagger-ui", fileName: "index.html" }])`

when i check my swagger ui on https://mydomain.io/my-api/swagger-ui/
I have this error `Not Found https://mydomain.io/swagger-ui/index.html`

my API path is ignored.

when i request https://mydomain.io/my-api/swagger-ui/index.html it's ok.

Am i missing something ?

Thanks.

**Comment by Romakita** [comment]
Hello @Madrity 
fileName option isn't used by Ts.ED framework. The link display in the terminal is the reference. There is no issue for me :)

See you
Romain
