### ISSUE TITLE
[QUESTION] Inject a Provider in an Interceptor

### ISSUE THREAD

**Issue by paschaldev** [TypedProject/tsed#1248]
I have an `AuthenticationProvider` that handles all the authentication logic of the app I am working on. It has a method `getAuthUser()` that I use to get the current authenticated user (Under the hood, this uses the `@tsed/async-hook-context` to pull JWT token from the request headers`

### AuthenticationProvider.ts

```ts
...

import { InjectContext } from '@tsed/async-hook-context'

@Injectable({
  type: ProviderType.PROVIDER,
  scope: ProviderScope.INSTANCE,
})
export default class AuthenticationProvider {
  private userAgent: UserAgentParser

  @InjectContext()
  protected $ctx: PlatformContext

  constructor(
    private readonly mailer: MailProvider,
    private readonly jwtService: JWTService,
    @Inject(UserModel) protected userModel: MongooseModel<UserModel>,
    @Inject(UserSessionModel) private userSessionModel: MongooseModel<UserSessionModel>
  ) {
    return
  }
}
...
```

This setup works fine with `Controllers` and `Middlewares`

### AuthMiddleware

```ts
...
@Middleware()
export class AuthenticationMiddleware implements IMiddleware {
  constructor(private readonly authenticationProvider: AuthenticationProvider) {
    return
  }
}
...
```

However, when I try to do the same thing with an `Interceptor`, it fails

### Interceptor
```ts
...
@Interceptor()
export class SingleContentInterceptor implements InterceptorMethods {
  /* eslint prettier/prettier: 0 */
  public constructor(
    private readonly authenticationProvider: AuthenticationProvider,
    @Inject(UserListModel) private readonly userListModel: MongooseModel<UserListModel>
  ) { }
}
```

<img width="1177" alt="Screen Shot 2021-02-16 at 7 27 00 PM" src="https://user-images.githubusercontent.com/13323281/108105486-f8647e80-708c-11eb-8957-f5410755d336.png">

**Comment by Romakita** [comment]
Your error means you have a bad import with AuthenticationProvider. Add a console.log(AuthenticationProvider) just after all import to see if the import is ok. If not, you have a circular dependencies.

**Comment by paschaldev** [comment]
Yes it is `undefined`, however importing another provider from the same directory wasn't `undefined`. I;ll check for Circular Depencies

<img width="884" alt="Screen Shot 2021-02-17 at 1 18 48 PM" src="https://user-images.githubusercontent.com/13323281/108204116-aae72080-7123-11eb-8787-b42a7dd764f5.png">

**Comment by paschaldev** [comment]
I fixed the Circluar Dependency issues (none was reported for the `AuthenticationProvider` by the way but still its undefined

<img width="786" alt="Screen Shot 2021-02-17 at 1 40 22 PM" src="https://user-images.githubusercontent.com/13323281/108205775-cbb07580-7125-11eb-885b-e1aab0282450.png">

**Comment by paschaldev** [comment]
I can confirm it's actually a circular dependency. Copied the content of `AuthenticationProvider` to another file (Gave it another name). Imported this files and it worked. I'll have to figure out this one
