### ISSUE TITLE
[QUESTION] Compile components with Webpack

### ISSUE THREAD

**Issue by progressivetr** [TypedProject/tsed#1266]
Due to tsed use glob pattern to scan components, i can not build project with webpack. Could i use also import statements to define components?

An example:

```javascript
Configuration({
  components: [ AuthService, LocationService ]
});
```

**Comment by Romakita** [comment]
Globpattern doesn’t works with webpack. you have to import manually controller or use require.context :)

**Comment by progressivetr** [comment]
I imported controller manually but i could not find any way to import services.

**Comment by Romakita** [comment]
If a controller your service, it’ll be imported automatically. Ts.ED usethe ES6 import to discover services :), so if one of your imported nodejs file use the service, Ts.ED will create the instance on server bootstrap.

**Comment by progressivetr** [comment]
Absolutely but Tsed use blob patterns to find and load services so i could not use tsed with webpack.

**Comment by Romakita** [comment]
Just import your services and middlewares with a a classic es6 import in your server.

import from “./path/to/myservices“

another solution is to use require.context.

Ts.ED works fine with webpack. Many project works with since a long time.

**Comment by Romakita** [comment]
https://github.com/TypedProject/tsed-example-webpack

**Comment by progressivetr** [comment]
Thanks for helping. I was already doing it with that project. Now, i have builded project with webpack but I get the following error :(

![image](https://user-images.githubusercontent.com/52868371/110236265-e405fa00-7f45-11eb-9532-8d165b3f1ea5.png)

**Comment by progressivetr** [comment]
The problem is related with Entity repositories. Entity repositories extends Repository object but its dont have "manager" object.

**Comment by Romakita** [comment]
Did you use typeorm? If yes, open an issue or ask question to typeorm teams. I’m not able to help you on this part ^^

**Comment by progressivetr** [comment]
I resolved problem. Thanks for helping. The problem is related with typeorm config (it was generated automatically with tsed cli). I added entities and migrations manually instead of reading json.
