### ISSUE TITLE
[QUESTION] Authentication on swagger 

### ISSUE THREAD

**Issue by panbhatt** [TypedProject/tsed#1274]
HI Team,
  is there a feature available in TSED.io through which we can protect our Swagger path only for specific users or can apply  any type of authentication on to it. like basic/digest/custom. we just wanted to stop anyone calling that API-DOCS unless can authenticate.

**Comment by Romakita** [comment]
Hello @panbhatt 

There is no feature to do that. You'd just use a middleware (like passport, or basic auth) to protect the swagger path.
See you
Romain

**Comment by panbhatt** [comment]
THanks. Can you please throw me an example, that would be great. we are using 5.56 version.

**Comment by panbhatt** [comment]
i have tried different way to do it. via using this.express.get('/api-docs', () )  and even tried @beforeRoutesInit() as this.use(MIDDLEWARE).

**Comment by Romakita** [comment]
Prefer the usage of this.express.use(‘/api-docs’, myMiddleware) on $afterInit or $beforeRoutesInit.

I haven’t example in mind ^^

**Comment by panbhatt** [comment]
Thanks a lot. This seems to be working. I think i might be doing something wrong.
