### ISSUE TITLE
[QUESTION] Typeorm Entity Repository

### ISSUE THREAD

**Issue by aldigjo** [TypedProject/tsed#1277]
Can you use EntityRepository as the singular way to interact with the DB? Do you still need to provide a TypeormService or injected connection if I am already injecting an EntityRepository? 

Also - I am getting my entityRepository as undefined when I try to run my source files with nodemon, but it seems to work fine when I build the TS files and run the js files. 

Am asking for clarification if there are certain connection requirements to use EntityRepository.

**Comment by aldigjo** [comment]
@Romakita Thanks for the response! 

for Jest unit tests, is there a different way to configure the entities?

**Comment by Romakita** [comment]
Just import the entity in your test. In think is enough :)
