### ISSUE TITLE
X-Request-ID in response should not overwrite an existing X-Request-ID request header

### ISSUE THREAD

**Issue by csnate** [TypedProject/tsed#1282]
## Informations
**Is your feature request related to a problem? Please describe.**
See below.

**Describe the solution you'd like**
With the addition of the X-Request-ID header in 6.21.0, I would also like to propose that you use an existing X-Request-ID header from the request (if it exists) instead of always creating a new ID in the response header. It makes it easier to track requests through a microservice architecture that way and X-Request-ID is a standard header to use for this specific purpose.

**Describe alternatives you've considered**

**Comment by Romakita** [comment]
Hello @csnate 
It's already possible by providing your own requestIdBuilder but we can do that in standard.

Here:
https://github.com/TypedProject/tsed/blob/production/packages/common/src/platform/utils/createContext.ts#L7

You can propose a small PR if you have a time :)

Romain

**Comment by csnate** [comment]
@Romakita I couldn't find any documentation on that, but would it look something like this:

```
@Configuration({
  logger: {
    reqIdBuilder(req: any): string {
        return req.get('x-request-id') || uuidv4().replace(/-/gi, "");
    }
  }
})
export class Server {}
```

Re: PR - sure thing! I'll try and get to it today.

**Comment by csnate** [comment]
#1287

**Comment by Romakita** [comment]
Merged :)
