### ISSUE TITLE
[QUESTION] v5 to v6 Migration Issues

### ISSUE THREAD

**Issue by royibernthal** [TypedProject/tsed#1285]
I'm migrating from v5 to v6.
For the sake of a clean migration - I completely recreated the project using the tsed cli. I'll copy my existing code from v5 into it.

1) I'm getting the following error when executing `npm start` (as created by tsed cli with no changes), and I'm getting the following error:
`Missing baseUrl in compilerOptions. tsconfig-paths will be skipped`

2) I'm trying to use dotenv with the new `npm start` created by the tsed cli.

Until now this is how I've been running my server locally in v5 while injecting my env file:
`nodemon --watch src/**/*.ts --ignore node_modules/**/* --exec ts-node -r dotenv/config src/index.ts dotenv_config_path=dev.env`

I tried to append dotenv to the `npm start` created by the tsed cli in v6, but the server won't go up (it doesn't even get to the "Start Server..." log):
`tsnd --inspect --ignore-watch node_modules --respawn --transpile-only -r tsconfig-paths/register dotenv/config src/index.ts dotenv_config_path=dev.env`

Of course it does run as expected before modifying `npm start`, excluding dotenv:
`tsnd --inspect --ignore-watch node_modules --respawn --transpile-only -r tsconfig-paths/register src/index.ts`

**Comment by Romakita** [comment]
Hello @royibernthal 

the first point isn’t an error. Just a warning. I think if you add the baseUrl in your tsconfig, it should solve the warning.

You don’t need to specify something for dotenv. Dotenv explain how the files are loaded. 
I don’t know why the server doesn’t start and I can’t help you (I’m not the author of tsnd/dotenv). 
But I’m pretty sure this not related to v6.

See you
Romain

**Comment by royibernthal** [comment]
Hey @Romakita 

Thanks for the quick response.

baseUrl - You're right.

DotEnv - Fair enough. I managed to get it to work with a different approach.

More migration questions coming soon :) (probably)

Regards,
Royi

**Comment by Romakita** [comment]
Sure ;) your feedback is welcome :)
