### ISSUE TITLE
[QUESTION] V6 Build project with npm instead of yarn

### ISSUE THREAD

**Issue by royibernthal** [TypedProject/tsed#1295]
In the tsed cli I chose to build my project using npm.

In package.json my build script is `yarn tsc`, is that a bug or is it intentional?

Is there any way to use npm in the build script instead? `npm tsc` seems to be an invalid command.

I'm deploying my server to a heroku app which uses npm, so it's important to only use npm and not mix yarn (`yarn: not found`).

**Comment by Romakita** [comment]
Replace yarn tsc by npm run tsc ;)

is not intentional, I forgot to use variable on scripts generation.

**Comment by royibernthal** [comment]
Makes sense, thanks :) More issue coming your way, trying to take this v6 to production.

**Comment by Romakita** [comment]
## Story

Fix the scripts generated by the CLI. Replace yarn by npm when the choosen packageManager is NPM.

See https://github.com/TypedProject/tsed-cli/blob/master/packages/cli/src/commands/init/InitCmd.ts#L236

**Comment by Romakita** [comment]
I released a new version of the CLI which fix this issue :)

**Comment by Romakita** [comment]
Solved with CLI v2.12.0
