### ISSUE TITLE
Can't set TTL to null

### ISSUE THREAD

**Issue by DavidSmith777** [TypedProject/tsed#1298]
I'm in the process of implementing cache, and have been following your documentation - https://tsed.io/docs/cache.html.  Unfortunately I've run into a couple of problems.

First, `@UseCache('myKey')` does cache the data, but it is not pulled out the same way it goes in.  We are building a `Map<string, MyObj>`, and later want to use the Map methods.  Unfortunately when we pull the data get the data back from the cache we have and plain object with series of keys to values with no Map methods.  If there is a solution to this, or something I may have missed it would be appreciated if could point me in the right direction.  

This led me to an alternate solution, and the second problem.  I went down the route of interacting with the cache store using the get/set methods.  This did pull the Map back properly so that was great, but when I wanted to disable the ttl as described in the documentation -  `await this.cache.set('key', 'value', { ttl: null });` I get a compilation error stating "Type 'null' is not assignable to type 'number | TtlFunction'."

I thought I could just do an end run with the TtlFunction and do `() => null`, but it seems this is also not an option.  I am using tsed version 6.34.2 with ts 4.2.2

**Comment by Romakita** [comment]
Hello @DavidSmith777 

I added extra documentation on the website to retrieve the expected type from a cached instance.

---

### Extract

node-cache-manager serialize all data as JSON object. It means, if you want to cache a complex data like an instance of class, you have to give extra parameters to the UseCache decorator. Ts.ED will use @@deserialize@@ function based on the given type (and collectionType) to return the expected instance.

```typescript
import {Injectable} from "@tsed/di";
import {UseCache} from "@tsed/common";

@Injectable()
export class MyService {
  @UseCache({type: MyClass})
  get(id: string): MyClass {
    return new MyClass({id});
  }
  
  @UseCache({type: MyClass, collectionType: Array})
  getAll(): MyClass[] {
    return [new MyClass({id: 1})];
  }
}
```
---

For your issue set `collectionType` to Map.

Node-cache-manager doesn't seem to allow setting the ttl to null. This is not a limitation of Ts.ED, I only used the typing provided by the author of node-cache-manager. I invite you to open an issue on their repository and come back to me when you have a solution :)

See you
Romain

**Comment by DavidSmith777** [comment]
Thanks for the feed back.  I mentioned TTL because that is what is in your documentation, but I will look at node-cache-manager.

**Comment by Romakita** [comment]
Yes sure :)
