### ISSUE TITLE
[QUESTION] Required socketIO parameters & CORS?

### ISSUE THREAD

**Issue by beatyt** [TypedProject/tsed#1300]
Hi,

I was trying to follow the socket.io example. I was having CORS errors.

While trying to configure I had to create in full:
```
  socketIO: {
    path: '/',
    serveClient: true,
    adapter,
    parser,
    connectTimeout: 45000,
    pingTimeout: 20000,
    pingInterval: 25000,
    upgradeTimeout: 10000,
    maxHttpBufferSize: 1e5,
    transports: ["polling", "websocket"],
    allowUpgrades: true,
    perMessageDeflate: false,
    httpCompression: true,
    wsEngine: require("ws").Server,
    initialPacket: undefined,
    cookie: false,
    cors: {
      origin: 'http://localhost:8080',
      methods: ['GET', 'POST'],
    },
    allowEIO3: false,
    destroyUpgrade: true,
    destroyUpgradeTimeout: 1000,
    allowRequest: (req, fn) => { fn(null, true) }
  },
```

All of these look required. Should some of them be optional?

Versions:
```
"@tsed/socketio": "^6.34.3",
"@types/socket.io": "^2.1.13",
"socket.io": "^4.0.0"
```

**Comment by Romakita** [comment]
I think I won’t be hepfull. I haven’t worked on socket module since a long time. So your question is totally out of my skills because it’s very specific to socket.io. 

Maybe a repo with a reproducible process could help me ^^

see you
Romain

**Comment by CarstenHouweling** [comment]
I was also having issues, i noticed i do not have to include the suggested imports

`import "@tsed/platform-express";
import "@tsed/socketio"; // import socket.io Ts.ED module`

If I include those imports, I also see that everything is required. Just leave them out.

**Comment by Romakita** [comment]
Your help is welcome to improve documentation.
Documentation website can be edited directly from the website:
<img width="213" alt="Capture d’écran 2021-03-22 à 09 51 30" src="https://user-images.githubusercontent.com/1763311/111963798-36254e80-8af4-11eb-9b24-d1d8287ee5c0.png">

See you
Romain
