### ISSUE TITLE
[BUG] Readme content build setup wrong if npm was selected as package manager

### ISSUE THREAD

**Issue by xCryzed** [TypedProject/tsed#1307]
## Information

- **Version:** 6.35.1

If during the installation process npm was selected as package manager the content of the readme file for the section 'Build setup' is for yarn.

![Screenshot 2021-03-26 075939](https://user-images.githubusercontent.com/39458340/112595517-d3d99000-8e0a-11eb-8177-cdaf77b18de0.png)

## Example

![image](https://user-images.githubusercontent.com/39458340/112595572-e358d900-8e0a-11eb-8db8-cd2263582532.png)

## Acceptance criteria

- [ ] The content of the readme is correct for npm selection as package manager.

**Comment by Romakita** [comment]
Hello @xCryzed 

Can you make a PR on the cli project please?

see you

**Comment by Romakita** [comment]
Fixed
