### ISSUE TITLE
[BUG] Module '"./controllers/pages/index.controller"' has no exported member 'IndexController'

### ISSUE THREAD

**Issue by xCryzed** [TypedProject/tsed#1309]
## Information

- **Version:** 6.35.1

After a new initialization of a tsed project there is an import statement (line 15) in server.ts file which tries to import a member called `IndexController` and points to `./controllers/pages/index.controller`. But the exported member in `index.controller` file is `IndexCtrl`.

## Example

Current import in server.ts:

```
import {IndexController} from "./controllers/pages/index.controller";
```

Should be changed to:

```
import {IndexCtrl} from "./controllers/pages/index.controller";
```

## Acceptance criteria

- [ ] The import statement is changed according to find the member IndexCtrl again.

**Comment by Romakita** [comment]
Ok I see the issue. Have selected Angular convention ?

**Comment by xCryzed** [comment]
@Romakita yes, its the Angular convention
