### ISSUE TITLE
[QUESTION] Page Passport.js - /tutorials/passport

### ISSUE THREAD

**Issue by pabloat81** [TypedProject/tsed#1314]
Hi. I like tsed a lot. 

I have 2 questions.

First, i cant realize for role auth where i must set the roles so then i can use:
 const roles = endpoint.get(AcceptRolesMiddleware);
In the login endpoint i have to set roles array somewhere?

Second question, is there an example of refresh token implementation with jwt strategy?

Regards.

**Comment by Romakita** [comment]
I don't understand your question about roles exactly :).

Here is an example to set roles:
```typescript
import {Controller, Post} from "@tsed/common";
import {Authorize} from "@tsed/passport";
import {AcceptRoles} from "../decorators/acceptRoles";

@Controller("/calendars")
export class CalendarController {
  @Post("/")
  @Authorize("local")
  @AcceptRoles("admin", "user") <= roles
  async post() {

  }
}
```

And to get roles:

```typescript
import {EndpointInfo, Middleware, Req} from "@tsed/common";
import {Unauthorized} from "@tsed/exceptions";

@Middleware()
export class AcceptRolesMiddleware {
  use(@Context() ctx: Context) {
    const {user, isAuthenticated} = ctx.getRequest()
    if (user && isAuthenticated()) {
      const roles = endpoint.get(AcceptRolesMiddleware);

      if (!roles.includes(user.role)) {
        throw new Unauthorized("Insufficient role");
      }
    }
  }
}
```
Why do you need to check roles on login????? Roles are always checked on a routes not for the login...

For the refresh token, if you have the original passport example, you will be able to implement the same things with Ts.ED. 

See you
Romain

**Comment by pabloat81** [comment]
Hi. Sorry for my english.

I ubderstand most of the examplei think, but my question is, where in that example i am setting roles from the database for this user?

I don t know if i am getting my self clear.

Thanks

**Comment by Romakita** [comment]
I don't know. Roles management depending entirely of your architecture/solutions choices. Passport.js doesn't provide solution about role base access control. It's your responsibility to implement that :)
The given example is just a basic usage to check roles. But you have to get roles when you login a user in the Protocol class from a service.

```typescript
@Protocol({
  name: "basic",
  useStrategy: BasicStrategy,
  settings: {}
})
export class BasicProtocol implements OnVerify, OnInstall {
  constructor(private usersService: UsersService) {
  }

  async $onVerify(@Req() request: Req, @Arg(0) username: string, @Arg(1) password: string) {
    checkEmail(username);

    // You domain application
    const user = await this.usersService.findOne({email: username});
    // Here you should have the user with his role!

    if (!user) {
      return false;
    }

    if (!user.verifyPassword(password)) {
      return false;
    }

    return user;
  }
}
```

**Comment by pabloat81** [comment]
OK now i inderstand. Thanks.

**Comment by Romakita** [comment]
Ok we can close this issue ;) ?

**Comment by pabloat81** [comment]
Yes thanks.

**Comment by Romakita** [comment]
Please consider [supporting](https://tsed.io/support.html) the framework if it provides value to you or your company and this support was of help to you. Supporting the framework means, amongst other things, that such support will be available in the future.
