### ISSUE TITLE
[BUG] Cannot find name 'expect' in src/server.integration.spec.ts:18:6 

### ISSUE THREAD

**Issue by xCryzed** [TypedProject/tsed#1324]
## Information

- **Version:** 6.38.1

After a new creation the import statement for the module chai is missing in the file src/server.integration.spec.ts.

## Example

```
import {PlatformTest} from "@tsed/common";
import SuperTest from "supertest";
import {Server} from "./server";

describe("Server", () => {
  let request: SuperTest.SuperTest<SuperTest.Test>;

  beforeEach(PlatformTest.bootstrap(Server));
  beforeEach(() => {
    request = SuperTest(PlatformTest.callback());
  });

  afterEach(PlatformTest.reset);

  it("should call GET /rest", async () => {
    const response = await request.get("/rest").expect(404);

    expect(response.body).to.deep.equal({
      errors: [],
      message: "Resource \"/rest\" not found",
      name: "NOT_FOUND",
      status: 404
    });
  });
});
```

needs default chai import:

```
import {expect} from "chai";
```

## Acceptance criteria

- [x] chai is imported per default after a new tsed initialization.

**Comment by Romakita** [comment]
@xCryzed You can fix the concerned template here please ? https://github.com/TypedProject/tsed-cli/blob/master/packages/cli-plugin-mocha/templates/generate/server.integration.hbs

**Comment by xCryzed** [comment]
@Romakita https://github.com/TypedProject/tsed-cli/pull/105 :)
