### ISSUE TITLE
[BUG] Using a falsy value when registering a provider with useValue causes a DI bug

### ISSUE THREAD

**Issue by EkiGui** [TypedProject/tsed#1325]
## Information

- **Version:** 6.38.1

## Example

All those providers will cause an obscure bug at app initialization:

```
import { registerProvider } from '@tsed/di';

registerProvider({ provide: 'SOME-KEY', useValue: 0 });
registerProvider({ provide: 'SOME-OTHER-KEY', useValue: null });
registerProvider({ provide: 'AND-ANOTHER-KEY', useValue: '' });
```

## My Solution

This is because the `if` statement in `InjectorService` is a bit loose so it passes in the `else` condition:

https://github.com/TypedProject/tsed/blob/1115f768ef78874a2093abe3e2eca9dd59eff4e2/packages/di/src/services/InjectorService.ts#L640-L651

Maybe we should try something like : `if (provider.useValue !== undefined) { ... }`

**Comment by Romakita** [comment]
Hello @Romakita 
Yes you can make a quick PR to fix that please :) ?

**Comment by EkiGui** [comment]
Sorry to arrive after the battle, I wanted to take care of it in the next few days.
Thanks a lot for your work on this framework!
