### ISSUE TITLE
Support for node-oidc-provider v7

### ISSUE THREAD

**Issue by adamprzy** [TypedProject/tsed#1328]
Hi,
installing oidc-provider before @tsed/oidc-provider produces error:

>  While resolving: app@1.0.0
>  Found: oidc-provider@7.2.0
>  node_modules/oidc-provider
>    oidc-provider@"^7.2.0" from the root project
>  
>  Could not resolve dependency:
>  peer oidc-provider@"^6.29.9" from @tsed/oidc-provider@6.38.2

So the installation guide from https://tsed.io/tutorials/oidc.html#installation is no longer directly applicable.
Installing @tsed/oidc-provider before oidc-provider works fine, but we end up with oidc-provider@6.31.1

Are there any plans for supporting oidc-provider version 7?

**Comment by Romakita** [comment]
Hello @adamprzy 

Yes I know that the v7 isn't compatible. I'm waiting this PR before starting migration: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52145 .

and because v6/v7 are incompatible (typescript removing), I won't support v6 anymore after the migration :)

See you
Romain

**Comment by Romakita** [comment]
Ok the types definition is available now: https://www.npmjs.com/package/@types/oidc-provider

**Comment by Romakita** [comment]
I'll add the v7 ASAP

**Comment by Romakita** [comment]
Hello @adamprzy 
The v7 introduce some change on the consent interaction and interactions views (ejs).

see you
