### ISSUE TITLE
[BUG] Examples decorator for Swagger docs has no affect

### ISSUE THREAD

**Issue by ClickerMonkey** [TypedProject/tsed#1329]
## Information

- **Version:** 6.\*.\*
- Packages: 

Using the .Examples() chained function has no effect on the examples found in swagger docs.

## Example

```ts
@Returns(200, ResponseModel).Of(InnerType).Description('Hello World').Examples([{ id: 3, name: 'okay' }])
```

## Acceptance criteria

- [ ] Examples overriding the default example

**Comment by Romakita** [comment]
Hello @ClickerMonkey 
After reading the swagger documentation, you example isn't correct.
Examples expect a Record<string, OS3Example> with different examples: https://swagger.io/docs/specification/adding-examples/

Add added more types on the Returns.Example decorator.

**Comment by ClickerMonkey** [comment]
Thank you!!!!
