### ISSUE TITLE
How can I independently implement request.body without using ExpressJS bodyParser

### ISSUE THREAD

**Issue by Manfredik** [TypedProject/tsed#1335]
The problem is that locally when I run the application everything is working, and on the product after building typescript in javascript my middleware refuses to work

```typescript
@Middleware()
export class BodyParser implements IMiddleware {
  use(@RawBodyParams() rawBody: Buffer, @Req() request: Req, @Next() next: Next): void {
    request.body = {};
    if (typeIs.hasBody(request)) {
      try {
        if (request.is('application/json')) {
          request.body = JSON.parse(rawBody.toString());
        }
        if (request.is('urlencoded')) {
          request.body = parse(rawBody.toString(), {
            allowPrototypes: true,
            arrayLimit: 100,
            depth: Infinity,
            parameterLimit: 1000
          });
        }
      } catch (error) {
        next(error);
        return;
      }
    }
    next();
  }
}
```

**Comment by Romakita** [comment]
Why did do that with a custom middleware?!

**Comment by Manfredik** [comment]
BodyParser quietly falls when using cors in post queries

**Comment by Romakita** [comment]
Simplication proposition:

```typescript
@Middleware()
export class BodyParser implements IMiddleware {
  use(@RawBodyParams() rawBody: Buffer, @Req() request: Req): void {
    request.body = {};
    if (typeIs.hasBody(request)) {
      
        if (request.is('application/json')) {
          request.body = JSON.parse(rawBody.toString());
        }
        if (request.is('urlencoded')) {
          request.body = parse(rawBody.toString(), {
            allowPrototypes: true,
            arrayLimit: 100,
            depth: Infinity,
            parameterLimit: 1000
          });
        }

    }
}
```

**Comment by Manfredik** [comment]
falls on the read function in read.js after the debug line ('read body')

**Comment by Manfredik** [comment]
The problem is that
RawBody locally is Buffer

On the production RawBody line

**Comment by Romakita** [comment]
… so to solve your issue you prefer to write more instead of fixing cors middleware? 
maybe your issue can be solved by configuring correctly the cors/bodyparser?

for your original question, there is no reason to have a different behavior between dev/prod (based on your given example). So it depend on how you register the middleware.

**Comment by Romakita** [comment]
Rawbody type change in production?

**Comment by Manfredik** [comment]
`public $beforeRoutesInit(): void | Promise<any> {
    this.app
      .use(cookieParser())
      .use(compress({}))
      .use(methodOverride())
      .use(bodyParser.json())
      .use(bodyParser.urlencoded({ extended: true }))
      .use(
        cors({
          origin: true,
          credentials: true,
          methods: 'POST, GET, OPTIONS',
          allowedHeaders: 'X-Auth-Token, Authorization, Content-Length, X-Requested-With, Accept',
          exposedHeaders: 'X-Auth-Token, Authorization, Content-Length, X-Requested-With, Accept',
          preflightContinue: false
        })
      )
      .use(UserAgent.express());
  }`

**Comment by Romakita** [comment]
Please, can you be more precise on the error. It’s an issue? A question? The problem can be reproduced?

**Comment by Manfredik** [comment]
Failed to localize problem in current example with my middleware
Locally, if you run the application via ts-node, the rawBody is passed as a buffer.

After the tsc project is assembled, an empty string is rawBody.
if you add manual processing request.on ('data') and request.on ('end') then the body post request is available in the variable

**Comment by Manfredik** [comment]
But locally request.on ('data') is not called if start app ts-node

**Comment by Romakita** [comment]
Ok I think, I need a repository example and a curl to understand your point.
