### ISSUE TITLE
[BUG] Error when building app

### ISSUE THREAD

**Issue by nxvxl** [TypedProject/tsed#1349]
## Information

- **Version:** 6.41.0
- Packages: 
  - @tsed/schema

## Example

1. Create project using latest version
```
tsed init .
```
2. Build project
```
npm run build
```

![image](https://user-images.githubusercontent.com/25476548/114689315-c8a9be00-9d3f-11eb-8c14-d225ef4a1468.png)

## Acceptance criteria

Run without error

I think it's pointing to the wrong path. should be `lib` instead of `src`

**Comment by Romakita** [comment]
Hello @nxvxl 
Thanks for the issue. It's released :)

See you
Romain
