### ISSUE TITLE
[BUG] @Required() decorator does not work for validation in controller

### ISSUE THREAD

**Issue by iamprathamesh** [TypedProject/tsed#1355]
## Information

- **Version:** 6.31.2
- Packages: @tsed/schema

I have added the @Required() decorator in my controller method but it does not tell that which fields are missing on the recieved object

## Example

My Interface:
```
export interface ResetStorePassword {
    email: string;
    newPassword: string;
    otp: number;
}
```

My controller method:
```
@Post('/reset-password')
@Summary("Update password")
@(Returns(200).Description("Success"))
async resetPassword(@Required() @BodyParams() resetPwdDetails: ResetStorePassword): Promise<void> {
    // Some code here
}

```

In the above example if any of my fields are missing in the json object recieved (email, newPassword, otp) then the error should be thrown to the client stating that the specific field is not passed.

But this does not happen and the code inside my method is executed.

According to the documentation here, this should work - 
https://tsed.io/api/schema/decorators/common/Required.html

**Comment by Romakita** [comment]
Hello @iamprathamesh 
I think you missunderstood how the decorator works. The required decorator check only the value of the body params and not the props of the model. Use jsonschema or a class for that.

see you
Romain

**Comment by iamprathamesh** [comment]
Hi @Romakita 

yes the required parameter check the value of body params. If I do not pass a key in my json object, the value should be null or undefined. Hence, it should throw up an error that some value is null. am I right?

Regards,
Prathamesh

**Comment by iamprathamesh** [comment]
Hi Romakita,

I am not sure how to use JsonSchema to resolve this query of mine. Can you please give me some sample code to refer to. This will be of great help. Also, Great job with TSED project. I can see it becoming the biggest framework for building server side applications.

Regards,
Prathamesh

**Comment by Romakita** [comment]
Hello @iamprathamesh 
In your case, the BodyParams is never undefined or null. Express return always an empty object and because you use `@BodyParams()` without expression (eg: `@BodyParams('user')`) the field will always truthy.

But with the recent version of Ts.ED you have two way to validate a parameters. One with the class:

```typescript
export class ResetStorePassword {
    @Required()
    @Email()
    email: string;
    
    @Required()
    newPassword: string;
    
    @Property()
    otp: number;
}
```

And one with the JsonSchema and the functional API:

```typescript
const {object, string, email, number} from "@tsed/schema";

const ResetStorePasswordSchema = object({
   email: email().required().example('admin@tsed.io').description('The email to reset password'),
   newPassword: string().required().description('The new password'),
   opt: number()
})

@Post('/reset-password')
@Summary("Update password")
@(Returns(200).Description("Success"))
async resetPassword(@Required() @BodyParams() @Schema(ResetStorePasswordSchema) resetPwdDetails: ResetStorePassword): Promise<void> {
    // Some code here
}
```

Just use your prefered solution :) and it'll work as expected ;)
See you
Romain
