### ISSUE TITLE
[BUG] Title

### ISSUE THREAD

**Issue by tlfbrito** [TypedProject/tsed#1357]
## Information

- **Version:** 3.0.0 (CLI)
- Packages: 
```
    "@tsed/ajv": "^6.43.1",
    "@tsed/cli-core": "3.0.0",
    "@tsed/common": "^6.43.1",
    "@tsed/core": "^6.33.1",
    "@tsed/di": "^6.33.1",
    "@tsed/exceptions": "^6.43.1",
    "@tsed/json-mapper": "^6.43.1",
    "@tsed/platform-express": "^6.43.1",
    "@tsed/schema": "^6.43.1",
    "ajv": "7.2.4",
    "body-parser": "^1.19.0",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.5",
    "cors": "^2.8.5",
    "cross-env": "^7.0.3",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "method-override": "^3.0.0"
```
After creating a new project with `tsed init` using the latest stable version, controllers don't seem to be registered anymore.

## Example
`Routes mounted:` empty list
![Screenshot 2021-04-17 at 17 08 15](https://user-images.githubusercontent.com/1071148/115119284-854d8a80-9f9f-11eb-80f2-06e2a7b7ef0b.png)

## Acceptance criteria

- [ ] Routes should be registered automatically after creating a new project.

**Comment by Romakita** [comment]
Fixed :)
Thanks for your issue
