### ISSUE TITLE
[FEAT] Allow enums in Params

### ISSUE THREAD

**Issue by ClickerMonkey** [TypedProject/tsed#1361]
## Informations
**Is your feature request related to a problem? Please describe.**
You can't pass enums or JsonSchemaObject to the following decorators:
- BodyParams
- PathParams
- QueryParams

**Describe the solution you'd like**
To be able to pass enums or JsonSchemaObject to the listed decorators above, and any similar decorator which accepts a type.

## Acceptance criteria

- [ ] The listed decorators accept an enum or JsonSchemaObject.

**Comment by Romakita** [comment]
I think you've missed the Enum decorator usage on params:
```typescript
@BodyParams() @Enum(MyEnum) enum: MyEnum
```

See you
Romain
