### ISSUE TITLE
[FEAT] Allow models with many groups to be aliased

### ISSUE THREAD

**Issue by ClickerMonkey** [TypedProject/tsed#1362]
## Informations
**Is your feature request related to a problem? Please describe.**
In my swagger docs I have a generated model name of "BillReviewItemBillReviewItemResultProjectOptionEmployeeOptionRateScheduleOptionLaborCodeTypeOptionJobTitleOption" which is of course crazy long, and is generated by this code:

```ts
@Returns(Status.OK, ResponseObjectModel).Of(BillReviewItemModel).Groups('billReviewItem.result', 'project.option', 'employee.option', 'rateSchedule.option', 'laborCodeType.option', 'jobTitle.option')
```

**Describe the solution you'd like**
It would be awesome if we could name this object being return - something user friendly. These really long generated names can really interfere with the UI and readability.

```ts
// maybe add Name or Alias?
@Returns(Status.OK, ResponseObjectModel).Of(BillReviewItemModel).Groups('billReviewItem.result', 'project.option', 'employee.option', 'rateSchedule.option', 'laborCodeType.option', 'jobTitle.option').Name('Bill Review Item Result')
```

**Describe alternatives you've considered**
I've tried using `.Title('override')`, `.Schema({ name: 'override' })` but neither worked.

## Acceptance criteria

- [ ] We're able to override the generated name for models with groups specified.

**Comment by Romakita** [comment]
Hello @ClickerMonkey 
Why you don't use an uniq group label instead of a list 'billReviewItem.result', 'project.option', 'employee.option', 'rateSchedule.option', 'laborCodeType.option', 'jobTitle.option' ?

**Comment by ClickerMonkey** [comment]
We have hundreds of models and thousands of relations, so it would result in hundreds of groups, specified on each property potentially. 

If this isn't even technically possible, it would be easier to handle a uniq group label if you didn't have to add it to every property (some models we have have over 100 properties) but perhaps it could be defined at the class level and the list of properties could be given. Maybe something like this?

```ts
@Groups<TaskModel>({
  'group1': ['id', 'name'],
  'group2': ['id', 'name', 'done', 'etc'],
})
class TaskModel {
  @Property(Number)
  id!: number;
 // ... etc
}
```

Just a thought...

**Comment by Romakita** [comment]
Hello @ClickerMonkey 

The group name is dependent on the endpoint context and not on the class, so the second solution will be confusing. Suddenly, the refactoring work will be just as complicated for you.

```typescript
@Groups<TaskModel>({
  'group1': ['id', 'name'],
  'group2': ['id', 'name', 'done', 'etc'],
})
class TaskModel {
  @Property(Number)
  id!: number;
 // ... etc
}
```
Versus:
```typescript
class TaskModel {
  @Property(Number)
  @Group('group1', 'group2')
  id!: number;
 // ... etc
}
```

But If you want to do that on you project, let's go. Ts.ED offer a lot of utils to implement decorators by your own way ;)

Here is the code:

```typescript
function GroupsAlias<T>(groups: Record<string, (keyof T)[]): ClassDecorator {
   const entries = Object.entries(groups);
   return JsonEntityFn((entity) => {
       entity.children.forEach((propEntity) => {
            const groups = entries.filter(([, props]) => props.includes(propEntity.propertyKey)).map(([key]) => key)

            Groups(...groups)(propEntity.target, propEntity.propertyKey)
       })  
   }
}
```
See you
Romain

**Comment by Romakita** [comment]
After some thought, it doesn't seem so uninteresting to me...
