### ISSUE TITLE
[BUG] Unexpected  crash of app

### ISSUE THREAD

**Issue by AlexDede** [TypedProject/tsed#1384]
## Information

Hi! 

In some cases, our application crashes with the following error on different controllers

```javascript
 /sources/node_modules/@tsed/common/lib/platform/services/PlatformHandler.js:174
         $ctx.data = er;
                   ^
 TypeError: Cannot set property 'data' of undefined
     at PlatformExpressHandler.onError (/sources/node_modules/@tsed/common/lib/platform/services/PlatformHandler.js:174:19)
     at PlatformExpressHandler.onCtxRequest (/sources/node_modules/@tsed/platform-express/lib/services/PlatformExpressHandler.js:36:25)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async onRequest.err.err (/sources/node_modules/@tsed/platform-express/lib/services/PlatformExpressHandler.js:16:21)
```

I can not share the application code, but if needed I can assist if need more information.

I am able to emulate this error only if I set  `req.$ctx = undefined!;` and controller method should throw any error. But we don't have any manipulation with `$ctx` in our code.

```javascript

@Controller()
export class TestController {

    constructor() {
    }

    @Get('/api/1.0/test')
    @Description('Some description')
    public async getBalance(@Req() req: express.Request): Promise<void> {
        req.$ctx = undefined!;
        throw new Error();
    }

}
```

- **Version:** 6.45.1
- Packages: 
```json
"dependencies": {
    "@koa/multer": "3.0.0",
    "@okta/okta-sdk-nodejs": "4.5.1",
    "@tsed/ajv": "6.45.1",
    "@tsed/common": "6.45.1",
    "@tsed/core": "6.45.1",
    "@tsed/di": "6.45.1",
    "@tsed/exceptions": "6.45.1",
    "@tsed/json-mapper": "6.45.1",
    "@tsed/mongoose": "6.45.1",
    "@tsed/platform-express": "6.45.1",
    "@tsed/schema": "6.45.1",
    "@tsed/socketio": "6.45.1",
    "@tsed/swagger": "6.45.1",
    "ajv": "8.1.0",
    "awesome-phonenumber": "2.49.0",
    "aws-sdk": "2.893.0",
    "card-validator": "8.1.0",
    "compression": "1.7.4",
    "config": "3.3.6",
    "connect-mongo": "4.4.1",
    "cookie-parser": "1.4.5",
    "cookie-session": "1.4.0",
    "currency-codes": "2.1.0",
    "currency-formatter": "1.5.7",
    "express": "4.17.1",
    "express-session": "1.17.1",
    "ioredis": "4.27.1",
    "ip": "1.1.5",
    "jwt-decode": "3.1.2",
    "luhn-alg": "1.0.1",
    "moment": "2.29.1",
    "moment-timezone": "0.5.33",
    "mongo-cursor-pagination": "7.4.0",
    "mongoose": "5.12.5",
    "mongoose-paginate-v2": "1.3.17",
    "nats": "1.4.12",
    "node-fetch": "2.6.1",
    "normalize-path": "3.0.0",
    "protobufjs": "6.10.2",
    "reflect-metadata": "0.1.13",
    "request": "2.88.2",
    "request-promise-native": "1.0.9",
    "similarity": "1.2.1",
    "simple-oauth2": "3.4.0",
    "socket.io": "4.0.1",
    "socket.io-redis": "6.1.0",
    "source-map-support": "0.5.19",
    "token-introspection": "3.0.2",
    "uuid": "8.3.2",
    "valid-south-african-id": "1.0.1"
  },
```

**Comment by Romakita** [comment]
Hello @AlexDede 
It's not enough to know why you have this issue, but the only reason that I see is you try to do something after the request is sent or the request is already done during the endpoint execution. Did you use combination with Next and Promise ?
The error always on the same method or it's random?

I'll try to secure the code to avoid the `$ctx.data = er`. I suspect there an error emitted by your code but the response is already sent to your consumer.

See you
Romain

**Comment by Romakita** [comment]
I tried your example, and the code throw the expected error. You probably have something else causing this error, but I don't think req.$ctx = undefined is the reason.

**Comment by Romakita** [comment]
The only way to have a request.$ctx undefined is here:
```typescript
  response.onEnd(async () => {
    await ctx.emit("$onResponse", ctx);
    await ctx.destroy();
    delete req.$ctx;
  });
```
https://github.com/TypedProject/tsed/blob/production/packages/common/src/platform/utils/createContext.ts#L39

So it means, the response is already send.

**Comment by AlexDede** [comment]
@Romakita Thanks for your reply!

> The error always on the same method or it's random?
> 

It is happening on the different controllers.

It seems that the root cause of my error was middleware that was added in `$afterRoutesInit`. And when I removed it my test example also start to work correctly
