### ISSUE TITLE
There should exist a proper guide how to implement JWT

### ISSUE THREAD

**Issue by sinner** [TypedProject/tsed#235]
There should exist a proper guide how to implement JWT.

Maybe should exist a decorator to specify the routes that are going to be validated by this JWT authorization... What do you think?

**Comment by Romakita** [comment]
Hi @sinner,
Actually no. But you can read this issue https://github.com/Romakita/ts-express-decorators/issues/179

**Comment by lwallent** [comment]
Hi @sinner 

Are you having issues with implementing JWT or are you just suggesting?

It is really pretty simple but often the requirements to the JWT Middleware is different. Which secrets are to be supported, different audiences and algorithms, so you will end up with your own middleware implementation anyways.

Basics:

JWT decorator

```typescript
export function JWT(): Function {
    return Store.decorate((store: Store) => {
        store
            .set(JWTMiddleware, {})
            .merge("operation", {
              security: [{"Token": []}],
              responses: {"401": {description: "No authorization token was found"}}
            });

        return UseBefore(JWTMiddleware);
    });
}
```
You can just wrap express-jwt (and use 'jwks-rsa' if you need rsa) middleware in your own JWT Middleware implementation. Something like:

```typescript
import * as ExpressJwt from "express-jwt";
@Middleware()
export class JWTMiddleware implements IMiddleware {

   
    async use(@Request()     request: Express.Request,
              @Response()    response: Express.Response,
              @Next()        next: Express.NextFunction) {
     
        let expressjwt = ExpressJwt({
            secret: ... ,
            audience: [ ...  ], 
            algorithms: [ ... ]
        });

        expressjwt(request, response, (err) => {
            if (err) { //in case of error pass that on
                return next(err);
            }
            
            //express jwt adds a user to the request
            let token = request['user'];
            response.locals.token = token;
            next();            
         });
    }
}
```

**Comment by sinner** [comment]
Thank you very much for your suggestion, they are going to be very useful.

**Comment by ekifox** [comment]
Up
