### ISSUE TITLE
[TOOLS] tsed-cli

### ISSUE THREAD

**Issue by Romakita** [TypedProject/tsed#244]
## Informations

Type | Version
---|---
Tools | 3.x

****

## Description

Create a command line tools to scaffold a project like angular-cli.

- Project configuration. Ability to choose basic Ts.ED extensions (Swagger, Socket.io, etc...),
- Generate a Service,
- Generate a Controller,
- Generate a Middleware.

**Comment by Romakita** [comment]
Proposal:

```bash
Usage: tsed [options] [command]


  Options:

    -V, --version  output the version number
    -h, --help     output usage information


  Commands:

    new              Scaffold a new Ts.ED project
    generate, g  Create a new components (Controller, Service, Middleware, etc...) 
    help [cmd]   Display help for [cmd]
```

**Comment by OskarLebuda** [comment]
@Romakita I am in the process of creating a CLI based on [Commander.js](https://github.com/tj/commander.js/) and [Inquirer.js](https://github.com/SBoudrias/Inquirer.js/). Do you think it will be helpful?

**Comment by Romakita** [comment]
@OskarLebuda  Yes, it could be helpul for new developers ;)

**Comment by OskarLebuda** [comment]
Ok, so I’ll try to finish it ASAP ;)

**Comment by d0whc3r** [comment]
Any update?

**Comment by Romakita** [comment]
On my side, I'm not able to work on currently ^^. @OskarLebuda want to work on. Tell me if you need help.

**Comment by OskarLebuda** [comment]
It’s almost done. I think I’ll create a pull request this week

**Comment by Romakita** [comment]
Nice. Take your time. I won’t be able to review it and merge the branch until two weeks. No computer and small network 😜.

See you ;) (I sent you an invite to the tsed repo ;))

**Comment by d0whc3r** [comment]
Any update?

**Comment by OskarLebuda** [comment]
Sorry for late, but I had some personal issues. I'll try to create PR this week

**Comment by edgesite** [comment]
@OskarLebuda is there any updates?
I think I can help with this.

We have to plan features first, like:
- Project Initializer (we need templates like CRA(https://github.com/facebook/create-react-app/tree/master/packages/react-scripts/template*) or Vue(https://github.com/vuejs-templates))
- Codegen: Service, Controller, etc...
- Debug/Test/Run, new version check in debug environment
- Upgrade mechanism use ts-simple-ast or just a simple git diff(like rn)

Seems the project initializer and codegen is the pain point of CLI and should have higher priority.

**Comment by edgesite** [comment]
^ @Romakita

**Comment by Romakita** [comment]
Hello @edgesite,
Currently, I'm really busy, I work on issue and enhancement on core framework. I know the CLI really importante and contributors are welcome. I can help on this topics to create dedicated repository or given any things required for the project (deployment, tasks, infos, etc...). I worked on projects examples last week which can be reused for a project template.

@OskarLebuda is the first to work on the cli (branch feat/cli). 

Tell what can I do to advance the subject and work togother :)

See you
Romain

**Comment by Romakita** [comment]
CLI can be develop on this repository https://github.com/TypedProject/tsed-cli if it's more comfortable for you :)

**Comment by edgesite** [comment]
Okay thanks for update. I think I can make the CLI works and make an iterate plan in a few weeks.

**Comment by shakilsiraj** [comment]
Any progress on this feature?  I can help if need be.

**Comment by Romakita** [comment]
Hello @shakilsiraj  

Your help is welcome ;)

**Comment by d0whc3r** [comment]
@Romakita could you initialize cli repo with some default config, like prettier or eslint or whatever you want to have? I was going to start with cli but I miss the basic skeleton, I started creating the basic features but I don't know which are your preferences

Thanks

**Comment by Romakita** [comment]
@d0whc3r Yes I doing that :)

**Comment by Romakita** [comment]
@d0whc3r I you write the cli in typescript or pure js ?

**Comment by d0whc3r** [comment]
typescript and rollup to transpile should be a good choise, also eslint instead of tslint

**Comment by Romakita** [comment]
rollup ?

**Comment by Romakita** [comment]
Ok rollup isn't necessary. We haven't needs about to create bundle. isn't a front-end application :)

**Comment by d0whc3r** [comment]
ok, then you plan to execute with ts-node?

**Comment by Romakita** [comment]
No, I'll compile the source to js (with tsc) and deploy it on npm :)
It's almost done :)

**Comment by d0whc3r** [comment]
ok, perfect

**Comment by Romakita** [comment]
The project base code is ready :)
I already implemented an example to generate a Controller.

The stack is based on: 
- Inquirer
- Commander 
- TsED DI
- TsED decorators
- Lerna.js (monorepo)
- Consolidate/handlebars for template
- Typescript

I sent you an invitation to the repo ;)
See you

**Comment by Romakita** [comment]
https://github.com/TypedProject/tsed-cli

**Comment by Romakita** [comment]
The cli is available in alpha version:

```
npm i -g @tsed/cli@alpha
```

Your feedback are welcome :)

See you

**Comment by Romakita** [comment]
Also I published the @tsed/cli-core package. This package is designed to help developer to create his own CLI with TypeScript and the Ts.ED DI framework + Plugins.

Here the readme:
https://github.com/TypedProject/tsed-cli/tree/master/packages/cli-core

**Comment by Romakita** [comment]
CLI is now in beta. Website is available: https://cli.tsed.io/

See you :)

**Comment by NachtRitter** [comment]
@Romakita 
If I select "Database -> TypeORM" installation gets stuck on "Resolve versions" step.

```
@tsed/cli 1.6.3
node 10.19.0
yarn 1.22.4
npm 6.13.4
Ubuntu 18.04
```

**Comment by Romakita** [comment]
Hello @NachtRitter 
I released a fix to print an error log when Resolves versions step fail. Can you  reinstall the CLI and run again the same command please :). 

See you
Romain

**Comment by NachtRitter** [comment]
@Romakita 
Unfortunately, there is no error. Only an endless step of resolving versions.

![image](https://user-images.githubusercontent.com/3122765/77941775-5e081a80-72c3-11ea-8c24-befe7e122e3a.png)

**Comment by Romakita** [comment]
Have you a network restrict or a proxy configured? 

I’ll try reproduce the bug by installing postgres.

**Comment by Romakita** [comment]
You can also run the command in verbose mode. Maybe the logs will be more interesting.

tsed init . —verbose

**Comment by Romakita** [comment]
Are you on windows ?

**Comment by NachtRitter** [comment]
@Romakita 
Nevermind, I guess it was really some issues with my router. I've checked and realized that I have a big latency between my notebook and router (during packages installation it was ~300-800 ms). After router rebooting looks like it works fine.

**Comment by Romakita** [comment]
Hoo coool xD.

Latest version add docker-compose generation, by adding service (database) according to your database choice :D

See you
Romain
