### ISSUE TITLE
Custom validation rules

### ISSUE THREAD

**Issue by kalu111** [TypedProject/tsed#312]
Hi @Romakita,
Is there any way to do that?

```typescript
class MyModel {
    @Rule(MyCustomValidationRule)
    id: string;
}
```

How can I register custom validation rules per model properties?
It is the proper location to do that in converters?

**Comment by Romakita** [comment]
Hi @kalu111,
Validation is assumed by AJV not by Converters Service. You can look on this documentation https://github.com/epoberezkin/ajv
See you,
Romain

**Comment by Romakita** [comment]
@kalu111 Do you find a solution ?

**Comment by kalu111** [comment]
I can not see any proper solution for me :)
The best and simple is to create `@Rule` decorator that accepts classes which implements more specific interface:

```typescript
interface IValidationRule {
    errorMessage: string;
    async rule(paramValue: any, paramName: string): Promise<boolean>;
}

class MyRule implements IValidationRule {
    errorMessage = 'Invalid property';
    constructor(@Inject(MyService) private myService: MyService) {}
    async rule(paramValue: any, paramName: string) {
        // my more complicated validation logic (select value form db or config)
    }
}

class MyModel {
    @Rule(MyRule)
    id: string;
}
```

Custom validation rules for property can be invoked right after `ajv` rules.
It is of course only my proposal.
Maybe you have a better approach?

**Comment by Romakita** [comment]
@kalu111 Sorry, I haven't a right solution. So this feature can be implemented in the `@tsed/ajv` package. If you have a time ;).
You can take as an example the interceptors packages dev by `mitevs`, to create your own class Rule (like filter or middleware).

```typescript
interface IValidationRule {
    errorMessage: string;
    async rule(paramValue: any, paramName: string): Promise<boolean>;
}

@Rule()  // add this class in the injector service
class MyRule implements IValidationRule {
    errorMessage = 'Invalid property';
    constructor(@Inject(MyService) private myService: MyService) {}
    async rule(paramValue: any, paramName: string) {
        // my more complicated validation logic (select value form db or config)
    }
}

class MyModel {
    @UseRule(MyRule) // attach this rule on class
    id: string;
}
```
Then, in the AjvService, find all custom rules from a given class.

**Comment by kalu111** [comment]
There is a great place to create `@ErrorMessage()` decorator to be able to set custom error message for property (even for already implemented ajv based validators).
What do you think @Romakita ?

I'm really thinking about take this job - I will ping to you when I'll be ready.

**Comment by unicreators** [comment]
@Romakita 
Is there any way to do that?

`
@Controller('/items')
export class AccountController {
    constructor(private itemService: ItemService) {
    }
    @Get('/:id')    
    async get(
       @PathParams('id') 
       @Required() // @Required((metadata)=> new CustomError1('code', 'message', '...'))
       @Type(Number,  (metadata)=> new CustomError2('code', 'message', '...'))
       @Range(1, 10, (metadata)=> new CustomError3('code', 'message', '...'))
        id: number) {
        return await this.itemService.getItem(id);
    }
}
`
