### ISSUE TITLE
How to validate type for non array members 

### ISSUE THREAD

**Issue by unintellisense** [TypedProject/tsed#370]
Hello,

I am trying to set up my model to validate non array members. I reviewed the documentation under https://romakita.github.io/ts-express-decorators/#/tutorials/ajv, and see AllowTypes can be used to specify the available types for a array, but I do not see how to do that for a non array member?

I've tried various combinations, mainly with Property and JsonProperty, and while I can get AllowTypes to return a validation error for a mismatch, my string member continues to allow number and boolean values (which end up being stringified).

Here is what my model looks like:

```
import { Required, Property } from "@tsed/common";

export default class Book extends Model {

 @Property()
  @Required()
  title: string

 @Property()
  @Required()
  isFiction: boolean
...
}
```

My endpoint:

```
@Post("/book")
  async postBook(@Required() @BodyParams("book") book: Book) {
   ...
  }
```

When I post to the endpoint, with this json:
```
{
	"book": {
		"title": 1111,
		"isFiction": -1
		
	}
}
```

This is what the object returned to my endpoint looks like:

```
{"title":"1111", "isFiction":true }
```

I would expect both properties to fail validation instead.

Thanks in advance for any help or information.

**Comment by unintellisense** [comment]
Thank you for your time and response.

I spent some time debugging today, and I think the actual cause of the issue is that the PrimitiveConverter is coercing these values before AJV is ever invoked.

I created a couple custom convertors like
```
@Converter(String)
export class StrictStringConverter implements IConverter {
  deserialize<T>(data: string, target: any, baseType: T, deserializer: IDeserializer): String | Number | Boolean | void {
    if (typeof data !== 'string')
      throw new BadRequest(`'${data}' is not a valid string.`);
    return data;
  }

  serialize(object: String | Number | Boolean): any {
    return object;
  }
}
```

... and now the errors thrown by the converters bubble up to the response. I can also just return the value (without testing typeof) and see AJV's exception bubbling up, but I think for now I'll leave this in the converter.

So, I guess this solves my specific issue.  If you had any interest in a change to allow this inherently in this framework, I would probably get around to making a PR :) . I'm not sure what you would have in mind as far as how it should be implemented.

**Comment by Romakita** [comment]
I've right for the PrimitiveConverter. Is volunteer, responsability of the ConverterService is to try to converter an object to his model according the type Model description. But you're implementation
can be added as example for the documentation or in future, we can merge your work (PR) with the currents converters and provide an option to use a strict conversion.

```typescript
@ServerSettings({
   converters: {
      modelStrict: true, // eq. validationModelStrict
      typeStrict: true // your options
   }
})
```
And an example of a converter:
```typescript
@Converter(String, Number, Boolean)
export class PrimitiveConverter implements IConverter {
  typeStrict: boolean = false;
  constructor(settings: ServerSettingsService) {
     this.typeStrict = (settings.get('converters') || {}).typeStrict;
  }

  deserialize(data: string, target: any): String | Number | Boolean | void {
    switch (target) {
      case String: // example with the string
        if (this.typeStrict && typeof data !== 'string') {
             throw new BadRequest(`'${data}' is not a valid string.`);
        }
        return "" + data;

      case Number:
        const n = +data;

        if (isNaN(n)) {
          throw new BadRequest("Cast error. Expression value is not a number.");
        }

        return n;

      case Boolean:
        if (data === "true") return true;
        if (data === "false") return false;

        return !!data;
    }
  }

  serialize(object: String | Number | Boolean): any {
    return object;
  }
}
```

For information, Ajv Validation is ran before ConverterService.  
https://github.com/Romakita/ts-express-decorators/blob/master/src/common/filters/class/FilterBuilder.ts#L21-L23
I tried this morning to configure Ajv, but I didn't find the right options...

See you,
Romain
