### ISSUE TITLE
How to test multiple rest API calls in a single it block

### ISSUE THREAD

**Issue by awaragi** [TypedProject/tsed#372]
## Informations

Type | Version
---|---
Question | 4.x

****

## Description
Using super test and chai-http, I am unable to call multiple rest API endpoints in a single it block. I am using your rest testing example which tests a single endpoint at a time. 

My usecase is a post (create) and a get to retrieves.  On the get method call I get an exception. 

## Acceptance criterias

- [ ] Answered

**Comment by Romakita** [comment]
Hi @awaragi,

Sorry for my late response. I never use chai-http. Can you send me an example of your test, pls ?
Maybe with the latest version (published yesterday) work fine. 
See you
