### ISSUE TITLE
Extending Express Request

### ISSUE THREAD

**Issue by azigelman** [TypedProject/tsed#391]
## Informations

Type | Version
---|---
Question | 4.x

****

## Description
Extending the express request.

I want to add a custom key to the express request. I have two possible solutions, I was wondering if there is a better / suggested way?

#### Example 1:
`request['statsdKey'] = 'someKey';`

#### Example 2:
`
declare global {
	namespace Express {
		interface Request {
			statsdKey: string;
		}
	}
}`

**Comment by milewski** [comment]
your second example is the correct way of doing it.. and usually this code lives inside a file called `typings.d.ts` in the root of your project.
