### ISSUE TITLE
Reusing framework's calculated stats

### ISSUE THREAD

**Issue by azigelman** [TypedProject/tsed#392]
## Informations

Type | Version
---|---
Question | 4.x

****

## Description
This is already calculated.

```
{
  "status": 200,
  "reqId": "1",
  "method": "GET",
  "url": "/api/account/1234",
  "duration": 1791
}
```
Is there a way to use these stats in other parts of my code?

## Acceptance criterias

- [x] Example (log, usecase, etc...)
- [x] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
Currently, isn't possible. But we can add a method on request to return the stats.

Something like that:
```typescript
req.log.stats();
```

@milewski What do you think about that ?
See you,
Romain

**Comment by milewski** [comment]
i cant think of a use case where such feature would be useful.. what is the goal of capturing these data on the server side?

**Comment by azigelman** [comment]
@milewski For metric gathering and monitoring. 
I am currently using https://github.com/uber/express-statsd which calculates response time all over again

**Comment by milewski** [comment]
i think a more precise measurement could be archived by having a reverse proxy in front of your express app.. for example `Caddy server` and using one of its plugins like [Prometheus](https://caddyserver.com/docs/http.prometheus) to gather more precise metrics not only about your requests in/out but your system etc if needed... 

just a suggestion tho

**Comment by TomerAmirV** [comment]
Thanks @milewski!
We are using similar monitoring frameworks but we have another issue,
we are running our server as a Docker container, and we have multiple services running on the same server. we would like to isolate our service and although not the most accurate, it's good enough for our needs.
