### ISSUE TITLE
[question] Any plan to support external DI into @tsed/*?

### ISSUE THREAD

**Issue by dario1985** [TypedProject/tsed#394]
## Description
There is any plan in the current roadmap to add support to external DI containers (like `InversifyJS` or `TypeDI`)?

**Comment by Romakita** [comment]
Hi @dario1985,
No because, Ts.ED already have his own DI.

**Comment by Romakita** [comment]
What is missing features in tsed DI ? What is your needs ?

**Comment by dario1985** [comment]
There is not a simple answer, I try to resume some reasons that I believe could be fine to be more container-agnostic:

- Need for some specific feature (eg. like async factories, advanced/tagged binding... )
- Already using some DI container or different standards (and decorators) in a project, and it could generate confusion and fragmentation 
- Some external libraries (like Ts.ED) already implement a default container and decorators but don't support/or hard to integrate with the Ts.ED interface (like [`typeorm`](https://github.com/typeorm/typeorm/blob/master/docs/faq.md#how-to-use-typeorm-with-a-dependency-injection-tool), and some [testing framework](https://github.com/timjroberts/cucumber-js-tsflow#bindings), etc)

**Comment by Romakita** [comment]
@dario1985 I understand your points.

Support different DI is big work (synchronize container between tsed/di and other DI container, etc..). But, integrate TypeORM can be planed in a future version :).

Work on agnostic container is also possible (I work on currently). But I need some help to know what is required to do that.

See you,
Romain

**Comment by Romakita** [comment]
@dario1985  TypeORM is supported by Ts.ED now 

Documentation is here https://romakita.github.io/ts-express-decorators/#/tutorials/typeorm

See you
Romain

**Comment by Romakita** [comment]
Hi @dario1985,

To support other DI, I need to understand what you want. Can you help me with some code examples, you have in mind ;) ?
See you,
Romain
