### ISSUE TITLE
Bug: Date Validation on QueryParam doesn't work

### ISSUE THREAD

**Issue by YehonatanVonage** [TypedProject/tsed#395]
TsED version: 4.17.5

TLDR: Type validation for Date in @queryparams doesn't work

I created controller & added route function of the next signature:
```
async foo(@Required() @QueryParams('start_date') startDate: Date) {
   ...
}
```

When I send a request with "startType query param" that its type is different from "date", the QueryParam validation doesn't work, and it doesn't throw any exception about mismatched type.

**Comment by Romakita** [comment]
Hi @YehonatanVonage,

Validation is only performed when you use a Model and AJV for example. Date is handle by the DateConverter. And currently, the code is that:
```typescript
/**
 * Converter component for the `Date` Type.
 * @private
 * @converters
 * @component
 */
@Converter(Date)
export class DateConverter implements IConverter {
  deserialize(data: string): Date {
    return new Date(data);
  }

  serialize(object: Date): any {
    return object.toISOString();
  }
}
```
You can override the DateConverter on your side to check the date. Something like that:
```typescript
/**
 * Converter component for the `Date` Type.
 * @private
 * @converters
 * @component
 */
@Conveter(Date)
export class DateConverter implements IConverter {
  deserialize(data: string): Date {
    const date = new Date(data);
    if (isNaN(d.getTime())) {  // d.valueOf() could also work
       throw new BadRequest("Cast error. Expression value is not a valid date.");
    }
    return date;
  }

  serialize(object: Date): any {
    return object.toISOString();
  }
}
```
If it works, a PR is welcome :)

See you
Romain

**Comment by milewski** [comment]
@Romakita today i was facing a similar problem, `toISOString()` wasnt being accepted by the validator only if i gave something like this: `2018-01-01` it would pass! ... so for the meantime i im doing something like this:

```ts
const date = new Date('2018-01-01').toISOString().split('T').shift() 
// which leaves me only with '2018-01-01' (ignore the redundancy here)
```

```ts
class myModel {
    @Required()
    @Format('date')
    date: Date
}

@Controller('/')
export class Controller {

    @Get('/')
    async root(@BodyParams() options: myModel) {
       
    }

}

**Comment by Romakita** [comment]
Hum @milewski in your case the problem come from AJV validator.

**Comment by Romakita** [comment]
Maybe you can check the JsonSchema generated in AjvService.

**Comment by Romakita** [comment]
v6 fix this issue :)
