### ISSUE TITLE
[Suggestion] Creating a response object

### ISSUE THREAD

**Issue by tomer-amir** [TypedProject/tsed#399]
## Informations

Type | Version
---|---
Suggestion | 4.x

****

## Description
Before this framework, I used to work with Java - Spring Boot.
When returning an object there, you usually wrap it with a `ResponseEntity` object that allows you to do things like setting the response status code easily.

Example (Java):
```java
@RequestMapping(value = "/create", method = RequestMethod.POST)
@ResponseBody
public ResponseEntity<User> createUser() {
    User user = new User()
    return new ResponseEntity(user, HttpStatus.CREATED);
}
```

For now, in TsED you need to do the following:
```typescript
@Post('/create')
createUser(@Response() response: ExpresResponse): User {
    response.status(201);
    return new User();
}
```

My suggestion is the create a `Response` (maybe with a better name) wrapper that will allow doing the same and will look like this:
```typescript
@Post('/create')
createUser(): Response<User> {
    return new Response<User>(new User(), 201);
}
```

I think this is much cleaner and more intuitive, but I come from Java 😜 

What do you think?

**Comment by kalu111** [comment]
It is good idea.

Does Response object can set additional headers?

**Comment by milewski** [comment]
You could also do this

```ts
@Post('/create')
@Status(201)
createUser(): User {
    return new User();
}
```

**Comment by kalu111** [comment]
Yes, I know :)

But in some situations it is a need to set header when its value can only be calculated  in request callback (controller method).

**Comment by milewski** [comment]
u could always throw errors and capture them on a middleware written the appropriate response for each case.. which is much cleaner than setting this info directly in the "request callback"

**Comment by TomerAmirV** [comment]
@milewski it's true, but only for error codes, right?
and as @kalu111 said, you could also set headers this way... by maybe I'm wrong cause thinking of it it might too similar to the Express response object, so we might just want to use it...

I'm not sure, this is why it's a suggestion 😅

**Comment by Romakita** [comment]
Hi guys,

If you want test your concept (to begin), it's possible without modification in tsed. The middleware that is responsible to build response is the SendResponseMiddleware.

You can override this middleware and implement your logic. Here a piece of code:
```typescript
@OverrideMiddleware(SendResponseMiddleware)
export class CustomSendResponseMiddleware extends SendResponseMiddleware {
constructor(private converterService: ConverterService) {}

  public use(@ResponseData() data: any, @Response() response: Express.Response) {
    
    if (data instanceof Response){

    } else {
       super.use(data, response);
    } 
  }
}
```

I propose you, to test locally this code and your feature with your own project. Then, if you think, this feature is interesting and maintainable, you can create a PR and propose this feature either in `@tsed/common` or as a separated module ;) (some

See you guys,
