### ISSUE TITLE
PropertyType & Property Name issue

### ISSUE THREAD

**Issue by EugenePisotsky** [TypedProject/tsed#410]
Hello!

I have an issue with converting `_id` into `id` for models which are used for `PropertyType`, for example:

```typescript
export class AdminModel {

    @Property({ name: 'id' }) // this one looks like _id in response, but it should be just id
    _id: string;

    @Ref(UserModel)
    user: Ref<UserModel>;

    @Property()
    role: string;

}

@Model({
    name: 'Service'
})
export class ServiceModel implements IServiceModel {
    
    @Property({ name: 'id' }) // this one works as expected and turns into id
    _id: string;

    @PropertyType(AdminModel)
    admins: AdminModel[];

}
```

Version: 4.23.0

Btw i tried to upgrade to the latest (4.26.3) to check if it's already fixed, but have the error related to SocketIO:

```
[1] [2018-07-08T01:41:21.447] [ERROR] [TSED] - { Error: Cannot find module '../../common/config/decorators/constant'
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
[1]     at Module.require (internal/modules/cjs/loader.js:598:17)
[1]     at require (internal/modules/cjs/helpers.js:11:18)
[1]     at Object.<anonymous> (/var/www/backend/node_modules/@tsed/src/socketio/services/SocketIOService.ts:15:1)
[1]     at Module._compile (internal/modules/cjs/loader.js:654:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
```

Thanks in advance and thanks for the time you spend to work on TsED. This project is amazing.

**Comment by Romakita** [comment]
Found and fixed :)

**Comment by RevanScript** [comment]
Thanks a lot! Works fine now

**Comment by RevanScript** [comment]
Not yet. Looks like it gave rise to an another bug (or feature, idk) :)
All `@Ref` which weren't populated return object now:

```
    @Ref(ItemCategoryModel)
    category: Ref<ItemCategoryModel>;
```

Returns:

```
    "category": {
        "id": "5b28784ea63afa026a88d8be"
    },
```

Expected just `"category": "5b28784ea63afa026a88d8be"` if `.populate('category')` wasn't used.

**Comment by Romakita** [comment]
Arg, it's very specific from Mongoose... I need to find another solution because, the latest fix break something too.

**Comment by RevanScript** [comment]
Any updates on this? :)

**Comment by Romakita** [comment]
Hello @RevanScript ,

No update, sorry... unfortunately, this problem is a bit complex and is related on other issues based on JsonSchema and ConverterService.  

I've already tried to fix your problem but it has introduce regression on other features. 

I've a lot of bug/enhancement in the backlog, this one is prioritized on top of the list, but it require more than one day to work on T.T
Sorry for the long time to fix that.

I'll try to focus my effort on this part ASAP.
Romain

**Comment by RevanScript** [comment]
Ok, no problem. I just asked to decide if i should wait or use a workaround until it's fixed.
Thanks for the answer and your work!

**Comment by Romakita** [comment]
I think, it would be better to work on workaround, share your works with me ;)

**Comment by Romakita** [comment]
v6 fix this issue
