### ISSUE TITLE
4.26.4 breaks ConverterService

### ISSUE THREAD

**Issue by milewski** [TypedProject/tsed#411]
Hi @Romakita version `^4.26.4` broke most of my tests 🤕, error message is 

```Property name on class ObjectID is required.```

the problem seems to be originating from this class on my middleware: 

```ts
this.converterService.serialize(data)
```

and this is what i am passing to the serialize() method:

```ts
async products() {

    return {
        products: await this.productService.find(...)
    }

}
```

**Comment by Romakita** [comment]
Hi @milewski ,
Can you be more precise ? What is the class of your data and the model ? 
The change is here:
https://github.com/Romakita/ts-express-decorators/blob/master/src/common/converters/services/ConverterService.ts#L75-L77

https://github.com/Romakita/ts-express-decorators/blob/master/src/common/converters/services/ConverterService.ts#L117

The serialisation for mongoose start from this file: https://github.com/Romakita/ts-express-decorators/blob/master/src/mongoose/utils/createModel.ts#L28

The fix solve the problem for this issue #410 but apparently, it add another bug.

Can you help me and investigate on your bug with the ObjectID ? Just to give me more information (or a fix :p).
I'll investigate on my side about the #410 issue.

See you ;)

**Comment by milewski** [comment]
im investigating these files you sent to see if i can find the reason, but meanwhile in my example this is the data that gets passed to the serialize method:

```

const data =  {
        products: await this.productService.find(...) // MongooseDocument<Model>[]
}

this.converterService.serialize(data)

```

**Comment by Romakita** [comment]
Ok. But this.productService.find(...) return a model base on Class or not ?

**Comment by milewski** [comment]
this is what the productService service is doing behind the scene the return is the `MongooseDocument<Product>[]` 

```
@Model() 
class Product {

}

class ProductService{
 constructor(
    @Inject(Product) public product: MongooseModel<Product>)
    super()
 }

 find(...){
    return this.product.find(....)
 }

}
```

**Comment by Romakita** [comment]
Product hasn't any field configured with decorator ?

**Comment by milewski** [comment]
it has ... it was just my bad example...

**Comment by Romakita** [comment]
ok ^^ I just need the Product class with his property, to find the bug ;)

**Comment by milewski** [comment]
ok i updated that... might have something to do with 

```

    @IgnoreProperty()
    _id?: string

    @IgnoreProperty()
    __v?: number

```

**Comment by Romakita** [comment]
Hum ok. I think I have an idea about your problem :). Thanks @milewski

**Comment by Romakita** [comment]
The latest release, fix the problem with the deserialisation when you have an array of Model in your class. For example: ProductCategory is affected by the latest release.

Can you send me the ProductCategory Model pls ?

**Comment by Romakita** [comment]
ok. Thanks @milewski :)
