### ISSUE TITLE
How to add types options to a custom interceptor?

### ISSUE THREAD

**Issue by floriantraber** [TypedProject/tsed#437]
## Informations

Type | Version
---|---
Question | 4.30.1

****

## Description
I'm trying to convert a TypeScript Decorator to Ts.ED. 

The following TypeScript code enforces a non-optional parameter cacheOption on the decorator. Optional or required fields of the type are checked on compile-time and produce an error.

```
export function cache(cacheOption: CacheOption) {
  return function (target, propertyKey: string, descriptor: PropertyDescriptor) {
```
 
Following the example on 
https://tsed.io/#/docs/interceptors?id=interceptor-class I can easily convert the method body itself. But after converting any type safety is lost. 

```
aroundInvoke(ctx: IInterceptorContext, opts?: any) {
```
In the example code, the  `aroundInvoke` method doesn't know that the `opts` parameter is of type string, neither is supplying of the parameter enforced should it be required.

**Comment by Romakita** [comment]
Hello @floriantraber 
I'm not sure what do you want. Can you give me more details ^^?
For information the interceptor is implement here: https://github.com/Romakita/ts-express-decorators/blob/production/packages/common/interceptors/utils/interceptorInvokeFactory.ts

https://github.com/Romakita/ts-express-decorators/tree/production/packages/common/interceptors

Maybe the code will help to explain me the problem ;)
See you
Maybe with this impl

**Comment by floriantraber** [comment]
I'm unable to create a generic Implementation that enforces the type of the parameter. My goal is to have the second parameter to be typed and not be of the type `any?` but to be generic. 

Example with an hardcoded interceptor and hardcoded options.

```


export interface ITypedOptions {
  requiredOption: string;
}

export function TypedIntercept<T extends IInterceptor>(options: ITypedOptions):
  (target: any, propertyKey: string, descriptor: PropertyDescriptor) => any {
  const interceptor = TypedInterceptor;
  return (target: any, propertyKey: string, descriptor: PropertyDescriptor) => {
    Store.from(target).merge('injectableProperties', {
      [propertyKey]: {
        bindingType: 'custom',
        propertyKey,
        onInvoke: interceptorInvokeFactory(propertyKey, interceptor, options),
      },
    } as IInjectableProperties);

    return descriptor;
  };
}

export interface ITypedInterceptor<T> {
  aroundInvoke: (ctx: IInterceptorContext<any>, options: T) => any;
}

@Interceptor()
export class TypedInterceptor implements ITypedInterceptor<ITypedOptions> {
  public async aroundInvoke(ctx: IInterceptorContext<any>, cacheOption: ITypedOptions) {
  }
}

// usage
@Service()
export class MyClass {
  **// typescript does NOT provide typing and compile-time checks to the second parameter.**
  @Intercept(TypedInterceptor, { thisParameterDoesnExists: 1 })
  // typescript enforces supplying of the parameter 'requiredOption'
  @TypedIntercept({ requiredOption: 'value' })
  public myMethod() {

  }
}
```

**Comment by Romakita** [comment]
This issue is to old. If the need is always available I encourage you to open a new Issue with the right spec :)
