### ISSUE TITLE
[Question] Production Deployment Process

### ISSUE THREAD

**Issue by sinner** [TypedProject/tsed#444]
## Informations

Type | Version
---|---
Question | 4.x

****

## Description
How should be the deployment process in a production environment? Is that already documented?

I think that we must not to use ts-node to deploy in production, this topic should be explained on the documentation.

Does it make sense for you?

## Acceptance criterias

- [ ] Example (log, usecase, etc...)
- [ ] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
Hello @sinner,

The deployment process is dependent of each project and what kind of server your application is deployed (Heroku, AWS etc...). For example, the process to deploy Ts.ED app on AWS is documented here http://tsed.io/tutorials/aws.html

For sure, it make sense to describe a common process if it's possible :D. Contributing on this part are welcome and would be awesome for developers :D 

If you have example or any idea, you can propose here or create PR (documentation is based on VuePress + markdown).

See you ;)
