### ISSUE TITLE
[Bug] Classes with same name and validation decorators collide/overwrite each other

### ISSUE THREAD

**Issue by aaronstaves** [TypedProject/tsed#450]
## Information

Type | Version
---|---
Bug | 4.31.4 (also affects earlier versions)

****

## Description
👉 [I've created a repository with a more in-depth explanation here.](https://github.com/aaronstaves/tsed-validation-model-with-same-classname) 👈 

No idea why this is happening, I can only speculate that validation definitions are registered/stored by using the class name and property of the object their validating.  With that said --

I have 2 classes, that have the same name and are nearly identical in structure.  Each class has a different validation method (i.e. `@MaxLength(5)` on a _FirstName_ property for one class and a `@MaxLength(10)` on a _FirstName_ property for another class.  For some reason, no matter which endpoint I submit to, the conversion -> validation seems to only be validating against one of these classes and not both.  

Changing the class name does fix this, but I would think that shouldn't matter in the long run.

## Acceptance criteria

- [ ] Sample repository listed in description validates against person criteria when posting to the `/Person` endpoint
- [ ] Ability to have 2 identical classes (names and properties) with different validation criteria, and the conversion -> validation validates appropriately.

**Comment by Romakita** [comment]
v5/v6 solve this issue by using `@Name()` decorator to change the class name in the generated swagger.
