### ISSUE TITLE
Swagger - show enum values for query param

### ISSUE THREAD

**Issue by YehonatanVonage** [TypedProject/tsed#458]
## Informations

Type | Version
Question about swagger on tsed
@tsed/swagger: 4.30.1

****

## Description
I created controller with get method, and added to it QueryParam, that its type is an enum.
When getting to the relevant swagger documentation about my get method, how can I show the user a list of the enum options for the param.
Currently it shows me textfield and not drop down of the enum values.

**Comment by Romakita** [comment]
Hello @YehonatanVonage,

Currently, isn't supported but the `@Schema` or `@Operation` can help you to customize the documentation for your method.

See you,
Romain

**Comment by SiergiejVatz** [comment]
@Romakita  Hello, if possible, please write an example of how to describe the query parameter so that in the query params swagger documentation is a list, not a string. I can't do it syntactically.
```
   @Operation(({ enum: ["last_month", "last_week", "last_year", "all_time"] }))
    @QueryParams("period") period: FilterPeriodType,
```
```
   @Schema(({ enum: ["last_month", "last_week", "last_year", "all_time"] }))
    @QueryParams("period") period: FilterPeriodType,
```

**Comment by Romakita** [comment]
@SiergiejVatz Your example works ?

**Comment by SiergiejVatz** [comment]
@Romakita doesnt work, but I fixed this.
<img width="689" alt="screen shot 2018-11-11 at 1 46 17 pm" src="https://user-images.githubusercontent.com/36629375/48312543-dda32580-e5b8-11e8-8b16-d575ec48c186.png">
<img width="982" alt="screen shot 2018-11-11 at 1 45 47 pm" src="https://user-images.githubusercontent.com/36629375/48312545-e7c52400-e5b8-11e8-8575-98d7ff0baed5.png">

I wrapped it in my decorator and passed query params into it, is it possible to somehow avoid such overcode in the controller, to generate swagger documentation

**Comment by liukun** [comment]
Seems I can use `@BaseParameter` to set those in schema.

```
  public async get(
    @BaseParameter({ enum: ['asc', 'desc'], default: 'asc' })
    @QueryParams('order')
    order: string = 'asc'
  ) {
    return {}
  }
```

**Comment by Romakita** [comment]
This feature is totally supported by v6.
