### ISSUE TITLE
[Question] Lang & traduction

### ISSUE THREAD

**Issue by Tlahey** [TypedProject/tsed#460]
## Informations

Type | Version
---|---
Question | 4.x

****

## Description

I would like to know if a language module is being integrated into TS.ED.

The goal would be to have a provider that can translate error messages (Exceptions nodeJs) into the user's language and integrate it into html templates.

Here is an example with [i18n-express](https://www.npmjs.com/package/i18n-express).

## Example 

On `ServerSettings` we can configure available language and directory,

REST call with Content-Language: en or fr or ...

So nodejs server know the location and set it.

We thought about several possibilities of implementation : 
- With a service available in all the application
- With a decorator that you can configure to translate parts of the response
- Provide it inside the $error handler to translate the error codes (but just for the errors and not success callback)

I do not know if you have other solutions ?

Thanks :)

**Comment by Romakita** [comment]
Hello @Tlahey ,
I don't have a solution for that, I never work on internationalization for Rest API with express :/
If you need help or more information, tell me.
Romain
