### ISSUE TITLE
Query param with array

### ISSUE THREAD

**Issue by YehonatanVonage** [TypedProject/tsed#472]
I use TSED version 4.30.1

I configure my controller with an endpoint that contains the next query param:
@QueryParams('questionList', String) questionList: string[]

I also use swagger for that endpoint, and it shows well the option to add multiple items to the questionList. 
The problem is that when I add multiple items (in the swagger) to the questionList param:
item: "question1"
item: "question2"
item: "question3"

and invoke the endpoint code, I get the questionList param with only one item that contains all of the questions, and it looks like this: 
["question1,question2,question3"]

What should I change to get the list of questions as multiple items in the questionList?
So it will be: ["question1", "question2", "question3"]

**Comment by Romakita** [comment]
Hello @YehonatanVonage ,

The documentation describe how you can configure the format for Array type. https://swagger.io/docs/specification/2-0/describing-parameters/#array

use collectionFormat with right value. I'll check on my side if this parameter is correctly configured...

See you
Romain

**Comment by Tlahey** [comment]
Hello @Romakita,

I have the same issue, on my controller I have : 

![image](https://user-images.githubusercontent.com/2856778/50518404-ba273200-0ab5-11e9-8168-86e55772db3a.png)

On swagger 

![image](https://user-images.githubusercontent.com/2856778/50518415-cdd29880-0ab5-11e9-8159-06caa0fa3c13.png)

And finally on the JSON swagger-specs

![image](https://user-images.githubusercontent.com/2856778/50518434-e478ef80-0ab5-11e9-81ca-6cfc35f4cfb4.png)

In the [swagger's spec](https://swagger.io/docs/specification/2-0/describing-parameters/#array), type must be an "array" and an object "items" must be contain type.

I don't know if it's possible but used
```typescript
@QueryParams("name", Array(String)) name: string[],
// insted of 
@QueryParams("name", String) name: string[],
```

Thanks.

**Comment by Romakita** [comment]
@Tlahey I think it's bug from SwaggerService. I'll fix that.

**Comment by Tlahey** [comment]
Thank you @Romakita

**Comment by Romakita** [comment]
@Tlahey For me it works fine with the v5.0.7

**Comment by Tlahey** [comment]
Hi @Romakita,

I upgrade to the latest version (5.0.7 common / core / di / swagger) and I have always the same issue =/

```typescript
@QueryParams("name", String) name: string[],
```

On my swagger-ui-dist (swagger-ui-dist@^3.13.6), I don't have the array.

I will try to do other tests.

**Comment by Tlahey** [comment]
I have the same issue with others types. If I don't set like this my queryParams

```typescript
@PathParams("logName") @Required() logName: string // swagger show param like an object
@PathParams("logName", String) @Required() logName: string // swagger show param like a string
```

**Comment by Romakita** [comment]
Hello @Tlahey 
I created a branch with different working examples (With QueryParams and PathParams). You can find examples on this link: https://github.com/Romakita/ts-express-decorators/blob/chore/query-params-swagger-example/integration/getting-started/src/controllers/calendars/CalendarsCtrl.ts

And you can checkout the branch and test locally (and compare with your project). I hope it'll help yo ^^

See you
Romain

**Comment by Romakita** [comment]
If the problem persist I invite you to continue the discussion on Gitter https://gitter.im/Tsed-io/community
See you

**Comment by Tlahey** [comment]
Ok, I switch on community :)

**Comment by Tlahey** [comment]
Issue: Add on tsconfig.json

```json
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
```

Thanks @Romakita

**Comment by abadyan-vonage** [comment]
The UI issue is fixed in Swagger but array is still passed as a single string and there seems to be no way around it.
Currently just parsing the string by ',' to get it to work.
