### ISSUE TITLE
Problem when testing REST with mongoose

### ISSUE THREAD

**Issue by weverton** [TypedProject/tsed#473]
## Informations

Type | Version
---|---
Question | 4.32.0

****

## Description
When I'm testing a REST API which uses mongoose connections the execution freeze at end of tests. After some researching I got that is because mocha hangs when mongoose is still connected to the database (https://stackoverflow.com/questions/48725343/mocha-hangs-after-execution-when-connecting-with-mongoose). 
How can I solve this?? How can I close all connections?? Is there any workaround?

**Comment by Romakita** [comment]
Hello @weverton,

You can close the connection with MongooseService https://github.com/Romakita/ts-express-decorators/blob/master/packages/mongoose/src/services/MongooseService.ts

This service contain all connection created by Ts.ED ;) 

```typescript
after(inject([MongooseServivce, Done], (mongooseService, done) => {
    const connection = mongooseService.get();

    connection.close(done);
}));
```

See you 
Romain
