### ISSUE TITLE
[Question] about default value in query params

### ISSUE THREAD

**Issue by azanorth** [TypedProject/tsed#474]
## Informations

Type | Version
---|---
Question | 4.32.0

****

## Description
Hello. I have a question about adding default value to query params.
Is it possible to add `@Default()` decorator to`@QueryParams()` decorator?
Something like this:
```typescript
  @QueryParams('count') @Default(10) count: number
```
All this is required in order to correctly build the file for the swagger.
After build should be this:
```javascript
  "parameters": [
    {
      "in": "query",
      "name": "count",
      "required": true,
      "type": "number",
      "default": "10"
    }
  ]
```

**Comment by Romakita** [comment]
Hello @azanorth 
Unfortunately I'm not if it's work correctly. But you can try and check the generated swagger spec ;)
If it didn't work, tell me. But I haven't time this month to work on :/. 
See you,
Romain

**Comment by Romakita** [comment]
Supported with v6
