### ISSUE TITLE
Swagger merges two different models with the same name

### ISSUE THREAD

**Issue by EugenePisotsky** [TypedProject/tsed#475]
I have two namespaces for example:

```typescript
export namespace Ns1 {
    export class Create {
        abc: string;
    }
}

export namespace Ns2 {
    export class Create {
        xyz: string;
    }
}
```

When i use them with actions:

```typescript
create(@BodyParams() params: Ns1.Create) {
    return true;
}

create2(@BodyParams() params: Ns2.Create) {
    return true;
}
```

Swagger creates one common model called `Create` that's got the following structure:

```
{
    abc: string,
    xyz: string
}
```

Not sure how much it's easy to fix, but would be awesome. Thanks :)

**Comment by Romakita** [comment]
Hum the problem come fron jsonschema which store the shema by te class name abd not from the symbol. Not easy ro fix that. I’ll try to fix that in future.

**Comment by RevanScript** [comment]
Ok, thanks! 
Maybe an additional decorator can solve it that allows to set a custom name. Like `@SwaggerName('Create2')` or something like that.

**Comment by Romakita** [comment]
`@Name` is available for that :)
