### ISSUE TITLE
openapi 3.0 support

### ISSUE THREAD

**Issue by azigelman** [TypedProject/tsed#480]
## Informations

Type | Version
---|---
Question | 4.30.1

****

## Description
Do you have intention to support openapi 3.0 spec?

I am using your framework and can't manage to do the following - 
 define a model with field that is either an array of numbers or null.
Also validate it with AJV

(As far as I managed to check it is not possible with swagger 2.0)

## Acceptance criterias

- [ ] Example (log, usecase, etc...)
- [ ] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
Hello @azigelman 
It's possible to support the new version, but I need help. If someone want to create a new package openapi 3.0 or improve the current `@tsed/swagger` package, you are welcome :)

**Comment by crisboarna** [comment]
Hello @Romakita,
Does tsed/swagger support OpenAPI 3.0 spec currently or it is not yet implemented ?

**Comment by Romakita** [comment]
Hello @crisboarna 

It’s in progress with https://github.com/TypedProject/tsed/pull/829 . But it’s not ready to be merged. This feature will introduce new decorators and support swagger2 and openapi3.
I’d just finish the new api. The next step is to replace old decorators. 
Change the version currently has no effect. The oas3 is a huge change :). 

But again the feature is still in progress. I hope, i’ll be able to embed this new feature with the Ts.ED v6 (this part is ready to be released).

The orther solution is to fork the current implementation and change the mapping. It’s possible but it’s not straightforward :/

See you
Romain

**Comment by Romakita** [comment]
v6 support this feature.
