### ISSUE TITLE
Converter Deserialize - Manual Render for SSE

### ISSUE THREAD

**Issue by saasrack** [TypedProject/tsed#483]
## Informations

Type | Version
Question | 4.26.0

****

## Description
Successfully implemented SSE (server sent events) within the Ts.ED Framework. However, I would also like to utilize the converter service to deserialize data corresponding to a data model to output to the SSE payload.

Is there a way to manually get the rendered output of the deserialize model? 

At the moment I use
`converterService.deserialize(obj, model)`
However, it also returns properties that are not described or ignored in the model.

**Comment by Romakita** [comment]
Hello @saasrack 

What do you means by "Is there a way to manually get the rendered output of the deserialize model?"

> converterService.deserialize(obj, model)
Hum, yes, you've right, the deserialize method merge obj inside the model and add extra properties not described in the model.

This method here https://github.com/Romakita/ts-express-decorators/blob/master/packages/common/src/converters/services/ConverterService.ts#L227 is responsible to deserialize a property.

Currently IConverterOptions hasn't option to not deserialize extra properties. But if you have a time to work on, you can add option and update convertProperty method 👍 (if you want).

See you
Romain

**Comment by saasrack** [comment]
It works correct if the deserialized data is being used with a Return Model in a controller. Also it shows the model correctly in swagger. This is were I wondering if there is an option to get this "rendered" deserialized data prematurely.

I'm more than happy to work on updating the converter method.

**Comment by Romakita** [comment]
@saasrack What do you mean by deserialized data prematurely ?

**Comment by saasrack** [comment]
@Romakita If I use the model as a response object `@Returns(ResponseModel)` in combination with `converterService.deserialize(obj, model)` in a controller, the output (http response) delivers the exact structure of the defined properties in this model. But I cannot accomplish this with `converterService.deserialize(obj, model)` only. On the other hand it has a benefit to have all properties until it gets exposed.

**Comment by Romakita** [comment]
this.converterService.serialize(data) serialize the data according the data type/model.
Example:

```typescript
@StrictModel(true) 
class MyModel {
   @Property()
   id: string;
}

const data: any = new MyModel()
data.id = "1";
data.extraProp = "test"

converterService.serialize(data) // => {id: 1}
```

I really don't know how I can help you, without an example of your usecase. I don't understand what you want.

See you
Romain

Note: I invited you on gitter if you want to keep this discussion in private
