### ISSUE TITLE
Loging with vscode

### ISSUE THREAD

**Issue by yantrab** [TypedProject/tsed#511]
How can i see the logs when debug with vscode?

**Comment by Romakita** [comment]
I don't know, I didn't use vscode :/ sorry

**Comment by Szauka** [comment]
@yantrab you can see the logs in the "DENUG CONSOLE" in the VsCode teminal. 

![image](https://user-images.githubusercontent.com/33459309/53488876-71750080-3a87-11e9-817d-b93c604769ec.png)

**Comment by antonovicha** [comment]
In order to see tsed log output in vscode debug console you need use
`"outputCapture": "std",` in launch configuration of your application.
