### ISSUE TITLE
[Question] Jsonapi serializer integration

### ISSUE THREAD

**Issue by isBatak** [TypedProject/tsed#512]
## Information

- **Version:** 5.x
- **Type:** Question

## Description
Hi @Romakita ,
I have a goal to create [JSON API](https://jsonapi.org/) (1.0 compliant) api.
What would be the best approach to integrate [jsonapi-serializer](https://github.com/SeyZ/jsonapi-serializer) with Ts.ED?
Is that even possible and do you have any examples or guidelines that could help me?
Thx!

**Comment by Romakita** [comment]
Hello @isBatak ,

I think the right way is to override the SendResponseMiddleware to change the SendResponse behavior. Here the documentation http://tsed.io/docs/middlewares/override/send-response.html

Or create a middleware/decorator which you can apply for a specific endpoint. 
See you,
Romain
