### ISSUE TITLE
Not fail on converts for params

### ISSUE THREAD

**Issue by azigelman** [TypedProject/tsed#518]
## Information

- **Version:** 4.30.1
- **Type:** Story

## Description
Enable params decoration without converter / with the possibility to ignore the errors

## Example

```
@QueryParams('myNumber', null, {convert: False})
```
OR
```
@QueryParams('myNumber', null, {failOnConvert: False})
```

## Acceptance criteria

- [ ] Criteria 1

## Notes
Use case: I would like to validate all parameters before failing a request in order to supply a list of invalid parameters.

I don't mind doing the change myself, WDYT is better?

**Comment by Romakita** [comment]
Hello @azigelman 
Sorry for the late reply. 

You can declare your own QueryParams decorator:
```typescript
export function QueryParams(expression?: string | any, useType?: any): Function {
  return ParamRegistry.decorate(QueryParamsFilter, {
    expression,
    useType,
    useConverter: true, // Change configuration here
    useValidation: true,
    paramType: ParamTypes.QUERY
  });
}
```
failOnConvert isn't possible right now without extra development on ConverterService :)
See you
Romain
