### ISSUE TITLE
@tsed/socketio - SocketUseBefore(MyMiddleware) has no effect.

### ISSUE THREAD

**Issue by bjarne1337** [TypedProject/tsed#533]
## Information

- **Version:** 5.6.0
- **Type:** Issue

## Description
SocketUseBefore(MyMiddleware) has no effect.

I am trying to use a middleware in a @SocketService() as described here:
http://tsed.io/tutorials/socket-io.html

Without using @SocketUseBefore(MyMiddleware) everything works fine ('user connected' / 'user disconnected' output as expected).
Using @SocketUseBefore() or @SocketUseAfter() does not have any effect. I expect the console output 'middleware called' before the 'user connected' message.

Am I doing something wrong?

## Example

SocketService:
```typescript
import {SocketService, SocketUseAfter, SocketUseBefore} from "@tsed/socketio";
import {SocketMiddlewareTest} from "./socket-middleware";

@SocketService('/')
@SocketUseBefore(SocketMiddlewareTest)
// @SocketUseAfter(SocketMiddlewareTest)
export class Socket {
    // @SocketUseBefore(SocketMiddlewareTest)
    $onConnection(){
        console.log('user connected');
    }
    $onDisconnect(){
        console.log('user disconnected');
    }
}

```

SocketMiddleware:
```typescript
import {Args, SocketMiddleware} from "@tsed/socketio";

@SocketMiddleware()
export class SocketMiddlewareTest {
    use(@Args() args: any[]){
        console.log('middleware called');
        console.log(args);
        return args;
    }
}

```

## Acceptance criteria

- [ ] Fixed or explained :)

**Comment by Romakita** [comment]
Hello @bjarne1337 
I'll try to reproduce your usecase ;)

See you,
Romain

**Comment by Romakita** [comment]
@bjarne1337 SocketMiddleware are called only when a message is received on methods which are annotated with `@Input`. For $onConnection and $onDisconnect are a speciale methods (hook) to handler user connection and disconnection.

Here right code to use middleware:
```typescript
@SocketService("/my-namespace")
@SocketUseBefore(UserConverterSocketMiddleware) // global version
@SocketUseAfter(ErrorHandlerSocketMiddleware)
export class MySocketService {

  @Input("eventName")
  @Emit("responseEventName") // or Broadcast or BroadcastOthers
  @SocketUseBefore(UserConverterSocketMiddleware)
  @SocketUseAfter(ErrorHandlerSocketMiddleware)
  async myMethod(@Args(0) user: User) {

    console.log(user);

    return user;
  }
}
``` 

See you
