### ISSUE TITLE
Is it possible to create a custom decorator like PathParams

### ISSUE THREAD

**Issue by carlosdubus** [TypedProject/tsed#561]
Hi. I like the framework a lot so far. So much easier to develop APIs. This is a question, sorry if it's in the docs but I couldn't find it.

I have a middleware that reads an auth token from the request headers and assigns a user to the request. `request.authUser = {}`

Would be great if I can inject the auth user to my endpoints like this:
`get(@AuthUser() authUser: AuthUser) {}`

Instead of 
```
get(@Request() request: express.Request){
   const authUser = (request as any).authUser as AuthUser
}
```

Is it possible?

**Comment by Romakita** [comment]
Hello @carlosdubus ,

Yes it's possible. Filters are here for that :) http://tsed.io/docs/filters.html

In your case: 
```typescript
import {Filter, IFilter} from "@tsed/common";

@Filter()
export class AuthUserFilter implements IFilter {
    transform(expression: string, request: Express.Request, response: Express.Response) {
        return (request as any).authUser
    }
}

export function AuthUser(): Function {
    return ParamRegistry.decorate(AuthUserFilter);
}
```

See you,
Romain

**Comment by carlosdubus** [comment]
@Romakita I missed filters on the docs. Thanks! Awesome work!!
