### ISSUE TITLE
Question: Is it possible to use class for QueryParams declaring?

### ISSUE THREAD

**Issue by microshine** [TypedProject/tsed#562]
## Information

- **Version:** 5.18.0

## Description

I'm trying to describe repeatable query params by class. Schema validation works fine, but I've got a problem with Swagger documentation. It doesn't show param description for grouped params

![image](https://user-images.githubusercontent.com/7333669/58801922-92179e00-8614-11e9-8717-0d7e92f5bd10.png)

I'd like to see

![image](https://user-images.githubusercontent.com/7333669/58802086-ec186380-8614-11e9-884f-af073abc00f5.png)

### Query params
```ts
class PageParams {
  @QueryParams("limit")
  limit: number = 20;
  
  @QueryParams("page")
  page: number = 0;
  
  @QueryParams("start")
  start: number = 0;
}
```

### Controller
```ts
@Controller("/test")
export class TestConntroller {

  @Get("/")
  public async test(
    @QueryParams() params: PageParams,
  ) {
    console.log("Page params:", params);
  }

}
```
### Console output
```
Page params: PageParams { limit: 20, page: 0, start: 0 }
```

**Comment by Romakita** [comment]
Hello @microshine,
Not sure, I have to test your usecase and fix it if it's possible :)
See you
Romain

**Comment by Romakita** [comment]
Released in v5

**Comment by chorsnell** [comment]
@Romakita I'm on `5.65.6` and the above just gives me

```TS1240: Unable to resolve signature of property decorator when called as an expression.```

**Comment by Romakita** [comment]
Your error is related to typescript. I had a project which is work correctly with this example. So I need more details on your issue. Can you open new issue please :)
