### ISSUE TITLE
Undefined body on error

### ISSUE THREAD

**Issue by striquer** [TypedProject/tsed#570]
## Information

- **Version:** 5.x
- **Type:** Story

## Description
All error returns using the GlobalErrorHandlerMiddleware have their body undefined, i want to be able to see the body on these requests. I think we don't need it for 500 errors, but adding the line bellow can solve this problem

## Example

```
if (error instanceof Exception || error.status) {
      request.log.error({
        error: {
          body: request.body,
          message: error.message,
          stack: error.stack,
          status: error.status,
          origin: error.origin
        }
      });

      this.setHeaders(response, error, error.origin);

      response.status(error.status).send(toHTML(error.message));

      return;
    }

```

Or do it optional when someone use an overridlemiddleware, something like this: 

## Example

```
@OverrideMiddleware(GlobalErrorHandlerMiddleware)
export class OverrideGlobalErrorHandler extends GlobalErrorHandlerMiddleware {

    constructor() {
        super();
    }

    use(@Err() error: any,
        @Req() request: Req,
        @Res() response: Res): any {

        error = {
              ...error,
              body: request.body
        }
        return super.use(error, request, response);
    }
}

```

and then on Global:

## Example
```

if (error instanceof Exception || error.status) {
      request.log.error({
        error: {
          body: error.body || undefined,
          message: error.message,
          stack: error.stack,
          status: error.status,
          origin: error.origin
        }
      });

      this.setHeaders(response, error, error.origin);

      response.status(error.status).send(toHTML(error.message));

      return;
    }

```

Any thoughts on it?

**Comment by Romakita** [comment]
Hello @striquer,

Log body and other parameters aren't a good idea by default. LogIncomingRequestMiddleware log some data but it's configurable. We can add extra settings to add extra data in the GlobalErrorHandlerMiddleware also. 

 Override middleware are right now the best solution if you have to customize error before logging.

See you
Romain

**Comment by striquer** [comment]
Hello again, i was looking in the LogIncomingRequestMiddleware and i think there is an error with the output. The params that i set into the serversettings doesn't match the output result and i think i know why.

If you look in this function:
`minimalRequestPicker(request) {
        const { fields = LogIncomingRequestMiddleware_1.DEFAULT_FIELDS } = this.injector.settings.logger;
        const info = this.requestToObject(request);
        return fields.reduce((acc, key) => {
            acc[key] = info[key];
            return acc;
        }, {});
}`

It's expecting an field called **fields** from the server settings, but on the server settings it's defined to requestFields: 

`logger: {
        debug: false,
        logRequest: true,
        requestFields: ["reqId", "method", "url", "headers", "body", "query", "params", "duration"]
}`

I tested and if you replace that **fields** to **requestFields** it'll work with the server settings configuration

**Comment by Romakita** [comment]
Hoo... can you make a pr ? Thanks for your investigation ;)

**Comment by striquer** [comment]
Sure, will do it. Thanks

**Comment by Romakita** [comment]
Thanks a lot ;)
