### ISSUE TITLE
Middleware being executed even if not set in controller

### ISSUE THREAD

**Issue by ghmendonca** [TypedProject/tsed#588]
## Information

- **Version:** 5.21.0
- **Type:** Issue

## Description
I have a controller which contains 2 endpoints. I also have a middleware that I use in others controllers but not this one. For some reason when I execute my endpoints in this controller, this middleware always execute but I can't have them to be executed, not in this controller.. As far as I can see, everytime I use the middleware decorator, it's being registered as global and I guess this is causing this to happen.. The right thing would be execute the middlewares only if set with useBefore, useAfter or any other decorator like this

**Comment by Romakita** [comment]
Hello @ghmendonca,
Without code example I can help you ^^. But if you use @UseBefore or @UseAfter on the right place, it should work as expected but it depending on the Controller path also.
The official documentation over middleware explain corretly the mechanism
 http://tsed.io/docs/middlewares.html#endpoint-middleware

Tell if something isn't correctly explained :)
See you

**Comment by ghmendonca** [comment]
I think you missunderstood.. What I want is to **not** use a middleware in a specific controller, not use in any route of this controller at all.

I have a controller like this:

```
import {
    Controller, Post,
    Required, BodyParams,
    Inject,
    Session
} from "@tsed/common";
import { AccountService } from "../services/AccountService";
import { Credential } from "../models/Credential";
import { Account } from "../models/Account";

@Controller('/')
export class AccountController {
    constructor(
        @Inject(AccountService)
        private accountService: AccountService
    ) { }

    @Post('/login')
    async login(
        @Required()
        @BodyParams(Credential)
        credentials: Credential,
        @Session()
        session: Express.Session
    ): Promise<{
        game: string,
        socket: string
    }> {
        const result = await this.accountService.login(credentials)

        if(result.character) {
            session.character = result.character
        }

        return result.tokens
    }

    @Post('/account')
    async createAccount(
        @Required()
        @BodyParams(Account)
        account: Account
    ): Promise<Account> {
        return await this.accountService.create(account)
    }
}
```

When I call the login route, it always passes through a middleware that obviously I don't want, since it's not in this controller.. I'm not calling this middleware globally in my server.ts file too, I'm just using it in other controller

**Comment by Romakita** [comment]
Ok I understand. I suppose your decorator are decorated by `@Controller('/')`. Can send me the code of the Controller where you registered the middleware, please ?

**Comment by ghmendonca** [comment]
Sure.

```
@Controller('/character')
@UseBefore(SessionMiddleware)
export class CharacterController {
    constructor(
        @Inject(CharacterService)
        private service: CharacterService,
        @Inject(Character)
        private model: MongooseModel<Character>
    ) { }

    @Get('/me')
    @Authenticated([Roles.PLAYER, Roles.ADMIN])
    async getMyCharacter(
        @Session('character')
        character: Character
    ): Promise<Character> {
        return character
    }

    @Get('/:id')
    @Authenticated([Roles.PLAYER, Roles.ADMIN])
    async getCharacter(
        @PathParams('id')
        id: string
    ): Promise<Character> {
        return await this.service.getById(id)
    }

    @Post('/')
    @Authenticated([Roles.PLAYER, Roles.ADMIN])
    async createCharacter(
        @Required()
        @BodyParams(Character)
        character: Character
    ): Promise<Character> {
        return await this.service.create(character)
    }
    .
    .
    .
}
```

Basically what I'm doing is, when the user logs in, I save him in session and in my other controllers I want to be sure that the session is set and if not, I throw an error. Right now when I try to login, I always get the error saying that I'm not in session

**Comment by ghmendonca** [comment]
Ok, now I removed completely the middleware from everywhere, I just left the file under the middlewares folder but I'm not using it anywhere and it still gets executed!!!

**Comment by ghmendonca** [comment]
I found the bug but I don't know if this is fixable.. I'm using express-session which I believe that behind the scene it register a middleware called SessionMiddleware but my middleware was also called SessionMiddleware.. So somehow my middleware was being executed because the express-session middleware was defined globally.. I just had to change my class name and it works

I'll leave this issue open since I don't know how to fix or if this can be fixed in this repository, but we can at least add a warning somewhere in the docs saying to not create a middleware called SessionMiddleware in case the programmer is using express-session
