### ISSUE TITLE
[Question] Always call errorFormat method

### ISSUE THREAD

**Issue by exsoflowe** [TypedProject/tsed#605]
## Information

- **Version:** 4.32.0
    @tsed/ajv: 5.1.3
- **Type:** Issue/Question

## Description
Is there possibility to transit all messages via errorFormat method?

## Example

I use errorFormat method:
```typescript
import {ServerLoader, ServerSettings} from "@tsed/common";
import "@tsed/ajv"; // import ajv ts.ed module

@ServerSettings({
    rootDir: __dirname,
     ajv: {
       errorFormat: (error) => `At ${error.modelName}${error.dataPath}, value '${error.data}' ${error.message}`,
       options: {verbose: true}
    },
})
export class Server extends ServerLoader { }

```
and I have Model:
```typescript
export class MyModel {
  @Required()
  @Schema({ type: 'string' })
  public MyId: string;
}
```
If I pass empty string I will get message

> Property MyId on class MyModel is required.

But if I remove myId field from request I will get message from errorFormat method.

I suggest this difference is due to the fact that we can't access for AJV errors messages. Or not?

**Comment by Romakita** [comment]
Ho right. It's because Required is handled by ConverterService and throw error "Property MyId on class MyModel is required." Other errors are thrown by Ajv.

**Comment by Romakita** [comment]
v6 use exclusively AJV to throw validation error.
