### ISSUE TITLE
[Request] Cache system

### ISSUE THREAD

**Issue by chiqui3d** [TypedProject/tsed#607]
## Information

- **Version:** 5.x

## Description
Leaving that for example database systems have their own cache system like for example TypeORM https://typeorm.io/#/caching, I think you should add some cache system with their own decorators.

Example: https://github.com/kwhitley/apicache
Cache types/strategies: https://scotch.io/tutorials/how-to-optimize-node-requests-with-simple-caching-strategies#toc-results-and-recommendation

**Comment by Romakita** [comment]
Hello @chiqui3d,

You can implement your own decorator to cache request and choose your prefered lib to doing that.

Example with apicache:

```typescript
import apicache from 'apicache'

let cache = apicache.middleware

@Controller('/')
class MyController {

   @Get()
   @UseBefore(cache('5 minutes'))
   getSomething(){
   }
}
```
You can implement your own decorator like that:

```typescript
import apicache from 'apicache'

const cache = apicache.middleware

export function Cache(option: string) {
   return UseBefore(cache(options))
}
```
And use it on controller or method:

```typescript
@Controller('/')
@Cache('5 minutes')// here 
class MyController {

   @Get()
   @Cache('5 minutes') // or here
   getSomething(){
   }
}
```
I think theses examples will help you!

If you want develop an official package for Tsed and provide a Cache strategy, you 're welcom :)

See you
Romain

**Comment by chiqui3d** [comment]
Okay, when I finish a job, I'll try all the features, including your example for a next job. And I'm also going to try to apply several cache strategies to the same decorator and that way I learn some design patterns.
