### ISSUE TITLE
GraphQL Example

### ISSUE THREAD

**Issue by j-tegen** [TypedProject/tsed#608]
## Description
I'm having trouble implementing a graphql service for my ts-ed server. It would be really helpful if the docs could include a very basic working repository. Any chance one could be created, or does anyone have a working example?

**Comment by Romakita** [comment]
Hello @j-tegen 
I can try to provide you a basic example. 
Currently our integration test implement an example :
https://github.com/TypedProject/ts-express-decorators/blob/master/test/integration/app/FakeServer.ts
And here dataSource and Recipe:
https://github.com/TypedProject/ts-express-decorators/tree/master/test/integration/app/graphql

Maybe theses examples will help you until the official example isn't out :)

See you
Romain

**Comment by j-tegen** [comment]
Thank you for the quick response! Those examples are great :)

From what I can see in the code I don't need to build the schema with `type-graphql`'s `makeSchema` method. Is that correct? Does the `componentScan` configuration handle this?

How would I add custom scalars to the schema?

Best Regards
Jonatan

**Comment by Romakita** [comment]
> Does the componentScan configuration handle this?
Yes if you add the right glob pattern, componantScan will discover Resolvers automatically

> How would I add custom scalars to the schema?
I don't know what is a custom scalars. I don't use graphQL currently ^^
