### ISSUE TITLE
[Feat] GraphQL : Ability to apply middleware to the graphql endpoint

### ISSUE THREAD

**Issue by bsparks** [TypedProject/tsed#612]
Currently since the GraphQL module boots up the server in $onInit it is not possible to apply middlewares to the /graphql endpoint. Express adds them in the order app.use is called, so by the time $onMountingMiddlewares hook is fired, this is already done.

Need to find a way to apply middlewares in the graphql module BEFORE setting up the graphql server. Possibly a separate registry of gql enabled middlewares and a single middleware applied that executes them? (so that we can use the injector later when that "main" middleware is executed).

I'm happy to help code it, if that design makes sense.

**Comment by Romakita** [comment]
Hello @bsparks ,
You can use $onInit hook on your server to register your middleware. 
```typescript
class ServerLoader {
  $onInit() {
      this.use(MyMiddleware)
  }
}
```
Server.$onInit is called before $onInit services and modules :)

It should work :)
