### ISSUE TITLE
Some services are not injected 

### ISSUE THREAD

**Issue by Chnapy** [TypedProject/tsed#616]
## Information

- **Version:** 5.25.1
- **Type:** Issue

## Description
Some services are not injected: **TypeORMService** in my own service, and **PassportLocalService** (from passport example) in my Server.
When I log them I always have `undefined` as value.
I used [typeorm example](https://github.com/TypedProject/tsed-example-typeorm) and [passportjs example](https://github.com/TypedProject/tsed-example-passportjs) to create my app.
When I compare my code with the examples, even the dependencies versions, I don't see what may cause the issue.
This issue doesn't concern all injections, others work well.

Note that I tried to add `@Inject()` before each broken service param, without success.

**I uploaded my whole code here 
[_TSDE_issue.zip](https://github.com/TypedProject/ts-express-decorators/files/3513417/_TSDE_issue.zip)**

## Code concerned

UserService.ts
```TypeScript
import {Connection} from "typeorm";
import {TypeORMService} from "@tsed/typeorm";
import {User} from "../entity/User";
import {AfterRoutesInit, Service} from "ts-express-decorators";

@Service()
export class UserService implements AfterRoutesInit {
    private connection!: Connection;

    // FIXME service is not injected !
    constructor(private typeORMService: TypeORMService) {
    }

    $afterRoutesInit() {
        this.connection = this.typeORMService.get()!;
        console.log("US this.connection =>", this.connection);
    }

    async create(user: User): Promise<User> {
        await this.connection.manager.save(user);
        console.log("Saved a new user with id: " + user.user_id);

        return user;
    }

    async find(user_id: User['user_id']): Promise<User> {
        const user = await this.connection.manager.findOneOrFail(User, user_id);
        console.log("Loaded user: ", user);

        return user;
    }

    async getAll(): Promise<User[]> {
        const users = await this.connection.manager.find(User);
        console.log("Loaded users: ", users);

        return users;
    }
}
```

Server.ts
```TypeScript
import {ServerLoader, ServerSettings, GlobalAcceptMimesMiddleware} from "@tsed/common";
import '@tsed/typeorm';
import Path from "path";
import methodOverride from 'method-override';
import cors from 'cors';
import bodyParser from 'body-parser';
import {PassportLocalService} from "./services/PassportLocalService";

const ormconfig_dev = require('../ormconfig-dev.json');
const rootDir = Path.resolve(__dirname);

@ServerSettings({
    debug: true,
    httpPort: Number(process.env.PORT || 2567),
    httpsPort: false,
    rootDir,
    mount: {
        '/rest': `${rootDir}/controllers/**/**.ts`
    },
    componentsScan: [
        `${rootDir}/middlewares/**/**.ts`,
        `${rootDir}/services/**/**.ts`,
    ],
    acceptMimes: ["application/json"],
    typeorm: [
        ormconfig_dev
    ]
})
export class Server extends ServerLoader {

    // @Inject() // Removed because not working, use a workaround instead
    $onMountingMiddlewares(): void | Promise<any> {

        // FIXME service is not injected if given in the constructor !
        const passportService: PassportLocalService = this.injector.get<PassportLocalService>(PassportLocalService)!;

        // We can see PassportLocalService and TypeORMService
        console.log(
            'All injectable:',
            this.injector.toArray().map(c => c.constructor.name)
        );

        this
            .use(GlobalAcceptMimesMiddleware)
            .use(methodOverride())
            .use(bodyParser.json())
            .use(bodyParser.urlencoded({
                extended: true
            }))
            .use(cors())

            // Configure passport JS
            .use(passportService.middlewareInitialize())
            .use(passportService.middlewareSession());


    }

    $onReady(): void {
        console.debug('Server initialized')
    }

    $onServerInitError(error: Error): void {
        console.error('Server encounter an error =>', error);
    }
}
```

package.json
```JSON
{
  "name": "timeflies-back",
  "private": true,
  "version": "0.0.1",
  "description": "Timeflies - Back",
  "main": "lib/index.js",
  "scripts": {
    "clean": "rimraf '{src,test}/**/*.{js,js.map}'",
    "start": "ts-node src/index.ts",
    "loadtest": "colyseus-loadtest loadtest/example.ts --room my_room --numClients 2",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Richard Haddad",
  "license": "UNLICENSED",
  "bugs": {
    "url": "https://github.com/Chnapy/timeflies-back/issues"
  },
  "homepage": "https://github.com/Chnapy/timeflies-back#readme",
  "devDependencies": {
    "@colyseus/loadtest": "0.10.2",
    "@types/cors": "2.8.5",
    "@types/express": "4.17.0",
    "@types/method-override": "0.0.31",
    "@types/node": "12.7.2",
    "@types/passport": "1.0.0",
    "@types/passport-local": "1.0.33",
    "ts-node": "8.3.0",
    "typescript": "3.5.3"
  },
  "dependencies": {
    "@colyseus/monitor": "0.10.0",
    "@tsed/typeorm": "5.25.1",
    "body-parser": "1.19.0",
    "colyseus": "0.10.9",
    "cors": "2.8.5",
    "express": "4.17.1",
    "method-override": "3.0.0",
    "passport": "0.4.0",
    "passport-local": "1.0.0",
    "pg": "7.12.1",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.0",
    "ts-express-decorators": "5.25.1",
    "typeorm": "0.2.18"
  },
  "engines": {
    "node": ">=8"
  }
}
```

I know I can restart from an example project but I really want to know what cause this issue.
Thank you for your help, I'm still discovering Ts.ED and it's been a while i'm looking for a solution :anguished:

**Comment by Romakita** [comment]
Hello @Chnapy,
Your problem come from ts-express-decorators. It's the legacy package and I'm not sure if it's works as expected (probably not). 
In your package.json remove "ts-express-decorators" and the following dependencies:
```json
{
  "dependencies": {
      "@tsed/core": "5.25.1",
      "@tsed/di": "5.25.1",
      "@tsed/common": "5.25.1",
      "@tsed/typeorm": "5.25.1",
   }
}
```
Then in your code, replace ts-express-decorators by @tsed/common 
Tell me if it works :)

See you

**Comment by Chnapy** [comment]
Hi, thanks for your answer.

So like you said I removed the `ts-express-decorator` dependency for the ones you listed.
I deleted all my `node_modules` an redo a `npm i` to be sure.
But it still not working 😞 

Also I was wrong about the typeORMService service. He's well injected ! 
Just the `this.connection = this.typeORMService.get()!;` (`UserService.ts`) is returning `undefined`, I don't know why.

However the issue about `Server.ts` is real 😞

**Comment by Romakita** [comment]
Ok for TypeORM, by default `this.typeORMService.get()` return the `default` connection name. 
 
in your configuration you've `dev` value set for the field `name`, so when you use `this.typeORMService.get()` you have to give `this.typeORMService.get('dev')` or change `dev` by `default`. I'll fix the TypeORM service to return the first connection by default in future.

I fixed all issues in this archive, the PassportLocalService work as expect:
[Archive.zip](https://github.com/TypedProject/ts-express-decorators/files/3516163/Archive.zip)

See you :)

**Comment by Chnapy** [comment]
Thanks it resolves my issue with `typeORMService`.

I checked your code, I don't see any difference in the `Server` class, maybe I miss something ?

I try to do something like that (I saw this in an example I think):
```typescript

    @Inject()
    $onMountingMiddlewares(
        passportService: PassportLocalService
    ): void | Promise<any> {

      this
           ...
           .use(passportService.middlewareInitialize())
           .use(passportService.middlewareSession());

   }
```
But when I do this `passportService` is `undefined`.

So I used a workaround to access to this service without "pretty" injection
```typescript
    const passportService = this.injector.get<PassportLocalService>(PassportLocalService)!;
```
It works but, well... If it can be better I don't say no.

Thank you for your time !

**Comment by Romakita** [comment]
Is strange. When I run the server, I have the passportService defined. I don't know why in your case you have an undefined service.

**Comment by Chnapy** [comment]
Maybe you're running the server with the workaround ?

**Comment by Romakita** [comment]
No just with ts-node and your npm task. I'll check tomorrow ;)

**Comment by dlinx** [comment]
@Chnapy did you enable `emitDecoratorMetadata` in `tsconfig`? The di requires decorator metadata to be emitted. I faced the same issue and worked after enabling this property.
@Romakita could you please add this info in the `Readme` as well.

**Comment by Romakita** [comment]
It’s already in the readme: https://github.com/TypedProject/ts-express-decorators/blob/master/readme.md

**Comment by Romakita** [comment]
And here https://tsed.io/getting-started.html#installation-from-scratch
