### ISSUE TITLE
Response behaviour with model which has several extends sub models

### ISSUE THREAD

**Issue by nirio69510** [TypedProject/tsed#622]
## Information

- **Version:** 5.6
- **Type:** Issue

## Description
Hi,

I have a model A with properties a1, a2
I have a model B which extends Model A with properties b1, b2
I have a model C which extends Model B with properties c1, c2

When I return an array of object of Model C, I got only properties of Model A and B.

If I use Express legacy method `res.json(obj)`, I got all expected properties.

Is someone already got this behaviour ?

Thanks

**Comment by Romakita** [comment]
hello @nirio69510 
Did you use `@Property` decorator over each property ? 
Here the doc about models: http://tsed.io/docs/model.html#example

See you,
Romain :)
