### ISSUE TITLE
How can I get raw body?

### ISSUE THREAD

**Issue by oscarcalvo** [TypedProject/tsed#625]
Question: I have a "normal" Ts.ed project with controlers etc.

`this.use(compression())
      .use(methodOverride())
      .use(json())
      .use(
        urlencoded({
          extended: true
        })
      );
`

Now in one route, due a [Stripe requeriments](https://stripe.com/docs/webhooks/signatures) I need to get the raw body. How can I get it only for one route? in express it would be 

`app.post('/webhook', bodyParser.raw({type: 'application/json'}), (request, response) => {
//request.body has the raw body
});`

Thanks

**Comment by Romakita** [comment]
Hello @oscarcalvo ,

You have to use `@UseBefore`:
```typescript
class MyController {
   @Post('/')
   @UseBefore(bodyParser.raw({type: 'application/json'}))
   body(@BodyParams() raw: any) {
   }
}
```
In addiction you can create you own decorator:
```typescript
import {applyDecorators} from "@tsed/core";
import {Post, UseBefore} from "@tsed/common";

export function RawPost(path: string, type: string = 'application/json'): Function {
   return applyDecorators(
     Post(path),
     UseBefore(bodyParser.raw({type}))
   )
}
```
usage:
```typescript
class MyController {
   @RawPost('/')
   body(@BodyParams() raw: any) {
   }
}
```
See you
Romain

**Comment by oscarcalvo** [comment]
Thanks @Romakita 
I tried and doesn't work. The call is done and all parameters set and ok except  body is not raw but json
Since I have the same code in Express pure app and working I think it not a problem of the code. my current endpoint

`@Post('webhook')
  @UseBefore(bodyParser.raw({ type: "application/json" }))
  async stripePaymentCompleteWebHook(
    @HeaderParams("stripe-signature") stripeSignature: string,
    @BodyParams() rawBody: any
  ) {}`

Thing is, using UseBefore adds a middleware to the queue in first place but the rest of middlewares are working. Or not?

**Comment by oscarcalvo** [comment]
Excuse me @Romakita Could you tell me anything about that?

**Comment by rodrigorellana** [comment]
hi @oscarcalvo , did you fix this? I have same issue

**Comment by chiqui3d** [comment]
A doubt under the ignorance, supposedly in `Express`, when you use `.use(bodyParser.json())`, you can do from the Request to the `body`, but in the decorator `@Req() request: Express.Request` you cannot access, is it for some particular reason?

**Comment by Romakita** [comment]
... I haven't reason. The request is a pure Node.js/Express object. Ts.ED doesn't delete body on request.

**Comment by dkoshe** [comment]
Hi @Romakita,
I am trying get rawBody in the UseAuth custom middleware, and not able to figure out any way to do it...
Help please..

controller... code:
```
   @Post("/")
    @Status(200)
    @ContentType("application/json")
    @UseAuth(MyCustomAuth, {mock: false})
    async handleCommand(@BodyParams() cmdpayload: MyModel): Promise<any> {
        ...
```

Custom Auth Middleware code:
```
@Middleware()
export class MyCustomAuth implements IMiddleware {
    public use(@Req() req: Req, @EndpointInfo() endpoint: EndpointInfo) {
        // retrieve options given to the @UseAuth decorator
        const options = endpoint.get(MyCustomAuth) || {};
        const rawBody = req.rawBody; // this doesn't exist
        ...
```

**Comment by Romakita** [comment]
Hello @dkoshe,

The body-parser documentation explain the usage of the raw body by using the Content-Type header:

```
// parse various different custom JSON types as JSON
app.use(bodyParser.json({ type: 'application/*+json' }))

// parse some custom thing into a Buffer
app.use(bodyParser.raw({ type: 'application/vnd.custom-type' }))

// parse an HTML body into a string
app.use(bodyParser.text({ type: 'text/html' }))
```
Same example with Ts.ED:

```typescript
@ServerSettings()
class Server extends ServerLoader {
   $beforeRoutesInit() {
      this.use(bodyParser.json({ type: 'application/*+json' }))
      this.use(bodyParser.json({ type: 'application/vnd.custom-type' }))
      this.use(bodyParser.json({ type: 'text/html' }))
   } 
}
```
Until you have configured your server, you will able to get the body as following: 

```
@Middleware()
export class MyCustomAuth implements IMiddleware {
    public use(@Req() req: Req, @EndpointInfo() endpoint: EndpointInfo) {
        // retrieve options given to the @UseAuth decorator
        const options = endpoint.get(MyCustomAuth) || {};
        const rawBody = req.body; // Buffer is the Content-Type is application/vnd.custom-type
    }
}
```
See you
Romain

**Comment by IARKI** [comment]
Same problem here, 
Looks like `@UseBefore(bodyParser.raw({ type: "application/json" }))` doesn't work.
The only solution I found so far is to set a `rawBody` param in verify option from bodyParser.json() 
in Server in $beforeRoutesInit.
Also you can set a condition to do it on only needed api calls to avoid unnecessary memory usage 
In my case I did it based on headers, if stripe signature headers is present
```
            .use(bodyParser.json({
                verify(req: Req, res: Res, buf: Buffer): void {
                    if (req.headers['stripe-signature']) {
                        req['rowBody'] = buf;
                    }
                }
            }))
```

**Comment by Romakita** [comment]
Yes it won't work because you already registered the bodyParser on server level :). Register the body parser twice won't work as expected. Isn't a problem with Ts.ED itself.

My example is clear, using the content-type, you can have the right content.
```typescript
@ServerSettings()
class Server extends ServerLoader {
   $beforeRoutesInit() {
      this.use(bodyParser.json({ type: 'application/*+json' }))
      this.use(bodyParser.raw({ 
          type: 'application/vnd.custom-type', 
          veriffy: (req) => {
            req.rawBody = req.body
          }  
      }))
      this.use(bodyParser.text({ type: 'text/html' }))
   } 
}
```

Then:

```typescript
@Post("/")
post(@Req("rawBody") rawBody: Buffer, @BodyParams() body: any, @BodyParams({useConverter: false}) rawBody2: any){
   console.log("rawBody", rawBody) // Buffer if headers["Content-Type"] = "application/vnd.custom-type"
   console.log("body", body) // Buffer also if headers["Content-Type"] = "application/vnd.custom-type" but wrong decoding
   console.log("body", body) // Buffer if headers["Content-Type"] = "application/vnd.custom-type"
}
```
Finally send a request with the right header to have the expected result :)

Additional tip. You can create you on decorator to get the RawBody:
```typescript
export function RawBody() {
  // or return Req('rawBody')
  return BodyParams({useConverter: false})
}
```

**Comment by chinhnguyen-hublet** [comment]
Below code also did the trick for me.

```typescript
export default class Server extends ServerLoader {
  /**
   * This method let you configure the express middleware required by your application to works.
   * @returns {Server}
   */
  public $beforeRoutesInit(): void | Promise<any> {
    this.use(cookieParser())
      .use(
        bodyParser.json({ // ==> Reuse the json parser
          verify: (req, res, buff) => {
            (req as any).rawBody = buff // ==> Save the body buff to rawBody to be mapped with @Req("rawBody")
          },
        })
      )
      .use(
        bodyParser.urlencoded({
          extended: true,
        })
      )
  }
}
```
