### ISSUE TITLE
routes are not loaded when using bootstrap

### ISSUE THREAD

**Issue by vichugunov** [TypedProject/tsed#631]
## Information

- **Version:** 5.27.3
- **Type:** Issue

## Description
I'm trying to make simple request to server accordingly to example: http://tsed.io/docs/testing.html#test-your-rest-api

However, it returns instead of expected status code just 404, not found.
When I have printed routes, it states, that it's an empty array:

```
  console.log test/controllers/Test.test.ts:25
      routes []

  ● test › should be forbidden

    expected 403 "Forbidden", got 404 "Not Found"

      at Test.Object.<anonymous>.Test._assertStatus (node_modules/supertest/lib/test.js:268:12)
      at Test.Object.<anonymous>.Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
      at Test.Object.<anonymous>.Test.assert (node_modules/supertest/lib/test.js:173:18)
      at Server.localAssert (node_modules/supertest/lib/test.js:131:12)

```

## Example

```
import 'jest'
import { TestContext, inject, bootstrap } from '@tsed/testing'
import * as SuperTest from 'supertest'
import {ExpressApplication, RouteService} from "@tsed/common"
import server from './../../src/server'

describe('test', () => {
  let request: SuperTest.SuperTest<SuperTest.Test>
  beforeAll(bootstrap(server))
  let routeService: RouteService

  beforeAll(inject([ExpressApplication, RouteService], (expressApplication: ExpressApplication, routeSvc) => {
    request = SuperTest(expressApplication)
    routeService = routeSvc
  }))

  beforeEach(TestContext.create)
  afterEach(TestContext.reset)

  it('should be forbidden', async () => {
    console.log('routes', routeService.getRoutes())
    await request.get('/test').expect(403)
  })
})


```

## Acceptance criteria

- [ ] Routes should be printed
- [ ] Test should pass

**Comment by Romakita** [comment]
Hello @vichugunov,

The example work for me and you can checkout getting-started example here: https://github.com/TypedProject/tsed-getting-started/blob/master/test/integration/controllers/calendars/Calendars.spec.ts

Can you remove `beforeEach(TestContext.create)`. Isn't used in the given examle :)

If you routes aren't loaded, you have to check glob pattern set to the mount options in your Server.

See you
Romain

**Comment by vichugunov** [comment]
@Romakita I tried to removed it - and it didn't help at all.
I created sandbox project and this error is reproduced: https://github.com/vichugunov/tsed-supertest-sample

**Comment by vichugunov** [comment]
just run `npm start` to see that it's alive and `npm test` to reveal that problem

**Comment by Romakita** [comment]
Ok the problem come from jest. Dynamic import doesn't work in jest context after typescript compilation (ts-jest override module,fs etc...)

So to solve it have differents options:
- import manually Controller/Service/etc... and use `mount: {'/': [MyController]}`
- use mocha instead of jest
- find a way to tell jest how it have to load typescript file dynamically.

Unfortunately, I can't help you to configure jest correctly jest for this usecase.

See you
Romain

**Comment by vichugunov** [comment]
@Romakita thanks, first variant works for me. 

As far, as I understood, that I need to find a way to require all files like that's done here: https://github.com/TypedProject/ts-express-decorators/blob/master/test/mocha.opts

If I find a way to do that - I will post that here.

Thanks for quick response and for help

**Comment by Romakita** [comment]
I think, jest or ts-jest should have a part dedicated to resolve module with the `import()` syntax.
If you find solution, yes I'll take it and create a new example repo about jest configuration :)
Thanks  ;)

**Comment by vichugunov** [comment]
And the easiest way is to require precompiled version of server within tests =)
But yes, that's definitely not clean solution.
