### ISSUE TITLE
@BodyParams doesn't work well with string

### ISSUE THREAD

**Issue by TranBaVinhSon** [TypedProject/tsed#633]
## Information

- **Version:** 5.x
- **Type:** Issue

## Description
`@BodyParams` doesn't work well with string

## Example
I use postman to send request to server, my json request:
```
{
    "name": "213"
}
```
**My controller:**

```javascript
@Controller("/templates")
@Docs("api-v1")
export class TemplateController {
  private connection: Connection;
  constructor(
    private templateService: TemplateService
  ) {}
  // $afterRoutesInit() {
  //   this.connection = getConnection("default");
  // }
  @Post("/")
  @ContentType("application/json")
  async create(
    @HeaderParams("clientId") clientId: number,
    @BodyParams() templateRequest: TemplateRequestModel,
    @Req() req: Express.Request,
    @Res() res: Express.Response
  ) {
    console.log(templateRequest.name); // return { [String: ''] '0': '2', '1': '1', '2': '3' }. // Wrong value
    console.log(req.body.name); // return 213
}
```
My `TemplateRequestModel` : 
```javascript 
export class TemplateRequestModel {
  name: string;
}
```

My `Server.ts`
```javascript
import {
  ServerLoader,
  ServerSettings,
  GlobalAcceptMimesMiddleware
} from "@tsed/common";
import "reflect-metadata";
import dotenv from "dotenv";
const cookieParser = require("cookie-parser");
const bodyParser = require("body-parser");
const compress = require("compression");
const methodOverride = require("method-override");

import "@tsed/typeorm";
import "@tsed/swagger";

import "./middlewares/ErrorHandlerMiddleware"
import config from "./config";
const rootDir = __dirname;

@ServerSettings({
  rootDir,
  acceptMimes: ["application/json"],
  httpPort: config.httpPort,
  httpsPort: false,
  // // config typeorm
  typeorm: [
    {
      name: "default",
      host: "xxxx",
      type: "mysql",
      port: 3306,
      username: "xxxx",
      password: "xxxx",
      database: "xxxx",
      logging: true, // logging query for debugging
    }
  ],
  // config swagger
  swagger: [
    {
      path: "/api-docs/v1",
      doc: "api-v1",
      showExplorer: true // display search bar
    }
  ],
  // mount controller + routing
  mount: {
    "/api/v1": `${rootDir}/controllers/v1/*.ts`
  }
})
export class Server extends ServerLoader {
  public $onMountingMiddlewares(): void | Promise<any> {
    dotenv.config();
    this.use(GlobalAcceptMimesMiddleware)
      .use(cookieParser())
      .use(compress({}))
      .use(methodOverride())
      .use(bodyParser.json({ limit: "50mb" }))
      .use(
        bodyParser.urlencoded({
          extended: true,
          limit: "50mb"
        })
      );
    return null;
  }
}
```

I read documentation
```
@BodyParams decorator provide quick access to an attribute Express.request.body.
```
But it seems like `@BodyParams` and `Express.request.body` are returning different values. But when I test with the object, both of them return the same value.
Any advice is welcome!

**Comment by Romakita** [comment]
Hello @TranBaVinhSon 
This bug is strange. String is alway considered as primitive type.
But you've missing the part over how a model must described. In the documentation here http://tsed.io/docs/model.html#example  we have a warning about model decoration. you have to add @Property() decorator over each property ^^

Can you fix your model and come back to me if the problem is always here.

See you
Romain

**Comment by TranBaVinhSon** [comment]
@Romakita, Thanks for quick response, but I see many `@Property()` decorators, `@PropertyType`, `@PropertyName`, `@PropertyFn`...., what's exactly decorator I have to add?

**Comment by TranBaVinhSon** [comment]
`The schema generated by Ts.ED list only properties decorated by at least one decorator.`. And is it ok if I use `@Description` or `@Title` decorator ? For example:
```javascript
export class TemplateRequestModel {
  @Title("name")
  @Description("Name of template")
  name: string;
}

```

**Comment by TranBaVinhSon** [comment]
Its really weird, when I change `TemplateRequestModel` to `any`, it worked 
```javascript
  async create(
    @HeaderParams("clientId") clientId: number,
    @BodyParams() templateRequest: any // using any instead of TemplateRequestModel
  ) {}
```
@Romakita Do you have any idea of this problem ?

**Comment by Romakita** [comment]
@TranBaVinhSon When you set any, ConverterService won't deserialize your model to a instance Class. So it work (apparently), by isn't the expected result.

Yes Title and Description inherit from Property decorator. It should work.
```typescript
export class TemplateRequestModel {
  @Title("name")
  @Description("Name of template")
  name: string;
}

@Property(): Can be used to declare a property without any transformation
@PropertyFn(): is a builder decorator. It can be used to manipulate the propertyMetadata (for plugin or extended decorator)
@PropertyName(): create an alias when your property is deserialized from json. I don't recommand to use this decorator... 
@PropertyType(): Can be used to override the default type given by the generated typescript metadata. It useful when you have an string[]. Typescript store only the Array type in metadata. In this case you have to use this decorator, to tell Ts.Ed how it must deserialize your property.

```typescript
class Model {
   @PropertyType(String)
     property: string[];
 }
```

I'll take a time to reproduce your bug. But currently all unit test about this usecase works for me.
Maybe the problem come from your registered middleware. 

See you
Romain

**Comment by Romakita** [comment]
Here a working example: https://github.com/Romakita/tsed-tranbavinhson
All for fine for me

**Comment by Romakita** [comment]
I invited you on the repository ;)

**Comment by TranBaVinhSon** [comment]
Awesome man, thanks for your great work. I will try to reproduce my bug as soon as possible 👍

**Comment by TranBaVinhSon** [comment]
@Romakita First of all, thanks for your great framework and your great enthusiasm. 👍 
We are using TsED on production, so I want to make sure TsED is mature enough.
This is my new bug, not only `@BodyParams`, but it seems like `@Req` doesn't work well.

```ts
  @Post("/")
  @ContentType("application/json")
  async create(@BodyParams() user: User,
    @Req() user1: Express.Request,
    @BodyParams() user2: User,
    @BodyParams() user3: any,
    @BodyParams(User) user4: User,
    @Req() user5: any): Promise<any> {
    console.log("user", user)
    console.log("user1", user1.body)
    console.log("user2", user2)
    console.log("user3", user3)
    console.log("user4", user4)
    console.log("user5", user5)
    // let tmpUser: User = new User();
    // tmpUser.name = "12321321";
    // console.log("tmpUser", tmpUser);
    // return await this.usersService.create(user);
  }
```
log
```
[start:run] user undefined
[start:run] user1 undefined
[start:run] user2 undefined
[start:run] user3 undefined
[start:run] user4 undefined
[start:run] user5 IncomingMessage {}
```

Please take a look at my sample repo: 
https://github.com/TranBaVinhSon/tsed_testing/blob/master/src/controllers/v1/UserController.ts#L36

Hope to hear your response soon! 🙇

**Comment by Romakita** [comment]
@TranBaVinhSon Thanks for your compliment. I a great new for us if you use our framework in production. 

Well... I checkout your repo, and I'm surprised because you haven't following the getting-started example ^^. Your bug is directly related with the server configuration.

You've missed to install  and register required middlewares like body-parser:

```typescript
import {GlobalAcceptMimesMiddleware, ServerLoader, ServerSettings} from "@tsed/common";
import "@tsed/typeorm";
import "@tsed/swagger";
import cookieParser from "cookie-parser";
import bodyParser from "body-parser";
import compress from "compression";
import methodOverride from "method-override";

const rootDir = __dirname;

// DB params

@ServerSettings({
  /// ...
})
export class Server extends ServerLoader {
  public $beforeRoutesInit(): void | Promise<any> {
    this
      .use(GlobalAcceptMimesMiddleware)
      .use(cookieParser())
      .use(compress({}))
      .use(methodOverride())
      .use(bodyParser.json()) // REQUIRED. BodyParams use req.body to works express basicly don't decode body payload
      .use(bodyParser.urlencoded({
        extended: true
      }));

    return null;
  }
}
```

Now your server works. I thinks we can said Ts.ED is mature, but as with any framework there are some bugs or missing features. It takes a long time :)

See you
Romain

**Comment by TranBaVinhSon** [comment]
@Romakita Thanks for quick response, I set up quickly my sample repo and forgot add middleware. After adding your code, my sample repo is working now. But on our `real` project, we already had middleware : 
```ts
  public $onBeforeRoutesInit(): void | Promise<any> {
    dotenv.config();
    this.use(GlobalAcceptMimesMiddleware)
      .use(cookieParser())
      .use(compress({}))
      .use(methodOverride())
      .use(bodyParser.json({ limit: "50mb" }))
      .use(
        bodyParser.urlencoded({
          extended: true,
          limit: "50mb"
        })
      );
    return null;
  }
```
When I remove `limit: "50mb"` at both json and urlencoded, my controller works very with ` @BodyParams() templateRequest: any` (still have `string` problem with `@BodyParams() templateRequest: TemplateRequest`)

The reason that I config `limit: "50mb"` in my bodyParser is I upload base64 of excel file inside my body request. Without limit the server will return `"error":"PayloadTooLargeError: request entity too large` error.

Do you any advice for my problem? Thanks in advance! 🙇

**Comment by TranBaVinhSon** [comment]
It seems like the problem is not from `limit: "50mb"`. When I change `onBeforeRoutesInit()` -> `beforeRoutesInit()`. Everything is ok (still have string problem with `@BodyParams() templateRequest: TemplateRequest`). 
Do you have any explanation? 🙇

**Comment by Romakita** [comment]
Can you checkout again the example: https://github.com/Romakita/tsed-tranbavinhson
And tell if it works. I tried with different scenario and for me it works. Here the curl:
```
curl -X POST "http://0.0.0.0:8080/rest/templates" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"name\": \"test\"}"
```

The problem come from the body-parser middleware. But not sure why you have a bad deserialization. 

So test the latest example and tell me.
See you

**Comment by olliem36** [comment]
I'm having the same issue:

`@BodyParams('phone') phone: string` is parsing my body string into an array.

I'm in the middle of setting up a bunch of services with this library, so i'm concerned there's an issue with a basic setup. Thanks for you help in advance.

Post body:
```
{
  "phone": "0123456789"
}
```

console log from the code below:
```
phone:  { [String: '']
  '0': '0',
  '1': '1',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5',
  '6': '6',
  '7': '7',
  '8': '8',
  '9': '9' }
```

controller:
```
@Controller('/otp')
export default class AppUserController {

  @Post('/send')
  public async sendOTP(
    @BodyParams('phone') phone: string,
  ): Promise<void> {
    console.log('phone: ', phone)
}
```

Server setup:
```
export default class Server extends ServerLoader {
  /**
   * This method lets you configure the middleware required for your application to work.
   * @returns {Server}
   */
  $beforeRoutesInit(): void|Promise<any> {
 
    this
      .use(compress({}))
      .use(methodOverride())
      .use(bodyParser.json({ limit: "50mb" }))
      .use(
        bodyParser.urlencoded({
          extended: true,
          limit: "50mb"
        })
      )
    return null
  }   
```

Package versions:
"@tsed/common": "^5.44.10",
"@tsed/core": "^5.44.10",
"@tsed/di": "^5.44.10",
"@tsed/swagger": "^5.44.9",
"@types/body-parser": "^1.19.0",
 "@types/compression": "^1.7.0",
"@types/dotenv": "^8.2.0",
"@types/express": "^4.17.3",
"@types/method-override": "0.0.31",
"@types/swagger-schema-official": "^2.0.21",
"body-parser": "^1.19.0",
"compression": "^1.7.4",
"cookie-parser": "^1.4.5",

**Comment by olliem36** [comment]
Update, I found a workaround, by using an interface:

```
interface SendOTPRequestDTO {
  phone: string
}

@Controller('/otp')
export default class AppUserController {

  @Post('/send')
  async sendOTP(
    @BodyParams() request: SendOTPRequestDTO,
  ): Promise<void> {
    console.log('phone: ', request.phone)
}
```

**Comment by Romakita** [comment]
@olliem36 I added a repository with your given example code. https://github.com/Romakita/tsed-issue-633

The BodyParams works (I use the swagger-ui and a supertest). So can you fork the repo, try to reproduce code and push a PR with the bug please :)

See you
Romain
