### ISSUE TITLE
Serve multiple static apps under subdomains

### ISSUE THREAD

**Issue by ghmendonca** [TypedProject/tsed#641]
## Information

- **Version:** 5.x
- **Type:** Issue/Story

## Description
I have two web apps that I want to serve. First, I am using graphql with tsed, which means the route '/graphql' needs to be reserved to it.

What I am doing right now is using the express-subdomain package to serve both apps under their domains, the thing is, one of them I want to serve at a wildcard subdomain and the other under the admin subdomain. What I did was pass this middleware on my server $onInit function and set to serve my app on every request, but this overrides the /graphql route too, so I can access my app but when my app requests the /graphql data, the server returns the static folder again.

Is there any way to get around of this? I tried couple things but none worked.. 

## Example

```typescript
export class Server extends ServerLoader {
    $onInit(): void | Promise<void> {
        const admin = express()
        admin.use(express.static(path.join(__dirname, '../../admin/build')))
        admin.get('*', (request, response) => {
            response.sendFile(path.join(__dirname, '../../admin/build/index.html'))
        })

        const user = express()
        user.use(express.static(path.join(__dirname, '../../user/build')))
        user.get('*', (request, response) => {
            response.sendFile(path.join(__dirname, '../../user/build/index.html'))
        })

        this.use(subdomain('*', user))
        this.use(subdomain('admin', admin))
    }
}

```

## Acceptance criteria

- [ ] Serve multiple apps under subdomains

**Comment by Romakita** [comment]
Hello @ghmendonca,
Honestly, I never tried to host different apps/domains with express. I prefer to deleguate this task to ngninx or other app server. But I see your problem. 
The "Cannot destructure property container of 'undefined' or 'null'." means you register your static to in advance in the lifecycle. The $onInit hook hasn't the context and container created correctly.

Try this code:
```typescript
export class Server extends ServerLoader {
    $beforeRoutesInit(): void | Promise<void> {
        const admin = express()
        admin.use(express.static(path.join(__dirname, '../../apitech-admin/build')))
        admin.all('/graphql', (request, response, next) => {
            next()
        })
        admin.all('*', (request, response, next) => {
            if(request.url === '/graphql') {
                next()
            } else {
                response.sendFile(path.join(__dirname, '../../apitech-admin/build/index.html'))
            }
        })

        this.use(vhost('admin.localhost', admin))
        this.use(vhost('admin.apitech.tk', admin))
    }
}
```

See you
Romain
