### ISSUE TITLE
Swagger: Can't obtain a correct swagger definition nesting an entity from other file

### ISSUE THREAD

**Issue by karlos1337** [TypedProject/tsed#642]
## Information

- **Version:** 5.31.0
- **Type:** Issue

## Description
Using a class imported from other file as nested property generate a wrong swagger definition of it.

## Example
```typescript
/* auth.entity.ts */
export class LoginResponse { 
    @Property() user: User; 
   @Property() token: string;
}

/* user.entity.ts */
export class User { @Property() name: string; }
```
Obtain this:
```
"PostLoginResponse": {
  "properties": {
    "user": {
      "type": "object"
    }
    "token": {
      "type": "string"
    }}
```

Only obtains a correct build and swagger definition ensuring that inter-dependencies are in the same file and ordering child classes on top of parent classes, not maintaining the order suppose a broken build with `User not defined`. With type-orm relationship decorators work fine but this case is not a database object and is not two-way related so syntax don't fit either.

## Acceptance criteria

- [ ] Swagger.json is builded correctly independent of model files organization.

**Comment by Romakita** [comment]
Hello @karlos1337 
Can you send me the imported code in addiction please. Isn't clear for me. 
Model file organization is very important, and I can't do a miracle if the Symbol/Class aren't imported correctly ;), it's a pure javascript/nodejs problem.

This example work (this case is covered by unit test and integration):
```typescript
export class User { @Property() name: string; }
```
```typescript
import {User} from "./user.entity.ts";

export class LoginResponse { 
   @Property() 
   user: User;  // User symbol is correctly collected by TypeScript metadata
   @Property()
   token: string;
}
```
One reason where this code won't work is if you have a circular dependencies:
```typescript
import {LoginResponse} from "./auth.entity.ts"; // weird example i agree

export class User { 
   @Property() name: string; 
   @Property() circular: LoginResponse;
}
```

```typescript
import {User} from "./user.entity.ts";

export class LoginResponse { 
   @Property() 
   user: User;  // User symbol is correctly collected by TypeScript metadata
   @Property()
   token: string;
}
```

So currently, I haven't enough element to help you and determine where come from your problem.
I created a repo with you're given example. Swagger generate the spec as expected.
https://github.com/Romakita/tsed-carlos
You have an invitation to this repo. You can modify code to reproduce the problem :)

See you
Romain

**Comment by karlos1337** [comment]
Hello @Romakita,
Thanks for creating the repo, I've tried hard to reproduce the error there but can't, maybe is not related with the proper import  and the problem is somewhere else, decorators conflicts? not sure now, here is the repo where I'm testing https://gitlab.com/krls/tsed-example-project and the entitiy files I'm using https://gitlab.com/krls/tsed-example-project/tree/master/src/entities , `npm i && docker-compose up` and can see the error on your own in `localhost:8080`

**Comment by Romakita** [comment]
Ok I try to find where come from you issue. Maybe you've right, decorators from TypeORM are in conflict with Ts.ED decorator. 
I'll inspect that,
See you

**Comment by Romakita** [comment]
Ok found. As I explaned, the circular references are a problem for Typescript metadata. 
And you have a circular reference between auth.entity.ts and user.entity.ts. 

Just split you auth.entity.ts to fix the problem. Create for example a postloginresponse.model.ts to solve your problem. 

See you
Romain

**Comment by Romakita** [comment]
Maybe we can plan to add new decorator to handler the Type correctly with the circular reference:

```typescript
@CircularRefWith(()=>User)
```

**Comment by karlos1337** [comment]
Sounds great :)

**Comment by Romakita** [comment]
Yes but not for now. I haven't time to work on this decorator :)

**Comment by Romakita** [comment]
v6 support this feature with @tsed/schema.
