### ISSUE TITLE
BaseHref Setting?

### ISSUE THREAD

**Issue by pirouet** [TypedProject/tsed#650]
## Information

- **Version:** 5.x
- **Type:** Question

## Description
Is there currently a way to set a global baseHref? Ideally I would like to have a way to say - possibly within the ServerSettings baseHref: '/application-service' and this would then be prepended to each route as opposed to having to find a way to add it to every route, whether that be in mount of the Controllers themselves.

**Comment by Romakita** [comment]
Hello @pirouet 

Middleware can doing that http://tsed.io/docs/middlewares.html#configuration

```typescript
import {Middleware, Req, Contant} from "@tsed/common";

@Middleware()
export class BaseHrefMiddleware {
  @Contant("baseHref", "/")
  private baseHref: string;

  use(@Req() req: Req) {
    req.baseHref = this.baseHref
  }
}

@ServerSetttings({ 
    baseHref: '/'
})
class Server extends ServerLoader {

    $beforeRoutesInit() { // or $onMountingMiddlewares (legacy hook)

       this.use(BaseHrefMiddleware)
   }
}
```

See you
Romain

**Comment by pirouet** [comment]
@Romakita thanks! ... Would it be an idea (happy to work on this) to not have to use Middleware to do this and instead, provide native support by setting "baseHref" - or alternative appropriate name - so it just works "out of the box"?

Absolutely no issue with the approach above but it does rely on adding another Middleware. What's your thoughts?

**Comment by Romakita** [comment]
I don’t understand why you need baseHref. req.url has the right information, no?

**Comment by Romakita** [comment]
Maybe a plugin can be a solution to do this?
