### ISSUE TITLE
Running logging middleware after body-parser

### ISSUE THREAD

**Issue by TranBaVinhSon** [TypedProject/tsed#687]
## Information

- **Version:** 5.x
- **Type:** Issue/Story

## Description
This actually not really a problem from TsED. But I don't know where should I ask a question about TsED. I always get very fast response from @Romakita in here, so I try to ask you again :bow:

Basically, I'm doing customized logging middleware, and I have to inspect to raw data by this code: `request._readableState.buffer.head.data`. But the body of my request is very very long (base64 of excel file). That's why I can't get all of the data from body: `Buffer.from(request._readableState.buffer.head.data).toString();`.

**My question**: Is there any way I can run `LogRequestMiddleware` after `body-parser` middleware in TsED ?
For now, my current solution isn't using middleware and moving log inside the controller, but that solution will make my controller's codebase become more difficult to maintain.

Any help is welcome, thanks in advance!

## Example

```js
import { LogIncomingRequestMiddleware, Req, OverrideProvider } from "@tsed/common";

@OverrideProvider(LogIncomingRequestMiddleware)
export class LogRequestMiddleware extends LogIncomingRequestMiddleware {
  public use(@Req() request: any): any {
    request.id = require("uuid").v4();
    this.onLogStart(request);
  }
  protected requestToObject(request: any): any {
    return {
      reqId: request.id,
      method: request.method,
      url: request.originalUrl || request.url,
      duration: new Date().getTime() - request.ctx.dateStart.getTime(),
    };
  }
  public $onResponse(request: any, response: any): any {
    this.onLogEnd(request, response);
  }

  /**
   * The separate onLogStart() function will allow developer to overwrite the initial request log.
   * @param {e.Request} request
   */
  protected onLogStart(request: any): any {
    switch (info.method) {
      case "POST":
        const requestBody: string = Buffer.from(request._readableState.buffer.head.data).toString();
        const requestBodyJson = JSON.parse(requestBody);
    }
  }
}

```

## Acceptance criteria

- [ ] Criteria 1

**Comment by Romakita** [comment]
Hello @TranBaVinhSon 

I see. I fact isn't possible. The logmiddleware is added by tsed.

**Comment by TranBaVinhSon** [comment]
Thanks for your quick response again. Do you any suggestions to handle this case (the body of request too long... ) ?

**Comment by Romakita** [comment]
You can use the $afterInit hook on Server level.

```
class Server {
   $afterInit (){
      this.use(bodyparser())
    } 
}
```
