### ISSUE TITLE
Asynchronous JSONSchema validation/AJV

### ISSUE THREAD

**Issue by YaroslavAverianovAE** [TypedProject/tsed#698]
## Information

- **Version:** 5.20.1

## Description
Hi,

Main question is: Could I do asynchronous validation (for body or for query/path params)? 
Like check is entity's id exists in db.

And one more: Why AjvService creates new instance of Ajv on each validation call instead of create single instance? 
I've asked, since: 
- creating new instance of Ajv each time is disabling already compiled schemas caching 
- we can't specify custom validation rules (keywords)

**Comment by Romakita** [comment]
Asynchronous validation isn't possible. But you can check ID with a middleware. It's preferable to handle this verification with a middleware ;)

> creating new instance of Ajv each time is disabling already compiled schemas caching
Ok i'll try optimize the point

> we can't specify custom validation rules (keywords)
It's not possible currently. It's a work in progress.

**Comment by YaroslavAverianovAE** [comment]
Hey,
as for middleware, I got what you mean and don't agree with it :)
Since I want to specify single layer of validating logic instead of splitting it on several one. Also that I will have several branches of async validation logic, so specifying several middlewares not so useful as defining custom async validation functions with decorators.
Anyway thank you for response.

**Comment by Romakita** [comment]
I need to evaluate the faisability with the new v6 version.

**Comment by Romakita** [comment]
Async function can be supported by simply adding an await when we validating a schema. Additionally, adding decorator to define custom injectable class to validate a specific keyword could be interesting.

```typescript
import {@Keyword, KeywordMethods} from "@tsed/ajv";

@Keyword("idExists", {
  async: true,
  type: 'number'
})
export class IdExistsKeyword implements KeywordMethods {
   @Inject()
   service: UserService;
   async validate(value: number) {
     return !!await this.service.findById(value)
  }
}
```

**Comment by YaroslavAverianovAE** [comment]
Hey @Romakita,
Thank you. Looks awesome.
Is there way to update context?

**Comment by Romakita** [comment]
What do you mean by update context?

**Comment by YaroslavAverianovAE** [comment]
I mean is there way to work with request context (like request data, post body, other params) from validate method.

**Comment by Romakita** [comment]
Keyword operate only on schema (by extension on a models). So it will works only for a given model on body. 

Query and Path doesn't have a keyword actually.
