### ISSUE TITLE
Validators for Query Parameters

### ISSUE THREAD

**Issue by tomer-amir-vonage** [TypedProject/tsed#723]
## Information
I would like to have validators for query parameters like there are for body parameters

**Describe the solution you'd like**

```ts
import { Controller, Get, QueryParams, Maximum, Minimum } from "@tsed/common";

@Controller('/test')
export class TestCtrl {
  @Get('/')
  test(@Maximum(10) @Minimum(1) @QueryParams() test: number) {}
}
```

**Current Error**: `[ERROR] [TSED] - TypeError: Cannot read property 'mapper' of undefined`

**Comment by Romakita** [comment]
@tomer-amir Validation on params isn't available (excepted for required). I work on this evolution.

**Comment by tomer-amir** [comment]
It will also be nice if the swagger will reflect that

**Comment by Romakita** [comment]
It will be supported also. The work is around the jsonschema package itself. 
My work about this feature is in progress ^^.

**Comment by Romakita** [comment]
v6 support this feature :) #619
