### ISSUE TITLE
[Question] Use implemented services separate from server

### ISSUE THREAD

**Issue by silveoj** [TypedProject/tsed#725]
I use
```
@tsed/common": "4.32",
@tsed/di": "5.32"
```
I have server with TSED and NodeJs application separated from this server.
This app uses some implemented services (`@Service() decorator`) from TSED server.

I have next folder structure:
```
projectFolder
  |_app.ts - here is @ServerSettings
  |_package.json - only one package.json. In root folder
  |_src
    |_constrollers
    |_services
    |_my-node-app
```

I use `ts-node` to run TS files:
`"npm run start": "ts-node src/my-node-app/my-app.ts"`

As I said, I want to use services (with a lot of DI inside each service) from my implemented TSED server code. I don't start server and start only my app.
In `my-app.ts` I use common TS class without decorators and use `InjectService`.

But why does it work? How does injector find my services in parent folder (`../my-node-app`)? `@tsed/di`? Is it safe way to use services?
```
// no any decorators
class MyClass {
  public init() {
     const injector = new InjectorService();
     await injector.load();
     const myService = injector.get<MyService>(MyService);
     // here I can use myService.
  }
}
```

Is it [[AWS] TSED.io without WEB API](https://github.com/TypedProject/ts-express-decorators/issues/604) similar to my case?

Thanks.

**Comment by Romakita** [comment]
Hello @silveoj 
You can take as example loadInjector function to help you. This function will load correctly the injector from the globalContainer (global container contains all class imported via ES6 import)

Here his impletementation:

```typescript
export async function loadInjector(injector: InjectorService, container: Container = createContainer()): Promise<LocalsContainer<any>> {
  // Clone all providers in the injector container
  injector.addProviders(container);

  // Resolve all configuration
  injector.resolveConfiguration();

  injector.settings.forEach((value, key) => {
    injector.logger.debug(`settings.${key} =>`, value);
  });

  injector.invoke(MvcModule); // invoke ConverterModule, ParseService, ValidationService, JsonSchemesService, RouteService . If you don't use theses classes in your code, you can skip this call. 

  return injector.load(container);
}
```
And use it to bootstrap your app:
```typescript
import {createInjector} from "@tsed/common" // packages/common/src/server/utils/createInjector.ts
import {loadInjector} from "./loadInjector"
import {MyService} from "./MyService"
import "./myService2"

async function bootstrap(settings = {}){
    const injector = createInjector(settings)
    
    await loadInjector(injector);

    const myService = injector.get<MyService>(MyService);

   // some stuff
}

bootstrap({
  // initial config
})
```

I hope this example will help you ;)
Romain

**Comment by silveoj** [comment]
Thanks.
But how does injector find my services in parent folder (../my-node-app)? @tsed/di? Is it safe way to use services?

**Comment by Romakita** [comment]
In this way, you have to import manually you Service in the my-node-app or use globby module to find file that match with a glob patterns and require it.

Ts.ED discover automatically class with annotation when the his file is imported :)
