### ISSUE TITLE
@mongoose/types is a required dependency - doco needs to be updated

### ISSUE THREAD

**Issue by oehm-smith** [TypedProject/tsed#734]
## Information

- **Version:** 5.x

I am upgrading to latest TSED after a while away from a project.  I followed the doco for https://tsed.io/tutorials/mongoose.html but the IDE couldn't find 'find'.  Eg:

    constructor(
    @Inject(AvDbModel) private model: MongooseModel<AvDbModel>) { }

    async search(query: AvDbModelQuery): Promise<AvDbModel[]> {
        const data: AvDbModel[] = await this.model.find(query)

And the compile failed with:

     [2020-01-11T18:40:24.861] [ERROR] [TSED] - src/persistence/DBAvService.ts:13:48 - error TS2339: Property 'find' does not exist on type 'MongooseModel<AvDbModel>'.

After re-installing I saw the WARNing:

     npm WARN @tsed/mongoose@5.36.2 requires a peer of @types/mongoose@^5.5.32 but none is installed. You must install peer dependencies yourself.

And after installing `@types/mongoose` the problem was fixed.

## Acceptance criteria

The documentation should include:

     npm install --save @types/mongoose

after (or with):

     npm install --save @tsed/mongoose

**Comment by Romakita** [comment]
Fixed
