### ISSUE TITLE
Returning file on success

### ISSUE THREAD

**Issue by denisprsa** [TypedProject/tsed#739]
## Informations
**Is your feature request related to a problem? Please describe.**

I'm trying to set in swagger to produce a file on 200. But cannot find if this is possible.

**Describe the solution you'd like**

```
@Returns(200, { description: 'on success', type: File })
@Produces('application/octet-stream')
public async downloadFile() {

}
```

which will produce 

```json
"responses": {
    "200": {
        "description": "on success",
        "schema": {
            "type": "file"
        }
    }
},
"produces": [
    "application/octet-stream"
]
```

**Comment by Romakita** [comment]
Hello @denisprsa 

If you write that:
```typescript
@Returns(200, { description: 'on success', type: 'file' })
@Produces('application/octet-stream')
public async downloadFile() {

}
```

It should work ?

**Comment by denisprsa** [comment]
Hey @Romakita 

Returns() expects second parameter to be the type of **ISwaggerResponses**, where property schema does not exist. Am I missing something?

https://github.com/TypedProject/tsed/blob/fb88a32fde32a0b245ddf2ad42f89aacd8d2f9b4/packages/swagger/src/interfaces/ISwaggerResponses.ts

**Comment by Romakita** [comment]
Fixed :)
