### ISSUE TITLE
Mongoose Unpopulated Refs

### ISSUE THREAD

**Issue by royibernthal** [TypedProject/tsed#744]
Unpopuated refs return plain id strings, which makes sense because that's what's actually stored and returned by mongoose under the hood, however, in this case the they are not represented correctly by their typings.

For instance, let's assume we have the following models:

```
@Model()
export default class User {

  @ObjectID('id')
  _id: string;

  @Property()
  name: string;

}

@Model()
export default class UserRef {

  @ObjectID('id')
  _id: string;

  @Ref(User)
  users: User[];

}
```

Let's assume these documents exist in the database, I'll use unrealistic ids for the sake of readability.

User ids: 'usera', 'userb'
UserRef ids: 'userref'

UserRef users will contain both usera and userb.

Finding UserRef by id 'userref', will result in the following document:

```
{
    "_id": "useref",
    "users": ["usera", "userb"]
}
```

users is by default unpopulated, which is fine, however its value in this case is not of type User[] but rather of type string[].

So while typescript treats doc.users as User[], it is in fact string[].

Once populated it of course contains User[] as expected.

In order for the typings to be correct in all cases, why not map the unpopulated ids into objects with _id?

Something like this:

```
{
    "_id": "useref",
    "users": [{"_id": "usera"}, {"_id": "userb"}]
}
```

Then users will always contain User[] regardless of whether it's populated or not. Naturally only _id will exist in unpopulated objects.

**Comment by Romakita** [comment]
Hello @royibernthal 
The object is returned by mongoose not by Ts.ED itself. I don't know if it's possible without patching all mongoose method. 

You can change the typing to reflect the reality no ?

```typescript
@Model()
export default class UserRef {

  @ObjectID('id')
  _id: string;

  @Ref(User)
  users: (User | string)[];
}
```
Or you can use getter / setter to implement the right behavior:

```typescript
@Model()
export default class UserRef {
  @IgnoreProperty()
  private _users: (User | string)[]

  @ObjectID('id')
  _id: string;

  @Ref(User)
  get users() {
     return this._users
  }
  
  set users(users: User[]){
    this.users = users // change this code by your own behavior
  }
}
```

See you,
Romain

**Comment by royibernthal** [comment]
Hey @Romakita 

I suppose it's possible, it just seems like a great amount of boilerplate code to do it for each reference I have. It felt like something that should be done at tsed level.

Do you personally not feel like it should be the appropriate behavior at tsed level? Being able to consistently treat models as entities rather than strings throughout the whole app sounds appealing to me.

What do you do in your own projects? Do you use the solutions you mentioned above?

**Comment by Romakita** [comment]
The choice to change the deserialization behavior will certainly impact all project based on tsed/mongoose package. Today, it's mongoose the responsible to transform plain object to class instance, not Ts.ED. I think it's a pur problem from mongoose and maybe an option/plugin exists to tell mongoosse how the ref should be deserialized.

> What do you do in your own projects? Do you use the solutions you mentioned above?

No I'd just thinking about this solution, I haven't tested this ^^

Maybe the solution is to create a decorator which reuse the existing Ref.

```typescript

/**
 * Define a property as mongoose reference to other Model (decorated with @@Model@@).
 *
 * The difference between @@Ref@@ and @@UseRef@@ is this decorator use allow the given model if you populate or not the query.
 *
 * ### Example
 *
 * ```typescript
 *
 * @Model()
 * class FooModel {
 *
 *    @UseRef(Foo2Model)
 *    field: Foo2Model
 *
 *    @UseRef(Foo2Model)
 *    list: Foo2Model[] 
 * }
 *
 * @Model()
 * class Foo2Model {
 * }
 * ```
 *
 * @param model
 * @param type
 * @returns {Function}
 * @decorator
 * @mongoose
 * @property
 */
export function UseRef(model: string | any, type: MongooseSchemaTypes = MongooseSchemaTypes.OBJECT_ID) {
  return applyDecorators(
    Ref(model, type),
    PropertyFn((propertyMetadata: PropertyMetadata) => {
      let localValue: any;
      Object.defineProperty(propertyMetadata.target, propertyMetadata.propertyKey, {
        set(v: any) {
          if (propertyMetadata.isArray) {
            localValue = v.map((item: any) => {
              if (typeof item === "string") {
                return Object.assign(new model(), {_id: item});
              }

              return item;
            });
          } else {
            localValue = Object.assign(new model(), {_id: v});
          }
        },
        get() {
          return localValue;
        },
        enumerable: true
      });
    })
  );
}

```
Honestly, I don't know if it's a good idea ^^ because when you'll use this decorator, mongoose will receive a list of User ref with only the _id prop when you'll update the document. I don't know what will be the side effect.

You can try it and we will see :)

**Comment by shprota** [comment]
I'd say it's a dangerous practice to mock unpopulated fields to an _id only partial. How would you differ unpopulated vs incomplete data in your code?
The Mongoose default approach seems very adequate here.

**Comment by royibernthal** [comment]
@Romakita Got it :) So technically if I don't intend to ever populate the field I might as well just specify the type as string, as the type doesn't affect mongoose, only the @Ref annotation. Is that correct?

```
@Ref(User)
  users: string[];
```

@shprota Technically each of my models have some required fields so I'd still be able to tell, but it's still a very good point. This actually made me rethink this.

**Comment by Romakita** [comment]
@royibernthal In the documentation you can write that:

```typescript
@Ref(User)
users: Ref<User>[];
```

It declare correctly the typing :)

**Comment by royibernthal** [comment]
@Romakita Got it, I have the full picture now. Thanks for the quick responses :)
