### ISSUE TITLE
TSED.io along with Serverless Framwork

### ISSUE THREAD

**Issue by alexandremello** [TypedProject/tsed#745]
Hi all!

I'm working with [Serverless Framework](https://serverless.com) for the deployment of Lambda functions attached to a API Gateway, and I would love to use TSED.io for route decorators and swagger documentation.
A search leads me to [Serverless-HTTP](https://serverless.com/plugins/serverless-http/) plugin to map an Express application into AWS API Gateway, but I couldn't figure out how to use this plugin with TSED.io. Is there a way to pass the Express `app` created by TSED.io to Serverless-HTTP to handle it?

**Comment by Romakita** [comment]
Hello @alexandremello 
Have you look on this page : https://tsed.io/tutorials/aws.html and https://github.com/TypedProject/tsed-example-aws

I think it match with you needs ;)
