### ISSUE TITLE
Combining authentication middlewares idea

### ISSUE THREAD

**Issue by PAStheLoD** [TypedProject/tsed#747]
## Informations
Combining Auth Middlewares

**Describe the solution you'd like**
I'd like to be able to simply combine custom middlewares with logical AND or OR, or something like ANY or ALL.

Basically something like passport's multi, but without the strange passport API.

**Describe alternatives you've considered**
I've tried to implement one (an AnyOf) middleware, but it turned out to be very impractical. My idea was to simply instantiate the middleware objects, call use() with the endpoint, req, resp params, and with a Promise-like next (so basically to know when next got called and with what), and catch exceptions (such as Unauthorized). And if at least one succeeded [so called next without error], then the combinator would do the same, otherwise it'd return the combined errors.

**Comment by Romakita** [comment]
Hello @PAStheLoD 
I’m sorry but I don’t understand ^^’
Can you explain me what you want a code example (if it’s possible). 

See you

**Comment by PAStheLoD** [comment]
Hello,

Sure, sorry, it was a bit late, and I slacked on a code example :)

```
import {BodyParams, Controller, Post, Req, Scope} from "@tsed/common";
import {ComplexAuthenticate, OneOf} from "@tsed/magicl-middlewares";
import {JWTAuthenticationMiddleware, ApiKeyAuthenticationMiddleware} from "../custom/stuff";

@Controller("/")
export class ExampleCtrl {
  @Post("/fancyEndpoint")
  @ComplexAuthenticate(OneOf([JWTAuthenticationMiddleware, ApiKeyAuthenticationMiddleware]))
  doTheThing(@Req() req: Req, @BodyParams("email") email: string, @BodyParams("thing_id") thingId: string) {
    // ...
  }
}
```

Of course the "AllOf" is what we currently have, after all simply chaining (composing) middlewares does this, but making middlewares optional, but not all of them optional would have a lot more expressive power.

Also, I guess it might be completely out of scope for TSed, I just wanted to pitch the idea and to ask what do you think about this, what would you recommend instead.

Thanks!
