### ISSUE TITLE
export AjvValidationError in @tsed/ajv

### ISSUE THREAD

**Issue by ziofat** [TypedProject/tsed#749]
## Informations
**Is your feature request related to a problem? Please describe.**
I have override the GlobalErrorHandlerMiddleware to produce my own error messages. However, AJV Validation Errors (which in `error.origin.errors`) has no type.

``` ts
@OverrideProvider(GlobalErrorHandlerMiddleware)
export class ErrorHandlerMiddleware extends GlobalErrorHandlerMiddleware {
    public use(
        @Err() error: Exception & IResponseError,
        @Req() request: Req,
        @Res() response: Res,
    ): Response {
        if (error instanceof ParseExpressionError) {
            // ajv validation error
            return response.status(error.status).json({
                errors: error.origin.errors, // error TS2339: Property 'errors' does not exist on type 'Error'.
                meta: {
                    id: request.log.id,
                    time: request.log.startDate,
                },
            });
        }
        if (error instanceof Exception) {
            return response.status(error.status).json({
                errors: error.errors,
                meta: {
                    id: request.log.id,
                    time: request.log.startDate,
                },
            });
        }
        $log.fatal({
            id: request.log.id,
            code: 500000,
            title: 'Internal Error',
            origin: error,
        });
        return response.status(500).json({
            errors: [{
                code: 500000,
                title: 'Internal Error',
            }],
        });
    }
}
```

**Describe the solution you'd like**
I think I can get through this with the `AjvValidationError` class.

```ts
import { AjvValidationError } from "@tsed/ajv";

if (error instanceof ParseExpressionError && error.origin instanceof AjvValidationError) {
    // ajv validation error
    return response.status(error.status).json({
        errors: error.origin.errors,
        meta: {
            id: request.log.id,
            time: request.log.startDate,
        },
    });
}

```

**Describe alternatives you've considered**
If you have better idea, I would glad to use it.

## Acceptance criteria

- [ ] I can use `error.origin.errors` in my program.

**Comment by Romakita** [comment]
Hello @ziofat 
When an AJV error is emitted, the error.origin is an instance of AjvValidationError.

```typescript
import { AjvValidationError } from "@tsed/ajv";

if (error.origin instanceof AjvValidationError) { // works
    // ajv validation error
    return response.status(error.status).json({
        errors: error.origin.errors,
        meta: {
            id: request.log.id,
            time: request.log.startDate,
        },
    });
}
```

**Comment by ziofat** [comment]
@Romakita Yes. That's what I mean.

Currently the issue is: 
```ts
import { AjvValidationError } from "@tsed/ajv";
```
This import statement is not working because `@tsed/ajv` does not export `AjvValidationError `

**Comment by Romakita** [comment]
Haaaaaaaa ok. Sorry ;) 
I'll fix that :)

**Comment by chiqui3d** [comment]
@Romakita 

I just activated Ajv and it doesn't show me the right error

`message: "Bad request on parameter "request.body".↵Error for username with value "aa" ↵ Property 0 on class String is not allowed."`

and I'm validating with `@MinLength(5)`. 

It should show the error that the minimum is 4 ....

Plus I have imported into the server.ts:

`import "@tsed/ajv";`

**Comment by Romakita** [comment]
Maybe you have another error thrown before the minLength ;)

**Comment by chiqui3d** [comment]
ok @Romakita,

I'm going crazy. It was because I was sending the content type like JSON on my application.

```
const res = await Fetch(config.apiEndpoint + path, {
        method: 'POST',
        headers: {
 	       "Content-Type" = "application/json"
		},
        body: data,
    })
```

you know what the explanation for that is?`

**Comment by chiqui3d** [comment]
@Romakita, but the error is:

```
Bad request on parameter "request.body".
At User, value '[object Object]' should have required property 'username'
```
Why doesn't it say anything about the minimum? and I'm validating with @MinLength(5).

```
{
  errorFormat: (error) => `At ${error.modelName}${error.dataPath}, value '${error.data}' ${error.message}`,
  options: { verbose: true }
}
```

**Comment by NachtRitter** [comment]
> ok @Romakita,
> 
> I'm going crazy. It was because I was sending the content type like JSON on my application.
> 
> ```
> const res = await Fetch(config.apiEndpoint + path, {
>         method: 'POST',
>         headers: {
>  	       "Content-Type" = "application/json"
> 		},
>         body: data,
>     })
> ```
> 
> you know what the explanation for that is?`

Did you set up propper body parser for JSON-body?

```typescript
import { GlobalAcceptMimesMiddleware, ServerLoader, ServerSettings } from '@tsed/common';
import * as bodyParser from 'body-parser';

@ServerSettings({
// your server config here
})
export class MyServer extends ServerLoader {
  $beforeRoutesInit() {
    this.use(bodyParser.json({ limit: '10mb' }));
  }
}
```

**Comment by chiqui3d** [comment]
Thanks @NachtRitter All that I have done, the only problem I have is with the `AJV validation.

I don't really know if it's a problem for me or AJV TSED, but if in `@BodyParams() body: User` remove User Type, everything works fine.

```ts
 @Post('/update/:id')
  @Description('Update user by ID')
  async update (@PathParams('id') id, @BodyParams() body): Promise<any> {
    const user = await this.userRepository.findOne(id)
    if (!user) {
      throw new NotFound('Not user found')
    }
    return this.userRepository.save({...user,...body})
  }
```
But the validator doesn't recognize. I think I'll look for other alternatives.

**Comment by chiqui3d** [comment]
I will try to use: https://github.com/typestack/class-validator
