### ISSUE TITLE
[BUG] swagger decorator changes response

### ISSUE THREAD

**Issue by silveoj** [TypedProject/tsed#750]
## Information

- **Version:** @tsed/swagger - 5.38.1

We updated @tsed/swagger from 5.1 to 5.38.1.

We use this decorator for GET endpoint:
```
@ReturnsArray(MyClass)
```
but this class returns object. It's our mistake but it works in 5.1 version for localhost and IIS server (responses are the same).

With 5.38.1 version responses are the different.
It returns response as object with properties in localhost.
But it always returns response as empty object (without properties) in server.

It started to work when we replaced from ```@ReturnsArray(MyClass)``` to ```@Returns(MyClass)```.
i.e. we get correct response.

Is it correct behavior in swagger to replace response? I thought swagger just creates documentation and does not affect response.

Thanks.

**Comment by Romakita** [comment]
Hello @silveoj,
Honestly, I don't understand your bug. If you endpoint return an array, you should use `@ReturnArray` and if your endpoint return object, you have to use `@Returns`.


I added an additional integration test here: https://github.com/TypedProject/tsed/blob/production/packages/swagger/test/swagger.integration.spec.ts
The generated swagger is ok.

Can you give more details about your bug or give repository link with your problem pls :)
