### ISSUE TITLE
[BUG] Memory Leak | JavaScript heap out of memory

### ISSUE THREAD

**Issue by NitzanHardonVonage** [TypedProject/tsed#754]
We had a memory leak on two different services running ts.ed framework on node 12.

After some investigating, we discovered the same error logs on both of the services:
```
FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory

<--- Last few GCs --->

[18:0x39f9c20] 429514310 ms: Scavenge 912.9 (989.3) -> 899.1 (989.3) MB, 4.8 / 0.1 ms  (average mu = 0.999, current mu = 0.999) allocation failure 
[18:0x39f9c20] 429516411 ms: Scavenge 914.1 (989.3) -> 900.3 (989.3) MB, 4.8 / 0.1 ms  (average mu = 0.999, current mu = 0.999) allocation failure 
[18:0x39f9c20] 429518553 ms: Scavenge 915.4 (989.3) -> 901.5 (989.3) MB, 4.8 / 0.1 ms  (average mu = 0.999, current mu = 0.999) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13725d9]
Security context: 0x3be9081808a1 <JSObject>
    1: /* anonymous */ [0x20e9a7407ac9] [/usr/src/app/node_modules/@tsed/common/lib/server/utils/contextMiddleware.js:~13] [pc=0x391e14c502e9](this=0x0e2eeab4fc79 <Object map = 0x2e9f2ac42191>)
    2: next [0x3be9081a3651](this=0x20e9a7407ea9 <JSGenerator>)
    3: /* anonymous */(aka /* anonymous */) [0xff65d1e9041] [/usr/src/app/node_modules/@tsed/common/lib/ser...
```   

- **Version:** 5.28.0 and 5.33.0
- Packages:
```
"@tsed/ajv": "5.33.0",
"@tsed/common": "5.33.0",
"@tsed/core": "5.33.0",
"@tsed/di": "5.33.0",
"@tsed/swagger": "5.33.0",
```
and:
```
"@tsed/common": "5.28.0",
"@tsed/core": "5.28.0",
"@tsed/di": "5.28.0",
"@tsed/swagger": "5.28.0",
```

We are checking if this memory leak was fixed on version `v5.41.2`.

**Comment by Romakita** [comment]
Hello @NitzanHardonVonage 

Have some questions to investigate correctly your issue: 
- Did you use request.ctx.logger in your code ? 
- Have you changed the logger settings?

```typescript
@ServerSettings({
   logger: {
       requestFields: ["reqId", "method", "url", "headers", "body", "query","params", "duration"]
   }
})
```

- how I can reproduce it? 

if it's possible, can you give me an access to your project? It'll be faster for me to understand and solve your problem ;)?

See you
Romain

**Comment by NitzanHardonVonage** [comment]
@Romakita 
I created a simple ts.ed API and I reproduced the memory leak.  I ran this API on an AWS Fargate service and I sent ~340 requests per second using locust (load test tool).
container settings:
```
memory (MiB)512
CPU (unit)256
``` 

https://github.com/NitzanHardonVonage/tsed-mem-leak

**Comment by Romakita** [comment]
Thanks for the repo example :). 
I published a fix too reduce the potential memory leaks on the createContext middleware. Can test it pls (latest version).

I’ll checkout your example and investigate with the same tool :). I’ll come back to you when I found the reason.

See you

**Comment by NitzanHardonVonage** [comment]
Adding my locust code to save you some time :)

```
import os
import random
from locust import HttpLocust, TaskSet, runners, task, web
from locust_check_results import run_validation_check

def get_id():
    return random.randint(1,100001)

names = ['string', 'name', 'nitzan', 'hardon', 'memory', 'leak' 'aaaa', 'bbbb', 'cccc', 'asdfasfsa', 'iy', 'nihfq', 'aga', 'jasdfh', 'csscs', 'dddd']
def get_name():
    return random.choice(names)


class LocustSet(TaskSet):

    def on_start(self):
        pass

    def on_stop(self):
        pass

    @task(1)
    def get_command(self):
        id = get_id()
        self.client.get("/ctrl/%i" % id, name="/ctrl/[id]")

    @task(1)
    def post_command(self):
        i = get_id()
        body = {'name': get_name()}

        self.client.post("/ctrl/%i" % i, name="/ctrl/[id]", json=body)

    @task(1)
    def put_command(self):
        id = get_id()
        name = get_name()
        self.client.put("/ctrl/%i?name=%s" % (id, name), name="/ctrl/[id]?name=[name]")

    @task(1)
    def delete_command(self):
        id = get_id()
        self.client.delete("/ctrl/%i" % id, name="/ctrl/[id]")

class MemLeakLocust(HttpLocust):
    host = "http://localhost:3000"
    task_set = globals()[os.getenv('TASK_SET', 'LocustSet')]
    min_wait = 0
    max_wait = 0


def get_common_headers(method, path):
    common_headers = {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
    }

    return common_headers
```

**Comment by NitzanHardonVonage** [comment]
As a response to your PR on the dummy project repository,
It looks like there is still a memory leak, even though I removed all the fields from the required fields array.

I ran it once again and I took a snapshot a few minutes after I started the locust test.
Adding the snapshots' results:
![Screen Shot 2020-02-12 at 14 41 12](https://user-images.githubusercontent.com/45146234/74335845-bdf34200-4da5-11ea-82de-e47d09d8521f.png)

In your opinion, is there any chance that the callback function's closure of the process variable in HandlerBuilders class is never released from the memory by the GC? - Same thing for the anonymous function incontextMiddleware.

**Comment by Romakita** [comment]
Hello @NitzanHardonVonage 

I found the problem. The fix is almost done ;)

For the rxjs, I used this to transform an Observable returned by the endpoint to a Promise.
I used rxjs also to handle params. I see where is the problem. I try avoid this.

**Comment by NitzanHardonVonage** [comment]
@Romakita great I'm glad to hear that!
Keep me updated on this :)

**Comment by Romakita** [comment]
Hello @NitzanHardonVonage 
I continue to investigate on the HandlerBuilder. The problem seems to come from the code using rxjs (as you figured out ;) ). Problem is to find the reason and how I can fix that without change all the code :(

See you

**Comment by Romakita** [comment]
Other important point: 

This code create a huge memory leak:
```
if (this.httpServer) {
      this.httpServer.keepAliveTimeout = 600000;
    }
    if (this.httpsServer) {
      this.httpsServer.keepAliveTimeout = 600000;
    }
```

**Comment by Romakita** [comment]
I reproduced the memomy leak with a pure express.js server:
```
const express = require("express");
const fs = require("fs");
const chalk = require("chalk");
const onFinished = require("on-finished");
const bodyParser = require("body-parser");
const compression = require("compression");
const cookieParser = require("cookie-parser");
const cors = require("cors");
const methodOverride = require("method-override");
const uuidv4 = require("uuid/v4");
const http = require("http");

const app = express();
const httpServer = http.createServer(app);

httpServer.keepAliveTimeout = 60000;

app.use(bodyParser.json());
app.use(cookieParser());
app.use(compression({}));
app.use(cors());
app.use(methodOverride());
app.use(bodyParser.urlencoded({
  extended: true
}));

function listen(http, port, address) {
  const promise = new Promise((resolve, reject) => {
    http.on("listening", resolve).on("error", reject);
  }).then(() => {
    const port = http.address().port;
    console.log("==>Port:", port);
  });

  http.listen(port, address);

  return promise;
}

const emitter = {
  async $emit(event, request, response) {
    // console.log("Event", event, request.id);
  }
};

app.use((request, response, next) => {
  const id = uuidv4().replace(/-/gi, "");
  request.id = id;
  request.ctx = {
    id
  };

  onFinished(response, (err, response) => {
    emitter.$emit("onResponse", request, response);
  });

  emitter.$emit("onRequest", request, response);

  next();
});
//
// app.get("/ctrl/:id", (req, res) => {
//   const {params: {id}} = req;
//
//   res.json({
//     id,
//     name: `${id} name`
//   });
// });
//
// app.post("/ctrl/:id", (req, res) => {
//   const {params: {id}, body: {name}} = req;
//
//   res.json({
//     id,
//     name
//   });
// });
//
// app.put("/ctrl/:id", (req, res) => {
//   const {params: {id}, body: {name}} = req;
//
//   res.json({
//     id,
//     name
//   });
// });
//
// app.delete("/ctrl/:id", (req, res) => {
//   const {params: {id}} = req;
//
//   res.json({
//     id,
//     name: `${id} name`
//   });
// });

listen(httpServer, 3000);


//------------------------------
const stats = [];

const write = () => {
  const data = JSON.stringify(stats);
  fs.writeFile(__dirname + "/../../stats.json", data, (err) => {
    if (err) {
      console.log(err);
    } else {
      console.log("\nSaved stats to stats.json");
    }
    process.exit();
  });
};

let last = 0;
const onTick = () => {
  try {
    global.gc();
  } catch (e) {
    console.log("You must run program with 'node --expose-gc index.js' or 'npm start'");
    process.exit();
  }
  const heapUsed = process.memoryUsage().heapUsed;
  stats.push(heapUsed);
  if (last) {
    console.log("Memory heap => ", heapUsed, heapUsed - last > 0 ? chalk.red("+") : chalk.green("-"));
  }
  last = heapUsed;
};
setInterval(onTick, 500);
setTimeout(write, 20000);
```

**Comment by Romakita** [comment]
Now here the graph with contextMiddleware + HandlerBuilder (without keepalive):
![without-keep-with-handler-builder](https://user-images.githubusercontent.com/1763311/74586320-c38b9a80-4fe6-11ea-9ce9-5cc35491ea13.png)
We can see a memory leaks but isn't huge.

Now without handlerBuilder:
![without-handler-builder](https://user-images.githubusercontent.com/1763311/74586374-27ae5e80-4fe7-11ea-97fa-03b3de94514a.png)

**Comment by NitzanHardonVonage** [comment]
I'll check what you said about the `keepAliveTimeout` and see it' effect on the memory.

I'm trying to understand if you still think that there is another problem coming from the code that using rxjs, or the only problem is with the keep-alive timeout?

**Comment by NitzanHardonVonage** [comment]
'm testing it with a new value but this value is greater than 60 seconds. The reason for it is that we are running our services as ECS tasks and we're using AWS load balancer. The load balancer requires us to set the keep-alive timeout to a value greater than 60 seconds to avoid 504 error responses: https://aws.amazon.com/premiumsupport/knowledge-center/504-error-classic/

**Comment by Romakita** [comment]
I understand the usage of the keepAliveTimeout option. 
We have two problem :
- one with the keepAliveTimeout which increase the memory and cpu usage. I see this topics (https://shuheikagawa.com/blog/2019/04/25/keep-alive-timeout/). Maybe adding 
- The rxjs usage in handler buildler create multiple Subject and Observable per endpoint. I consume a huge memory for nothing. I have to optimize this part. This is my main point for this week :)

**Comment by NitzanHardonVonage** [comment]
Hey @Romakita 
is there any new update about the memory-leak?

**Comment by Romakita** [comment]
Yes. I removed the rxjs on handler builder. I’m on the unit test. 
Remove rxjs and use a native approach take a long time ^^

I hope my work will finish today or tommorow

**Comment by Romakita** [comment]
Branch is ready here https://github.com/TypedProject/tsed/pull/770

**Comment by Romakita** [comment]
I runned load testing with the new implementation:

![new-version](https://user-images.githubusercontent.com/1763311/75373749-317b7000-58cb-11ea-94a6-f7e46ff2b83e.png)

The consumed memory is better but the leak is always here... (I'm not sure...)

**Comment by Romakita** [comment]
I'll merge the current work to let you run your own load test. Maybe the actual version is better in your case :)

**Comment by Romakita** [comment]
V5.44.0 is released :)

**Comment by NitzanHardonVonage** [comment]
@Romakita I ran the same load test, still got the same exception

**Comment by Romakita** [comment]
Is a bad news. I removed rxjs and refactored the code to avoid all potential memory leak. I clean after each request all data.

Honestly I need help to a find where is the problem and Understand chrome dev tools result isn’t easy (it don’t help me to fix the problem).

The code responsible to build handlers is here:
https://github.com/TypedProject/tsed/tree/production/packages/common/src/platform

https://github.com/TypedProject/tsed/blob/production/packages/common/src/platform/services/PlatformHandler.ts#L60

Can you review the code maybe you’ll see something.

**Comment by NitzanHardonVonage** [comment]
Yes of course, I'll dig into it tomorrow, hopefully I could find something.
