### ISSUE TITLE
Boolean converter should return undefined if parameter is optional

### ISSUE THREAD

**Issue by biglouch01** [TypedProject/tsed#758]
## Informations

When a optional boolean parameter isn't set in url, boolean converter should return `undefined` instead of `false`.

### Exemple 

My controller :

```typescript
@Get('/news')
@Description('Get list of news')
@Returns(NewsList)
public async get(
    @QueryParams('forced') forced?: boolean,
  ): Promise<NewsList> {
  console.log('forced', forced) // print forced false if forced == undefined
  return something...;
}
```

With this url : `localhost:3000/news`, console.log should print `forced undefined` but print `forced false`.
Works perfectly with `localhost:3000/news?forced=true`, console.log print `forced true`.

### Possible solution

Add `if (data === "") return undefined;` in the **switch case Boolean** in [this file](https://github.com/TypedProject/tsed/blob/v5.42.1/packages/common/src/converters/components/PrimitiveConverter.ts).
Or just `return undefined;` instead of `return !!data;`

**Comment by Romakita** [comment]
Released :)
