### ISSUE TITLE
@Returns for generics

### ISSUE THREAD

**Issue by jcbjoe** [TypedProject/tsed#762]
## Informations
**Is your feature request related to a problem? Please describe.**

Hello! It would be really useful if the @Returns decorator would allow for generic types. For example I am using a return type of PagniationReturn which has two variables at current, data and totalCount. My generic allows me to tell Typescript which type I want data to be. This is really useful as it allows me to reuse the same PagniationReturn. I have also seen a usecase in other systems I have worked on where they have a generic return model which contains information like return code, error, data, information etc..

So what I would like is a decorator that supports generic types for returns, for example: 
![image](https://user-images.githubusercontent.com/3605644/74374164-cbc0bb80-4dd5-11ea-9a5e-083476154045.png)

However this throws an error.

**Describe the solution you'd like**

I would like the following to not error: 
![image](https://user-images.githubusercontent.com/3605644/74374164-cbc0bb80-4dd5-11ea-9a5e-083476154045.png)

And in swagger look like:
![image](https://user-images.githubusercontent.com/3605644/74374434-52759880-4dd6-11ea-8599-0e0adb4414f8.png)

**Describe alternatives you've considered**
Currently I just fill in the return type OR I make the return type the Pagniation Result

## Acceptance criteria

- Not sure what this is ?

**Comment by Romakita** [comment]
#619
