### ISSUE TITLE
[Question] Endpoint late registration

### ISSUE THREAD

**Issue by jpramondon** [TypedProject/tsed#765]
## Information

- **Version:** 5.32
- Packages: common / core / DI / swagger / testing

Hi there,
I have been trying to register new controllers on a started instance for a couple of hours and I'm starting to blindfoldly call internal functions that I'm not used to ... obviously I'm getting nowhere with this kind of strategy :D 
So I'm here to ask for a pointer on how to do this.
The idea is that a server has already been created with a single route, but then I would like to "dynamically" register new controllers (already proper Controller classes at that time).
Many thanks !

## Example

Below is what I came up with.
I created an `index.ts` file that (among other loads of api-unrelated things) starts a Server instance with a single controller doing : 

```typescript
function initNode(): Promise<Server> {
    ...
    return Promise.resolve(new Server());
}

initNode();
```

Then here's the server. As you can see, I've been a little too desperate and tried a lot of things.
I truly believe I'm not that far, but I can't find a working process.
As you will notice, the Server class sports a `unleash` function that tries to register other controllers, but it fails: nothing really happens, no new controllers registered.

```typescript
@ServerSettings({
    rootDir,
    logger: { level: "debug" },
    mount: {
        '/': `${rootDir}/controllers/HealthController.ts`
    },
    swagger: ([{ path: "/spec", outFile: path.resolve(rootDir, "./swagger.json") }]),
    acceptMimes: ["application/json"]
})
export class Server extends ServerLoader {
    
    public unleash(): Promise<void> {
        // this.addControllers("/", PermissionsController);
        // this.settings.mount['/'] = `${rootDir}/controllers/*.ts`;
        this
            // .scan(`${rootDir}/controllers/*.ts`, '/')
            // .mount('/', `${rootDir}/controllers/*.ts`)
            .addControllers('/', `${rootDir}/controllers/*.ts`);
        //this.start.httpServer.close( () => {
        //    this.logger.debug("http server closed");
        //    this.start();
        //});
        return this.runLifecycle();	
        // return this.loadSettingsAndInjector();
        // return; 
        // return this.start();
        // this.logger.debug("Finished unleashing server");
    }

}

```

## Acceptance criteria

- [ ] Tell me if it's actually possible to perform such late controller registration
- [ ] Either show me an example or a documentation pointer to achieve this

**Comment by jpramondon** [comment]
I wanted to file a question, not a bug. Sorry about that ... :cry:

**Comment by Romakita** [comment]
No problem :)

**Comment by Romakita** [comment]
Hue... Have you followed the getting-started, because you create new Server which is not a promise and it doesn't start the server.

In your index.ts paste this code:
```typescript
import {$log, ServerLoader} from "@tsed/common";
import {Server} from "./Server";

async function bootstrap() {
  try {
    $log.debug("Start server...");
    const server = await ServerLoader.bootstrap(Server);

    await server.listen();
    $log.debug("Server initialized");
  } catch (er) {
    $log.error(er);
  }
}

bootstrap();
```

It should solve your problem. 

See you
Romain

**Comment by Romakita** [comment]
https://tsed.io/getting-started.html#create-your-express-server

**Comment by jpramondon** [comment]
Thank you very much for your time and answer @Romakita.

For now, with the sample code I provided, the server starts ok and serves the single registered route on "/_health" properly. But then, later, when I'm calling the `unleash` function to register new controllers, nothing new happens and calls on new routes returns a 404.

I'm updating my code with yours and let you know.
Thanks again.

**Comment by jpramondon** [comment]
I just came to realize my example is missing something :D
I'm actually doing a `server.start()` later on in some code I did not bother to share with you ...
Anyway, to make things clearer, I'm updating to your way of initializing the server and get back to you.

**Comment by Romakita** [comment]
Hoo ok. The right way to register routes manually is to use the hooks server:

```typescript
@ServerSettings({
    rootDir,
    logger: { level: "debug" },
    mount: {
        '/': `${rootDir}/controllers/HealthController.ts`
    },
    swagger: ([{ path: "/spec", outFile: path.resolve(rootDir, "./swagger.json") }]),
    acceptMimes: ["application/json"]
})
export class Server extends ServerLoader {
    
    public $beforeRoutesInit(): Promise<void> {
        // add your routes /coontroller here
    }

}
```

**Comment by jpramondon** [comment]
We're getting close ! Thank you.
But isn't the `$beforeRoutesInit` function only executed once, at the server startup ?
What if the server is already started and serving some routes ? What should I call on the server instance to have the new routes registered ? Something like `runLifecycle` ?
Or maybe my way of registering new routes is not the right one ? `this.addControllers('/', `${rootDir}/controllers/MyLateRegisteringController.ts`);`

I'm pretty sure now I haven't been clear on what I'm trying to achieve :smile: 
I started a server with a single route. Once started, I'm trying to add new controllers.
I should have put it this way from the start ... sorry.

Thanks again for your time. Really appreciated.

**Comment by Romakita** [comment]
Normally you should use the @ServerSettings decorator to add a controller but it's also possible to doing that with the .addController() until you haven't started the server with `.listen()`. `runLifecycle()` is the  method called by `listen()` and it invoke all events described here (https://tsed.io/docs/hooks.html). 
Once this method is ran, it's impossible to add manually controllers without using hooks.

```
@ServerSettings({
    rootDir,
    logger: { level: "debug" },
    mount: {
        '/': [
          `${rootDir}/controllers/HealthController.ts`,
          `${rootDir}/controllers/MyLateRegisteringController.ts` // the right way import controller
         MyLateRegisteringController // or by his class
        ]
    },
    swagger: ([{ path: "/spec", outFile: path.resolve(rootDir, "./swagger.json") }]),
    acceptMimes: ["application/json"]
})
export class Server extends ServerLoader {
    $beforeRoutesInit() {
       // it also possible to add controller
    }
}

// Other way
async function bootstrap() {
  try {
    $log.debug("Start server...");
    const server = await ServerLoader.bootstrap(Server);
    server.addController('/', MyCtrl) // it also possible here
    await server.listen();
    // server.addController('/', MyCtrl) // here is to late
    $log.debug("Server initialized");
  } catch (er) {
    $log.error(er);
  }
}

bootstrap();
```

By I don't understand why you have to register you endpoint later ? Is for manager route order  (already described in my example) or other something ?

See you
Romain

**Comment by jpramondon** [comment]
Thanks again for your help. The explanation could not be clearer :+1: 

The idea was to register controllers only after sanity checks had been performed. After struggling for a couple of hours, I had the feeling Tsed was simply not designed to work like this (so already had a plan B in mind), this is why I filed the issue originally, and you just confirmed that.

So change of plan and design. I have registered all my routes just as before in the server settings, started the server, and added a middleware that acts as a latch and tells whether the routes should be served or not (depending on these infamous sanity checks).

Keep up the great work !

Cheers,

Jerome

**Comment by Romakita** [comment]
You can perform sanity check before loading route and throw error by using a service (maybe):

```typescript
@Module()
export class SanityCheckModule {
  $afterInit() {
     // this hook is called just before $beforeRoutesInit
    if (!ok) {
       throw new SanityCheckError() // will stop the server loading
    }
  }
}
```
> Then import your module with an ES6 "import "./SanityCheckModule"

I don't know if this solution solve your issue ^^

See you
Romain
