### ISSUE TITLE
[BUG] (web/Documentation) controllers/Middleware call sequence

### ISSUE THREAD

**Issue by d0whc3r** [TypedProject/tsed#768]
## Information

- **Version:** 5.x
- Packages: documentation tsed.io web

In web tsed.io, in https://tsed.io/docs/middlewares.html#call-sequences there is an image (https://tsed.io/assets/img/middleware-call-sequence.9d80cf70.svg), in this image there are two blocks with the same text, in "Endpoints" section "UseAfter middlewares" I supose that 1 should be UseAfterEach

**Comment by d0whc3r** [comment]
Also, another bug in documentation, the urls https://tsed.io/docs/request-data-persistence.html and https://tsed.io/docs/hooks.html haven't the left drawer menu

**Comment by Romakita** [comment]
Fixed :)
Thanks for your feedback @d0whc3r ;)
