### ISSUE TITLE
[QUESTION] Unit test with @Next decorator

### ISSUE THREAD

**Issue by Madrity** [TypedProject/tsed#769]
Hello,

I want to test one of my controller's function who use Next decorator

//simplified
`public myFunction(@Next() next: Express.NextFunction): Promise<void> {
    next();
}`

I tried to use sinon.spy() but the Type not matched Express.NextFunction.
I tried to create Express.NextFunction, but got an error "next() is not a function"

Anybody have already do this ?

Thx.

**Comment by Romakita** [comment]
Try this:
```
myFunction (mySpy as any)
```
