### ISSUE TITLE
[QUESTION] Nested objects params in Swagger

### ISSUE THREAD

**Issue by RickStanley** [TypedProject/tsed#774]
Hello, is it possible to nest objectes in Swagger with decorators?

Works if it's left alone as: `@BodyParams("campos", EnvioCampoConteudo) campos: EnvioCampoConteudo[]`
![image](https://user-images.githubusercontent.com/23178554/75571729-22fa9900-5a30-11ea-9c8c-3910c00ec44e.png)`

But doesn't work if the endpoint has more fields like:
```
    @HeaderParams("x-cliente-token") token: string,
    @MultipartFile("midia") midia: Express.Multer.File,
    @MultipartFile("midia_thumbnail") midia_thumb: Express.Multer.File,
    @BodyParams("form_id") form_id: number,
    @BodyParams("evento_id") evento_id: number,
    @BodyParams("campos", EnvioCampoConteudo) campos: EnvioCampoConteudo[] ← I want this as an array of objects payload
```
![image](https://user-images.githubusercontent.com/23178554/75571960-a0260e00-5a30-11ea-8467-2a5b8a53a796.png)

It is set as a string.

**Comment by RickStanley** [comment]
Changing to `@BodyParams(EnvioCampoConteudo) campos: EnvioCampoConteudo[]`, doesn't work (as expected?)
![image](https://user-images.githubusercontent.com/23178554/75572608-7d482980-5a31-11ea-9e5b-fa2efe725d21.png)

**Comment by RickStanley** [comment]
For reference, my model is simple:

```typescript
@Entity()
export class EnvioCampoConteudo extends BaseEntity {

  @PrimaryGeneratedColumn()
  _id: number;

  @Column()
  @Property()
  @Required()
  conteudo: string; // this is what I need from deserialization

  @ManyToOne(type => Envio, envio => envio.conteudos)
  envio: Envio;

  @ManyToOne(type => Campo)
  campo: Campo;

}
```

**Comment by Romakita** [comment]
Hello @RickStanley 
Swagger 2.0 doesn't allow schema usage when the payload is a formData: 
https://swagger.io/docs/specification/2-0/describing-parameters/#form-parameters
