### ISSUE TITLE
[BUG] Class constructor ValidationErrorMiddleware cannot be invoked without 'new'

### ISSUE THREAD

**Issue by lucasdidur** [TypedProject/tsed#779]
## Information

- **Version:** 5.x
- Packages: https://github.com/TypedProject/tsed/tree/production/packages/mongoose

Just use a POST to create a new Calendar

	[2020-03-14T16:18:00.543] [ERROR] [TSED] - {
	  method: 'POST',
	  url: '/rest/calendars/',
	  headers: {
		'content-type': 'application/javascript',
		'user-agent': 'PostmanRuntime/7.23.0',
		accept: '*/*',
		'cache-control': 'no-cache',
		'postman-token': 'edf31f26-2dd4-40fc-80ec-186295162ef1',
		host: '127.0.0.1:8000',
		'accept-encoding': 'gzip, deflate, br',
		'content-length': '19',
		connection: 'keep-alive'
	  },
	  body: undefined,
	  query: {},
	  params: {},
	  reqId: '3088e863b95d4b54a84cc90b4ada0ebb',
	  time: 2020-03-14T19:18:00.543Z,
	  duration: 13,
	  error: {
		status: 500,
		message: "Class constructor ValidationErrorMiddleware cannot be invoked without 'new'",
		stack: "TypeError: Class constructor ValidationErrorMiddleware cannot be invoked without 'new'\n" +
		  '    at Layer.handle [as handle_request] (C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
		  '    at trim_prefix (C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\index.js:317:13)\n' +
		  '    at C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\index.js:284:7\n' +
		  '    at Function.process_params (C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\index.js:335:12)\n' +
		  '    at next (C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\index.js:275:10)\n' +
		  '    at C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\index.js:635:15\n' +
		  '    at next (C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\index.js:260:14)\n' +
		  '    at Function.handle (C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\index.js:174:3)\n' +
		  '    at router (C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\index.js:47:12)\n' +
		  '    at Layer.handle [as handle_request] (C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\layer.js:95:5)\n' +
		  '    at trim_prefix (C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\index.js:317:13)\n' +
		  '    at C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\index.js:284:7\n' +
		  '    at Function.process_params (C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\index.js:335:12)\n' +
		  '    at next (C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\index.js:275:10)\n' +
		  '    at urlencodedParser (C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\body-parser\\lib\\types\\urlencoded.js:100:7)\n' +
		  '    at Layer.handle [as handle_request] (C:\\Users\\ldidu\\IdeaProjects\\tsed-example-mongoose\\node_modules\\express\\lib\\router\\layer.js:95:5)',
		origin: undefined
	  }
	}

**Comment by Romakita** [comment]
Ok I'll test that :)

**Comment by Romakita** [comment]
The undefined value on the body is a bit strange XD

**Comment by lucasdidur** [comment]
I thought about it too, this is my body

	{
		"name": "Nome",
		"owner": "Lucas"
	}
