### ISSUE TITLE
[Question] Dynamic response status code, headers, redirects, templates etc. — howto?

### ISSUE THREAD

**Issue by aristofun** [TypedProject/tsed#780]
Didn't find anything in the docs&tutorials — what is the right way to dynamically at runtime set result status code, http headers, redirects or template to render inside controller action?

Like you do in rails etc.?

**Comment by Romakita** [comment]
Hello @aristofun 

You just have to inject response as following:

```typescript
@Get('/')
getMethod(@Res() res: Res) {

  res.status(201)
  res.set('Content-Type', '')

  // etc... 
}
```
