### ISSUE TITLE
[BUG] storage._handleFile is not a function

### ISSUE THREAD

**Issue by thanhchuongitc** [TypedProject/tsed#781]
#Information

- **Version:** 5.x
- Packages: 
"@types/multer": "^1.3.9",
"@tsed/multipartfiles": "^5.41.2",
"multer": "1.4.2",

I set option @ServerSetings  
```
    {
        multer: {
        storage: handleStorage(),
    }
```
With handleStore function will return multer.StorageEngine, but I when upload is error and crash node

**Comment by Romakita** [comment]
Hello @thanhchuongitc 
Can you give a repository with a reproductible example please.
I haven't enough information to reproduct your problem.

See you
Romain

**Comment by chiqui3d** [comment]
The same thing happened to me, I had to pass the storage function directly to the controller, because as a global function it doesn't work. I guess it should be fixed, while you can do it on the controller:

```ts
import { MulterOptions, MultipartFile } from '@tsed/multipartfiles'
import { diskStorage } from 'multer';

const storage = diskStorage({
  destination: function (req, file, cb) {
    cb(null, './public/uploads/profiles')
  },
  filename: function (req, file, cb) {
    cb(null, file.originalname)
  }
});

  @Post('/upload/:id')
  @Description('Upload image profile by user ID')
  @MulterOptions({ dest: './public/uploads/profiles', storage: storage })
  async upload (@MultipartFile('image') image, @PathParams('id') id): Promise<any> {
    const user = await this.userRepository.findOne(id);
    if (!user) {
      throw new NotFound('Not user found')
    }
    user.image = '/uploads/profiles/' + image.originalname;
    return this.userRepository.save(user);
 
  }
```

**Comment by thanhchuongitc** [comment]
> The same thing happened to me, I had to pass the storage function directly to the controller, because as a global function it doesn't work. I guess it should be fixed, while you can do it on the controller:
> 
> ```ts
> import { MulterOptions, MultipartFile } from '@tsed/multipartfiles'
> import { diskStorage } from 'multer';
> 
> const storage = diskStorage({
>   destination: function (req, file, cb) {
>     cb(null, './public/uploads/profiles')
>   },
>   filename: function (req, file, cb) {
>     cb(null, file.originalname)
>   }
> });
> 
>   @Post('/upload/:id')
>   @Description('Upload image profile by user ID')
>   @MulterOptions({ storage: storage })
>   async upload (@MultipartFile('image') image, @PathParams('id') id): Promise<any> {
>     const user = await this.userRepository.findOne(id);
>     if (!user) {
>       throw new NotFound('Not user found')
>     }
>     user.image = '/uploads/profiles/' + image.originalname;
>     return this.userRepository.save(user);
>  
>   }
> ```

Thank you, I fixed it

**Comment by Romakita** [comment]
I keep this issue open. I'll fix this ASAP

**Comment by Romakita** [comment]
Fixed :)
