### ISSUE TITLE
[BUG] AJV Validation take null value

### ISSUE THREAD

**Issue by amourlanne** [TypedProject/tsed#782]
## Information

- **Version:** 5.44.9
- Packages: @tsed/ajv

I send POST request with json data corresponding to my User model. 

```json
{
    "username": "amourlanne",
    "fullName": "Alexis Mourlanne",
    "email": "alexis.mourlanne@github.com",
    "gender": "male"
}
```
Controller
```js
import {BodyParams, Controller, Post} from "@tsed/common";
import {User} from "../Entities/User";

@Controller("/users")
export class UserController {
  
  @Post("/")
  private async create(@BodyParams() user: User): Promise<User> {
    return user;
  }
}
```
Model
```js
import {Entity, Column, PrimaryGeneratedColumn} from "typeorm";
import {Email, Enum, MaxLength, MinLength, Property, Required} from "@tsed/common";

import {GenderEnum} from "../Enums/GenderEnum";

@Entity("users")
export class User {

  @Property()
  @PrimaryGeneratedColumn()
  id: number;

  @Required()
  @MaxLength(20)
  @MinLength(3)
  @Column()
  username: string;

  @Required()
  @Column()
  fullName: string;

  @Email()
  @Required()
  @Column()
  email: string;

  @Required()
  @Enum(GenderEnum)
  @Column({
    type: 'enum',
    enum: GenderEnum,
  })
  gender: GenderEnum;
}
```
But AJV validation throw an error, he detect null value. 

```AJV_VALIDATION_ERROR: At User.username, value '' should be string```

The @BodyParams decorator without the User model type work great.

You can have access to my repository https://github.com/amourlanne/express-tsed-boilerplate.
I think i do something wrong. When you have time, can you take a look on my issue.

**Comment by Romakita** [comment]
Hello @amourlanne 
I check your boilerplate ;)
Thanks

**Comment by Romakita** [comment]
Hello @amourlanne 
I tested your boilerplate, sent a request with the same payload with swagger-ui, and it works XD.

<img width="1422" alt="Capture d’écran 2020-03-20 à 18 36 53" src="https://user-images.githubusercontent.com/1763311/77190592-d4de3000-6ad9-11ea-88d6-c9ab19984998.png">

Have you tested with swagger-ui or postman ?

See you
Romain

**Comment by amourlanne** [comment]
I tested with postman.
But i have upgrade all @tsed packages to version 5.44.10 and that works. thank you a lot ! ;)
