### ISSUE TITLE
[QUESTION] Listen on UNIX socket

### ISSUE THREAD

**Issue by AmeBitto** [TypedProject/tsed#784]
It is possible to run tsed on UNIX socket?

**Comment by Romakita** [comment]
Hello @AmeBitto 
I don't know. I never use Unix socket. What is it ? and what do you want  to do with Ts.ED? 
See you
Romain

**Comment by AmeBitto** [comment]
Hello @Romakita 
Thank you for you reply! I want to make something similar:
```javascript
var express = require('express')
var app = express()
app.listen('/tmp/sock')
```
This code from Express official documentatin - https://expressjs.com/sk/api.html

> Starts a UNIX socket and listens for connections on the given path. This method is identical to Node’s http.Server.listen().

**Comment by Romakita** [comment]
Haaa ok. 
You can give the path to httpPort maybe :) it accept a string.
