### ISSUE TITLE
[QUESTION] Custom param decorators

### ISSUE THREAD

**Issue by IARKI** [TypedProject/tsed#785]
Is there any way to create custom param decorators? I didn't find any examples 
I want to implement a decorator @User that will return a current user after endpoint passes Auth middleware

**Comment by Romakita** [comment]
Hello @IARKI 

With the new CLI it's possible to generate a param decorator :) `tsed g decorator` (npm i -g @tsed/cli@beta)

For your question, here the code:
```
import {Req} from "@tsed/common";

export function ReqUser(): ParameterDecorator {
  return applyDecorators(
   Req('user') // if the user is attached to request (req.user)
  );
}
```
See you,
Romain
