### ISSUE TITLE
[BUG] INJECTION_ERROR: Unable to inject dependency. Given token is undefined.

### ISSUE THREAD

**Issue by NachtRitter** [TypedProject/tsed#786]
## Information

- **Version:** 5.44.12
- Packages:  only that packages that are installed by @tsed/cli during project initialization

I'm faced with an injection error issue when 2 services inject each other.

## Example

```typescript
// src/services/OrdersService.ts
import { Service } from '@tsed/common';

import { PaymentsService } from './PaymentsService';

@Service()
export class OrdersService {
  constructor(private paymentsService: PaymentsService) {
  }
}

// src/services/PaymentsService.ts
import { Service } from '@tsed/common';

import { OrdersService } from './OrdersService';

@Service()
export class PaymentsService {
  constructor(private ordersService: OrdersService) {
  }
}

```

**Comment by Romakita** [comment]
Hello,
Circular reference cannot be resolved by injector. Isn’t a bug but a limitation from typescript and is a bad conception pattern if you have that. 

I encourage you to refactor your code to avoid this circular reference ;). I think it’s always possible to develop application without circular ref.

See you

**Comment by NachtRitter** [comment]
@Romakita thanks. I know that it's caused by circular reference.
I'd like to implement app architecture like: Controller -> Service -> Repository with oner entity repository per service pattern. So, what's why I'd like to inject e.g. PaymentsService to OrdersService rather than PaymentsRepository to OrdersService.

**Comment by Romakita** [comment]
But if you haven't another choices:
```typescript
// src/services/OrdersService.ts
import { Service } from '@tsed/common';

import { PaymentsService } from './PaymentsService';

@Service()
export class OrdersService {
  private paymentsService: PaymentsService
  
  @Inject()
  injector: InjectorService;
 
  $onInit() {
     this.paymentsService = this.injector.get<PaymentsService>(PaymentsService)
  }  
}

// src/services/PaymentsService.ts
import { Service } from '@tsed/common';

import { OrdersService } from './OrdersService';

@Service()
export class PaymentsService {
  constructor(private ordersService: OrdersService) {
  }
}
```

Try it :)

**Comment by NachtRitter** [comment]
@Romakita thanks a lot!
Your solution works fine!

**Comment by NachtRitter** [comment]
@Romakita 
btw, I also use `$afterRoutesInit` lifecycle hook to make some interactions with TypeORM as described in [docs.](https://tsed.io/tutorials/typeorm.html#typeormservice).
So, Can I use injector from your example above in `$afterRoutesInit` instead of `$onInit`?
Is it correct? What the best purposes to use `$onInit` and `$afterRoutesInit`?
Thanks!

**Comment by Romakita** [comment]
Yes you can. The injector is available during all lifecycle hooks used on the you services :)
