### ISSUE TITLE
[QUESTION] Deep Population with Schema

### ISSUE THREAD

**Issue by IARKI** [TypedProject/tsed#791]
Hi 
I have next models
```
@Schema()
export class ReviewSchema {
    @Ref(UserModel)
    user: Ref<UserModel>;

    @Property()
    comment: string;

    @Property()
    rating: number;
}

@Model({name: 'Product'})
export class Product {
    @Property()
    title: string;

    @Property()
    reviews: ReviewSchema[];
}
```
So all reviews will be saved under Product doc instead of having a different collection in database
Is it possible to populate `user` while doing query for Product.
I tried it in different ways, but it seems like it doesn't work

**Comment by Romakita** [comment]
Hello @IARKI,

I think you’ve missed to use @PropertyType decorator on reviews.

´´´typescript
@Model({name: 'Product'})
export class Product {
    @Property()
    title: string;

    @PropertyType(ReviewSchema)
    reviews: ReviewSchema[];
}
´´´

**Comment by IARKI** [comment]
Thanks. It worked.
