### ISSUE TITLE
[QUESTION] Is it possible to use some components without initialize the Ts.ED server?

### ISSUE THREAD

**Issue by codyrin93** [TypedProject/tsed#796]
I want to use [ConverterService.deserialize()](https://github.com/TypedProject/tsed/blob/v5.44.17/packages/common/src/converters/services/ConverterService.ts#147) to deserialize JSON object with AJV validation in my use case. 

My current workaround is starting the singleton Ts.ED server:
```typescript
class TsedServer extends ServerLoader {
    private static instance: TsedServer;

    public static getInstance(): TsedServer {
        // start server and get server instance here
    }
}
```
And then get the server instance's `ConverterService` in my utility class:
```typescript
let deserialize = <T extends MyModel>(
    model: object,
    modelClass: Clazz<T>
): T => {
    let converter: ConverterService | undefined = TsedServer.getInstance()
        .injector
        .get<ConverterService>(ConverterService);

    if (_.isUndefined(converter)) {
        throw new Error("ConverterService not initialized");
    }

    return converter.deserialize(model, modelClass);
};
```
Since I have adopted the [decorators](https://tsed.io/tutorials/ajv.html#decorators) to my model classes. I hope to reuse some features provided by Ts.ED instead of writing another codes for validating model with those decorators.

In general, is there any workaround to get those components (not only ConverterService) without starting Ts.ED server? Thanks.

**Comment by Romakita** [comment]
Hello @codyrin93 
Yes it's possible by creating your own injector instance. But the class used with this decorator will be run in a seperated container from the server. 

```typescript
import {Type} from "@tsed/core";
import {createInjector, ConverterModule, ConverterService} from "@tsed/common";

const injector = createInjector();

injector.invoke(ConvertModule);

export deserialize<T extends Model>(obj: any, useType: Type<T>): T {
   return injector.get<ConverterService>(ConverterService)!.deserialize(obj, useType);
}
```
Test it and tell me if it works :)

See you
Romain

**Comment by codyrin93** [comment]
it does not work for me.
`injector.get<ConverterService>(ConverterService)` return `undefined`

**Comment by codyrin93** [comment]
Hi @Romakita 

It does not work for me.
`injector.get<ConverterService>(ConverterService)` return `undefined`

I also wonder where can I find the module need to be invoked in `injector.invoke()` as I cannot find the injectables' belonging module.

**Comment by Romakita** [comment]
Hello @codyrin93 
You are on which version of @tsed/common package?

**Comment by codyrin93** [comment]
@Romakita 
I am using version 5.44.17

**Comment by Romakita** [comment]
Ok maybe a forgot to export ConvertModule.

Try this
```
import {Type} from "@tsed/core";
import {createInjector, ConverterService} from "@tsed/common";

const injector = createInjector();

injector.invoke(ConverterService);

export deserialize<T extends Model>(obj: any, useType: Type<T>): T {
   return injector.get<ConverterService>(ConverterService)!.deserialize(obj, useType);
}
```

**Comment by codyrin93** [comment]
Thanks @Romakita . It works now.
