### ISSUE TITLE
[QUESTION] How to mock service when testing with supertest

### ISSUE THREAD

**Issue by marghidanu** [TypedProject/tsed#797]
Hello, 

How can I mock a service when using supertest. I'm guessing I need to mock the service before the `TestContext.bootstrap()`? If so, how can this be done?

**Comment by angusmunro** [comment]
Hi here is an example with jest that works for me.

`
let request: SuperTest.SuperTest<SuperTest.Test>;
let cacheMock: jest.Mock;

  beforeAll(TestContext.bootstrap(Server));
  beforeAll((TestContext.inject([ExpressApplication, ServiceToMock], async (expressApplication: ExpressApplication, serviceToMock: ServiceToMock) => {
    request = SuperTest(expressApplication);
    cacheMock = jest.fn();
    cacheService.set = cacheMock;
  })));

  afterAll(() => {
    cacheMock.mockRestore();
    TestContext.reset();
  });`

**Comment by Romakita** [comment]
If you use mocha, you can use Sinon to mock something :)
