### ISSUE TITLE
[BUG] ConverterService deserialize string value returns object

### ISSUE THREAD

**Issue by codyrin93** [TypedProject/tsed#800]
## Information

- **Version:** 5.44.17
- Packages: @tsed/common

ConverterService deserialize object to a Class with string field will return object value but not a string.

## Example Mocha test:

```typescript
import {ConverterService, createInjector, Default, PropertyType} from "@tsed/common";

describe("ConverterService", function () {

    it('should convent model', function () {
        class Model {
            @Default("foo")
            @PropertyType(String)
            public readonly foo: string = "foo";
        }

        const injector = createInjector();
        injector.invoke(ConverterService);
        let converter: ConverterService = injector!.get<ConverterService>(ConverterService)!;

        let obj = {foo: "bar"};
        let result = converter.deserialize(obj, Model);

        console.log(typeof result.foo); // object
        console.log(result.foo); // [String: ''] { '0': 'b', '1': 'a', '2': 'r' }
        console.log(typeof obj.foo); // string
        console.log(obj.foo); // bar
    });
});
```
`result.foo` should be a string `"bar"` but not a object `{ '0': 'b', '1': 'a', '2': 'r' }`
It does not deserialize string field correctly even I dismiss `@PropertyType(String)` in class field.

## Acceptance criteria

- [ ] corresponding string field should be deserialized to string value

**Comment by Romakita** [comment]
@codyrin93 Thanks a lot for the given reproductible error. I'll fix that ASAP :)

**Comment by codyrin93** [comment]
@Romakita 

Just some extra findings.
I found that the ConverterService instance get from initialized Ts.ED server instance works fine:

```typescript
    it('should deserialize plain obj to model', async function () {
        @ServerSettings({})
        class TsedServer extends ServerLoader {}

        let server = await (ServerLoader.bootstrap(TsedServer, {}));
        let converter: ConverterService = server
            .injector
            .get<ConverterService>(ConverterService)!;

        let obj = {foo: "bar"};
        let result = converter.deserialize(obj, Model);

        console.log(typeof result.foo); // string
        console.log(result.foo); // bar
        console.log(typeof obj.foo); // string
        console.log(obj.foo); // bar
    });
```
But the server instance has no any configuration. The instance get from injector without starting the server should behave the same as the one get from server. (Suppose both instance should use the default configuration)

**Comment by Hadard753** [comment]
+1

**Comment by Romakita** [comment]
@Hadard753  Yes I found this issue also. For me, It's due to the difference with between `@tsed/common` and `@tsed/testing`. Check in your package.json if the versions are the same.

A fix is on going :)

@codyrin93 This bug is fixed for your  usecase :)
