### ISSUE TITLE
[BUG] Cast error on GET request with body params

### ISSUE THREAD

**Issue by robertwestbury** [TypedProject/tsed#801]
## Information

- **Version:** "5.44.17

I have this really, really weird error with a get request. I have this code here:
```ts
  @Get('/:form')
  get(@PathParams('form') form: string) {
    return 'hi';
  }
```
And whenever I make the request, I get this error: `Cast error. Expression value is not a number.`. Other GET requests with path params work fine, and very weirdly this doesn't error:

```ts
  @Get('/:form/a')
  get(@PathParams('form') form: string) {
    return 'hi';
  }
```

I've been struggling with this for hours now so if anyone can help that would be amazing.

**Comment by Romakita** [comment]
Hello @robertwestbury 
Unfortunately, I haven't reproduced the bug. Maybe an access to your repo can help me (or a small repo with the reproducible error).

See you
Romain

**Comment by robertwestbury** [comment]
I figured it out - it's because there was another route above it that had the same "route" without the wildcard (e.g. /hello and /:name can both be matched). Maybe load the functions in the order they're defined in the class like nestjs does?

**Comment by robertwestbury** [comment]
Nevermind - it's not.

**Comment by robertwestbury** [comment]
I have not been able to produce a reproducible example, but I would be happy to show you my code or hop into a call if that would be helpful. I have been stuck on this for days now and I'm getting pretty frustrated. @Romakita

**Comment by Romakita** [comment]
@robertwestbury Yes. You can send me an invitation to your repository and review the code. You can add also a comment to figure out the code where the problem is ;)
A call can be planed next week if it's better for you, but an access to your repo will be enough to understand your  problem and propose a fix if it's necessary :)

Romain

**Comment by robertwestbury** [comment]
I will not be able to share the code, but if we can call that would be perfect

**Comment by chiqui3d** [comment]
I hope I can help: Look at this example that works perfectly for me.

```ts
import {Controller, Get, PathParams, ReturnType} from '@tsed/common'
import { UserRepository } from '@src/Repository/UserRepository ';
import { NotFound } from 'ts-httpexceptions'
import {UserDTO} from "@src/DTO/UserDTO"

@Controller('/users')
export class UserController {

    constructor(private userepository: UserRepository ) {
    }

    @Get('/:id(\\d+)')
    @ReturnType({type: UserDTO})
    async check (@PathParams('id') id: string): Promise<UserDTO> {
        const user = await this.userRepository.findOne(id);
        if (!user) {
            throw new NotFound('Not user found')
        }

        return user;
    }
    @Get('/hello$')
    hello (): string {
        return 'Hi! TS.ED';
    }
    @Get('/:id/form')
     form (@PathParams('id') id: string): string {
       return id
    }

}
```

https://expressjs.com/en/guide/routing.html
https://tsed.io/docs/controllers.html#routes-order

**Comment by Romakita** [comment]
@robertwestbury When are you available?
