### ISSUE TITLE
[BUG] Controller returns array as object and receive string param as object

### ISSUE THREAD

**Issue by Hadard753** [TypedProject/tsed#805]
## Information

- **Version:** 5.47.0
- Packages: common

A few sentences describing the overall goals of the issue.
When receiving a QueryParams or PathParams of type string in a controller endpoint a weird object 'array like' is received for example instead the string "abc" an object looks like {0: 'a', 1: 'b', 2: 'c'}.
I managed to works around this by setting the type of the parameter to any instead string or by
 switching back to version 5.44.13 which seems to resolved this issue but  it caused another issue:
when controller endpoint suppose to return an array it returns an object for example instead of ['a','b','c'] it returns {0: 'a', 1: 'b', 2: 'c'} which can also be resolved by injecting the @Res and use res.json to return the response.
and I can't find a version in which both of this works in a stable way it always either or

## Example
```typescript
  @Get('/:scope/:scopeId')
  async getByScopeId(@PathParams('scope') scope: string) {
    //Here scope will be {0: 'a', 1: 'b', 2: 'c'} instead of 'abc' in version 5.47.0
  }
  @Get('/:scope/:scopeId')
  async getByScopeId(@PathParams('scope') scope: any) {
    //This way it works in version 5.47.0
  }

 @Post('/:scope/:scopeId')
  async updateAllScopeSettings(
    @PathParams('scope') scope: string,
  ): Promise<any[]> {
//Here the function will return  {0: 'a', 1: 'b', 2: 'c'} instead of ['a','b','c']  in version 5.44.13
    return await this.dataAccess.updateByScopeId(scope);
  }

 @Post('/:scope/:scopeId')
  async updateAllScopeSettings(
    @PathParams('scope') scope: string,
@Res response:any
  ): Promise<any[]> {
//This way it works  in version 5.44.13
    return response.json(await this.dataAccess.updateByScopeId(scope));
  }
```
## Acceptance criteria

- [ ] Criteria 1

**Comment by Romakita** [comment]
Hello @Hadard753 
I'll try to reproduce your problem a release a fix :)

**Comment by Romakita** [comment]
Hello @Hadard753 
I added a project  with your given usecases here https://github.com/Romakita/tsed-issue-805
Unfortunately, everything works fine. Can checkout this project, try it. 

if it's works also for you, it's probably a problem with your Server/project configuration. In this case, try to reproduce  the same configuration to reproduce the bug. When it's done, create a PR on this repository :)

See you :)

**Comment by Romakita** [comment]
Hello @Hadard753 
I think the problem come from the package.json and the tsed versions added to it.

Can check your package.json please and check all "@tsed/*" version. You have to set the same version for all package. :)

See you

**Comment by Hadard753** [comment]
Thanks for all your help if anyone else will bump into it in the future the only thing solved the problem for me was to set the version to 5.44.13
