### ISSUE TITLE
[QUESTION] How to override controller's endpoint in child controller?

### ISSUE THREAD

**Issue by xrip** [TypedProject/tsed#811]
Hello!

I've got a trouble. Having two controllers 

MainCtrl.ts
```ts
@Controller('/main')
export class MainCtrl {
    async bootstrap(): Promise<any> {
        return { hello: 'world' };
    }

    @Get('/')
    async mainIndex(): Promise<any> {
        return {
            ...await this.bootstrap(),
            foo: 'bar',
        };
    }
}
```

and ChildCtrl.ts
```ts
@Controller('/child/')
export class ChildCtrl extends MainCtrl {
    @Get('/')
    async childIndex(QueryParams('page') page: number = 0): Promise<any> {
        return {
            ...await this.bootstrap(),
            buz: 'baz',
        };
    }
}
```

When i access ``` /main/ ``` i get ```JSON { hello: 'world', foo: 'bar' } ```
When i access ``` /child/ ``` i SHOULD get ```JSON { hello: 'world', buz: 'baz' } ```
but i GET  ```JSON { hello: 'world', foo: 'bar' }``` - return of mainIndex() method from MainCtrl
 is there any way to fix it?

**Comment by xrip** [comment]
Found temporary solution
Change ChildCtrl from ```@Controller('/child/') @Get('/') ``` to ```@Controller('/') @Get('/child/')``` 
but looking for more elegant way

**Comment by chiqui3d** [comment]
I don't think there's a elegant way, when you use parent controllers with routes.

**Comment by xrip** [comment]
Another solution is to make an abstract Ctrl class that contains bootstrap method which is extended by MainCtrl and ChildCtrl
