### ISSUE TITLE
[QUESTION] @tsed/common JSON schema generation for PropertyType

### ISSUE THREAD

**Issue by boyko** [TypedProject/tsed#812]
First let me thank you for this great project! 
I am struggling to understand the JSON schema generation behaviour. When using a class for a model property that extends other classes. The generated JSON schema only includes the properties defined directly on the class but not
the inherited properties. The following test fails because the `name` property is missing from M2 in the definitions. Is this the expected behaviour?

```ts
import { inject, TestContext } from "@tsed/testing";
import { JsonSchemesService, Property } from "@tsed/common";

class M1 {
  @Property()
  public name: string;
}

class M2 extends M1 {
  @Property()
  public age: number;
}

class M3 {
  @Property()
  public nested: M2;
}

describe("JsonSchemesService", () => {
  describe("use case: nested model property", () => {
    after(TestContext.reset);
    it("should return a schema with his definitions",  inject(
      [JsonSchemesService],
      (service: JsonSchemesService) => {
        // GIVEN
        const result = service.getSchemaDefinition(M3);
        console.log(result);
        // WHEN
        expect(result).to.deep.equal({
          definitions: {
            M2: {
              properties: {
                age: {
                  type: "number"
                },
                name: {
                  type: "string"
                }
              },
              type: "object"
            }
          },
          properties: {
            nested: {
              $ref: "#/definitions/M2"
            }
          },
          type: "object"
        });
      }
    ));
  });
});
```

**Comment by chiqui3d** [comment]
Check the `@PropertyType(M2)` https://tsed.io/docs/converters.html#validation

**Comment by boyko** [comment]
I did use it, but the result was the same. You have the same result in [JsonSchemesService.spec.ts](https://github.com/TypedProject/tsed/blob/production/packages/common/src/jsonschema/services/JsonSchemesService.spec.ts) where the schema definitions contain a JsonAgeModel schema without the inherited properties.

The JSON schema for M2 (and JsonAgeModel in the specs) is fine on its own. The problem occurs when using M2 or JsonAgeModel as a property of another class (regardless of @PropertyType() usage).

**Comment by Romakita** [comment]
It's strange. Inheritance is supported since a long time by our framework. I've a unit test about this usecase...
