### ISSUE TITLE
[BUG] Email validation does not work

### ISSUE THREAD

**Issue by Chechotkin** [TypedProject/tsed#814]
## Information

- **Version:** 5.49.1
- Packages: common

Email validation in body does not work.

Steps to reproduce:
 - clone https://github.com/TypedProject/tsed-example-session
 - add new class in existing controller :
```javascript
class MyModel {
  @Required()
  @Email()
  @MinLength(5)
  email: string;
}
```
 - add new POST request in existing controller :
```javascript
@Post()
  postWithValidation(@BodyParams() payload: MyModel): any {
    $log.info("Validation passed!", payload);
    return "OK";
  }
```
- npm i
- npm start
- run curl:
```
curl --location --request POST 'http://localhost:8080/rest' \
--header 'Content-Type: application/json' \
--data-raw '{
	"email": "wwww"
	
}'
```
Expected result : error
Actual result: in console - OK, 
in logs - Validation passed! MyModel { email: 'wwww' }

## Acceptance criteria

- [ ] Criteria 1

**Comment by marefati110** [comment]
you can use ```@Format('email')`` .

**Comment by Chechotkin** [comment]
The result is the same with  @Format('email')

**Comment by Romakita** [comment]
Ok. Have you added @tsed/ajv package ? 
The validation is performed by this package :)

Sorry for this confusion, is realize isn't clearly explained in the documentation.

**Comment by Chechotkin** [comment]
Yes
`"dependencies": {
    "@tsed/ajv": "^5.49.1",`

**Comment by Chechotkin** [comment]
`... "ajv": "^6.12.2",...`

**Comment by amourlanne** [comment]
Do yo import it as well ? import "@tsed/ajv";

**Comment by Romakita** [comment]
I create a small repo with working integration test
https://github.com/Romakita/tsed-issue-814

**Comment by Chechotkin** [comment]
It works, but what's the trick?

**Comment by Chechotkin** [comment]
The trick in this:
 'import "@tsed/ajv";'
Thanks ))
