### ISSUE TITLE
[QUESTION] Why do you naming decorator @Controller for path ?

### ISSUE THREAD

**Issue by Overfacto** [TypedProject/tsed#815]
hello, this project is so impressive to me and I think this project can be help improved productivity for Typescript. Cheer your project. 

I have a question about some terminologies like `@Controller`.

Why did not use @Path for api mapping ? is there any something reasons ?

I hate the terminology 'Controller' why that is so ambiguous.
That is maybe originated from Controller of 'MVC pattern'.

Many people use this word as 'API Layer' but Controller of MVC means the layer which has business codes like **Service Layer**.

In my opinion, Spring Framework makes worse this confusions when java was major Programming Language (previous Oracle-Google legal war). That bad influence until nowadays although .

It is reason maybe avoiding confusions why JAX-RS specified `@Path` as API Mapping annotations (decroator in Typescript).

I hope to know you have any something reasons.
If there is no some important reasons, I think It is maybe good following JAX-RS terminologies

**Comment by Romakita** [comment]
Hello @Overfacto,
I think, I won't have a satisfying answer for your question.
Many framework use this terminology to declare a class that is responsible to mapping client request to a service (Nest.js, node-decorators, routing-controllers, etc...). It's really common, and  I guess you already ask this question to the authors of theses frameworks also :)

But I understand this word can be confusing (but your are the first it ask about that). 

Today, Ts.ED use the this term to:
- declare a path and a class which will be mapped with Express routing,
- declare nested controller,
- register the class in the DI as controller (it's a bit different from a pure provider in a Ts.ED sense),
- handle client request,
- return a response.

So, based on theses given sentences, `Controller` word is not bad, I agree not the better, but better than `@Path` which is just responsible to declare a path and cannot be used to summarize the different actions accomplished by the Ts.ED `Controller`.

And right now, I agree, is really easy to use this work to identify the concept when I need explain something in the documentation. But, I'm aware for an alternative which will summarizes correctly this feature.

See you :)

**Comment by Overfacto** [comment]
@Romakita  Ok, I got it. I was surfing about nestjs, and then found they use it too.

I can accept that terminology because of popularity..

I cheer you.
