### ISSUE TITLE
[QUESTION] Switch off AJV validation for extra fields (5.42.0 works - 5.49.2 - don't)

### ISSUE THREAD

**Issue by silveoj** [TypedProject/tsed#817]
I use ```TypeORM``` model (with decorators) for ```AJV``` in ```@BodyParams```:

```
@Entity({
  name: 'MyModel',
})
export class MyModel {
  @PrimaryGeneratedColumn({
    name: 'Id',
    type: 'int',
  })
  @JsonProperty()
  @Example(32)
  public id: number;
}
```
Controller:
```
@BodyParams() model: MyModel,
```
In ```v5.42.0``` I send to backend this model:
```
{
 id: 33,
 myNewProp: 'myNewProp', // I don't describe this prop in MyModel
}
```
It's works. But somewhere in ```v.5.49.1``` - ```5.49.2``` (or earlier) I started to get error:
```
Property myNewProp on class MyModel is not allowed.
```
The same error I get for class without ```TypeORM``` decorators.

I can't find options in AJV to disable this behavior (I remember I saw this option)
My config:
```
options: { verbose: true },
```

What should I change for new versions? Thanks

Also I updated to ```5.50.0``` and I even can't login: server was started but I can't any response.

My current versions:
```
    "@tsed/ajv": "5.49.2", // 5.50.0 for all packages - can't login
    "@tsed/common": "5.49.2",
    "@tsed/core": "5.49.2",
    "@tsed/di": "5.49.2",
    "@tsed/exceptions": "5.49.2",
    "@tsed/multipartfiles": "5.49.2",
    "@tsed/swagger": "5.49.2",
    "@tsed/typeorm": "5.49.2",
    "ajv": "6.12.2", // I tried any versions
```
app.ts imports these packages:
```'@tsed/ajv'```, ```'@tsed/common'```, ```'@tsed/swagger'```, ```'@tsed/typeorm'```.

**Comment by amourlanne** [comment]
Hey, take a look of "additional properties" validation !  https://tsed.io/docs/converters.html#validation

**Comment by silveoj** [comment]
Yes, I already tried it. It works. Thanks a lot.
(I checked some commits and can't find changes in ```additionalProperties``` properties).

But what about ```5.50.0``` version. Can this version have "breaking changes"? Or something wrong on my side? (I can't provide access to out repository)

**Comment by Romakita** [comment]
Hello,

The v5.50.0 shouldn’t have breaking (isn’t the goal) but by introducing pipes feature, maybe I miss something on validation side. Can you describe precisely your problem with v5.50 please

**Comment by Romakita** [comment]
Hello @silveoj 
I found an issue related to the build on v5.50.0. The Ajv provider metadata isn't correctly compiled by typescript. It broke all ajv validation.

The v5.52.1 fix the issue ;)

**Comment by silveoj** [comment]
Thanks. It works with v5.52.1
