### ISSUE TITLE
[QUESTION] How to disable logging other then errors?

### ISSUE THREAD

**Issue by robertwestbury** [TypedProject/tsed#819]
The logging is helpful in development, but in production it can be a bit of a pain. Is there any way I can disable request logs unless their status code is >=500? Many thanks.

**Comment by jellz** [comment]
It looks like you're looking for `logger.logRequest` on [the docs](https://tsed.io/configuration.html#logger)

**Comment by robertwestbury** [comment]
Oops, figured it out last night but thanks for trying to help!
