### ISSUE TITLE
[QUESTION] Import controller from another npm package (lerna monorepo)

### ISSUE THREAD

**Issue by vedranjukic** [TypedProject/tsed#827]
I have a lerna monorepo project and the idea to have separate bootstrap packages (entrypoints) that would import controllers and middlewares from a single package. That would allow each entrypoint to define its own set of express middlewares and configuration options, for example custom auth provider.
From what I understand is that ServerLoader doesn't recognize metadata from imported controller/middleware classes.
When I move those files inside the bootstrap package (the same package where ServerLoader is instantiated) they are correctly detected.
Is there a way to achieve this or am I heading in the wrong direction?

**Comment by Romakita** [comment]
Hello @vedranjukic
You have to import manually your controller on the Server.ts.

```typescript
import {MyController} from "@scope/package"

@Configuration({
   mount: {
     '/rest': [
        MyController
     ]
  }
})
class Server extends ServerLoader {
}
```

Maybe by using `@Module`, it will also possible to doing that but I'm not sure.

```typescript
@Module({
  imports: [MyService], // will work 
  mount: {
    '/rest': [MyController] // not sure if this configuration will work
  }
})
export class MyModule {}
```

```typescript
import "@scope/package" // just import the package. the module will be discover automatically.

@Configuration({})
class Server extends ServerLoader {
}
```
See you
Romain

**Comment by vedranjukic** [comment]
Hi,
thanks for the reply!

I've created a simple example repo where I tried what you've proposed, but both suggestions don't work.

[](https://github.com/vedranjukic/tsed-lerna-example)

**Comment by Romakita** [comment]
@vedranjukic Sorry for this confusion. My example use @Configuration and you mix @ServerSettings and @Configuration. I'll checkout your example and push a PR on  your repo :)

**Comment by vedranjukic** [comment]
PR works, thanks man!
