### ISSUE TITLE
[QUESTION] Performance issue in AWS API Gateway and AWS Lambda

### ISSUE THREAD

**Issue by pradeeptk304** [TypedProject/tsed#831]
Hi,

I am planning to use tsed in AWS Lambda exposed through AWS API Gateway, serverless-framework. The first call to the API(simple, returns hardcoded data) takes more than a second.

So I used webpack to reduce the size of the package but it crashed due to require.extensions in node_modules/@tsed/core/lib/index.js, line number 4. As a hack I used "if (!(require.extensions && require.extensions[".ts"]))" instead to fix the crash. And the performance seems to be improved by half. So seems like webpack helps to reduce the package size and hence improves the performance.

What is the proper way to handle this, as I see comments in previous issues asking not to use webpack?

Thanks,
Pradeep

**Comment by Romakita** [comment]
Bundle the source code won't solve your issue. The code is executed on server side :)

**Comment by Romakita** [comment]
The first call take a long time because the server is bootstrapped inside the aws function. This is maybe not the optimal way, because the componentScan and bootstrap lifecycle take a long time.

Can you try with this code:

```typescript
const promise = ServerLoader.bootstrap(Server);
// The function handler to setup on AWS Lambda console -- the name of this function must match the one configured on AWS
export async function awsHanlder(event: any, context: any) {
  const server = await promise
  const lambdaServer = awsServerlessExpress.createServer(server.expressApp, null, binaryMimeTypes);

  return awsServerlessExpress.proxy(lambdaServer, event, context, 'PROMISE').promise;
}
```

**Comment by pradeeptk** [comment]
Yes, test on require.extensions solved the crash. I am importing the controllers and components manually.

I saw 500ms difference after using webpack. Will try your suggestion and update the ticket.

**Comment by pradeeptk** [comment]
Also createServer inside awsHandler will be called for every single API call as per your example. I avoided it like this

let server;
let lambdaServer;

export async function awsHanlder(event: any, context: any) {
  if (!server || !lambdaServer) {
    server = await ServerLoader.bootstrap(Server);
    lambdaServer = awsServerlessExpress.createServer(
      server.expressApp,
      null,
      binaryMimeTypes
    );
  }

  return awsServerlessExpress.proxy(lambdaServer, event, context, "PROMISE")
    .promise;
}

**Comment by pradeeptk** [comment]
I tried moving ServerLoader.bootstrap(Server) outside the awsHandler and did not see performance improvement. Seems like the solution using webpack works better. Tomorrow I will try to create a branch in the tsed AWS proj with webpack solution.

**Comment by pradeeptk304** [comment]
I am not able to push the webpack related change to aws example repo, I am getting a 403. Could you please help? I am using https.

**Comment by pradeeptk304** [comment]
Any update on this? Will you be able to fix the crash when using web pack?

**Crash location 1**
WARNING in ./node_modules/@tsed/core/lib/index.js 4:5-23
require.extensions is not supported by webpack. Use a loader instead.
 @ ./node_modules/@tsed/common/lib/index.js 4:13-34
 @ ./src/lambda.ts

**Crash location 2**
WARNING in ./node_modules/@tsed/common/lib/platform-builder/utils/cleanGlobPatterns.js 6:12-30
require.extensions is not supported by webpack. Use a loader instead.
 @ ./node_modules/@tsed/common/lib/platform-builder/utils/index.js 6:21-51
 @ ./node_modules/@tsed/common/lib/platform-builder/index.js
 @ ./node_modules/@tsed/common/lib/index.js
 @ ./src/lambda.ts

**Comment by Romakita** [comment]
@pradeeptk304 I totally forgot to give you an access to the repo. 
Invitation is sent. If you can push the project example with webpack, I'll able to fix your issue :)

Thanks for your help
Romain

**Comment by Romakita** [comment]
I need to understand the problem and after I'll able to deploy fix quickly :)

**Comment by Romakita** [comment]
Did you seen this line in Server.ts ? ^^
 // Automatic Import, /!\ doesn't works with webpack/jest, use  require.context() or manual import instead
This is the first problem. With webpack, globpattern doesn't work because your application is not compile is a pure node.js environment.

I'll modify the project example :)

**Comment by Romakita** [comment]
@pradeeptk304  v5.57.4 fix the issue. Thanks for your help with the webpack configuration :)

**Comment by pradeeptk304** [comment]
Thanks, will test the fix today and report back

**Comment by pradeeptk304** [comment]
I see 2 new warning from webpack

```
WARNING in ./node_modules/@tsed/core/lib/index.js 5:10-17
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@tsed/common/lib/index.js
 @ ./src/lambda.ts

WARNING in ./node_modules/@tsed/core/lib/index.js 5:30-37
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@tsed/common/lib/index.js
 @ ./src/lambda.ts
```

**Comment by Romakita** [comment]
Yep it's normal. Webpack see dynamic require usage in code. Don't care about this there is no solution.

Just run the compiled js.

**Comment by pradeeptk304** [comment]
But it is not crashing anymore.
