### ISSUE TITLE
[QUESTION] BAD_REQUEST Property bar on class Foo is not allowed

### ISSUE THREAD

**Issue by KBroichhausen** [TypedProject/tsed#842]
Here is a simplified version of my problem in a much bigger application.

I have frontend which sends a POST-Reuqest with the following body:
`{"fooobject":{"bar":"Hello"}}`

At the backend, I have the following method in a controller:
```
	@Post("/something")
	async saveAFoo(
		@Required() @BodyParams("fooobject") foo: Foo,
		@Response() res: ExpressResponse
	) {
		return res.status(200);
	}
```

The answer is I receive is:
`Property bar on class Foo is not allowed.`

Class Foo is defined as:
```
class Foo {
	bar: string;
}
```

So, stupid question: What is the problem? I have a `Foo `class defined containing `bar `as `string `and sending a matching object, don't I?

As I said, I have a much bigger application and the problem started when upgrading from TSED 5.45.4 (where it is working) to 5.46.0. With the newest version, I got the same results. I checked at which point it stops to work to give you better info.

**Comment by Romakita** [comment]
@KBroichhausen  The property bar is declared on the Foo model ? 
If not, the change about this version is around the strict model option.

if you don't care about additional properties on your model, you can use the new options:
```typescript
import {Configuration} from "@tsed/common";

@Configuration({
  converter: {
    additionalProperties: "error" // default: "error", "accept" | "ignore"
  }
})
export class Server {

}
```
Tell me if it works :)
Romain

**Comment by KBroichhausen** [comment]
Thanks! That's exactly what I meant with "I maybe completely missing a point" ;)
