### ISSUE TITLE
[QUESTION] How to provide Tags in swagger

### ISSUE THREAD

**Issue by pradeeptk304** [TypedProject/tsed#844]
How can I add tags to endpoints I did the following and now I see duplicate Tags.

```typescript
@ServerSettings({
  .....
  swagger: [
    {
      path: "/api-docs",
      spec: { swagger: "2.0", tags: [{name: "Test", description: "description"}]},
    },
  ]
})
`
```

```typescript
@Controller("/test")
export class TestController {

  @Get()
  @Operation({ tags: ["Test"], summary: "Test." })
  async testMethod(
    @Required() @BodyParams() tokenRequest: TokenRequest
  ): Promise<string> {
   ......
  }
}
```
`

Expected:-
testMethod tagged with "Test" in swagger doc

Actual:-
testMethod is tagged with "Test" and "TestController" in swagger doc

**Comment by Romakita** [comment]
```
@Controller("/test")
export class TestController {

  @Get()
  @Summary('Summary')
  @Operation({tags:['tag']})
  async testMethod(
    @Required() @BodyParams() tokenRequest: TokenRequest
  ): Promise<string> {
   ......
  }
}
```

**Comment by Romakita** [comment]
Fix will be released soon

**Comment by pradeeptk304** [comment]
Thanks, Fix works

**Comment by pradeeptk304** [comment]
Sorry I spoke too early, now I see the Controller name added as tags in the Tags section of the swagger header

tags:
  - name: Test
    description: description
  - name: TestController

**Comment by pradeeptk304** [comment]
any update to my previous comment?

**Comment by Romakita** [comment]
I haven't your previous comment sorry :)

**Comment by pradeeptk304** [comment]
Thanks for helping out

**Comment by Romakita** [comment]
Hello @pradeeptk304 
I can't reproduce your bug :/
Yes but it's normal use @Operation({tag: []}) has no impact on the tags fields. The fields is generated from the name of the controller.

You can use the @Name decorator if your goal is to change all operations:
```

@Controller("/test")
@Name('Test')
export class TestController {

  @Get()
  @Summary('Summary')
  async testMethod(
    @Required() @BodyParams() tokenRequest: TokenRequest
  ): Promise<string> {
   ......
  }
}
```

**Comment by pradeeptk304** [comment]
I used 

@ServerSettings({
  .....
  swagger: [
    {
      path: "/api-docs",
      spec: { swagger: "2.0", tags: [{name: "Test", description: "description"}]},
    },
  ]
})

to define the Tags, did you use it too? In the swagger I saw Tags "Test" and "TestController". If you still cannot reproduce then I can upload sample code.

**Comment by Romakita** [comment]
Try this code:
```

@Controller("/test")
@Name('Test')
export class TestController {

  @Get()
  @Summary('Summary')
  async testMethod(
    @Required() @BodyParams() tokenRequest: TokenRequest
  ): Promise<string> {
   ......
  }
}
```

**Comment by pradeeptk304** [comment]
I see "Test" been added in the "tags" section of swagger twice. I guess first time from @ServerSettings and Second from Controller("@Name").

I came remove the one from @ServerSettings but "@Name" doesn't have an option to provide description.

**Comment by Romakita** [comment]
Use @Description on class should solve your problem.

**Comment by pradeeptk304** [comment]
Thanks that worked.

I have to remove Tags from @ServerSettings and use @Name and @Description on Controller
