### ISSUE TITLE
[QUESTION] Use configuration settings inside decorator

### ISSUE THREAD

**Issue by psicomante** [TypedProject/tsed#850]
Hi Romain,

I'm facing an issue about the `@Protocol` decorator. I would like to add it some settings coming from Environment variables (i'm using dotenv) through the `ServerSettingsService`.

i have this code:

```ts
@Protocol<StrategyOptions>({
    name: "jwt",
    useStrategy: Strategy,
    settings: {
        jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
        secretOrKey: "my_secret_key"
        
        // issuer: "accounts.examplesoft.com",
        // audience: "yoursite.net"
    }
})
export class JwtProtocol implements IProtocol {
<something>
}
```

i would like to take `secretOrKey` from the ServerSettings. Is there a way? My knowledge of TS decorator is very poor, unfortunately, so i don't know when they are executed or dataflow of decorators.

Thank you, as always :)

**Comment by psicomante** [comment]
Obviously, an easy way would be using `process.SOME_VAR`. I would like to follow a easy testable/injectable way instead.

**Comment by Romakita** [comment]
Hello @psicomante yes it's totally possible. 

```@typescript
@Configuration({
   passports: {
     protocols: {
       jwt: {
         settings: {
            secretOrKey: "my_secret_key"
        
            // issuer: "accounts.examplesoft.com",
            // audience: "yoursite.net"
          }
       }
     }
  }
}) // or ServerSettings
```

Since the v5.57.5, use @Protocol as the same effect as @Configuration decorator. The configuration set with @Protocol will be merge with the global server configuration. The result in the global settings is that:

```
{
   passports: {
     protocols: {
       jwt: {
         name: "jwt",
         useStrategy: Strategy,
         settings: {
            secretOrKey: "my_secret_key"
        
            // issuer: "accounts.examplesoft.com",
            // audience: "yoursite.net"
          }
       }
     }
  }
}
```
This feature allow you to get the protocol configuration from any other Injectable service. Example:

```typescript
@Injectable()
class TokenGenerator {
   @Constant('passport.protocols.jwt.settings')
   jwtSetting: any;

   getToken(sub: string){
      return jwt.sign({...this.settings, sub})
   }
}
```

See you
Romain

**Comment by psicomante** [comment]
Hello Romain,

Thanks! It works, i wrote also a test, using your comment about inject configuration in `PlatformTest.create`

```ts
describe("JwtBearerService Test", () => {
    beforeEach(() => PlatformTest.create({
        passport: {
            protocols: {
                jwt: {
                    settings: {
                        secretOrKey: "test",
                        expireTime: 86400,
                        algorithm: "HS256"
                    }
                }
            }
        }
    }));
    
    <tests...>

});
```

Note: you put in the code the `passports` property but only `passport` works.

Cheers
Psicomante

**Comment by psicomante** [comment]
May i close the question o you usually left them open?

**Comment by Romakita** [comment]
No you can close this issue if all is ok for you :)
