### ISSUE TITLE
[BUG] Cannot read property 'statics' of undefined

### ISSUE THREAD

**Issue by ghmendonca** [TypedProject/tsed#852]
## Information

- **Version:** 5.57.7
- Packages: @tsed/platform-express

Can't start the project because something is wrong with the platform-express package

## Example
Just did a fresh tsed init and tried to start the project and got this:

`TypeError: Cannot read property 'statics' of undefined`

I did some logs and checked that the method loadStatics inside of PlatformExpress class is getting something from PlatformExpressStatics and trying to call a funcition called statics, but the return from `injector.get()` is undefined and is causing the next line to throw this error.

## Acceptance criteria

- [ ] Fix this bug

**Comment by Romakita** [comment]
Hello @ghmendonca 
Can you give me your server code please?

**Comment by ghmendonca** [comment]
@Romakita here is the code: https://github.com/ghmendonca/tsed-bug

I didn't add anything, just did the tsed init and commented the line GlobalAcceptMiddleware line because it was causing an error and also the typeorm configuration, since I won't be using it just now

**Comment by Romakita** [comment]
Ok I commented also the content in DefaultConnection.ts because you have removed the TypeORM configuration and this factory consume the typeorm configuration.
All of the code works. No issue on the statics.

**Comment by ghmendonca** [comment]
I see, thanks man! I guess would be good if you add some error handling around this, I also had an issue with the path property missing from the graphql configuration and the error that I got wasn't related to it, so I had to deeply debug, I can submit these error handles if you want

**Comment by Romakita** [comment]
ha ook :). In this case, this is the DefaultConnection code responsible to the error, so I fix the CLI and its template :)

For GraphQL, If you have the error and if it's related to @tsed/graphql, a PR can help me ;) (or if you know where exactly come from the problem, it's fine also).

See you
Romain
