### ISSUE TITLE
How to create a custom 404 page for non existing routes and set custom headers?

### ISSUE THREAD

**Issue by dileepgopal** [TypedProject/tsed#856]
TSED version : 5.42.1
View : ejs template engine

TSED generate the following html for 404 status code. 

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /nonroute</pre>
</body>
</html>
```

I would like to create a custom 404 page so that I can set custom headers.

**Comment by Romakita** [comment]
Here is the page : https://tsed.io/tutorials/not-found-page.html#customize-404
See you
Romain ;)

**Comment by dileepgopal** [comment]
@Romakita 

Thanks for the quick response.
It worked !!!

Thanks,
Dileep G

**Comment by dileepgopal** [comment]
@Romakita 

Following error happening for loading ejs file
Unhandled rejection TypeError: req.next is not a function

`@Middleware()
export class NotFoundMiddleware {

  use(
    @Res() response: Express.Response
  ): void {

    // Or with ejs
    response.status(404).render("404.ejs");
  }

}`

JSON response is working fine

**Comment by Romakita** [comment]
Have your install ejs ? It's not a problem from Ts.ED but from Express/Ejs :)

**Comment by Romakita** [comment]
https://tsed.io/tutorials/templating.html

**Comment by dileepgopal** [comment]
@Romakita 
Yes, I have configured ejs and it works for other routes. Other routes I am using @Render() decorator to load the template and pass the data in return statement. I am not sure how to mention the @Render() in the middleware

**Comment by Romakita** [comment]
I musn't use the @Render on middleware. Your problem related on the response.render() usage. 
With ejs you have to call render like this:

```typescript
 response.render(viewPath, data, next); // so in your case response.render('404.ejs', {}, next)
```
Try this

**Comment by dileepgopal** [comment]
@Romakita 

It worked for me.
Thank you very much for your help
