### ISSUE TITLE
[QUESTION] Using pipe in a controller decorator

### ISSUE THREAD

**Issue by owolfy** [TypedProject/tsed#859]
I am getting payload from Github. It comes as a string which I parse using JSON.parse. I began doing some readings and I saw that ParseService is deprecated but I couldn't understand how to use the pipe (if it possible in my case).

My current decorator looks somewhat like this:
`@Post('/')`
`post(@BodyParams() payload: { innerPayload: string }) {}`

Is it possible to use pipe in this case (DeserializerPipe I assume) inside the decorator in order to convert payload to an object of type SomeCustomModel instead of the way I'm doing it?

**Comment by Romakita** [comment]
Hello @owolfy 
Sorry for the late answer. So if I understand, the payload contain a field with a JSON, right ?

```typescript
@Injectable({priority: -1}) // to be called before DeserializePipe
export class InnerPayloadPipe implements IPipe {
  transform(value: any, param: ParamMetadata) {
    return JSON.parse(value.innerPayload);
  }
}


@Post('/')
post(@BodyParams() @UsePipe(InnerPayloadPipe) payload: MyModel) {}
```

See you
Romain

**Comment by owolfy** [comment]
@Romakita you understood correctly.

I am getting another error due to the Model.
Error: 'Bad request on parameter "request.body".\nProperty before on class MyModel is not allowed.'

However if i change my code to

`@Post('/')
post(@BodyParams() @UsePipe(InnerPayloadPipe) payload: any) {}
const payloadModel : MyModel = payload;`

Everything works just fine. I tried removing @BodyParams to check if it is related, it's not.

**Comment by Romakita** [comment]
By in this case, your payload in not an instance of MyModel :)

The Pipe won't be the solution.

Another option is to use the @PropertyDeseralize() decorator.

```typescript

class InnerPayloadModel {
  @Property()
   something: string;
} 

class MyModel {
  @PropertyDeserialize(input => JSON.parse(input))
  innerPayload: InnerPayloadModel
} 

class MyController {
  @Post('/')
  post(@BodyParams() payload: MyModel) {
     console.log(classOf(payload)) // MyModel
     console.log(classOf(payload.innerPayload)) // InnerPayloadModel
     console.log(payload)
  }
}
```
I think this example will works as expected :)
See you

**Comment by owolfy** [comment]
It still happens, I will continue investigate. Basically what I'm trying to do is to use github's webhooks but from some odd reason it keeps failing.

My hacky solution is this:
`post(@BodyParams() payload: { payload: string })`
`const gitEvent: GitEventsModel = JSON.parse(payload.payload);`

Thanks @Romakita  for your help. You also gave me some ideas for future implementations in my project ^_^
