### ISSUE TITLE
[QUESTION] Decorator/Middleware execution order when using MulterOptions

### ISSUE THREAD

**Issue by artur-app-logik** [TypedProject/tsed#865]
## Package versions
```json
    "@tsed/common": "^5.59.2",
    "@tsed/core": "^5.59.2",
    "@tsed/multipartfiles": "^5.59.2",
    "multer": "^1.4.2"
```

## Problem
We use a custom Authentication middleware, which is implemented according to the official tsed guide. It appends an object called `user` to the Express `req` object, containing user identifying information. It has been used across our application server  for a while so we know that it works.
Now when we tried to use the `MulterOptions`-decorator to use custom storage middlewares for each Controller method that needs multipart form data handling, it does not work as we would expect: when the functions defined inside the `diskStorage`-config object are executed, the aforementioned `user`-object is not defined inside the Express `req`-object. 

Is there a way to control the order of execution of those two middlewares (to guarantee the `user`-object is defined BEFORE the multer StorageEngine callbacks are executed)?

## Example code explaining the problem

```js  
...
const multerStorage = multer.diskStorage({
  destination: function(req, file, cb) {
    console.log(req.user); // undefined, but should be defined if the Authentication middleware has been executed before

    cb(null, `${rootDir}/../uploads`);
  },
  filename: function(req, file, cb) {
    const suffix= Date.now();
    cb(null, file.fieldname + "-" + suffix);
  }
});
...
@Post("/requests")
  @Authenticated({ allowedGroups: ["someGroup"] }) // overwritten by our custom Authentication middleware
  @MulterOptions({ storage: multerStorage })
  public async create(
    @MultipartFile("image") files: Express.Multer.File[],
    @Req() req: Express.Request
  ) {
    console.log(req.user); // is defined ({userId: 'xyz', ...})

    return true;
  }
...
```

**Comment by Romakita** [comment]
Hello @Romakita 
I think without a fix isn't possible. If your Authenticated decorator use the UseBefore decorator, it means the MultipartFile use also UseBefore decorator and has a priority on the Authenticated decorator. 

I'll try to fix that. 

See you
Romain

**Comment by Romakita** [comment]
I think it's fixed: https://github.com/TypedProject/tsed/blob/production/packages/multipartfiles/src/decorators/multipartFile.ts#L79
Can you update your project and test? please

**Comment by artur-app-logik** [comment]
It does work now! I tested it on version `5.65.5`. We now use the `Context.set()` function to set the user object inside the authentication middleware, and I can find the user object inside the context field.

Thank you very much!
