### ISSUE TITLE
[QUESTION] Update to Passport.js Facebook docs

### ISSUE THREAD

**Issue by joelrozen** [TypedProject/tsed#868]
After spending hours trying to figure out how to implement this, can I suggest the docs for the facebook passport.js please be updated.

I recommend updating in two spots to represent a simple, common use case which is simply logging in to a website.

In the AuthCtrl snippet.

can `@Authenticate("facebook", {scope: "read_stream"})` be changed to `@Authenticate("facebook", {scope: ["email"]})` since `read_stream` is deprecated from facebook.

Secondly, in the Facebook Protocol snippet.
in the StrategyOptions settings, add `profileFields: ['id', 'emails', 'name']`
If this is not passed in with the strategy options, then when the verify function is called, facebook will ONLY return the id and name, NOT the email, even if the email scope was requested.

Lastly, and not a big deal, but but line 22 of the same snippet references `discordId`

**Comment by Romakita** [comment]
Hello @joelrozen 
Yes sure, I'll fix that :). The build is on going ;)

Thank for your help !
