### ISSUE TITLE
[BUG] Title

### ISSUE THREAD

**Issue by tiran1984** [TypedProject/tsed#869]
## Information

- **Version:** 5.60.0
- Packages: passport 

Define a different User Model into the 

```
@ServerSettings({
...
    passport: {   userInfoModel: Credentials},
...
}
```

the lgin process will work but by the next authentication  I get these error

    message: 'Property token on class UserInfo is not allowed.',
    stack: 'UNKNOWN_PROPERTY_ERROR: Property token on class UserInfo is not allowed.\n' +
      '    at ConverterService.skipAdditionalProperty (C:\\Daten\\source\\workspace\\XXX\\node_modules\\@tsed\\common\\src\\converters\\services\\ConverterService.ts:305:15)\n' +
      '    at ConverterService.convertProperty (C:\\Daten\\source\\workspace\\XXX\\node_modules\\@tsed\\common\\src\\converters\\services\\ConverterService.ts:247:14)\n' +
      '    at C:\\Daten\\source\\workspace\\XXX\\node_modules\\@tsed\\common\\src\\converters\\services\\ConverterService.ts:192:19\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at ConverterService.deserialize (C:\\Daten\\source\\workspace\\XXX\\node_modules\\@tsed\\common\\src\\converters\\services\\ConverterService.ts:189:22)\n' +
      '    at PassportSerializerService.deserialize (C:\\Daten\\source\\workspace\\XXX\\node_modules\\@tsed\\passport\\src\\services\\PassportSerializerService.ts:28:42)\n' +
      '    at pass (C:\\Daten\\source\\workspace\\XXX\\node_modules\\passport\\lib\\authenticator.js:357:9)\n' +
      '    at Authenticator.deserializeUser (C:\\Daten\\source\\workspace\\XXX\\node_modules\\passport\\lib\\authenticator.js:362:5)\n' +
      '    at SessionStrategy.authenticate (C:\\Daten\\source\\workspace\\XXX\\node_modules\\passport\\lib\\strategies\\session.js:60:10)\n' +
      '    at attempt (C:\\Daten\\source\\workspace\\XXX\\node_modules\\passport\\lib\\middleware\\authenticate.js:366:16)',
    status: 400,

```
export declare class Credentials {

  id:string;
  token:string;
  name:string;
}

```

## Acceptance criteria

- [ x] Criteria 1

**Comment by Romakita** [comment]
Hello @tiran1984 
Have your read the documentation about the model? https://tsed.io/docs/model.html#example
All properties must be decorator with at least one decorator provided by Ts.ED :)

Fix your model and try again please :)
See you
Romain

**Comment by Romakita** [comment]
And why have you declare instruction before class?

**Comment by tiran1984** [comment]
me was not clear that I have decorate these model also. But thanks for your fast answer
