### ISSUE TITLE
Authenticated user get in EntitySubscriber 

### ISSUE THREAD

**Issue by tiran1984** [TypedProject/tsed#872]
Is it possible to get into an EntitySubscriber the info which login user has do the request?

**Comment by Romakita** [comment]
You have to forward the request from your controller to the EntitySubscriber (I think).

**Comment by tiran1984** [comment]
Is it not possible to do this during a middleware. 
So the framework will handle these by it self

**Comment by Romakita** [comment]
You can handle this with a middleware but after you have to forward the request explicitly to the EntitySubscriber.

**Comment by tiran1984** [comment]
Do you have an example

**Comment by Romakita** [comment]
I haven't example, I never used the EntitySubscriber.

**Comment by Romakita** [comment]
And I don't know what you want exactly. Give some examples code and maybe I could help you :)

**Comment by tiran1984** [comment]
```
@Middleware()
export class CustomMiddleware implements IMiddleware {

  use(@Req() request: Req, @EndpointInfo() endpoint: EndpointInfo) {
    if (request.user && request.isAuthenticated()) {
      // request.user["name"] -> store the username in typeorm;
    }
  }
}

@EventSubscriber()
export class EntitySubscriber implements EntitySubscriberInterface {

beforeInsert(event: InsertEvent<any>) {
    if(request.user["name"])
    {
      event.entity.user = request.user["name"] // or from typeorm 
    }
  }
}

```
The middleware read the current auth user and save them some where. 

So when we do an insert we can set the current auth user in the entity

**Comment by Romakita** [comment]
Ok. It's complicated. Your EntitySubscriber is a singleton. Request can be concurrent, so store a request somewhere in TypeORM will be a problem in this case because user name won't be the expected one, if two request are handled by the server. 

TypeORM isn't designed to manage that (and it's normal). There is no magical solution, sorry ^^.

See you
Romain
