### ISSUE TITLE
[BUG] @Returns with non-200 status is not documented in swagger since 5.36.0

### ISSUE THREAD

**Issue by Pokemonjpups** [TypedProject/tsed#874]
## Information

- **Version:** 5.60.2 although I believe it affects all versions above 5.36.0
- Packages: `@tsed/common` `@tsed/core` `@tsed/di` `@tsed/platform-express` `@tsed/swagger` `body-parser` `compression` `cookie-parser` `express` `method-override`

**A few sentences describing the overall goals of the issue.**

I believe this affects all versions of tsed created after 5.36.0. I'm not sure what commit specifically broke it though.

Essentially, if you try to use `@Returns` or `@ReturnType` with a non-200 status code (or non-200/non-400 status code if you have required params), then the status codes are non documented in swagger.

## Example
Pull each of these, run `npm i` then run `tsc` and `node dist/index.js` then visit /api-docs to see what I mean. The controller method is in controllers/Example.ts 
- **Working:** Here is an example of 5.36.0 where `@Returns()` works with non-200 status codes: https://github.com/Pokemonjpups/working-tsed
- **Broken:** Here is an example of 5.60.2 where using non-200 status codes causes the statuses to not be documented in swagger: https://github.com/Pokemonjpups/broken-tsed

## Acceptance criteria

- [ ] All non-200 status codes should show up in swagger docs when documented with `@Returns` (from `@tsed/swagger`) or `@ReturnType` (from `@tsed/common`)

**Comment by Romakita** [comment]
Hello @Pokemonjpups 
Thanks for the detailed issue :) and my apologize for the regression :/

I added complementary integration test to not reproduce this problem in future!

The release is on going ;)
See you
Romain

**Comment by chorsnell** [comment]
For anyone running into this (I was having the same issue on `5.60.2`), upgrading to `5.60.4` doesn't actually build correctly. It 

I skipped ahead to `5.60.7` and it worked 👍
