### ISSUE TITLE
[QUESTION] How can i inject a dynamic value into a @Service from @Middleware?

### ISSUE THREAD

**Issue by pierrebenazzibr** [TypedProject/tsed#878]
The problem: I can get Injected value in the service, but after the first request, the Injected value ( e.g. KEYDS ) never changes.
Anyone knows how to do it properly?

MY MIDDLEWARE

first try...
```typescript
@Middleware()
export class TenantMiddleware implements IMiddleware {

        registerProvider({
        provide: Symbol.for("KEYDS"),
        scope: ProviderScope.REQUEST,
        useValue() {
          return req.headers['keyds'];
        }

}
      });
```

second try...
```typescript
@Middleware()
export class TenantMiddleware implements IMiddleware {

registerValue(Symbol.for("KEYDS"), req.headers['keyds']);

}

```
      

MY SERVICE CLASS

```typescript
@Service()
@Scope(ProviderScope.REQUEST)
export class UsuarioService {

    public constructor(@Inject(KEYDS) keyds: any,
                       public readonly oauthTokenService: OAuthTokenService,
                       public readonly usuarioRepositorio: UsuarioRepositorio) {

      console.log('service: keyds injected: ' + keyds);

```

**Comment by Romakita** [comment]
Hello @pierrebenazzibr 

It's a good question... let me try to give you a working example in a dedicated repository :)

**Comment by Romakita** [comment]
Hello @pierrebenazzibr 
Here is a working example: https://github.com/Romakita/tsed-issue-882

The main point is, you have to decorator the Controller with @Scope(ProviderScope.REQUEST) also, If you want to use the UsersService with the Request scope :) 

See you
Romain

**Comment by pierrebenazzibr** [comment]
Thank you so much for your reply!!

I will give a try soon, although i managed to pass the `keyds` ( my database tenant ID ) with get and set common methods...
I think injecting keyds from Middleware through Controller, then to Service and finally to Repository layer, would be more easy for other developers, when they start coding the application features, cause they will only need to code bussines logic.
But i'm a little bit concern about performance with RequestScope utilization.

`
 @Controller('/autenticacao/v1')
export class AutenticacaoController {

     constructor(private usuarioService: UsuarioService) {}   /* usuarioService is injected as Singleton */

  @Get('/example')
  example( @Req() req: Request, @Res() res: Response, @Next() next: NextFunction) {
       this.usuarioService.setRequest(req)
 }
}

`

In the example above, i only use one instance of `usuarioService`...
In RequestScope, i will have one instance for every request.

Do you think this could have an impact in performance, as i will have this kind of logic in more than 100 Controllers, Services and Repositories throughout the system....

PS.: The project will have around 1 million users... so we are talking about an API with a high traffic.

**Comment by Romakita** [comment]
Hello @pierrebenazzibr 
The Request scope have an impact on performance and memory usage, because you'll create a new sandbox/diContainer for each request.
So if you can managed that without scope request it's better.

The optimal approach is to get only needed parameter for your endpoint:
```typescript

 @Controller('/autenticacao/v1')
export class AutenticacaoController {

     constructor(private usuarioService: UsuarioService) {}   /* usuarioService is injected as Singleton */

  @Get('/example')
  example(@HeaderParams('keyds') keyds: string, @BodyParams() user: UserModel) {
       this.usuarioService.setRequest(keyds, user)
 }
}
```
Forward request to the Service is a bad pattern  (but something you have no choice). 

Use `@Context` decorator/class can be a good solution for your usecase: See https://tsed.io/docs/request-data-persistence.html#context

Example:
```typescript
@Middleware()
class TenantIdsMiddleware {
   use(@HeaderParams("keyds") keyds: string, @Context() context) {
      context.set('KEYDS', context);
  }
} 

@Injectable()
class UsersService { 
   addUser(user: UserModel, ctx: Context) {
       ctx.logger.info(ctx.get('KEYDS'))
   }
}

@Controller("/")
@UseBefore(TenantIdsMiddleware) // protect all routes for this controller
class MyCtrl {
  usersService: UsersService;
  @Post("/")
  get(@BodyParams() user: UserModel, @Context() ctx: Context) {
    context.logger.info({event: "auth", data: user}); // Attach log to the request

    this.usersService.addUser(user, ctx);
  }
}
```
This approach is optimal :)

See you
Romain
