### ISSUE TITLE
Tsed TypeORM Azure SQL token value by PROMISE

### ISSUE THREAD

**Issue by panbhatt** [TypedProject/tsed#882]
I am trying to establish TYPEORM connection to Azure SQL. So my steps are to get first a token via hitting a URL (means i m in the promise loop) and then i have to export my Server class with the typescript annotations. Problem is how i can change the TypeORM annotation values since the PROMISE would take some time to resolve. Seems like we can't do it. Any ideas or solutions, i seem to stuck there. 
I am using typescript.

**Comment by Romakita** [comment]
Hello @panbhatt 

You can get your token before bootstrapping the Server, no ?

```
import {$log} from "@tsed/common";
import {PlatformExpress} from "@tsed/platform-express";
import {Server} from "./Server";

async function bootstrap() {
  try {
    $log.debug("Start server...");
    // add your getToken action here
   const token = await getAzureToken()

    const platform = await PlatformExpress.bootstrap(Server, {
    });

    await platform.listen();
    $log.debug("Server initialized");
  } catch (er) {
    $log.error(er);
  }
}

bootstrap();
```

It's just an idea :)

**Comment by panbhatt** [comment]
Thanks for this. however i m using @ServerSettings where typeorm info is embedded. So in the code above how can i change the Decorator property values on the Server Class. 
I am using ServerLoader.bootstrap(Server, {})

**Comment by Romakita** [comment]
I the same approach with the legacy ServerLoader :)

```typescript
async function bootstrap() {
  try {
    $log.debug("Start server...");
    // add your getToken action here
   const token = await getAzureToken()

    const platform = await PlatformExpress.bootstrap(Server, {
        typeorm: {
           yourconnection: {
              ... add typeorm configuration and your token (remove typeorm configuration from the @ServerSettings decorator)
           }
        }
    });

    await platform.listen();
    $log.debug("Server initialized");
  } catch (er) {
    $log.error(er);
  }
}

bootstrap();

```

**Comment by panbhatt** [comment]
Thanks a lot for this. This seems to be a way for overriding the configuration. 
Isn't it great if you can compile all these tips and tricks in a blog somewhere. Excited to see these :)

**Comment by panbhatt** [comment]
hey @Romakita  : Just wanted to know do we have a way to keep on refreshing our connection pool (with typeorm) i.e. continously change the token on a regular basis and give it to TYpeorm so that it can built is internal connection pool on a regular basis. Please
