### ISSUE TITLE
TSED LOG redirection to file

### ISSUE THREAD

**Issue by panbhatt** [TypedProject/tsed#884]
Is there a mechanism to redirect all the TSED logs (plus any other logs coming out of libraries used in the project) to a single file. 
This is what i have done. is there a better way to do it. 

https://gist.github.com/panbhatt/d0abd901752619c133419af5a4cb43cb

**Comment by NachtRitter** [comment]
Look into this: https://logger.tsed.io/appenders/file.html

**Comment by jappyjan** [comment]
but how do i inject the appender into the default $log instance?

**Comment by Romakita** [comment]
Just get the $log variabel from @tsed/common and add your appender :) 

```typescript
import {$log} from "@tsed/common";


$log.appenders.set("file", {
    type: 'file', 
    filename: 'all-the-logs.log'
});

```

**Comment by jappyjan** [comment]
Thank you a lot! Worked like a charm.
