### ISSUE TITLE
Using ValidationService and CoverterService on a model provided to a custom method

### ISSUE THREAD

**Issue by royibernthal** [TypedProject/tsed#887]
I'm accepting a model as one of the arguments in a method that's unrelated to a Controller (an AMQP consumer).
I'd like to be able to verify and deserialize that model, in the exact same way as @BodyParams, @QueryParams, etc.

I went over the converters doc and wasn't able to find anything on the matter.
https://tsed.io/docs/converters.html

I reckon it boils down to the following:
https://github.com/TypedProject/tsed/blob/736441fd974c08a882e7e7ba256653a38382e364/packages/common/src/mvc/pipes/ValidationPipe.ts

https://github.com/TypedProject/tsed/blob/736441fd974c08a882e7e7ba256653a38382e364/packages/common/src/mvc/pipes/DeserializerPipe.ts

However, I'm not sure what would be the best way to proceed.

**Comment by Romakita** [comment]
Hello @royibernthal 

With the Ts.ED v5 you have to use the injector to get the right services and validate you object.
This problem will be solved with the v6.

To perform validation you create a function as following:

```typescript
import {Container, GlobalProviders} from "@tsed/di";
import {converterService} from "@tsed/common";
import "@tsed/ajv";
import * as Ajv from "ajv";
const ajv = new Ajv({verbose: false})

const injector = new InjectorService()
const container = new Container(GlobalProviders.entries());
injector.load()

function validate(obj, model) {
   const converterService = injector.get(converterService);
   const schema = getJsonSchema(model)
   obj = converterService.deserialize(obj, model, {
     ignoreCallback: (obj: any, type: any) => type === Date, // will be obsolete in v6
    checkRequiredValue: false //
   });
  
  const valid = ajv.validate(schema, obj)
  
  if (!valid) {
    throw valid.errors; // change by your own Error
  } 
 
  return obj;
}
```
This code should works in v5 but it'll probably wrong in v6.

In v6 the validation will be performed before deserialization :)

```typescsript
import {deserialize}  from "@tsed/json-mapper";
import {getJsonSchema} from "@tsed/schema";
import * as Ajv from "ajv";

const ajv = new Ajv({verbose: false})

function validate(obj, model) {
  const schema = getJsonSchema(model);
  const valid = ajv.validate(schema, obj);
  
  if (!valid) {
    throw valid.errors; // change by your own Error
  } 
 
  return deserialize(obj, {type: model});
}
```

See you
Romain

**Comment by royibernthal** [comment]
Hey @Romakita 

The injection doesn't work for me - converterService returns undefined.
Also, the container reference is not used, is that on purpose?

Btw, any ETA on v6?

```
import { Container, GlobalProviders, InjectorService } from '@tsed/di';
import { ConverterService, $log } from '@tsed/common';
import '@tsed/ajv';

const injector = new InjectorService()
const container = new Container( GlobalProviders.entries() ); //this reference is not used?

injector.load();

export function test() {
   const converterService = injector.get(ConverterService);

   $log.info(converterService); //undefined
}
```

**Comment by Romakita** [comment]
Hoo I forgot to give the container to injector.load() sorry :)

ETA?

**Comment by royibernthal** [comment]
Still undefined, what am I missing?

```
const injector = new InjectorService()
const container = new Container( GlobalProviders.entries() );

injector.load(container);

const converterService = injector.get(ConverterService);

console.log(converterService); //undefined
```

That's great, can't wait to see it :)

**Comment by Romakita** [comment]
Sorry, this is the right code:
```typescript
const injector = new InjectorService()
const container = new Container( GlobalProviders.entries() );

injector.addProviders(container); // fix this line

const converterService = injector.get(ConverterService);

console.log(converterService); //undefined

```

**Comment by royibernthal** [comment]
Still undefined lol.

Is there maybe some prerequisite I'm missing in order for this to work?
For instance running it only after the server finished initializing or something of the sort.

**Comment by Romakita** [comment]
I wrote an example here: https://github.com/Romakita/tsed-test-model

;)

**Comment by royibernthal** [comment]
Thanks, I appreciate the effort :)

So the final touch missing was:
`const converterService = injector.invoke<ConverterService>(ConverterService);`

Instead of injector.get.

It seems like converterService.deserialize handles type errors and missing parameters, so what does ajv.validate do that converterService.deserialize doesn't?

**Comment by Romakita** [comment]
This is a legacy behavior. Converter validate only the property availability (when you use the Required decorator), but not the entire rules. In v6, ConverterService (JsonMapper) won't perform this validation. Ajv is the only responsible to validate your model accross a valid JsonSchema ;)

**Comment by royibernthal** [comment]
Got it, thanks :)
