### ISSUE TITLE
[QUESTION] Access Request object in validation pipe

### ISSUE THREAD

**Issue by denisatsqnp** [TypedProject/tsed#890]
Hi!

Do not know the correct way to handle this, suppose the following controller:

```typescript
import { Controller, Get, Inject, BodyParams, Post, Patch } from '@tsed/common'
import { UserRepository } from '../repository/UserRepository'
import { User } from '../entity/User'
import { UseEntityParam } from '../decorators/UseEntityParam'
import _ from 'lodash'

@Controller('/users')
export class UsersController {

    @Inject()
    private userRepo: UserRepository

    @Patch('/:id')
    updateAction(@UseEntityParam(User) user: User, @BodyParams() update: User): Promise<User> {
        return this.userRepo.save(_.assign(user, update))
    }

    @Get('/:id')
    detailsAction(@UseEntityParam(User) user: User): User {
        return user
    }

    @Get('/')
    listAction(): Promise<User[]> {
        return this.userRepo.find()
    }

    @Post('/')
    createAction(@BodyParams() user: User): Promise<User> {
        return this.userRepo.save(user)
    }
}
```

The user entity has an email validation which is required, this works perfectly for `createAction` as I receive the user entity after the validation completes, for `updateAction` I just want the `fistName` property on the entity updated, however I receive email validation error which is expected, so what would be the correct way to handle this? Maybe somehow inject the request object into the validation pipe and skip validation if it's a patch method or delay the validation until `_.assign(user, update)`?

Thanks in advance!

**Comment by Romakita** [comment]
With the v5, you have to create two models to avoid your validation issue (v6 will solve this issue by using Ignore decorator with options).

Example:

```typescript
export class UserCreation {
  @Email()
  email: string;
  
  @MinLength(3)
  fistName: string;
}

export class User extends UserCreation {

}

export class UserPatch extends UserCreation {
  @IgnoreProperty()
  email: string;
}


@Controller('/users')
export class UsersController {

    @Inject()
    private userRepo: UserRepository

    @Patch('/:id')
    updateAction(@UseEntityParam(User) user: User, @BodyParams() update: UserPatch): Promise<User> {
        return this.userRepo.save(_.assign(user, update))
    }

    @Get('/:id')
    detailsAction(@UseEntityParam(User) user: User): User {
        return user
    }

    @Get('/')
    listAction(): Promise<User[]> {
        return this.userRepo.find()
    }

    @Post('/')
    createAction(@BodyParams() user: UserCreation): Promise<User> {
        return this.userRepo.save(user)
    }
}
```

I agree, maintain multiple models isn't the better solution. But it works :) 
See you
Romain

**Comment by denisatsqnp** [comment]
Hi Romain, thank you for your prompt response!
This could be a solution, I have now discovered `useValidation` option on `@BodyParams`, setting it to `false` could do the trick as well.
I think it could be now closed,
Thanks.

**Comment by Romakita** [comment]
Ok :)
