### ISSUE TITLE
[BUG] CollectionOf does not exist in 5.57.7

### ISSUE THREAD

**Issue by kpapadatos** [TypedProject/tsed#891]
## Information

- **Version:** 5.57.7
- Packages: @tsed/common

According to [documentation](https://tsed.io/tutorials/mongoose.html#collections), `CollectionOf` should exist.
![image](https://user-images.githubusercontent.com/3382344/89731366-3f731680-da4f-11ea-99e0-cfd4d26403bd.png)

## Example

```ts
import { CollectionOf } from "@tsed/common";

```

## Acceptance criteria

- [ ] `CollectionOf` should exist

**Comment by Romakita** [comment]
CollectionOf is only available on the latest version 5.62.0. Use PropertyType for your version :) 

See you

**Comment by Romakita** [comment]
Note: by default, documentation is only available for the latest version ;).
