### ISSUE TITLE
TypeORM MSI AUTH-  Connection Pooling - Revalidation of connection based on new AUTH token

### ISSUE THREAD

**Issue by panbhatt** [TypedProject/tsed#892]
We are working with Azure SQL via TYPEORM (connecting via MSI AUTH). The token seems to expire after every 4 hours. this means that all the connections present in the connection pool are invalid( we can see the logs that when we try to execute a query via a pooled connection, it throws an error saying TOKEN UnAuthorized). 
Since we have to get token via hitting an external URL is there is a way this can be automated rather then just restarting the application. Azure SQL nodejs driver is TEDIOUSJS. This is driving us nuts as i dont think this should be handled in the code and should be a part of TEDIOUSJS in case this rotation of MSI Token needs to be handled. 
any help on this is appreciated.

**Comment by Romakita** [comment]
Hello @panbhatt 
I don't know how I can help you. This question should be opened on TEDIOUS and TypeORM projects. 
One of the solution (not the better) can be to disable Token authentification on Azure and use a classic credentials ?
Or configure an higher TTL for your access_token? 

See you
Romain

**Comment by Romakita** [comment]
https://github.com/typeorm/typeorm/issues/4510

**Comment by panbhatt** [comment]
CLosing this issue, since this is related to the tediousjs library.

**Comment by funkydev** [comment]
@panbhatt I did a PR https://github.com/typeorm/typeorm/pull/7477
