### ISSUE TITLE
[QUESTION] x-amazon-apigateway

### ISSUE THREAD

**Issue by vedranjukic** [TypedProject/tsed#893]
How to add "x-amazon-apigateway" objects to methods? Or maybe this is not a scope of tsed (is there some cmd tool to do this)?

**Comment by Romakita** [comment]
What is x-amazon-apigateway? It's an header ?

**Comment by vedranjukic** [comment]
It's a swagger extension

https://swagger.io/docs/specification/2-0/swagger-extensions/#:~:text=Extensions%2C%20or%20vendor%20extensions%2C%20are,%2C%20such%20as%20x%2Dlogo%20.&text=Many%20API%2Drelated%20products%20that,%2C%20ReDoc%2C%20APIMatic%20and%20others.

for example

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration.html
