### ISSUE TITLE
[QUESTION] @Name works on swagger docs, but not in api return

### ISSUE THREAD

**Issue by demetriosouto** [TypedProject/tsed#894]
I am using the Name decorator to change the exposed name of some properties on my api, when I go over the swagger docs, it has the proper name defined inside Name decorator, but when I call my api, ir returns de original property name.

I was using version 5.44.x before and it worked with the Property({name: ""}) decorator, but after changing to version 5.62.x, it stopped working, even after changing the decorator to Name. I opened as a question, because I don't know if I did something wrong when changing the version.

Here is an example model and controller:

```
export class MyModel {
    @Name("propName")
    name?: string;

    @Name("propDescription")
    description?: string;
}
```

```
@Get("/test-model")
  @Returns(MyModel)
  getTeste(): MyModel {
    let model = new MyModel();
    model.name = "testName";
    model.description = "testDescription"
    return model;
  }
```

**Comment by Romakita** [comment]
Hello @demetriosouto 
It’s always an issue or it’s solved?
