### ISSUE TITLE
Protect / static contents with passportjs

### ISSUE THREAD

**Issue by panbhatt** [TypedProject/tsed#895]
HI,
  I am working on a application, where i need to protect all the statics route with a passport strategy. Any idea how it can achieved.

**Comment by Romakita** [comment]
Hello @panbhatt 
You can use the passport raw middleware for that.

```typescript
class Server {
  @Inject()
  app: PlatformApplication;

  $afterRoutesInit(){
     this.app.use("/statics", passport.authorize("type", {}), express.statics())
  }
}
```

See you
Romain

**Comment by panbhatt** [comment]
Thanks. we are now using $afterRoutesInit() to override this as of now. however i think there would be a better solution in terms of annotations.

**Comment by Romakita** [comment]
Annotation cannot be used here because statics files is exposed by a raw express function.
