### ISSUE TITLE
[BUG] @Summary isn't being processed

### ISSUE THREAD

**Issue by brakmic** [TypedProject/tsed#900]
## Information

- **Version:** 5.62.4
- Packages: @tsed/schema

A few sentences describing the overall goals of the issue.

## Example

```
import {BodyParams, Controller, Delete, Get, PathParams, Post, Put, Required, Status, Description} from '@tsed/common';
import {Returns, ArrayOf, Summary} from '@tsed/schema';

@Description('My Controller')
@Controller({
  path: '/resources',
  children: [],
})
export class MyController {
  @Get('/:id')
  @Summary('Finds a resource by ID')
  @Description('Finds a resource by ID')
  @Returns(204, Resource)
  @Returns(404, {description: 'Not found'})
  async get(@Required() @PathParams('id') id: number): Promise<Resource> {
    return await new Promise<Resource>((resolve, reject) => resolve(this.getDummyResource(id)));
  }
}

```

The swagger.json doesn't contain any entry regarding "summary". Only the "description" properties are present. Therefore, the generated documentation also lacks these information.

```json
"paths": {
"/api/resources/{id}": {
"get": {
"operationId": "MyController.get",
"tags": [
"MyController"
],
"parameters": [
{
"in": "path",
"name": "id",
"type": "number",
"required": true
}
],
"responses": {
"200": {
"description": "Success"
}
},
"description": "Finds a resource by ID"
},
```

**Comment by brakmic** [comment]
However, when I import Summary from '@tsed/swagger' it gets generated. 
There seem to be a difference between the two. I have seen something similar regarding the @Description decorator that's marked as deprecated (one should user @Title instead).

**Comment by Romakita** [comment]
Hello @brakmic 
Maybe a forgot something on the v5 website but @tsed/schema cannot be used with the current Ts.ED version. 
I prepare v6 and some deprecated comments are wrong. I'll fix that :)

**Comment by Romakita** [comment]
All deprecated are correct. I don't know why you have a deprecated information on the Title, Description and Summary decorators.
All deprecated message are addressed only for v6...

**Comment by Romakita** [comment]
You can see on these links. all message are addressed for v6 users:
https://tsed.io/api/common/jsonschema/decorators/Description.html#overview
https://tsed.io/api/common/mvc/decorators/method/Returns.html#overview

Summary isn't deprecated on v5.

**Comment by brakmic** [comment]
> All deprecated are correct. I don't know why you have a deprecated information on the Title, Description and Summary decorators.
> All deprecated message are addressed only for v6...

I have deprecated info on Description when I import it from @tsed/common. 

```shell

Add description metadata on the decorated element.

::: warning This decorator will be removed in v7. For v6 user, use @@Title@@ from @tsed/schema instead of @tsed/common. :::
```

When I import it from @tsed/schema the deprecation warning disappears.

The same warning appears when I import Returns and ReturnsArray from @tsed/common. When I import Returns from @tsed/schema (or ArrayOf as replacement for ReturnsArray) then no warnings appear.

The same is happening with Title (warning when @tsed/common, no warning when imported from @tsed/schema)

```shell
Add title metadata on the decorated element.

::: warning This decorator will be removed in v7. For v6 user, use @@Title@@ from @tsed/schema instead of @tsed/common. :::
```

But I think I get it now. For _Swagger things_ I should use **@tsed/swagger** (Summary etc.) and _for non-deprecated variants_ I should use **@tsed/schema** instead of @tsed/common.

Many thanks!
