### ISSUE TITLE
[QUESTION] How to configure for Firebase Cloud Functions?

### ISSUE THREAD

**Issue by lucasdidur** [TypedProject/tsed#902]
Hello,

I want to deploy my project on firebase, but I have no idea how to setup TsED for this. 
Can you help?

**Comment by Romakita** [comment]
Hello @lucasdidur 
I added an example to use Ts.ED project with a firebase cloud function.
https://github.com/TypedProject/tsed-example-firebase-funtions

Can you test this example and tell me if it's works ;)
See you
Romain

**Comment by lucasdidur** [comment]
Thank you, I will test.
