### ISSUE TITLE
@Authorize is not called if user is logged in?

### ISSUE THREAD

**Issue by virus2016** [TypedProject/tsed#911]
## Information

- **Version:** 5.x
- Packages: passport

I have used the @Authenticate and successfully authenticated and now I would like to link my Facebook, google or twitter accounts. My understanding is to use the @Authorize to get the account information back from the third provider. Once authenticated, I can not get information back from the other providers because the middleware is stopping the redirect?

https://github.com/TypedProject/tsed/blob/c6424c4a6c2199722d63223fa9798e5acef5fef4/packages/passport/src/middlewares/PassportMiddleware.ts#L8-L15

If I do not @Authenticate and use the @Authorize, I am redirected always to the callback and information is returned in req.account which is correct and I can use onVerify perfectly. 

## Acceptance criteria

- [ ] If @Authenticate has been successful and req.user is set, endpoints that have @Authorize should redirect me to the callback.

I hope this makes sense @Romakita!

**Comment by virus2016** [comment]
If I remove the: 

```typescript
     if (request.user && request.isAuthenticated()) { 
       return; 
     } 
```

@authorize is working as it should but @authenticate is now not maintaining the user as you have probably guessed.

I was going to do a PR for this but I am just copying this file and having 2 middlewares - one with the if statement and one without. I feel there is probably a better way? 

Many thanks,
Cal

**Comment by Romakita** [comment]
Hello @virus2016 
If you think it should be the right behavior, yes make a PR :). Your solution seems to be good for me ;)

Thanks @virus2016  ;)
Romain

**Comment by Romakita** [comment]
Hello @virus2016 
Have you the time to work on the PR?

See you :)

**Comment by Romakita** [comment]
As I understand, you use @authenticate decorator then  @authorize to link connected user with a social profile. 

The usecase work if you use a localStrategy and the user have already an account. But what about the usecase where the user is new? It must create his account then link his profile?

In my usecase, I use only authorize decorator because all authentication are delegated to an oidc server. So current middleware implementation works as expected.

I think we have to describe all possible usecase / usage the decorator to determine the right implementation :)

What do you think?

**Comment by virus2016** [comment]
Hi @Romakita! 

I haven't have time to work on it at the moment. 

PassportJs doesn't really explain the authorize very well. The best description I can give it is:

Authorize allows users who are already logged in to access our third party providers while maintaining the original user account. On successful login of the third provider, *req.account* is populated with the third party profile information. If the user has already logged in with Authenticate then *req.user* is maintained even after the authorize callback has happened using *req.user*. ￼
￼￼
This works if I remove those lines as mentioned however, I'm not sure of the best implementation for tsed. 

I felt that another middleware with the if logged in check removed would do it? 

Hope this helps!
