### ISSUE TITLE
[QUESTION] Can you update the response data in a UseAfter middleware?

### ISSUE THREAD

**Issue by bpofficial** [TypedProject/tsed#914]
Pretty much all the details in the title. I'm trying to filter data and update the response using a UseAfter middleware. Ty :)

**Comment by Romakita** [comment]
You have two solutions: middleware or interceptor (https://tsed.io/docs/interceptors.html#decorators).

With the middleware:
```typescript
class MyAfterMiddleware {
   use(@Context() ctx: Context) {
      console.log(ctx.data)
      ctx.data = mapData()
  } 
}
```

See you
Romain

**Comment by bpofficial** [comment]
I was under the impression that I could use context although I wasn’t entirely sure how updating the context within the middleware was going to update the context globally. Although since you’ve mentioned it I’m assuming you’re using a get and set in the context class in order to set it globally right?

**Comment by Romakita** [comment]
Context is a ref which contain the current data returned by the endpoint. Context is attached to the express request, and will be consumed by Ts.ED to create the response.
