### ISSUE TITLE
[BUG] After JWT Strategy the controller function is never get called

### ISSUE THREAD

**Issue by panbhatt** [TypedProject/tsed#922]
Version: 5.57.x

We are trying to Create a Passport Strategy "JWT" and using cookie to store the JWT Token. 
when we are trying to validate via using @Authorize("jwt") in the controller, the control is never going to the @GET Request method handler. we can the request is always in PENDING status on the browser. Are we doing something wrong here. 

our controller method is: 

```javascript
@Controller("/temp")
@Authenticate("jwt") // we also tried @Authorize("jwt") same results
export class  ABCContrl {

    @Get("/")
     async search() : Promise<any>{ //Never Reaching here.. 
}
}
```

```
@Protocol<StrategyOptions>({

  name: "jwt",

  useStrategy: Strategy,

  settings: {

    jwtFromRequest: ExtractJwt.fromExtractors([cookieExtractor]),

    secretOrKey: Constants.JWT_SECRET,

    issuer: Constants.JWT_ISSUER,

    audience: Constants.JWT_AUDIENCE,

  },

})

export class JwtApiAuthProtocol implements OnVerify {

  constructor() {}

  async $onVerify(@Req() req: Req, @Arg(0) jwtPayload: any) {

    console.log("CONING HERE");

    $log.info(`FROM JWT -> ${JSON.stringify(jwtPayload)}`);

    console.log(jwtPayload.data.token);



    let user: any = {

      ...jwtPayload.data,

    };

    return user;

  }

}

function cookieExtractor(req: any) {

  var token = null;

  console.log(req.cookies);

  if (req && req.cookies) token = req.cookies["user_profile_token"];

  return token;

}
```

**Comment by Romakita** [comment]
Hello @panbhatt 
This is not a bug from tsed, i think.
Look on this example: https://github.com/TypedProject/tsed-passport-jwt-example/blob/master/src/protocols/JwtProtocol.ts
I attached the user to the request to fix the problem. I don’t exactly why.

Can you compare your example with your code ;)

See you

**Comment by panbhatt** [comment]
Thanks @Romakita  : i tried this, however user is not a property on the request, so getting that error. 
Also do we need to specify the USER MODEL somewhere, 

i tried doing this (req as any).user = user; even that does not worked.

**Comment by panbhatt** [comment]
Thanks @Romakita . I have resolved the issue. I still don't know why there is no errors, but i m missing some @types/passport-jwt in my dev dependencies. As soon as i added them, it works like a charm. 
Just a question on this, is there any way in which we can customize the UNAUTHENTICATED response that is being sent if there is a problem with the JWT token either it is not present or expired.

**Comment by Romakita** [comment]
Unauthenticated is probably thrown by passportjs itself. So I don't know :)

**Comment by panbhatt** [comment]
Thanks. I will try to wrap it up in a middleware and try this. 
Also is there is a way i can make my @Authenticate to be optional. E.g. it should not be applied in my local env but should apply in the DEV/TEST environment (as i may not have full setup at local system).

**Comment by panbhatt** [comment]
@Romakita : Is there something we can do like this [https://stackoverflow.com/questions/15388206/sending-back-a-json-response-when-failing-passport-js-authentication/15397432](https://stackoverflow.com/questions/15388206/sending-back-a-json-response-when-failing-passport-js-authentication/15397432) or it is already implemented but not documented. Please can u help.

**Comment by Romakita** [comment]
You can override PassportMiddleware to change his behavior (optional in the expected profile).

For your second point, if you are on the latest Ts.ED version ExceptionFilter feature can help you to handler error.
https://tsed.io/docs/exceptions.html#exception-filter (for old version, you can use GlobalErrorHandler).

Also `@authorize` decorator accept passport options describe in passport doc. It can help you.

See you
Romain

**Comment by panbhatt** [comment]
Thanks @Romakita  for your valuable feedback. 
1. For Returning the JSON response, i think we need to modify @tsed/passport, since passport.js supports it but via a custom callback. The way we can do it is to use something that we can pass to Settings in @protocol (like a function that will generate the Error JSON response) and use it via ProtocolService.invoke() (line no 26 in PassportModule.ts). 
Once we have the function available in ProtocolService we can use that function in lin no 69 [https://github.com/TypedProject/tsed/blob/production/packages/passport/src/services/ProtocolsService.ts](https://github.com/TypedProject/tsed/blob/production/packages/passport/src/services/ProtocolsService.ts) to respond correctly with the JSON error response, if required. 
   

2. For the second option to conditionally execute @Authorize @Authenticate, i think we need to expand the options and use it in the decorators only if a condition is true (which was provided in the options E.g process.env.NODE_ENV == 'dev')

Let me know what you think, for time being, i think i can use Middle ware as you have suggested earlier . Thanks a lot for suggestions and always responsive. I love this framework.

**Comment by Romakita** [comment]
It soons to be good. If you have a time, your help would be really appreciate to make a PR. I’m currently focused on the v6 :)

**Comment by panbhatt** [comment]
Thanks, i will try to raise a PR soon.
