### ISSUE TITLE
TSED basic layout logger still generate special characters on startup ?[32m

### ISSUE THREAD

**Issue by panbhatt** [TypedProject/tsed#925]
Hi Team,
   Is there is way to remove these special characters from the System startlogs. I tried to convert the logger to Basic , however all logs are fine except the startup logs which still produce ?[32m for colored output. It was present in the list of URI's and Mounting Middleware logs and Route init logs.

**Comment by Romakita** [comment]
@panbhatt you can disable routes logging on startup with logger. disableRoutesSummary. it’s probably there where you have colors (hard codded).

**Comment by panbhatt** [comment]
Thanks a lot for the suggestion. we resolved it via using your suggestions and diving down in another file that is called on $beforeRouteInit. we commented it via using patch-package and the log file now doesn't seem to have this output. 
Thanks agian.
