### ISSUE TITLE
Logger cloud appender

### ISSUE THREAD

**Issue by waterydan** [TypedProject/tsed#933]
Hi, do you have an example how to create a logger appender that can send an error to a remote service? I would like have all error logs sent to google's stackdriver. Is it something can be done? 

Thanks

**Comment by Romakita** [comment]
Hello @waterydan 

You can take as example the logger-smtp https://github.com/TypedProject/logger/tree/master/packages/smtp

If you have a time, you can sent a PR on https://github.com/TypedProject/logger with your new appender. (Just copy the packages/smtp and implement your appender) and I’ll can give you feedback and comment on it ;)

See
Romain
