### ISSUE TITLE
[EPIC] Fix typo in documenation for Hacktoberfest

### ISSUE THREAD

**Issue by Romakita** [TypedProject/tsed#940]
## Information

For the hacktoberfest you can easily find typo on these documentation: 

- https://github.com/TypedProject/tsed/tree/production/docs 
- https://github.com/TypedProject/tsed-cli/tree/master/docs 
- https://github.com/TypedProject/logger/tree/master/docs 

Just edit markdown file, fix it and create PR by using github interface ;)

See you

**Comment by Kat-lc** [comment]
Hello! May I be assigned this one?

**Comment by Romakita** [comment]
Sure, this issue can be shared with any vonlunteers. There is a lot of pages ;)

Thanks for help :)

**Comment by Romakita** [comment]
Tabular form ?

**Comment by yash2189** [comment]
![Screenshot_20201014-212320](https://user-images.githubusercontent.com/31548778/96014078-92a88180-0e63-11eb-8e51-7da8ba00c180.jpg)
I mean by this @Romakita .Can I make it more clear in like by separating them and and creating table of contents?

**Comment by Romakita** [comment]
I'm sorry but you musn't change this part of the readme. It's the metadata used by Vuepress to generate the website. 
If you change that you'll broke the https://tsed.io website :)  

See you

**Comment by yash2189** [comment]
Oh I'm sorry I misunderstood it.
