### ISSUE TITLE
[V6] Fix v6 documentation

### ISSUE THREAD

**Issue by Romakita** [TypedProject/tsed#942]
## Information

For the hacktoberfest and to prepare the v6, you can easily find typo on this branch/PR:

https://github.com/TypedProject/tsed/pull/941/files

If you find typo, create branch from https://github.com/TypedProject/tsed/tree/v6-update-documentation, then create PR on
this branch. I'll merge it quickly :)

## Pages can be reviewed

- [x] [Getting started](https://github.com/TypedProject/tsed/blob/rc/docs/getting-started/README.md)
- [x] [Create your first controller](https://github.com/TypedProject/tsed/blob/rc/docs/getting-started/create-your-first-controller.md)
- [x] [Start from scratch](https://github.com/TypedProject/tsed/blob/rc/docs/getting-started/start-from-scratch.md)
- [x] [Start with the CLI](https://github.com/TypedProject/tsed/blob/rc/docs/getting-started/start-with-cli.md)
- [x] [Migration guide](https://github.com/TypedProject/tsed/blob/rc/docs/getting-started/migration-from-v5.md)
- [x] [Models](https://github.com/TypedProject/tsed/blob/rc/docs/docs/model.md) 
- [x] [Swagger](https://github.com/TypedProject/tsed/blob/rc/docs/tutorials/swagger.md) 
- [x] [Serve files](https://github.com/TypedProject/tsed/blob/rc/docs/docs/serve-files.md) 
- [x] [Templating](https://github.com/TypedProject/tsed/blob/rc/docs/docs/templating.md)
- [x] [Uploading files](https://github.com/TypedProject/tsed/blob/rc/docs/docs/upload-files.md)
- [x] [Exceptions](https://github.com/TypedProject/tsed/blob/rc/docs/docs/exceptions.md)
- [x] [Controllers](https://github.com/TypedProject/tsed/blob/rc/docs/docs/controllers.md)
- [x] [AWS](https://github.com/TypedProject/tsed/blob/rc/docs/tutorials/aws.md)

## Acceptance criteria

- [x] Your PR start from the [`rc`](https://github.com/TypedProject/tsed/tree/rc) branch

**Comment by bdsvc-github** [comment]
Deployment starting to ephemeral!

**Comment by bdsvc-github** [comment]
Deployed to ephemeral!
