### ISSUE TITLE
[v6] Improve Ignore context

### ISSUE THREAD

**Issue by Romakita** [TypedProject/tsed#949]
## Information

Currently, all module use ConverterServices.serialize. The goal is to give an extra option to know where this method is used. This extra option will be forwarded to Ignore decorator and let developer to know who code serialize his object.

## Describe the solution you'd like

```typescript
class User {
  @Name("id")
  _id: string;

  @Property()
  firstName: string;

  @Property()
  lastName: string;

  @Ignore((value, ctx) => ctx.endpoint) // should not serialized when the object is returned by an endpoint.
  password: string;

  @Ignore((value, ctx) => ctx.mongoose) // should be serialized when the object is returned by an endpoint.
  scopes: string[];

  @Ignore()
  alwaysIgnored: string;
}
```

For example, with the given User model, password must not serialized by the json-mapper.

To validate the scenario add integration test in this file: https://github.com/TypedProject/tsed/blob/beta/packages/platform-test-utils/src/tests/testResponse.ts#L97

```typescript
  @Get("/scenario10/:id")
  public testScenario10(@PathParams("id") id: string): string {
     const user = new User();
     
     user._id = id;
     user.lastName = "lastName";
     user.firstName = "firstName";
     user.password = "password";
     user.scopes = ["admin"];
     user.alwaysIgnored = "alwaysIgnored"

     return user;
  }
```

Expected:

```typescript
describe("Scenario10: Model serialization", () => {
  it("should ignore password when a User instance is serialized", () => {
        const response = await request.get("/rest/response/scenario10/1").expect(400);

        expect(response.body).to.deep.equal({
            id: "1",
            lastName: "lastName",
           firstName: "firstName",
           scopes: "scopes"
        });
  })
})
```

The serialization is performed here for the endpoint: https://github.com/TypedProject/tsed/blob/beta/packages/common/src/platform/services/PlatformHandler.ts#L236

All extra properties given to ConverterService.serialize will be forward to the `ctx` parameter (cf: `@Ignore((value, ctx: JsonHookContext) => ctx.endpoint) /`).

## Acceptance criteria

- [ ] Properties are correctly ignored when the callback match with the JsonHookContext,
- [ ] Integration cover the different scenario described in the issue.

## Next issues
This issue allow to start the following issues: #808

**Comment by Ryan-Willpower** [comment]
Could you give me any information about this line, please?

```ts
@Ignore((value, ctx) => !ctx.mongoose)
```

**Comment by Romakita** [comment]
Sure :) Let write more details on the issue ;)

**Comment by Romakita** [comment]
@Ryan-Willpower I think the issue is correctly described now ;)

**Comment by Ryan-Willpower** [comment]
I think I will try on this task. But I have to learn about the codebase first.

**Comment by Romakita** [comment]
Sure :)

You have to start your branch from beta instead of production ;)

**Comment by Romakita** [comment]
Hello @Ryan-Willpower,

Do you working on it? 
See you
Romain

**Comment by IARKI** [comment]
Can it be done at the endpoint level? For the same field - you may want to return the field for some endpoint, but want to ignore for some other. 
Also, I'm using services to call mongoose DB -> parse data and return to endpoint function -> endpoint function is doing some other parsing or call some other services and sending the response.
Will the converter take care of ignoring inside the service?

**Comment by Romakita** [comment]
@IARKI  For the endpoint level, this is the following issue #808 
Mongoose doesn't use the serializer, it's pretty different in this case. The JsonSchema is used by @tsed/mongoose to create Mongoose schema. Ignore isn't correctly implemented at this level. 
But the goal is to improve the Ignore decorator to have a control on the serialized properties depending on the context where the serialization function is used (endpoint, mongoose, etc...).
