### ISSUE TITLE
[BUG] tslint is deprecated

### ISSUE THREAD

**Issue by rluvaton** [TypedProject/tsed#952]
## Information

TSLint is deprecated in favor of ESLint https://github.com/palantir/tslint/issues/4534#issue-413722441
- **Version:** 5.65.4
- Packages: 

A few sentences describing the overall goals of the issue.

Migrate to ESLint by replacing `.tslint` with `.eslint`

## Solution

See: 
- https://github.com/TypedProject/tsed-cli/package.json and https://github.com/TypedProject/tsed-cli/
- https://github.com/TypedProject/tsed-cli/blob/master/.eslintrc

## Acceptance criteria

- [ ] Travis CI run linter
- [ ] Linter is executed on commit

**Comment by Romakita** [comment]
I already done the eslint migration for the tsed-cli, but for tsed itself I’m not motivated :p.

**Comment by akrifari** [comment]
Hi, I would like to contribute to this issue

**Comment by Romakita** [comment]
Hello @akrifari 
Your contribution is welcome :)
I assign you on this task. You can start your branch from production ;)

See you
Romain
