### ISSUE TITLE
[DOC] Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Romakita** [TypedProject/tsed#967]
## Informations

This issue is to create a code of conduct file on root project :)

**Comment by selinsezi** [comment]
Can I work on this issue?

**Comment by Romakita** [comment]
Sorry @selinsezi 
Somebody had already created a PR for this issue.

See you

**Comment by Romakita** [comment]
https://github.com/TypedProject/tsed/pull/975
