### ISSUE TITLE
[BUG] Dropdown is to long on small screen

### ISSUE THREAD

**Issue by Romakita** [TypedProject/tsed#971]
## Information

The dropdown is to long. See the capture here:

![Capture d’écran 2020-10-08 à 08 42 55](https://user-images.githubusercontent.com/1763311/95424192-9491b280-0942-11eb-864c-ceb9ce8e56b0.png)

The goal is to fix the maxHeight of the dropdown.

## How to start website

Checkout the project and run these commands:

```sh
npm install -g yarn
yarn install
```

Then run documentation (mac/linux):
```
yarn api:build // works on mac/linux only
yarn vuepress:serve
```

For windows users. Copy this file https://tsed.io/api.json to `/docs/.vuepress/public/api.json` and run:
```
yarn vuepress:serve
```
Open in your browser with this url: http://localhost:8081/

## How to fix

The theme is located in a separated repository: https://github.com/TypedProject/vuepress-theme-tsed
But vuepress allow to override original theme by editing the css file here:

https://github.com/TypedProject/tsed/blob/production/docs/.vuepress/style.css

For this PR, you can fix the issue by implementing the right css rule directly in this file :)

## Acceptance criteria

- [ ] The dropdown has a limited maxHeight and can be displayed on small screen,
- [ ] The maxHeight is a ratio of the viewPort
- [ ] The dropdown display a scrollbar when content exceeds item size

**Comment by GaganSingh5** [comment]
Hey DEV, I would like to work on this project!!

**Comment by GaganSingh5** [comment]
Hi @Romakita  i have fixed the bug should i create a pull request??

**Comment by Romakita** [comment]
Yes sure :)
